### ISSUE TITLE
Email alert setup?

### ISSUE THREAD

**Issue by ZillaG** [Yelp/elastalert#1000]
I setup email info in my config.yaml file. However, each rule requires an alert, and I want to use an email alert. How can I make each rule use the email setup in the config.yaml file?

**Comment by Qmando** [comment]
Anything in config.yaml will be used as the default in rules, however, you still need to define a couple properties, like name, index, type, alert, and if using email alerter, the email recipient. So, things like smtp settings can be reused, but you still need
```
alert: email
email: foo@example.com
```

**Comment by ZillaG** [comment]
I see. If I want ALL my email alerts to go to the same email, I have to define it in EACH rule? Now if I want to change the email address, I'll have to change it in ALL the rules? That's not very efficient.

**Comment by Qmando** [comment]
It's not. This feature is on the roadmap.
