### ISSUE TITLE
not able to make a alert rule

### ISSUE THREAD

**Issue by val31** [Yelp/elastalert#1018]
Hi 

I'm trying to do a simple test on an alert (this one is just an example, I also try exampls from elastalert directory)
```
es_host: myIP
es_port: 9200
name: Test rule
type: any
index: myindex-*
num_events: 50
timeframe:
    hours: 4
alert:
- "command"
command:
- "echo \"toto\""
```

I've got 
$ pip freeze | grep elast
elastalert==0.1.2
elasticsearch==5.2.0

but this command
$ elastalert-test-rule --config /orus/elastalert-master/config.yaml test.yaml
give me 

INFO:urllib3.connectionpool:Starting new HTTP connection (1): 10.31.66.242
WARNING:elasticsearch:GET http://myIP:9200/myindex-*/_search?ignore_unavailable=true&size=1 [status:400 request:0.003s]
Error running your filter:
RequestError(400, u'parsing_exception', {u'status': 400, u'error': {u'line': 1, u'root_cause': [{u'reason': u'no [query] registered for [filtered]', u'type': u'parsing_exception', u'line': 1, u'col': 68}], u'type': u'parsing_exception', u'reason': u'no [query] registered for [filtered]', u'col': 68}})
INFO:elastalert:Note: In debug mode, alerts will be logged to console but NOT actually sent. To send them, use --verbose.
INFO:urllib3.connectionpool:Starting new HTTP connection (1): myIP
WARNING:elasticsearch:GET http://myIP:9200/myindex-*/_search?_source_include=%40timestamp%2C%2A&ignore_unavailable=true&scroll=30s&size=10000 [status:400 request:0.002s]
ERROR:root:Error running query: TransportError(400, u'parsing_exception', u'no [query] registered for [filtered]')

Any idea ?
Thanks

**Comment by Qmando** [comment]
I think you need to upgrade elastalert. 0.1.2 doesn't support Elasticsearch 5

**Comment by val31** [comment]
Thanks. I was afraid of that...

**Comment by val31** [comment]
Is that version OK ?
# pip freeze | grep elast
elastalert==0.1.8
elasticsearch==5.2.0

It's not working but I've got a problem with cryptography module :'(

**Comment by val31** [comment]
OK Alerts are OK
