### ISSUE TITLE
es_host not being read from rules files after commit b31cd7ffdaece87a51493a811673f5e773bf9f53

### ISSUE THREAD

**Issue by fabianlee** [Yelp/elastalert#1021]
The 'es_host' key defined in a rule file is no longer being used after the commit below a few days ago related to optionally reading ES_HOST, ES_PORT from environment variables.
https://github.com/Yelp/elastalert/commit/b31cd7ffdaece87a51493a811673f5e773bf9f53

As a test, do an out-of-the-box installation, with a master config.yml pointing to your ES instance.
Then for simplicities sake, delete all the files in the example_rules directory except example_cardinality.yaml and run elastalert

_$ python -m elastalert.elastalert --config config.yml_
ERROR:root:Traceback (most recent call last):
  File "/tmp/elastalert/elastalert/elastalert.py", line 914, in run_all_rules
    num_matches = self.run_rule(rule, endtime, self.starttime)
  File "/tmp/elastalert/elastalert/elastalert.py", line 642, in run_rule
    self.current_es_addr = (self.current_es.host, self.current_es.port)
AttributeError: 'Elasticsearch' object has no attribute 'host'

ERROR:root:Uncaught exception running rule Example cardinality rule: 'Elasticsearch' object has no attribute 'host'

You may then think it is because example_cardinality.yaml does not define its own es_host and es_port, so go ahead and have the rule file set its own keys, run it again and you get the same result.

If you then comment out the current change on line #644 of elastalert.py and modify it back to the before the commit, the command runs successfully both with or without the es_host/es_port variables defined explicitly in example_cardinality.yaml

        #self.current_es_addr = (self.current_es.host, self.current_es.port)
        self.current_es_addr = (rule['es_host'], rule['es_port'])

I would have submitted a pull request if I though it was just this single line causing an issue, but this commit reaches into alerts and other areas and I'm not sure how much needs to be rolled back.

**Comment by danielpops** [comment]
+1. I'm seeing the exact same issue with this commit. I suggest that this commit be rolled back.

**Comment by Qmando** [comment]
Fixed by #1027

**Comment by micahhausler** [comment]
I'm making a patch for this
