### ISSUE TITLE
match_body subfields dispaly '?' on Kibana

### ISSUE THREAD

**Issue by mrchang7** [Yelp/elastalert#1029]
Hey guys,

Like below, the elastalert document on Kibana displays '?' for the sub-fields of match_body even after I refresh the index. Not sure this is a bug or what shall I do? 
FYI, I used metric_aggregation rule and using elk 5.3. 

```
t _index	   	elastalert_status
t _type	   	elastalert
t alert_info.command	   	echo Alert Raised: cpu > 70
t alert_info.type	   	command
 alert_sent	   	true
 alert_time	   	April 17th 2017, 12:42:17.534
? match_body.@timestamp	   	  2017-04-17T16:42:16.533541Z
? match_body.cpu_max	   	  81
? match_body.num_hits	   	  32
? match_body.num_matches	   	  1
```

Thanks.

**Comment by Qmando** [comment]
This is not a bug. match_body is an "object", meaning it contains arbitrary fields. This is because different alerts could have different types for fields. Kibana/Elasticsearch doesn't really support many operations on "object" mapped fields. ``match_body`` was not really ever meant to be used in Elasticsearch, other than for Elastalert to save the raw data used to generate an alert.

**Comment by mrchang7** [comment]
Thanks Qmando. 
BTW the alert_info is not an object? Because the refresh could get rid og ? on its subfields.

**Comment by vitalinoborges** [comment]
> Thanks Qmando. BTW the alert_info is not an object? Because the refresh could get rid of ? for its subfields.

Because of `match_body` doesn't mapping for your proprierties. But `alert_info` has!

Trying this query: `GET /elastalert/_mapping`

You will show something like this:

```
        "alert_info": {
          "properties": {
            "type": {
              "type": "keyword",
              "ignore_above": 1024
            }
          }
        },
        "match_body": {
          "type": "object",
          "enabled": false
        }
```

The fields of `alert_info` (and `rule_name`, and others) are mapped. But fields of `match_body` object isn't.
