### ISSUE TITLE
Version conflict

### ISSUE THREAD

**Issue by kernelpanicfbsd** [Yelp/elastalert#1037]
Hello, I'm using FreeBSD 11 and have used these instructions (https://blog.gufi.org/2016/03/16/elk-stack-elasticsearch-logstash-and-kibana-on-freebsd-part-3/) to create a virtual environment which Elastalert has been installed into. 
However, when I run  `./bin/elastalert-create-index` I get the following error:

> Traceback (most recent call last):
>   File "./bin/elastalert-create-index", line 6, in <module>
>     from pkg_resources import load_entry_point
>   File "/usr/local/elastalert/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3036, in <module>
>     @_call_aside
>   File "/usr/local/elastalert/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3020, in _call_aside
>     f(*args, **kwargs)
>   File "/usr/local/elastalert/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3049, in _initialize_master_working_set
>     working_set = WorkingSet._build_master()
>   File "/usr/local/elastalert/lib/python2.7/site-packages/pkg_resources/__init__.py", line 656, in _build_master
>     return cls._build_from_requirements(__requires__)
>   File "/usr/local/elastalert/lib/python2.7/site-packages/pkg_resources/__init__.py", line 669, in _build_from_requirements
>     dists = ws.resolve(reqs, Environment())
>   File "/usr/local/elastalert/lib/python2.7/site-packages/pkg_resources/__init__.py", line 859, in resolve
>     raise VersionConflict(dist, req).with_context(dependent_req)
> pkg_resources.ContextualVersionConflict: (requests 2.5.1 (/usr/local/elastalert/lib/python2.7/site-packages), Requirement.parse('requests==2.2.1'), set(['exotel']))

Any help is greatly appreciated.

**Comment by Qmando** [comment]
Run ``python -m elastalert.create_index`` instead. Instead of ``elastalert``, run ``python -m elastalert.elastalert``

**Comment by kernelpanicfbsd** [comment]
Thanks for getting back to me; I ran the following commands:

```
virtualenv /usr/local/venv
source /usr/local/venv/bin/activate.csh
pip install elastalert
```

This did seem to successfully install elastalert and although I can see some elastalert files in the ./bin directory I can't see an ./etc directory or find the config.yaml.example file - do I need to create it myself?
Sorry for asking these simple questions, whilst I have dabbled with simple python scripts before, I've never used virtual environments or pip.

Thanks.

**Comment by Qmando** [comment]
You'll need to create your own config.yaml.

**Comment by kernelpanicfbsd** [comment]
Thankyou very much for your help, its much appreciated.
