### ISSUE TITLE
Does elastalert support mulit-ES instances?

### ISSUE THREAD

**Issue by dreampuf** [Yelp/elastalert#1040]
I checked the document and source code. Seems the `es_host` just configure as a single node. It requires a string. elasticsearch-py do support hosts. Do you guys has an idea to support multi-instances? That would help to redundancy and allow some failure of one ES instance.

**Comment by omercnet** [comment]
how are your other applications accessing your es cluster?

for large scale deployments it's best to use a load balancer and/or round-robin dns that would point to a client node

**Comment by dreampuf** [comment]
@omercnet thank you response. The question is that will makes us depend on some LB or DNS service. 
We want minimal rely on.

**Comment by omercnet** [comment]
@dreampuf you could set it up in /etc/hosts as a last resort
But how are your other clients that connect to elasticsearch (kibana?) configured?

**Comment by dreampuf** [comment]
@omercnet Kibana will consider a tribe node as the end point. 
But the single point failure still on it and I didn't found a way to avoid the tribe node crash.

**Comment by omercnet** [comment]
@dreampuf using a load balancer, backed by a roundrobin dns should cover you pretty well
either way, this is an elasticsearch support question and not related to elastalert, please take this to https://discuss.elastic.co/

**Comment by dreampuf** [comment]
thank you anyway.
