### ISSUE TITLE
Using multiple values in a filter with 'not', 'and', and 'or'

### ISSUE THREAD

**Issue by raviteja7** [Yelp/elastalert#1043]
Hello,

I am not sure whether this filter is valid  or not

filter:
- query:
    query_string:
        query: "field1: value and not field2: value1 or field2:value2"

so effectively I want an alert if { field1 matches the value and simultaneously field2 does not match any of the two values }

Is this possible.

Thanks

**Comment by Qmando** [comment]
field1: value AND NOT field2: value AND NOT field2: value

**Comment by Qmando** [comment]
https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html

**Comment by raviteja7** [comment]
For some reason, it is not working 
My current filter is 
filter:
- query:
    query_string:
        query: "columns.name: iexplore.exe and not columns.remote_port: 800 and not 
                  columns.remote_port: 443"

but I received an alert for this (even though columns.name is not iexplore.exe)
![image](https://cloud.githubusercontent.com/assets/2549509/25253311/597a9b02-25ee-11e7-9564-a0431fa90b89.png)

if columns.name is iexplore.exe and the remote port is not 800,443 send an alert. I followed your comment, but it is not working

**Comment by Qmando** [comment]
Read the documentation. Capitalization matters. AND and NOT need to be uppercase.

**Comment by raviteja7** [comment]
@Qmando  perfect, it works. Thank a lot
