### ISSUE TITLE
error with ES5.3

### ISSUE THREAD

**Issue by jerem97** [Yelp/elastalert#1057]
Elastalert works correctly until updating ES to version 5.3.
Now with ES 5.3 I have an error:

avril 25 15:41:07 test-elastalert python[7333]: return func(*args, params=params, **kwargs)
avril 25 15:41:07 test-elastalert python[7333]: File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/__init__.py", line 257, in index
avril 25 15:41:07 test-elastalert python[7333]: _make_path(index, doc_type, id), params=params, body=body)
avril 25 15:41:07 test-elastalert python[7333]: File "/usr/local/lib/python2.7/dist-packages/elasticsearch/transport.py", line 301, in perform_request
avril 25 15:41:07 test-elastalert python[7333]: status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
avril 25 15:41:07 test-elastalert python[7333]: File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_requests.py", line 72, in perform_request
avril 25 15:41:07 test-elastalert python[7333]: self._raise_error(response.status_code, raw_data)
avril 25 15:41:07 test-elastalert python[7333]: File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/base.py", line 102, in _raise_error
avril 25 15:41:08 test-elastalert python[7333]: raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
avril 25 15:41:08 test-elastalert python[7333]: RequestError: TransportError(400, {u'root_cause': [{u'reason': u'Validation Failed: 1: an id must be provided if version ty...
Hint: Some lines were ellipsized, use -l to show in full.

Can you help me solve the problem.
I use the elastalert version v.0.0.91.
Should be changed to version v.0.1.9

**Comment by Qmando** [comment]
ES 5 wasn't supported until v0.1.something. Upgrade to the latest version of elastalert and also make sure you upgrade the elasticsearch python library, ``pip install --upgrade elasticsearch``

**Comment by jerem97** [comment]
Thank you.
The procedure for upgarde ?

**Comment by Qmando** [comment]
pip install --upgrade elastalert

**Comment by jerem97** [comment]
The update is done but at startup I have errors.
Do you have an idea ?

  Loaded: loaded (/lib/systemd/system/elastalert.service; enabled)
   Active: failed (Result: exit-code) since mar. 2017-05-09 14:29:57 CEST; 13min ago
  Process: 8036 ExecStart=/usr/bin/python -m elastalert.elastalert --config config.yaml (code=exited, status=1/FAILURE)
 Main PID: 8036 (code=exited, status=1/FAILURE)

mai 09 14:29:57 test-elastalert python[8036]: self.handle_error('Uncaught exception running rule %s: %s' % (rule['name'], exception), {'rule': rule['name']})
mai 09 14:29:57 test-elastalert python[8036]: File "/opt/elastalert-master/elastalert/elastalert.py", line 1292, in handle_error
mai 09 14:29:57 test-elastalert python[8036]: self.writeback('elastalert_error', body)
mai 09 14:29:57 test-elastalert python[8036]: File "/opt/elastalert-master/elastalert/elastalert.py", line 1038, in writeback
mai 09 14:29:57 test-elastalert python[8036]: doc_type=doc_type, body=body)
mai 09 14:29:57 test-elastalert python[8036]: File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/utils.py", line 73, in _wrapped
mai 09 14:29:57 test-elastalert python[8036]: return func(*args, params=params, **kwargs)
mai 09 14:29:57 test-elastalert python[8036]: TypeError: create() takes at least 5 arguments (5 given)
mai 09 14:29:57 test-elastalert systemd[1]: elastalert.service: main process exited, code=exited, status=1/FAILURE
mai 09 14:29:57 test-elastalert systemd[1]: Unit elastalert.service entered failed state.

**Comment by Qmando** [comment]
What do you get when you type
``pip freeze | grep elasticsearch`` ?

The version needs to match the version of Elasticsearch you are using.

You probably want either

``pip install --upgrade "elasticsearch>=5.0"``
or ``pip install --upgrade "elasticsearch<5.0"``

**Comment by jerem97** [comment]
I have that "elasticsearch==5.3.0"

**Comment by Qmando** [comment]
You are still using the old version of elastalert. This might happen if you have the old source code checked out and are running python from that directory. I thought that even if you had run "python setup.py install" and then did "pip install --upgrade" that it would work, but maybe I'm wrong.

**Comment by jerem97** [comment]
68/5000
Absolutely.
When I run python setuo.py install, I have this :
Using /usr/local/lib/python2.7/dist-packages
Finished processing dependencies for elastalert==0.0.91

We see that the link with the old version.
So I have done a complete installation with the new version elastalert (0.1.12).
And everything works fine.

Thank you for your help
