### ISSUE TITLE
Cannot find a way to set an alert to run every day at a certain time

### ISSUE THREAD

**Issue by nnedev1** [Yelp/elastalert#1059]
I was wondering if someone had found a way to where a query can run every day at a certain time to check if a particular set of files have been received according to ES.

**Comment by Qmando** [comment]
You can do ``type: flatline`` with ``timeframe: {hours: 25}`` and then filter on the files you want.

There's not exactly support for only querying at certain times of the day, but you can write an enhancement to do that. Here's an example: https://github.com/Yelp/elastalert/issues/868#issuecomment-273700508
