### ISSUE TITLE
Confussiong about num_hits and num_matches

### ISSUE THREAD

**Issue by lisakaymera** [Yelp/elastalert#1060]
I'm not sure if this is a bug, or more of just a timing issue.

I wanted to write a custom rule based off of frequency that keeps track of events within a certain range.

Frequency waits until a threshold has been exceeded. I would like to make a rule that has a minimum and maximum threshold.
This counts events, and doesn't bother with the values of the fields in them, so I probably shouldn't be using Metric Aggregations (I think?)

I wrote a custom rule that was mostly copied and pasted off of the original Frequency Rule. 
I just changed about two lines of code, and that was adding two new required fields:

num_events_min
num_events_max

The second line of code I changed was:
 if self.occurrences[key].count() >= self.rules['num_events']: 
 to
 if self.occurrences[key].count() >= self.rules['num_events_min'] and self.occurrences[key].count() < self.rules['num_events_max']:

In my new rule file, i specify num_events_min: 10 and num_events_max: 15

When I print out the value of self.occurrences[key].count() I get 10
But when I get a notification, I instead get:
num_hits: 16
num_matches: 1

I think I'm confused on what num_hits and num_matches is supposed to be as opposed to
 self.occurrences[key].count()

Can anyone help clear this up for me?
What field in self.matches would  self.occurrences[key].count() actually correspond with?

**Comment by Qmando** [comment]
self.occurences[key] is an EventWindow that automatically adjusts based on the timeframe. The 16 hits could be spread out over an hour, for example, and if the timeframe was only 15 minutes, the .count() would only include the events in the last 15 minutes. 

There is no direct relation between matches, hits and .count(). It depends on the timeframe, buffer_time and the num_events.
