### ISSUE TITLE
SNS alerts not working in 0.1.12

### ISSUE THREAD

**Issue by cdivitotawela** [Yelp/elastalert#1063]
Noticed a problem with the SNS notifications and issue seems to be related method might have not updated for boto3. Please find the details below. 

Tag: 0.1.12

Error:
Following error throws while trying to send a SNS notification.

File "elastalert/alerts.py", line 828, in alert
    sns_client.publish(self.sns_topic_arn, body, subject=self.create_title(matches))
  File "/usr/lib/python2.7/site-packages/botocore-1.5.44-py2.7.egg/botocore/client.py", line 251, in _api_call
    "%s() only accepts keyword arguments." % py_operation_name)
TypeError: publish() only accepts keyword arguments.

Cause:
Boto3 publish method signature is different and it seems the parameters passing need to be explicitly defined.

Solution:
Update the the class "class SnsAlerter(Alerter)" in alerts.py as follows
sns_client.publish(TopicArn=self.sns_topic_arn, Message=body, Subject=self.create_title(matches))

Reference - http://boto3.readthedocs.io/en/latest/reference/services/sns.html#SNS.Client.publish

**Comment by Qmando** [comment]
Excellent bug report. Looks pretty straightforward to fix. I'll try to get this done soon.
