### ISSUE TITLE
email_from_field as an array?

### ISSUE THREAD

**Issue by bobbyhubbard** [Yelp/elastalert#1064]
I'm trying to configure elastalert to read an array from data which looks like:

```
"orgManagers": [
    "test@test.com",
    "a@b.com"
], ...
```

And my alert configuration looks like:

`email_from_field: "orgManagers"`

Now this works as a single email address, but I need to send the alert to multiple recipients not known by the alert itself...those recipients come from the data. I've looked at enhancements but it looks like only the email field supports multiple. Ideas?

**Comment by Qmando** [comment]
Ah, I only added support for a single address. I'll try add this feature in soon. Here's a quick patch you could try until I add this feature:

```
diff --git a/elastalert/alerts.py b/elastalert/alerts.py
index 1c6895e..b4e383d 100644
--- a/elastalert/alerts.py
+++ b/elastalert/alerts.py
@@ -391,6 +391,8 @@ class EmailAlerter(Alerter):
                     to_addr = [recipient]
                 elif 'email_add_domain' in self.rule:
                     to_addr = [recipient + self.rule['email_add_domain']]
+            else:
+                to_addr = recipient
         email_msg = MIMEText(body.encode('UTF-8'), _charset='UTF-8')
         email_msg['Subject'] = self.create_title(matches)
```

**Comment by bobbyhubbard** [comment]
Thanks! Yeah it _should_ always be valid address. :)

**Comment by prayagupd** [comment]
@Qmando It should work with email distribution list(DL) too, right?

**Comment by Qmando** [comment]
@prayagupd Yup!

**Comment by bobbyhubbard** [comment]
@Qmando Would a pull request be helpful for this?

**Comment by chettu** [comment]
@bobbyhubbard : Did you get this working ?

**Comment by bobbyhubbard** [comment]
Apologies, havent had a moment to validate it. Hoping to do so soon

________________________________
