### ISSUE TITLE
Comparing the value of a field against the value of another field

### ISSUE THREAD

**Issue by Trustys** [Yelp/elastalert#1074]
My goal is to compare the value of a field against the value of another field. 

For example : 

Field1 value : Azerty
Field2 value: Azerty.something

I would like to drop an alert if Field 1 and Field 2 share a same (partial) value (Azerty in this example)

I didn't found any existing function which could to the job in the doc. Do you know any other way to do this ?

**Comment by Qmando** [comment]
Subclass CompareRule
https://github.com/Yelp/elastalert/blob/master/elastalert/ruletypes.py#L112

http://elastalert.readthedocs.io/en/latest/recipes/adding_rules.html

**Comment by Trustys** [comment]
Exactly @Qmando . Issue solved. Thanks for your support ! :-)
