### ISSUE TITLE
Less hits than the count found in ES

### ISSUE THREAD

**Issue by mrchang7** [Yelp/elastalert#1076]
Our system is more likely real-time monitoring one. Given the same query string and window (in milliseconds) elastalert sometimes report less hits than what I can find in the ES. I guess the elastalert might send the query slightly early (few seconds) before the data actually come down to the elasticsearch. It misses 1 or 2 hits even though the full data events are found in ES. Can I configure the elastalert to query with a slight delay? Or am I guessing in a wrong way?

**Comment by Qmando** [comment]
Add to your rule
```
query_delay:
  minutes: 5
```
