### ISSUE TITLE
Newest requirements are breaking setup

### ISSUE THREAD

**Issue by fabianlee** [Yelp/elastalert#1077]
There are several breaking issues with setup module requirements.  Also, the documentation does not state the required dependencies, nor reflect the recent deletion of requirements.txt.  I've proven this out using a fresh vagrant box (ubuntu/trusty v20170502.0.0).

Most of these issues below happen whether or not using a virtualenv, or installing with "pip install -e .".  By applying the proposed pull request, the install works successfully by all methods (virtualenv/non-virtualenv, python setup.py install, pip install -e .).

**I have submitted (and tested) a pull request to address all the problem I will now describe in this issue**
https://github.com/Yelp/elastalert/pull/1069

**1. Setup fails, compile error if you don't install setuptools>=11.3 before running install**

$ vagrant up
$ vagrant ssh
$ sudo /bin/bash
$ apt-get install git software-properties-common python python-pip -y
$ apt-get install python-dev libffi-dev libssl-dev -y
$ git clone https://github.com/Yelp/elastalert.git
$ cd elastalert
$ python setup.py install

> Searching for setuptools>=17.1
> Reading https://pypi.python.org/simple/setuptools/
> Best match: setuptools 35.0.2
> Downloading https://pypi.python.org/packages/88/13/7d560b75334a8e4b4903f537b7e5a1ad9f1a2f1216e2587aaaf91b38c991/setuptools-35.0.2.zip#md5=c368b4970d3ad3eab5afe4ef4dbe2437
> Processing setuptools-35.0.2.zip
> Writing /tmp/easy_install-poh62g/mock-2.0.0/temp/easy_install-RBLthp/setuptools-35.0.2/setup.cfg
> Running setuptools-35.0.2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-poh62g/mock-2.0.0/temp/easy_install-RBLthp/setuptools-35.0.2/egg-dist-tmp-mun1H7
> Traceback (most recent call last):
>   File "setup.py", line 47, in <module>
>     'twilio>=6.0.0',
>   File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
>     dist.run_commands()
>   File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
>     self.run_command(cmd)
>   File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
>     cmd_obj.run()
>   File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 73, in run
>     self.do_egg_install()

Resolution: Have added note about Ubuntu package dependencies, and need to install setuptools>=11.3 using pip

Also described in issue https://github.com/Yelp/elastalert/issues/995

 **2. Setup Fails, JIRA module mandates requests>=2.10.0**

$ vagrant up
$ vagrant ssh
$ sudo /bin/bash
$ apt-get install git software-properties-common python python-pip -y
$ apt-get install python-dev libffi-dev libssl-dev -y
$ pip install "setuptools>=11.3"
$ git clone https://github.com/Yelp/elastalert.git
$ cd elastalert
$ python setup.py install

> Best match: requests-toolbelt 0.7.1
> Processing requests-toolbelt-0.7.1.tar.gz
> Writing /tmp/easy_install-QkQL_Y/requests-toolbelt-0.7.1/setup.cfg
> Running requests-toolbelt-0.7.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-QkQL_Y/requests-toolbelt-0.7.1/egg-dist-tmp-Dz7EDs
> no previously-included directories found matching 'docs/_build'
> warning: no previously-included files matching '*.py[cdo]' found anywhere in distribution
> warning: no previously-included files matching '__pycache__' found anywhere in distribution
> warning: no previously-included files matching '*.so' found anywhere in distribution
> warning: no previously-included files matching '*.pyd' found anywhere in distribution
> zip_safe flag not set; analyzing archive contents...
> Moving requests_toolbelt-0.7.1-py2.7.egg to /usr/local/lib/python2.7/dist-packages
> Adding requests-toolbelt 0.7.1 to easy-install.pth file
> 
> Installed /usr/local/lib/python2.7/dist-packages/requests_toolbelt-0.7.1-py2.7.egg
> error: requests 2.2.1 is installed but requests>=2.10.0 is required by set(['jira'])

Resolution: Changed setup.py to make requests>=2.10.0

 **3. Setup Completes, but run elasalert and it throws error about Twilio module**

$ vagrant up
$ vagrant ssh
$ sudo /bin/bash
$ apt-get install git software-properties-common python python-pip -y
$ apt-get install python-dev libffi-dev libssl-dev -y
$ pip install "setuptools>=11.3"
$ git clone https://github.com/Yelp/elastalert.git
$ cd elastalert
$ vi setup.py (modify so requests>=2.10.0)
$ python setup.py install

This time setup completes successfully, BUT if you run /user/local/bin/elastalert you get a stack error from the Twilio module.  This is because the twilio module being used is the latest dev branch, and a 6.1 stable version needs to run instead of 6.3.dev

> Traceback (most recent call last):
>   File "/usr/local/bin/elastalert", line 11, in <module>
>     load_entry_point('elastalert==0.1.12', 'console_scripts', 'elastalert')()
>   File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 560, in load_entry_point
>     return get_distribution(dist).load_entry_point(group, name)
>   File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2648, in load_entry_point
>     return ep.load()
>   File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2302, in load
>     return self.resolve()
>   File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2308, in resolve
>     module = __import__(self.module_name, fromlist=['__name__'], level=0)
>   File "/usr/local/lib/python2.7/dist-packages/elastalert-0.1.12-py2.7.egg/elastalert/elastalert.py", line 20, in <module>
>     from alerts import DebugAlerter
>   File "/usr/local/lib/python2.7/dist-packages/elastalert-0.1.12-py2.7.egg/elastalert/alerts.py", line 26, in <module>
>     from twilio.base.exceptions import TwilioRestException
> ImportError: No module named base.exceptions

Resolution: need to make twilio>=6.0.0,<6.1 so

 **4. ElastAlert breaks ElasticSearch 2.x support**

ElastAlert has always supported ElasticSearch 2.x and 5.x, but the setup.py is now written so that elasticsearch>=5.3.0 is hardcoded.  This would not be a big deal if you could run a pip install on elasticsearch<3.0.0 and it would use that module instead.

However, if you run pip install "elasticsearch<3.0.0", pip works, however now if you run the wrapper /usr/local/bin/elastalert, you get the following message at the end of the stack trace

>     raise DistributionNotFound(req, requirers)
> pkg_resources.DistributionNotFound: The 'elasticsearch>=5.3.0' distribution was not found and is required by elastalert
> 

Resolution: Go back to using just 'elasticsearch' in setup.py.  Then the user can run pip install of elasticsearch<3.0.0 and now the wrapper works.

 **5. Install Documentation Updated**

Have added to documentation the fact that on Debian, certain packages must be installed first.  Also that running pip install of setuptools>=11.3 required first, and that requirements.txt is no longer a necessary step (since it is now removed from project).

**Comment by Qmando** [comment]
Requirements.txt was just added back, I didn't mean to remove it.

I also changed the documentation to instruct users to ``pip install elastalert`` instead of using setuptools, which I should have changed a long time ago. People really should be installing the released versions from pypi rather than cloning master.

I also removed the elasticsearch pin on >=5.3.0 in setup.py. This

**Comment by kenjones-cisco** [comment]
@Qmando Has there been consideration for moving to using plugins for enabling different Alerters, and potentially other features? That would mean that most of the dependencies would be part of the plugin and not directly part of elastalert. An example framework leveraging what comes native with Python setuptools would be [stevedore](https://docs.openstack.org/developer/stevedore/). Because the plugins can be loaded from any package declaring an entrypoint for a given namespace, only the required features for a given install would require installing certain dependencies.

elastalert provides the framework and the execution engine. And the plugins provided as part of the configuration would provide implementations for how the alert is sent. Also even an elasticsearch plugin that works within v2.x and another for 5.x

**Comment by fabianlee** [comment]
@Qmando - whether via pypi, "python setup.py install" or "pip install -e .", there are still outstanding issues.  

* Debian dependency on libffi-dev and other packages that are not documented
* Prerequisite on "setuptools>11.3" (whether installation by pypi, 'setup.py install', or 'pip install -e .') 
* Runtime dependency on "requests>=2.10.1" (for jira extension)

_If you make the changes described in my original post and pull request, then not only does an install from pypi work, but also "python setup.py install" as well as "pip install -e ."  Why limit those who want to install the latest code?_



I'm using a fresh vagrant ubuntu/trusty v20170502.0.0, so all this can be replicated.

**1. Install from pypi fails, compile error if you don't install setuptools>=11.3 before running install**

Proposed Resolution: Document the fact that setuptools>=11.3 is a prerequisite, along with a certain set of packages for Debian distributions

$ vagrant up
$ vagrant ssh
$ sudo /bin/bash
$ apt-get install git software-properties-common python python-pip -y
$ apt-get install python-dev libffi-dev libssl-dev -y
$ pip install elastalert -e .

>   Found existing installation: pyOpenSSL 0.13
>     Not uninstalling pyOpenSSL at /usr/lib/python2.7/dist-packages, owned by OS
>   Running setup.py install for oauthlib
>   Found existing installation: setuptools 3.3
>     Not uninstalling setuptools at /usr/lib/python2.7/dist-packages, owned by OS
>   Running setup.py install for cffi
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/usr/local/lib/python2.7/dist-packages/setuptools/__init__.py", line 12, in <module>
>         import setuptools.version
>       File "/usr/local/lib/python2.7/dist-packages/setuptools/version.py", line 1, in <module>
>         import pkg_resources
>       File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 72, in <module>
>         import packaging.requirements
>       File "/usr/local/lib/python2.7/dist-packages/packaging/requirements.py", line 9, in <module>
>         from pyparsing import stringStart, stringEnd, originalTextFor, ParseException
>     ImportError: No module named pyparsing
>     Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/cffi/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-l9z2Cl-record/install-record.txt --single-version-externally-managed --compile:
>     Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/usr/local/lib/python2.7/dist-packages/setuptools/__init__.py", line 12, in <module>
>     import setuptools.version
>   File "/usr/local/lib/python2.7/dist-packages/setuptools/version.py", line 1, in <module>
>     import pkg_resources
>   File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 72, in <module>
>     import packaging.requirements
>   File "/usr/local/lib/python2.7/dist-packages/packaging/requirements.py", line 9, in <module>
>     from pyparsing import stringStart, stringEnd, originalTextFor, ParseException
> ImportError: No module named pyparsing
> ----------------------------------------
> Cleaning up...
> Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/cffi/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-l9z2Cl-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_root/cffi
> Storing debug log for failure in /home/vagrant/.pip/pip.log
> 

The pip.log referenced in the above message says:

> Cleaning up...
>   Removing temporary dir /tmp/pip_build_root...
> Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/cffi/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-SrEm_f-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_root/cffi
> Exception information:
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
>     status = self.run(options, args)
>   File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 283, in run
>     requirement_set.install(install_options, global_options, root=options.root_path)
>   File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1436, in install
>     requirement.install(install_options, global_options, *args, **kwargs)
>   File "/usr/lib/python2.7/dist-packages/pip/req.py", line 707, in install
>     cwd=self.source_dir, filter_stdout=self._filter_install, show_stdout=False)
>   File "/usr/lib/python2.7/dist-packages/pip/util.py", line 715, in call_subprocess
>     % (command_desc, proc.returncode, cwd))
> InstallationError: Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/cffi/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-SrEm_f-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_root/cffi
> 
> 


**2. Install completes, but runtime error from Jira extension needing "requests>=2.10.0"**

Proposed Resolution: change setup.py to make requests>=2.10.0

$ vagrant up
$ vagrant ssh
$ sudo /bin/bash
$ apt-get install git software-properties-common python python-pip -y
$ apt-get install python-dev libffi-dev libssl-dev -y
$ pip install "setuptools>=11.3"
$ pip install elastalert -e .
$ /usr/local/bin/elastalert

Traceback (most recent call last):
  File "/usr/local/bin/elastalert", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3036, in <module>
    @_call_aside
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3020, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3049, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 656, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 669, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 859, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (requests 2.2.1 (/usr/lib/python2.7/dist-packages), Requirement.parse('requests>=2.10.0'), set(['jira']))

**Comment by fabianlee** [comment]
Thanks, @Qmando ! 

I validated against the master branch, and all scenarios are now working (pip install elastalert -e ., python setup.py install, virtualenv/non virtualenv)

Closing.

**Comment by Qmando** [comment]
Thank YOU! 😄
