### ISSUE TITLE
Generalization of the ChangeRule

### ISSUE THREAD

**Issue by pralabhkumar** [Yelp/elastalert#1079]
1 ) Change rule should be able to compare on multiple keys 
2) Also there should be a property which can trigger notification on just not on change in columns/field  values but with change in column/filed values  with some threshold.

We did following changes to do the same . But it would be good ,if it can be merged with main code.

1)  We have changed the rules.yaml to have property compare_key  a,b . 
2) We change config.py to have 
if 'compare_key' in rule:
        for val in rule['compare_key'].split(',') :
                include.append(val)

3)  val = lookup_es_key(event, self.rules['compare_key'].split(",")[0])
     val1 = lookup_es_key(event, self.rules['compare_key'].split(",")[1])

4) For threshold 
  changed = (int(self.occurrences[key]) - int(val)) < threshold value

Ideally threshold value should come from rules.yaml

**Comment by Qmando** [comment]
Please open a pull request if you have code changes.

**Comment by pralabhkumar** [comment]
Yes I'll open a pull request in couple of days

**Comment by pralabhkumar** [comment]
done with code changes ,will create a pull request by tomorrow

**Comment by pralabhkumar** [comment]
@Qmando  : Can u please review the pull request . Currently its doing  on 

1 ) Change rule should be able to compare on multiple keys . If any key have change in value then notification will go

**Comment by pralabhkumar** [comment]
@Qmando : Can u please review the pull request

**Comment by Qmando** [comment]
I will do it soon!

**Comment by pralabhkumar** [comment]
@danielpops : I have added changes as suggested by you . Please review

**Comment by pralabhkumar** [comment]
@danielpops @Qmando ,Could you please review and provide your suggestions

**Comment by pralabhkumar** [comment]
@danielpops @Qmando Could you please review and provide your suggestions
