### ISSUE TITLE
How to get every alerts for cardinality type ?

### ISSUE THREAD

**Issue by stefansaye** [Yelp/elastalert#1081]
I have set my rule as you said below,if  "For any EID, alert if there are more than 3 departments" in one minutes timeframe  will be alert

     index: logstash-*
     type: cardinality
     es_conn_timeout: 30
     timeframe:
        minutes: 1
     max_cardinality: 2
      cardinality_field: "department"
     query_key: "eid"

but ,it's will only alert for first time , if next minute get the threshold ,it's will be no alert 
it's will be looks like "INFO:elastalert:Ignoring match for silenced rule XXXXXX"

I have try to set 

     realert:
         minutes: 0

but it's will be not "For any EID, alert if there are more than 3 departments in one minutes" threshold

so ,  I try to count every attach the threshold counts in enhancement ,when counts is 2 then alert ,
or have other method can do that  ?

Will elastalert do  get every alerts for cardinality type ?  I haven't been able to find it...

**Comment by Qmando** [comment]
You still see "Ignoring match for silenced rule XXX" even after adding realert 0?

**Comment by stefansaye** [comment]
Qmando,
if I adding realert 0 won't see  "Ignoring match for silenced rule XXX"
But it's will be not "For any EID, alert if there are more than 3 departments in one minutes" threshold
that not I want 
So Will elastalert do get every alerts for cardinality type ? I haven't been able to find it...

**Comment by Qmando** [comment]
``But it's will be not "For any EID, alert if there are more than 3 departments in one minutes" threshold
that not I want``

???

Why isn't it? Why does adding realert change that?

**Comment by stefansaye** [comment]
Qmando,
if I add realert 0 to my rule,

**Comment by stefansaye** [comment]
Qmando,
if  I adding realert 0 won't see "Ignoring match for silenced rule XXX" 
 and it's will be not "For any EID, alert if there are more than 3 departments in one minutes" threshold.
But I want "For any EID, alert if there are more than 3 departments"

**Comment by Qmando** [comment]
What behavior are you seeing?

Realert doesn't change anything. It's still "For any EID, alert if there are more than 3 departments in one minutes".

**WHY** do you say it's not that?
