### ISSUE TITLE
Dont know whether it is installed or not

### ISSUE THREAD

**Issue by windowsansiblernew** [Yelp/elastalert#1084]
i have followed the url to install elastalert http://elastalert.readthedocs.io/en/latest/running_elastalert.html#downloading-and-configuring
, it says to install 
`$ pip install -r requirements.txt`
but when i run that i am getting this 
`
Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'`

and also 
`Next, open up config.yaml.example`
i could not see where it is

**Comment by Qmando** [comment]
Those files are both in the top level directory in master.

https://github.com/Yelp/elastalert/blob/master/requirements.txt
https://github.com/Yelp/elastalert/blob/master/config.yaml.example

You probably just want to run ``pip install elastalert`` and that's all you need to do.

**Comment by windowsansiblernew** [comment]
but where do these get stored ? i cant see them anywhere in the server

**Comment by Qmando** [comment]
If you ran ``pip install elastalert``, you are done.

IF, and only if, you cloned repository do you need to run pip install requirements.txt.

**Comment by windowsansiblernew** [comment]
ok, where can i see the config.yaml.example file :(

**Comment by Qmando** [comment]
Look two comments above

**Comment by Qmando** [comment]
https://github.com/Yelp/elastalert/blob/master/config.yaml.example

**Comment by windowsansiblernew** [comment]
i dont understand, if i run pip install elastalert will it create any directory under which it will create these files for me or i should create all these by myself?

**Comment by Qmando** [comment]
When you ran pip install, it installed elastalert as a library into your local python installation.

Now, typing ``elastalert`` will start elastalert.

You need a config file and a folder with rule files. There are example rule files and an example config in the github repository.

**Comment by windowsansiblernew** [comment]
ok thanks

**Comment by windowsansiblernew** [comment]
i created config.yaml file in a folder and when i ran 
` elastalert-create-index`
i got this
```
Traceback (most recent call last):
  File "/usr/local/bin/elastalert-create-index", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3020, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 616, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 629, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 807, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: requests>=2.0.0

```

**Comment by windowsansiblernew** [comment]
Installed the oauth lib, now getting a different error

```
Traceback (most recent call last):
  File "/usr/local/bin/elastalert-create-index", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3020, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 616, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 629, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 812, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (six 1.8.0 (/usr/lib/python2.7/dist-packages), Requirement.parse('six>=1.9'), set(['mock']))

```

**Comment by windowsansiblernew** [comment]
any help?

**Comment by chrislujan** [comment]
Try installing python-dev and possibly `pip install --upgrade pip` to fix your errors. To answer your other question, if installed via pip, I don't think you end up with the 'example_rules' and other files that come from the git repo.

**Comment by Qmando** [comment]
You've got a couple options

1. use ``python -m elastalert.create_index`` instead of ``elastalert-create-index`` and ``python -m elastalert.elastalert`` instead of ``elastalert`` and ``python -m elastalert.test_rule`` instead of ``elastalert-test-rule``. This bypasses the pkg_resources runtime check for package issues and will probably work fine.

2. Uninstall elastalert and install it again via pip. Do not use ``python setup.py install``. When you install via setuptools and then change the version of libraries via pip, it gives you this error. I only recently changed the documentation for installation so sorry for the confusion.

3. maybe pip install --upgrade elastalert will overwrite the package entrypoints, I dunno.

4. Try to resolve these dependencies manually, like ``pip install "six==1.8.0``, etc

**Comment by windowsansiblernew** [comment]
if i run python -m elastalert.create_index  it prompts me for inputs, so it would create a config file for me?

**Comment by Qmando** [comment]
It creates an index in Elasticsearch required for Elastalert to run. You can probably use the defaults for everything.
