### ISSUE TITLE
How to create custom index and  field ?

### ISSUE THREAD

**Issue by stefansaye** [Yelp/elastalert#1087]
elastalert will create a index (Default elastalert_status)  , Can I create like logstash_log-*  ? 

Can I custom which field in the index ? How to define the value to field ?

**Comment by Qmando** [comment]
Mappings are defined here.
https://github.com/Yelp/elastalert/blob/master/elastalert/create_index.py#L106

You can add additional fields and re-create the index.

**Comment by stefansaye** [comment]
Qmando,
but when I try to create new index like logstash-log-* , get the error message "must not contain the following characters [\\, /, *, ?, ", <, >, |,  , ,]'}) " , because I want to create index like logstash-log-2017.05.01 for every day, how to create the index like this ?
 I can not find how to custom field for my new index from your link (https://github.com/Yelp/elastalert/blob/master/elastalert/create_index.py#L106)?
as i see, it's default field is @timestamp,_id,_index,_score,_type,data.rule,message,traceback , how can I add new field and delete field  ?

**Comment by Qmando** [comment]
https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping.html
