### ISSUE TITLE
Customising email subject and content

### ISSUE THREAD

**Issue by windowsansiblernew** [Yelp/elastalert#1089]
How can we customise the email subject and content, can i have one of the ES field names in my subject?

**Comment by windowsansiblernew** [comment]
any help?

**Comment by Qmando** [comment]
For content:
http://elastalert.readthedocs.io/en/latest/ruletypes.html?highlight=alert_text#alert-content

For subject:
http://elastalert.readthedocs.io/en/latest/ruletypes.html?highlight=alert_text#alerts
