### ISSUE TITLE
No mapping found 

### ISSUE THREAD

**Issue by stefansaye** [Yelp/elastalert#1092]
When I'm running ElastAlert ,got the error message as below ,

     WARNING:elasticsearch:GET http://X.X.X.X:9200/elastalert_status/silence/_search?_source_include=until%2Cexponent&size=1 [status:400 request:0.005s]
    ERROR:root:Error while querying for alert silence status: TransportError(400, u'search_phase_execution_exception', u'No mapping found for [until] in order to sort on')
  

I have  run elastalert-create-index to create elastalert_status index

and run curl -XGET 'http://X.X.X.X:9200/elastalert_status/_mapping/elastalert_status' 
 
    {
      "elastalert_status" : {
        "mappings" : {
          "elastalert_status" : {
            "_all" : {
              "enabled" : false
            },
            "dynamic_templates" : [ {
              "integer field" : {
                "mapping" : {
                  "type" : "integer",
                  "doc_values" : true
                },
                "match" : "*",
                "match_mapping_type" : "integer"
              }
            }, {
              "date field" : {
                "mapping" : {
                  "type" : "date",
                  "doc_values" : true
                },
                "match" : "*",
                "match_mapping_type" : "date"
              }
            }, {
              "long field" : {
                "mapping" : {
                  "type" : "long",
                  "doc_values" : true
                },
                "match" : "*",
                "match_mapping_type" : "long"
              }
            }, {
              "float field" : {
                "mapping" : {
                  "type" : "float",
                  "doc_values" : true
                },
                "match" : "*",
                "match_mapping_type" : "float"
              }
            }, {
              "double field" : {
                "mapping" : {
                  "type" : "double",
                  "doc_values" : true
                },
                "match" : "*",
                "match_mapping_type" : "double"
              }
            }, {
              "byte field" : {
                "mapping" : {
                 "type" : "byte",
                 "doc_values" : true
                },
                "match" : "*",
                "match_mapping_type" : "byte"
              }
            }, {
              "short field" : {
                "mapping" : {
                  "type" : "short",
                  "doc_values" : true
                },
               "match" : "*",
                "match_mapping_type" : "short"
              }
            }, {
              "binary field" : {
                "mapping" : {
                  "type" : "binary",
                  "doc_values" : true
            },
            "match" : "*",
            "match_mapping_type" : "binary"
          }
        }, {
          "geo_point field" : {
            "mapping" : {
              "type" : "geo_point",
              "doc_values" : true
            },
            "match" : "*",
            "match_mapping_type" : "geo_point"
          }
        }, {
          "string fields" : {
            "mapping" : {
              "index" : "not_analyzed",
              "omit_norms" : true,
              "type" : "string",
              "doc_values" : true
            },
            "match" : "*",
            "match_mapping_type" : "string"
          }
        } ],
        "properties" : {
          "@timestamp" : {
            "type" : "date",
            "format" : "strict_date_optional_time||epoch_millis"
          },
          "endtime" : {
            "type" : "date",
            "format" : "strict_date_optional_time||epoch_millis"
          },
          "hits" : {
            "type" : "long"
          },
          "matches" : {
            "type" : "long"
          },
          "rule_name" : {
            "type" : "string",
            "index" : "not_analyzed"
          },
          "starttime" : {
            "type" : "date",
            "format" : "strict_date_optional_time||epoch_millis"
          },
          "time_taken" : {
            "type" : "double"
          }
        }
      },
      "elastalert_error" : {
        "_all" : {
          "enabled" : false
        },
        "dynamic_templates" : [ {
          "integer field" : {
            "mapping" : {
              "type" : "integer",
              "doc_values" : true
            },
            "match" : "*",
            "match_mapping_type" : "integer"
          }
        }, {
          "date field" : {
            "mapping" : {
              "type" : "date",
              "doc_values" : true
            },
            "match" : "*",
            "match_mapping_type" : "date"
          }
        }, {
          "long field" : {
            "mapping" : {
              "type" : "long",
              "doc_values" : true
            },
            "match" : "*",
            "match_mapping_type" : "long"
          }
        }, {
          "float field" : {
            "mapping" : {
              "type" : "float",
              "doc_values" : true
            },
            "match" : "*",
            "match_mapping_type" : "float"
          }
        }, {
          "double field" : {
            "mapping" : {
              "type" : "double",
              "doc_values" : true
            },
            "match" : "*",
            "match_mapping_type" : "double"
          }
        }, {
          "byte field" : {
            "mapping" : {
              "type" : "byte",
              "doc_values" : true
            },
            "match" : "*",
            "match_mapping_type" : "byte"
          }
        }, {
          "short field" : {
            "mapping" : {
              "type" : "short",
              "doc_values" : true
            },
            "match" : "*",
            "match_mapping_type" : "short"
          }
        }, {
          "binary field" : {
            "mapping" : {
              "type" : "binary",
              "doc_values" : true
            },
            "match" : "*",
            "match_mapping_type" : "binary"
          }
        }, {
          "geo_point field" : {
            "mapping" : {
              "type" : "geo_point",
              "doc_values" : true
            },
            "match" : "*",
            "match_mapping_type" : "geo_point"
          }
        }, {
          "string fields" : {
            "mapping" : {
              "index" : "not_analyzed",
              "omit_norms" : true,
              "type" : "string",
              "doc_values" : true
            },
            "match" : "*",
            "match_mapping_type" : "string"
          }
        } ],
        "properties" : {
          "@timestamp" : {
            "type" : "date",
            "format" : "strict_date_optional_time||epoch_millis"
          },
          "data" : {
            "properties" : {
              "rule" : {
                "type" : "string",
                "index" : "not_analyzed"
              }
            }
          },
          "message" : {
            "type" : "string",
            "index" : "not_analyzed"
          },
          "traceback" : {
            "type" : "string",
            "index" : "not_analyzed"
          }
        }
      },
      "elastalert" : {
        "_all" : {
          "enabled" : false
        },
        "dynamic_templates" : [ {
          "integer field" : {
            "mapping" : {
              "type" : "integer",
              "doc_values" : true
            },
            "match" : "*",
            "match_mapping_type" : "integer"
          }
        }, {
          "date field" : {
            "mapping" : {
              "type" : "date",
              "doc_values" : true
            },
            "match" : "*",
            "match_mapping_type" : "date"
          }
        }, {
          "long field" : {
            "mapping" : {
              "type" : "long",
              "doc_values" : true
            },
            "match" : "*",
            "match_mapping_type" : "long"
          }
        }, {
          "float field" : {
            "mapping" : {
              "type" : "float",
              "doc_values" : true
            },
            "match" : "*",
            "match_mapping_type" : "float"
          }
        }, {
          "double field" : {
            "mapping" : {
              "type" : "double",
              "doc_values" : true
            },
            "match" : "*",
            "match_mapping_type" : "double"
          }
        }, {
          "byte field" : {
            "mapping" : {
              "type" : "byte",
              "doc_values" : true
            },
            "match" : "*",
            "match_mapping_type" : "byte"
          }
        }, {
          "short field" : {
            "mapping" : {
              "type" : "short",
              "doc_values" : true
            },
            "match" : "*",
            "match_mapping_type" : "short"
          }
        }, {
          "binary field" : {
            "mapping" : {
              "type" : "binary",
              "doc_values" : true
            },
            "match" : "*",
            "match_mapping_type" : "binary"
          }
        }, {
          "geo_point field" : {
            "mapping" : {
              "type" : "geo_point",
              "doc_values" : true
            },
            "match" : "*",
            "match_mapping_type" : "geo_point"
          }
        }, {
          "string fields" : {
            "mapping" : {
              "index" : "not_analyzed",
              "omit_norms" : true,
              "type" : "string",
              "doc_values" : true
            },
            "match" : "*",
            "match_mapping_type" : "string"
          }
        } ],
        "properties" : {
          "@timestamp" : {
            "type" : "date",
            "format" : "strict_date_optional_time||epoch_millis"
          },
          "alert_info" : {
            "properties" : {
              "command" : {
                "type" : "string",
                "index" : "not_analyzed"
              },
              "type" : {
                "type" : "string",
                "index" : "not_analyzed"
              }
            }
          },
          "alert_sent" : {
            "type" : "boolean"
          },
          "alert_time" : {
            "type" : "date",
            "format" : "strict_date_optional_time||epoch_millis"
          },
          "match_body" : {
            "properties" : {
              "@timestamp" : {
                "type" : "date",
                "format" : "strict_date_optional_time||epoch_millis"
              },
              "_id" : {
                "type" : "string",
                "index" : "not_analyzed"
              },
              "_index" : {
                "type" : "string",
                "index" : "not_analyzed"
              },
              "_type" : {
                "type" : "string",
                "index" : "not_analyzed"
              },
              "attacker" : {
                "type" : "string",
                "index" : "not_analyzed"
              },
              "attackerCN" : {
                "type" : "string",
                "index" : "not_analyzed"
              },
              "duration" : {
                "type" : "string",
                "index" : "not_analyzed"
              },
              "eventEnd" : {
                "type" : "string",
                "index" : "not_analyzed"
              },
              "eventStart" : {
                "type" : "string",
                "index" : "not_analyzed"
              },
              "ifindex" : {
                "type" : "string",
                "index" : "not_analyzed"
              },
              "interface" : {
                "type" : "string",
                "index" : "not_analyzed"
              },
              "message" : {
                "type" : "string",
                "index" : "not_analyzed"
              },
              "portname" : {
                "type" : "string",
                "index" : "not_analyzed"
              },
              "range" : {
                "type" : "string",
                "index" : "not_analyzed"
              },
              "received_at" : {
                "type" : "date",
                "format" : "strict_date_optional_time||epoch_millis"
              },
              "rootcause" : {
                "type" : "string",
                "index" : "not_analyzed"
              },
              "snmptrap_error_index" : {
                "type" : "string",
                "index" : "not_analyzed"
              },
              "snmptrap_error_status" : {
                "type" : "string",
                "index" : "not_analyzed"
              },
              "snmptrap_generic_trap_type" : {
                "type" : "string",
                "index" : "not_analyzed"
              },
              "snmptrap_host" : {
                "type" : "string",
                "index" : "not_analyzed"
              },
              "snmptrap_hostname" : {
                "type" : "string",
                "index" : "not_analyzed"
              },
              "snmptrap_oid" : {
                "type" : "string",
                "index" : "not_analyzed"
              },
              "snmptrap_payload" : {
                "type" : "string",
                "index" : "not_analyzed"
              },
              "syslog_host" : {
                "type" : "string",
                "index" : "not_analyzed"
              },
              "syslog_host,syslog_message" : {
                "type" : "string",
                "index" : "not_analyzed"
              },
              "syslog_hostname" : {
                "type" : "string",
                "index" : "not_analyzed"
              },
              "syslog_message" : {
                "type" : "string",
                "index" : "not_analyzed"
              },
              "timestamp" : {
                "type" : "date",
                "format" : "strict_date_optional_time||epoch_millis"
              },
              "type" : {
                "type" : "string",
                "index" : "not_analyzed"
              }
            }
          },
          "rule_name" : {
            "type" : "string",
            "index" : "not_analyzed"
          }
        }
      },
      "_default_" : {
        "_all" : {
          "enabled" : false
        },
        "dynamic_templates" : [ {
          "integer field" : {
            "mapping" : {
              "type" : "integer",
              "doc_values" : true
            },
            "match" : "*",
            "match_mapping_type" : "integer"
          }
        }, {
          "date field" : {
            "mapping" : {
              "type" : "date",
              "doc_values" : true
            },
            "match" : "*",
            "match_mapping_type" : "date"
          }
        }, {
          "long field" : {
            "mapping" : {
              "type" : "long",
              "doc_values" : true
            },
            "match" : "*",
            "match_mapping_type" : "long"
          }
        }, {
          "float field" : {
            "mapping" : {
              "type" : "float",
              "doc_values" : true
            },
            "match" : "*",
            "match_mapping_type" : "float"
          }
        }, {
          "double field" : {
            "mapping" : {
              "type" : "double",
              "doc_values" : true
            },
            "match" : "*",
            "match_mapping_type" : "double"
          }
        }, {
          "byte field" : {
            "mapping" : {
              "type" : "byte",
              "doc_values" : true
            },
            "match" : "*",
            "match_mapping_type" : "byte"
          }
        }, {
          "short field" : {
            "mapping" : {
              "type" : "short",
              "doc_values" : true
            },
            "match" : "*",
            "match_mapping_type" : "short"
          }
        }, {
          "binary field" : {
            "mapping" : {
              "type" : "binary",
              "doc_values" : true
            },
            "match" : "*",
            "match_mapping_type" : "binary"
          }
        }, {
          "geo_point field" : {
            "mapping" : {
              "type" : "geo_point",
              "doc_values" : true
            },
            "match" : "*",
            "match_mapping_type" : "geo_point"
          }
        }, {
          "string fields" : {
            "mapping" : {
              "index" : "not_analyzed",
              "omit_norms" : true,
              "type" : "string",
              "doc_values" : true
            },
            "match" : "*",
            "match_mapping_type" : "string"
          }
        } ]
      }
    }
    }
  }

Any ideas of how I should proceed?

**Comment by Qmando** [comment]
Delete the index and recreate it. There's some issue with not all mappings applying cleanly sometimes. Sorry about that.

**Comment by stefansaye** [comment]
Qmando,
I have delete it and recreate ,

    # curl -XDELETE 'X.X.X.X:9200/elastalert_status'
    {"acknowledged":true}
    # elastalert-create-index
    New index name? (Default elastalert_status)
    Name of existing index to copy? (Default None)
    Index elastalert_status already exists. Skipping index creation.


but still got the error 
     No mapping found for [until] in order to sort on

**Comment by Qmando** [comment]
It said ``Index elastalert_status already exists`` after you deleted it?

**Comment by stefansaye** [comment]
Qmando,
YES, ElastAlert still running in the background.
Am I have to stop elastalert first when I delete the elastalert-status ?

**Comment by Qmando** [comment]
Yes.

**Comment by stefansaye** [comment]
Qmando,
I have stop elastalert and delete the elastalert-status,
then create the index again , but still get the error message again 


    run curl -XGET 'http://X.X.X.X:9200/elastalert_status/_mapping/elastalert_status'
    {
      "elastalert_status" : {
        "mappings" : {
          "elastalert_status" : {
            "_all" : {
              "enabled" : false
            },
        "dynamic_templates" : [ {
          "integer field" : {
            "mapping" : {
              "type" : "integer",
              "doc_values" : true
            },
            "match" : "*",
            "match_mapping_type" : "integer"
          }
        }, {
          "date field" : {
            "mapping" : {
              "type" : "date",
              "doc_values" : true
            },
            "match" : "*",
            "match_mapping_type" : "date"
          }
        }, {
          "long field" : {
            "mapping" : {
              "type" : "long",
              "doc_values" : true
            },
            "match" : "*",
            "match_mapping_type" : "long"
          }
        }, {
          "float field" : {
            "mapping" : {
              "type" : "float",
              "doc_values" : true
            },
            "match" : "*",
            "match_mapping_type" : "float"
          }
        }, {
          "double field" : {
            "mapping" : {
              "type" : "double",
              "doc_values" : true
            },
            "match" : "*",
            "match_mapping_type" : "double"
          }
        }, {
          "byte field" : {
            "mapping" : {
              "type" : "byte",
              "doc_values" : true
            },
            "match" : "*",
            "match_mapping_type" : "byte"
          }
        }, {
          "short field" : {
            "mapping" : {
              "type" : "short",
              "doc_values" : true
            },
            "match" : "*",
            "match_mapping_type" : "short"
          }
        }, {
          "binary field" : {
            "mapping" : {
              "type" : "binary",
              "doc_values" : true
            },
            "match" : "*",
            "match_mapping_type" : "binary"
          }
        }, {
          "geo_point field" : {
            "mapping" : {
              "type" : "geo_point",
              "doc_values" : true
            },
            "match" : "*",
            "match_mapping_type" : "geo_point"
          }
        }, {
          "string fields" : {
            "mapping" : {
              "index" : "not_analyzed",
              "omit_norms" : true,
              "type" : "string",
              "doc_values" : true
            },
            "match" : "*",
            "match_mapping_type" : "string"
          }
        } ],
        "properties" : {
          "@timestamp" : {
            "type" : "date",
            "format" : "strict_date_optional_time||epoch_millis"
          },
          "endtime" : {
            "type" : "date",
            "format" : "strict_date_optional_time||epoch_millis"
          },
          "hits" : {
            "type" : "long"
          },
          "matches" : {
            "type" : "long"
          },
          "rule_name" : {
            "type" : "string",
            "index" : "not_analyzed"
          },
          "starttime" : {
            "type" : "date",
            "format" : "strict_date_optional_time||epoch_millis"
          },
          "time_taken" : {
            "type" : "double"
          }
        }
        }
        }
      }
    }

**Comment by allantaylor81** [comment]
the same prolem

**Comment by kmeinster** [comment]
Might be a long shot but could you show how the timestamp in your index is set within elastic? (index pattern). We have quite some developers writing against elastic instead of using logstash.

In short, those indices have "timestamp" instead of "@timestamp" if it doesn't contain the little neat @ symbol in front, it fails with the exact same error :)

**Comment by Qmando** [comment]
If you upload documents with logstash, Elasticsearch will generate a mapping for you.

@kmeinster you can add
```
timestamp_field: timestamp
```
