### ISSUE TITLE
 Compare fields using enhancement

### ISSUE THREAD

**Issue by leandrob04** [Yelp/elastalert#1109]
Hi,
I am having problem like issue #964. I wonder if I use enhancement, can use a filter in the rule? My demand compares to Web access IPs with threat IPs, does this solve my problem?

I'm starting with the solution and we were in doubt how I can do this

Thank you for help!

**Comment by Qmando** [comment]
Yes, you can use filters and enhancements at the same time.

**Comment by leandrob04** [comment]
Well, I think this enhancements model does not work well in my case because I have to do the two field searches and after that compare.
Do you have any suggestions not too advanced to solve this problem?

**Comment by Qmando** [comment]
Can you explain the scenario you want?

You have web access IP logs, and you want to compare that to a list of threat IPs? Are the threat IPs also stored in Elasticsearch? Is it a static list?

**Comment by leandrob04** [comment]
Yes, all information is on elasticsearch. I have a field in an index called client_ip and another field in another index called threat_ip.

**Comment by Qmando** [comment]
Why would the enhancement from the other issue not work?

**Comment by leandrob04** [comment]
I've been researching and I think this improvement solves my problem but I had trouble running. I changed all the required fields but an error occurred.

Can you help me? Thank you.

![error1](https://cloud.githubusercontent.com/assets/28788376/26653985/68c34796-462b-11e7-9604-1eaabe5e1e69.png)
![error2](https://cloud.githubusercontent.com/assets/28788376/26654019/892b9b50-462b-11e7-971b-15889ce4166b.png)

**Comment by Qmando** [comment]
Instead of 
```
super(IsIPMalicious, self)
```
you want
```
super(IsIPMalicious, self).__init__(*args)
```

**Comment by leandrob04** [comment]
It worked, but again an error occurred

![error4](https://cloud.githubusercontent.com/assets/28788376/26657374/d1d23d56-4639-11e7-8cf0-19d82dd5a2b0.png)

**Comment by Qmando** [comment]
Leave the line as I posted it, ``es = Elasticsearch(host=self.rule['es_host'], port=self.rule['es_port'])``

**Comment by leandrob04** [comment]
This worked perfectly. Just as a remark to anyone who uses this kind of rule, `search_type` is not necessary in elasticsearch 5.

One last question, would it be possible to record in the email alert the IP that had relation between the two indexes and the timestamp?

I made this rule but it did not work.

![error5](https://cloud.githubusercontent.com/assets/28788376/26700169/c310d07a-46f2-11e7-8140-cc08314cbc28.png)

**Comment by Qmando** [comment]
Your config looks correct. It shows up as ``<MISSING VALUE>``?

**Comment by leandrob04** [comment]
I tested both ways, with or without `alert_text_only`. The strange thing is that it doesn't send in both ways and in kibana doesn't appear the email error status only the status of hits and matches.

Can there be something in the improvement that is causing the problem?

**Comment by Qmando** [comment]
Please tell me you're not actually sending it to "elastalert@example.com"

**Comment by leandrob04** [comment]
No, it's just a test. Because if you were send the email would give an elastalert_error smtp

**Comment by Qmando** [comment]
You think this doesn't work because it doesn't give you an error?

Are you actually running elastalert or just using "elastalert-test-rule"?

**Comment by leandrob04** [comment]
Yes, it's running as a daemon. I already tried sending gmail the alert, but it does not work.

Even with the little experience I have with the tool I know I should have feedback from the alert, if worked or not. This doesn't even occur.

**Comment by Qmando** [comment]
Are you running it with ``--verbose`` flag and capturing the output? It will say ``Email sent to elastalert@example.com`` if it succeeds. It will also create a document in elasticsearch with ``_type: elastalert`` with either ``alert_sent: false`` or ``alert_sent: true`` if it fails or succeeds.

**Comment by leandrob04** [comment]
Yes, it's matching but the alert isn't being triggered. The `alert_sent` message isn't created in elasticsearch.
![error6](https://cloud.githubusercontent.com/assets/28788376/26738695/78a7256c-47a5-11e7-9734-59bba79409cd.png)

**Comment by Qmando** [comment]
``Ignoring match for silenced rule`` means that you ran the rule at some point with a ``realert`` setting, causing a silence stash to be created. The default is actually 1 minute, but if you see this message all the time, it's seems like it's been set previously.

You can bypass this by either changing the rule's name, or, deleting all documents of ``_type: elastalert_silence`` from Elasticsearch and restarting Elastalert.

You'll still get only 1 alert per query unless you add
```
realert:
  minutes: 0
```
to the config.

**Comment by leandrob04** [comment]
Interesting. I made the modifications that you suggest to me but the rule continues with the same problem.

**Comment by Qmando** [comment]
Do you have logs from when elastalert starts with the new rule name?

**Comment by leandrob04** [comment]
![error7](https://cloud.githubusercontent.com/assets/28788376/26740045/765eb75c-47aa-11e7-8c26-8067d4b67908.png)

**Comment by Qmando** [comment]
Oooh I know the issue. Sorry I didn't suggest this earlier. You need to add either

```
realert:
  minutes: 0
```

which will prevent silence stashes from ever being created

OR 

```
run_enhancements_first: true
```

whcih is to prevent a "match" from creating a silence stash but THEN getting dropped by the enhancement.

**Comment by leandrob04** [comment]
Well, the problem of silence doesn't have more however it still doesn't trigger the email alert
![error7](https://cloud.githubusercontent.com/assets/28788376/26741073/61332ce2-47ae-11e7-80dd-b98a65964675.png)

.

**Comment by Qmando** [comment]
Did you mean to post the same screenshot again?

**Comment by leandrob04** [comment]
Sorry, I put a wrong image, but I did some more tests and the rule really works successfully. Thanks a lot for the help. The work done by the tool's developers is really good.
