### ISSUE TITLE
alert command format for snmptrap execution

### ISSUE THREAD

**Issue by mrchang7** [Yelp/elastalert#1113]
Hi,

I'm trying to format a command alert with 'snmptrap' linux command. It's usage goes like: 
  USAGE: snmptrap [OPTIONS] AGENT TRAP-PARAMETERS

I tried something like below by providing the alert_args from enhancement module: 
  command: ["snmptrap", "-v", "2c", "-c", "public", "{match[alert_args]}"]

But it throws this issue:
getaddrinfo("nms:1620 '' .........(trap parameter list with spaces)...........", NULL, ...): Name or service not known
snmptrap:

So, I'm wondering how to correctly format the command to be executed. The same command works at the plain command-line prompt. 

Thanks!

**Comment by mrchang7** [comment]
We found if we make it a single string without using list [ ] in the command, it works.

**Comment by Qmando** [comment]
The difference is whether shell=True is passed to subprocess.Popen. If the command depends on shell tricks, it would work as a string but not as a list. As examples, if you wanted to use $ENV variables or ~ (home dir) in your command, you would need for it to be a string.

**Comment by mrchang7** [comment]
Thanks Qmando. That explains well.
