### ISSUE TITLE
ImportError: DLL load failed: The specified procedure could not be found

### ISSUE THREAD

**Issue by haoc** [Yelp/elastalert#1120]
I'm having trouble running elastalert. This is the error I'm getting. 

![elastalert](https://cloud.githubusercontent.com/assets/6219058/26362177/d0745ca2-3fa2-11e7-87e4-fbbbe939dd74.png)

I'm able to create an index, but I'm not sure what I'm missing as I can't run it.

Thanks.

**Comment by Qmando** [comment]
You seem to have a broken blist installation. Try installing from here, http://www.lfd.uci.edu/~gohlke/pythonlibs/#blist

I have very limited experience with Python on Windows so I can't give you more detailed instructions.

**Comment by haoc** [comment]
I did `pip install blist-1.3.6-cp27-cp27m-win_amd64.whl` with the file I got from [here](http://www.lfd.uci.edu/~gohlke/pythonlibs/#blist). 

I'm running Widows 7 Enterprise x64.

Is there a certain way/directory I need to install the blist?

**Comment by Qmando** [comment]
Try running ``pip install --upgrade pip wheel`` first?

**Comment by haoc** [comment]
Actually, I just deleted my blist and ran `pip install blist` and it fixes it. Not sure why my blist was broken in the first place, but a fresh new install fixed it. Thanks.
