### ISSUE TITLE
can i send alerts generated from elastlaert to any event management tool?

### ISSUE THREAD

**Issue by shahinasm** [Yelp/elastalert#1122]
Hi,
can i send alerts generated from elastlaert to any event management tool?

like zenoss, netcool, alerta.io...

if it is possible can you suggest the procedure for it.

**Comment by Qmando** [comment]
Elastalert supports simple HTTP POSTs and arbitrary commands, so you can probably make it work with those.

http://elastalert.readthedocs.io/en/latest/ruletypes.html?#command for the command alerter.

The POST one is actually missing documentation but the code is here, https://github.com/Yelp/elastalert/blob/master/elastalert/alerts.py#L1267, you would use it with "simple" type alerter.

**Comment by shahinasm** [comment]
Thank You
