### ISSUE TITLE
relative path for smtp_auth_file?

### ISSUE THREAD

**Issue by yuanxu-li** [Yelp/elastalert#1127]
To specify email alert, we need to provide `smtp_auth_file` as:
```
smtp_auth_file: /home/justin/credentials/auth.yaml
```

Since I need to set it up in different places, I am wondering if it is possible that we can specify the auth file as a relative path, so that I can put `auth.yaml` under the same directory, and use it like:
```
smtp_auth_file: auth.yaml
```

Looks like it only supports absolute file path right now.

**Comment by Qmando** [comment]
I think technically it does support relative paths, but that is relative to CWD when you run Python, not to the rule file. In other places we do support relative-to-the-rule-yaml paths, so this would be a good feature to add.
