### ISSUE TITLE
FOSS Approval

### ISSUE THREAD

**Issue by mrchang7** [Yelp/elastalert#1132]
I have a few questions on trying to get FOSS approval of this package. FYI, our platform is RH7.2.

- Elastalert is installed on top of lots of packages (requirements.txt and more). Do we need to get the FOSS approval for each of the packages to use it for commercial purpose? 

- Actually we do not use most of the alert types, then can we take them off in our codes? Would this fall into the "modification of codes" and be permissible? 

Thanks!

**Comment by Qmando** [comment]
Well, I am not a lawyer, but, this is licensed under Apache which basically means you can do anything you want with it. You can visit https://pypi.python.org/pypi/PACKAGENAME to see the license for each library used.

You can definitely get rid of most of the alert types. If you remove the imports at the top of alerts.py, you can skip installing the respective libraries (twilio, exotel, jira, etc) and everything should work fine as long as you don't use those alerters.

**Comment by mrchang7** [comment]
Thanks Qmando. 

Is texttable also something I can remove? Looks like I can as long as I don't use two options as in the code below:

   if 'aggregation' in self.rule and 'summary_table_fields' in self.rule:

**Comment by Qmando** [comment]
Correct, it's only used if you use ``summary_table_fields``

**Comment by mrchang7** [comment]
Okay great thanks!
