### ISSUE TITLE
Elastalert run as service 

### ISSUE THREAD

**Issue by windowsansiblernew** [Yelp/elastalert#1134]
i followed this thread for running elastalert as service in ubuntu through systemd but it keeps failing, any help?
https://github.com/Yelp/elastalert/issues/194

**Comment by Qmando** [comment]
Please give more information. What is failing.

**Comment by windowsansiblernew** [comment]
i was trying systemd in ubuntu, can we run elastalert as service in amazon linux?

**Comment by Qmando** [comment]
You still haven't given any information as to how it's failing or what exactly you tried. You can run it as a service under any type of Linux, provided you've got the right service config file or init script.

**Comment by windowsansiblernew** [comment]
i got this resolved by moving to a new server..thanks for your time :)

**Comment by Qmando** [comment]
Duplicate of #194
