### ISSUE TITLE
index_not_found_exception when trying to use "elastalert-rule-from-kibana" to create partial config

### ISSUE THREAD

**Issue by monitoringit** [Yelp/elastalert#1139]
I am using 5.2.1 ES and 0.1.14 elastalert version. When i try to create partial configuration from kibana dashboard, i get this exception.
**(elastalert) [root@ip-10-93-73-114 elastalert]# elastalert-rule-from-kibana
Elasticsearch host: elasticsearch.xxx.com
Elasticsearch port: 9200
Dashboard name: Vault Requests Analysis
Method for querying Elasticsearch[GET]:**
WARNING:elasticsearch:GET http://elasticsearch.xxx.com:9200/kibana-int/dashboard/_search?_source_include=dashboard [status:404 request:0.004s]
Traceback (most recent call last):
  File "/opt/elastalert/bin/elastalert-rule-from-kibana", line 11, in <module>
    sys.exit(main())
  File "/opt/elastalert/local/lib/python2.7/site-packages/elastalert/rule_from_kibana.py", line 21, in main
    res = es.search(index='kibana-int', doc_type='dashboard', body=query, _source_include=['dashboard'])
  File "/opt/elastalert/local/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 73, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/opt/elastalert/local/lib/python2.7/site-packages/elasticsearch/client/__init__.py", line 623, in search
    doc_type, '_search'), params=params, body=body)
  File "/opt/elastalert/local/lib/python2.7/site-packages/elasticsearch/transport.py", line 312, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/opt/elastalert/local/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py", line 128, in perform_request
    self._raise_error(response.status, raw_data)
  File "/opt/elastalert/local/lib/python2.7/site-packages/elasticsearch/connection/base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.NotFoundError: TransportError(404, u'index_not_found_exception', u'no such index')

**Comment by Qmando** [comment]
Are you using Kibana3?

**Comment by monitoringit** [comment]
I am using kibana ver 5.2.1


Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Quentin Long <notifications@github.com> Date: 6/2/17  1:35 PM  (GMT-05:00) To: Yelp/elastalert <elastalert@noreply.github.com> Cc: monitoringit <krajshiva@gmail.com>, Author <author@noreply.github.com> Subject: Re: [Yelp/elastalert] index_not_found_exception when trying to use "elastalert-rule-from-kibana" to create partial config (#1139) 
Are you using Kibana3?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Yelp/elastalert","title":"Yelp/elastalert","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Yelp/elastalert"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Qmando in #1139: Are you using Kibana3?"}],"action":{"name":"View Issue","url":"https://github.com/Yelp/elastalert/issues/1139#issuecomment-305860351"}}}
