### ISSUE TITLE
elastalert-test-rule does not exit with a proper error code when there is a ConnectionError on Linux

### ISSUE THREAD

**Issue by ehouarn-perret** [Yelp/elastalert#1143]
Hi there,

First, thanks for the good work, ElastAlert is really a great piece of software and I really like the fact that it carries a tool like elastalert-test-rule for testing purposes, which turns to be particularly useful when using it as part of a CI process. 

However, it's a bit of a pain since the wrapper (of the underlying Python script) elastalert-test-rule, does not actually return an error code different from 0 when there are for example some actual errors like say ConnectionErrors.

Typically here is an example of a rule that fails because the es_host is not properly set:

```

Traceback (most recent call last):
  File "/opt/elastalert/.env/lib/python2.7/site-packages/elasticsearch/connection/http_requests.py", line 56, in perform_request
    response = self.session.request(method, url, data=body, timeout=timeout or self.timeout)
  File "/opt/elastalert/.env/lib/python2.7/site-packages/requests/sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/elastalert/.env/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/opt/elastalert/.env/lib/python2.7/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
ERROR:root:Error running query: ConnectionError(('Connection aborted.', gaierror(-2, 'Name or service not known'))) caused by: ConnectionError(('Connection aborted.', gaierror(-2, 'Name or service not known')))
elastalert_error - {'message': "Error running query: ConnectionError(('Connection aborted.', gaierror(-2, 'Name or service not known'))) caused by: ConnectionError(('Connection aborted.', gaierror(-2, 'Name or service not known')))", 'traceback': ['Traceback (most recent call last):', '  File "/opt/elastalert/.env/lib/python2.7/site-packages/elastalert-0.1.3-py2.7.egg/elastalert/elastalert.py", line 250, in get_hits', "    res = self.current_es.search(scroll=scroll_keepalive, index=index, size=rule['max_query_size'], body=query, ignore_unavailable=True, **extra_args)", '  File "/opt/elastalert/.env/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 68, in _wrapped', '    return func(*args, params=params, **kwargs)', '  File "/opt/elastalert/.env/lib/python2.7/site-packages/elasticsearch/client/__init__.py", line 498, in search', '    params=params, body=body)', '  File "/opt/elastalert/.env/lib/python2.7/site-packages/elasticsearch/transport.py", line 301, in perform_request', '    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)', '  File "/opt/elastalert/.env/lib/python2.7/site-packages/elasticsearch/connection/http_requests.py", line 67, in perform_request', "    raise ConnectionError('N/A', str(e), e)", "ConnectionError: ConnectionError(('Connection aborted.', gaierror(-2, 'Name or service not known'))) caused by: ConnectionError(('Connection aborted.', gaierror(-2, 'Name or service not known')))"], 'data': {'rule': 'my issues'}}
```

Imho this should return something explicit to the caller (e.g. bash) but turns out nope, we just get 0 as (non) error code.

I double checked the documentation:
- https://elastalert.readthedocs.io/en/latest/running_elastalert.html#testing-your-rule)
- https://elastalert.readthedocs.io/en/latest/ruletypes.html#testing  

But it seems there is nothing to enforce that there should be something stopping the test when there is something wrong.

I think it should be the responsibility of the wrapper (i.e. ownership) to return that something went wrong instead letting me grep or use regular expressions on the output to determine if any errors have been raised.

Is there a proper workaround for that? Grepping it's definitely not errorproof and lacks of clarity.
I was thinking about running the actual underlying Python wrapped with a try / catch clause but not sure this is going to be any better. I am not against writing my own tooling for that purpose, but would like to know whether there is already something out there that could me help out to achieve what I am aiming at.

**Comment by Qmando** [comment]
Hm, this is a good point. The underlying elastalert code catches most exceptions so errors will generally show up as the ``elastalert_error - {'message': ....}`` line that you've shared.

I'll probably add something like 
```
@@ -256,8 +256,13 @@ class MockElastAlerter(object):

             if mock_writeback.call_count:
                 print("\nWould have written the following documents to writeback index (default is elastalert_status):\n")
+                errors = False
                 for call in mock_writeback.call_args_list:
                     print("%s - %s\n" % (call[0][0], call[0][1]))
+                    if call[0][0] == 'elastalert_error':
+                        errors = True
+                if errors:
+                    exit(1)
```
which is effectively the same as your grep method.

There's probably a couple other places where "errors" can occur without changing the exit code and without emitting an ``elastalert_error`` document, so this is definitely not a comprehensive fix.

**Comment by ehouarn-perret** [comment]
@Qmando thanks that's also what I figured out. Actually I am wondering if I just remove all the return None and raise the related exception in [base_path\elastalert\test_rule.py](https://github.com/Yelp/elastalert/blob/master/elastalert/test_rule.py) it should also be fine, right?

**Comment by Qmando** [comment]
Yeah those changes would probably be fine too. I'm willing to merge this if you open a pull request.

**Comment by ehouarn-perret** [comment]
@Qmando ok then will work on that tonight and create a pull request
I am thinking about something like `elastalert-test-rule --error-stop`
Just require a bit of change in the parser of `run_rule_test ` function and instead of `return None` to raise the error that is supposedly caught.

By the way, if you have a better terminology for the argument, just let me know.

**Comment by ehouarn-perret** [comment]
@Qmando just created the pull-request, created something quite simple, a bit stricter than what you suggested, maybe a bit too dumb.

Pull request: https://github.com/Yelp/elastalert/pull/1153
May want to add unit tests tho ~~

CI: https://travis-ci.org/Yelp/elastalert/builds/240241603?utm_source=github_status&utm_medium=notification
