### ISSUE TITLE
timestamp_field error with unix type.

### ISSUE THREAD

**Issue by qingxp9** [Yelp/elastalert#1144]
```
ERROR:root:Error running query: TransportError(400, u'search_phase_execution_exception', u'failed to parse date
 field [1.496638310584814E9] with format [epoch_second]')
```
How can i solve it?

**Comment by Qmando** [comment]
I think this is an Elasticsearch issue: https://github.com/elastic/elasticsearch/issues/21489

See discussion from https://github.com/Yelp/elastalert/issues/996

I'm not actually sure how to solve it

**Comment by Qmando** [comment]
Closing as duplicate of #996
