### ISSUE TITLE
Help Adding new Rule Type

### ISSUE THREAD

**Issue by umerebryx** [Yelp/elastalert#1146]
Hi Guys,
I have come across a use case that is not handled by any of the existing rule types (correct me if I am wrong). I will explain what I am trying to achieve first:

I have an application logs that I need to monitor, one particular event that I am looking for is "userlogin". I have a rule that will alert when there are multiple "failed login attempts" this is being handled by "frequency" Rule type. Now I want to take this a step further and write a rule that can alert whenever there is a bruteforce attempt on a user account. That means I not only have to look for:

> errorMessage: 'Failed authentication'

I will also need something that will keep track of userName field.

> userName : xxxxx

Now if I use 'frequency'  rule type for this scenario with below filter:
```
filter:
- query:
   query_string:
     query: "(eventName : ConsoleLogin) AND (errorMessage : Failed authentication)"
```
I will wrongly get a brutforce alert since 'frequency' rule type doesn't keep track of 'userName' field. I need a rule similar to 'frequency' but which will only trigger if a second field is constant which in my case is 'userName'.

Any suggestion is welcome. If there is an existing rule that can handle this please let me know, if not please suggest how can I add a custom rule type to handle this scenario.

Thanks

**Comment by cbarbaza** [comment]
Hi @umerebryx ,
If i understand will you want detect brut force behavior for each user ?
I think you can look at the "query_key" option.
This option will make your rule unique for each field that you put on "query_key".

In my case i use it to have a rule that send alert for each of my server with the option : query_key:["hostname"]
In the documentation : https://elastalert.readthedocs.io/en/latest/ruletypes.html#frequency 

> query_key: Counts of documents will be stored independently for each value of query_key

Best regards.

**Comment by umerebryx** [comment]
@cbarbaza , thanks for your prompt response. I tried 'query_key' option. Below is the final query that elastalert generates against my rule:
```
{
  "aggs": {
    "filtered": {
      "aggs": {
        "counts": {
          "terms": {
            "field": "userIdentity.userName",
            "size": 50
          }
        }
      },
      "filter": {
        "bool": {
          "must": [
            {
              "range": {
                "@timestamp": {
                  "gt": "2017-04-06T09:48:55.406366Z",
                  "lte": "2017-06-06T09:49:55.406366Z"
                }
              }
            },
            {
              "query": {
                "query_string": {
                  "query": "(eventName : ConsoleLogin) AND (errorMessage : Failed authentication)"
                }
              }
            }
          ]
        }
      }
    }
  }
}
```
If I run this manually I get all documents from my ES domain instead of the ones matching this query.  
Can you please share an example rule that you have used. Thanks

**Comment by Qmando** [comment]
Just take your existing rule and add ``query_key: userIdentity.userName`` and it will work as you expect. 

When you use that query that elastalert generated, what API are you hitting? Are you getting both documents AND aggregation results? Have you actually confirmed that it *doesn't* work in Elastalert or did you only try copying the filter?

If you don't use the count search type you will also get individual documents back, and the filters only apply to the aggregation, so these will be random documents.

**Comment by umerebryx** [comment]
@Qmando @cbarbaza  , thanks guys, 'query_key' did exactly what I was looking for.
