### ISSUE TITLE
boto3 is a mandatory package? 

### ISSUE THREAD

**Issue by mrchang7** [Yelp/elastalert#1149]
Hi,

I'm checking the license of the python packages. 

Among other things, boto3 appears being used in auth.py. As dependency boto3 requires botocore which uses docutils, which is mixed of BSD and GPL licenses. 

Wondering if the elastalert can work without boto3 (and aws-requests-auth). If possible, how can we modify the codes? 

Or can we have a way not use the package docutils? 

Thanks!

**Comment by mrchang7** [comment]
For the question I raised above. I tried the following code for auth.py and it looks working. Will it be alright with this if we don't use AWS? 

`# -*- coding: utf-8 -*-
import os

class Auth(object):

    def __call__(self, host, username, password, aws_region, profile_name):
        """ Return the authorization header.

        :param host: Elasticsearch host.
        :param username: Username used for authenticating the requests to Elasticsearch.
        :param password: Password used for authenticating the requests to Elasticsearch.
        :param aws_region: AWS Region to use. Only required when signing requests.
        :param profile_name: AWS profile to use for connecting. Only required when signing requests.
        """
        if username and password:
            return username + ':' + password

        if not aws_region and not os.environ.get('AWS_DEFAULT_REGION'):
            return None

        return None
`

**Comment by Qmando** [comment]
Maybe I'm missing a reference, but you can delete auth.py and apply this diff:
```
--- a/elastalert/util.py
+++ b/elastalert/util.py
@@ -5,7 +5,6 @@ import logging

 import dateutil.parser
 import dateutil.tz
-from auth import Auth
 from elasticsearch import RequestsHttpConnection
 from elasticsearch.client import Elasticsearch
 from six import string_types
@@ -275,12 +274,6 @@ def replace_dots_in_field_names(document):
 def elasticsearch_client(conf):
     """ returns an Elasticsearch instance configured using an es_conn_config """
     es_conn_conf = build_es_conn_config(conf)
-    auth = Auth()
-    es_conn_conf['http_auth'] = auth(host=es_conn_conf['es_host'],
-                                     username=es_conn_conf['es_username'],
-                                     password=es_conn_conf['es_password'],
-                                     aws_region=es_conn_conf['aws_region'],
-                                     profile_name=es_conn_conf['profile'])

     return Elasticsearch(host=es_conn_conf['es_host'],
                          port=es_conn_conf['es_port'],
@@ -288,7 +281,6 @@ def elasticsearch_client(conf):
                          use_ssl=es_conn_conf['use_ssl'],
                          verify_certs=es_conn_conf['verify_certs'],
                          connection_class=RequestsHttpConnection,
-                         http_auth=es_conn_conf['http_auth'],
                          timeout=es_conn_conf['es_conn_timeout'],
                          send_get_body_as=es_conn_conf['send_get_body_as'])

diff --git a/elastalert/create_index.py b/elastalert/create_index.py
index 84dc180..270327a 100644
--- a/elastalert/create_index.py
+++ b/elastalert/create_index.py
@@ -9,7 +9,6 @@ import time
 import argparse
 import elasticsearch.helpers
 import yaml
-from auth import Auth
 from elasticsearch import RequestsHttpConnection
 from elasticsearch.client import Elasticsearch
 from elasticsearch.client import IndicesClient
@@ -85,12 +84,6 @@ def main():
         send_get_body_as = args.send_get_body_as

     timeout = args.timeout
-    auth = Auth()
-    http_auth = auth(host=host,
-                     username=username,
-                     password=password,
-                     aws_region=aws_region,
-                     profile_name=args.profile)

     es = Elasticsearch(
         host=host,
@@ -99,7 +92,6 @@ def main():
         use_ssl=use_ssl,
         verify_certs=verify_certs,
         connection_class=RequestsHttpConnection,
-        http_auth=http_auth,
         url_prefix=url_prefix,
         send_get_body_as=send_get_body_as)
```

**Comment by mrchang7** [comment]
Yes, it works with those diffs applied. Thanks for your swift response!!
