### ISSUE TITLE
Query different filters and different rules on multiple indices

### ISSUE THREAD

**Issue by kiranmai444** [Yelp/elastalert#1155]
I want to run multiple queries on multiple indices of elasticsearch in elastalert. How can I do that?
for example : I want to use the first filter and type "any" on index abc*, the second filter and type "frequency" on index xyz*

 

     type: any
     type: frequency
     index: abc*
     index: xyz*
     filter:
      - match:
        loglevel: "INFO"
     filter:
      - match:
        loglevel: "ERROR"

**Comment by Qmando** [comment]
You can't have multiple rules in a single file. Create two rule files.
