### ISSUE TITLE
Stuck in recursive run_query when using scroll

### ISSUE THREAD

**Issue by skiptomyliu** [Yelp/elastalert#1158]
Attempting to troubleshoot an issue that I'm seeing.  I'm using a frequency rule that will alert where it appears that self.num_hits never reaches self.total_hits  so it continues to call itself (def run_query).  It keeps running even after reaching the end timeframe because it expected to eventually gather all of self.total_hits.

`INFO:elastalert:Queried rule Bruteforce Login Detected from 2017-06-08 11:53 PDT to 2017-06-08 12:18 PDT: 31453 / 0 hits (scrolling..)`

I can of course modify the check to break out if it reaches the end of the timeframe, but I'm curious if there's any suggestions to troubleshoot as to why my self.num_hits never reaches and equals self.total_hits making it recurse forever.

**Comment by Qmando** [comment]
Hmm, I haven't encountered this before. When you make a query to Elasticsearch, it gives you a scroll ID and the total number of documents that will be returned in that scroll. It usually matches up nicely but I guess some times it doesn't. It would probably make sense to break out of the scroll if we get 0 results back.

**Comment by skiptomyliu** [comment]
Thanks for the suggestion @Qmando, I'll dig a bit further as well to determine what is the initial cause of the num_hits and total_hits mismatch.  Likely will end up just default breaking as you suggested.

We like the scroll feature because sometimes the results that are returned are exceptionally large even after modifying timeframe and after filtering results through the query as much as we possibly can.
