### ISSUE TITLE
Json Format for alert text

### ISSUE THREAD

**Issue by monitoringit** [Yelp/elastalert#1162]
I am trying to pass alert text as  JSON message to AWS SNS. Is there a way to do it? I am trying to form json output in alert_text but may be there is an easy way?
Example:

> alert_text_args:

- name
- beat.hostname
- stack
- message
- source
alert_text: '{ "RuleName": "{0}","Host": "{1}","Stack": "{2}","Message": "{3}", "LogPath": "{4}" }'
alert_text_type: alert_text_only

> 

Error Received==>
NFO:elastalert:Ran Grafana Service is not running from 2017-06-12 17:38 UTC to 2017-06-12 17:39 UTC: 0 query hits (0 already seen), 0 matches, 0 alerts sent
INFO:elastalert:Queried rule i-067bb50098c89750e-AnyRule from 2017-06-12 17:36 UTC to 2017-06-12 17:39 UTC: 2 / 2 hits
ERROR:root:Traceback (most recent call last):
  File "/opt/elastalert/local/lib/python2.7/site-packages/elastalert/elastalert.py", line 1169, in alert
    return self.send_alert(matches, rule, alert_time=alert_time)
  File "/opt/elastalert/local/lib/python2.7/site-packages/elastalert/elastalert.py", line 1246, in send_alert
    alert.alert(matches)
  File "/opt/elastalert/local/lib/python2.7/site-packages/elastalert/alerts.py", line 827, in alert
    body = self.create_alert_body(matches)
  File "/opt/elastalert/local/lib/python2.7/site-packages/elastalert/alerts.py", line 239, in create_alert_body
    body += unicode(BasicMatchString(self.rule, match))
  File "/opt/elastalert/local/lib/python2.7/site-packages/elastalert/alerts.py", line 132, in __str__
    self._add_custom_alert_text()
  File "/opt/elastalert/local/lib/python2.7/site-packages/elastalert/alerts.py", line 70, in _add_custom_alert_text
    alert_text = alert_text.format(*alert_text_values)
KeyError: u' "RuleName"'

**Comment by Qmando** [comment]
Add
```
alert_text_args:
 - host
 - stack
 - message
```

The rule name you have to staticly code

**Comment by monitoringit** [comment]
I think the issues is with trying to use curly braces to start the json message formation. As soon as it is sees curly braces it is thinking that i am referring it to variable. I tried escaping curlybraces using backslash but it doesnt help. When i remove curly braces, it sends the message.

**Comment by Qmando** [comment]
Use double brackets.
```
alert_text: '{{"RuleName": "{0}", /// }}'
```

**Comment by monitoringit** [comment]
Thanks double curly braces makes it work

**Comment by ulich** [comment]
A bit late, but I had the same problem and solved it like this:

I created a custom alerter, inheriting from the alerter i actually want to use (here: SNS)

```
import json
from elastalert.alerts import SnsAlerter

class SnsJsonAlerter(SnsAlerter):

    def create_alert_body(self, matches):
        return json.dumps(matches)
```
