### ISSUE TITLE
generate_kibana_link  doesn't work with 'and'/'or' in filter

### ISSUE THREAD

**Issue by Dmitry1987** [Yelp/elastalert#1168]
Issue type: bug report

When using 'and' in filter like:
```
filter:
- and:
  - term:
      level: "ERROR"
  - term:
      environment_type: "production"
```

the 'generate_kibana_link' option doesn't work:
``` 
elastalert.util.EAException: generate_kibana_link is incompatible with filters other than term, query_string and range. Consider creating a dashboard and using use_kibana_dashboard instead.
```

removing 'and' helps. but I think it should work with it too.

also I want to ask what does the link to kibana mean:  http://xxx.xx.xx.xx:9200/_plugin/kibana/#/dashboard/temp/AVynIPc57uefRtV5UnuR

is it a temporary graph created dynamically by elastalert during search?  I didn't find any documentation about those options:

![image](https://user-images.githubusercontent.com/9369080/27140003-25c56d36-512d-11e7-9c8b-e0f7e0b4a895.png)

what does 'use_kibana_dashboard' do, which dashboard it will use?
and which values I can put into 'kibana4_start_timedelta' for example, is it dynamic like from "buffer_time" or depends on a rule type? (I guess it will show a graph with "from" - " to" times of the alert period which triggered it)

thanks :)

**Comment by Qmando** [comment]
Remove the and from your filter. Everything is already joined with an implicit and.

http://elastalert.readthedocs.io/en/latest/ruletypes.html#use-kibana-dashboard

http://elastalert.readthedocs.io/en/latest/ruletypes.html?highlight=kibana4_start_timedelta#kibana4-start-timedelta

```
kibana4_start_timedelta:
  minutes: 60
```
will give you 60 minutes back from the alert time in the default time window.

**Comment by Dmitry1987** [comment]
Thanks @Qmando !  I used the search in sidebar and because it always pointed to only 1 page I assumed there's no more pages where each param explained :) such a shame.. 

Another question:  is it possible to edit the mail templates somehow?  which python file responsible for it so I can hack on it? :P

**Comment by Qmando** [comment]
You can use ``alert_text`` to change the contents of the alert, along with ``alert_text_args``, ``alert_text_type``, etc.
It's generated using this class: https://github.com/Yelp/elastalert/blob/master/elastalert/alerts.py#L42

**Comment by Dmitry1987** [comment]
Supercool! I was able to find and modify also the victorops fields that I need.  Also I did a small "enhancement" module like on this example:  http://elastalert.readthedocs.io/en/latest/recipes/adding_enhancements.html#enhancements

and it works, just fails in case I want to skip matches with "DropMatchException"  :(  I'll open a separate issue, so it'll be searchable for others who might have it. 
thank you!

**Comment by Qmando** [comment]
You're importing DropMatchException and not creating a new class, right?

**Comment by Dmitry1987** [comment]
Hi @Qmando , it is my bad python knowledge.. I just didn't imported anything expected this function to just work (thought maybe it's in the 'enhancement' object :) ). Then I did a quick search on code and saw it, then realized I just need to import.  then it worked :+1: 
thanks!
