### ISSUE TITLE
Error Installing and Can't Create Index

### ISSUE THREAD

**Issue by JimKeating2** [Yelp/elastalert#1180]
Have tried several times to install on Debian 8 VM with the same error at the "python setup.py install" part of the installation process:   (I found that it is a critical error because I cannot create an index.)

Installed /usr/local/lib/python2.7/dist-packages/chardet-3.0.4-py2.7.egg
error: six 1.8.0 is installed but six>=1.9 is required by set(['mock'])

Install commands:
cd /opt
apt-get install python-pip python-dev libffi-dev libssl-dev git
git clone https://github.com/Yelp/elastalert.git
cd /elastalert
pip install "setuptools>=11.3"
python setup.py install
pip install "elasticsearch>=5.0.0"

I looked over a previous thread # 1084 but could not glean anything from it.
Not a python guru but sure would appreciate some help as we need to get email alerts setup.
Thanks in advance for your help!   JK

jimk@dcpud.org

**Comment by Qmando** [comment]
Try installing via pip instead.

**Comment by JimKeating2** [comment]
I've fixed the issue by doing a "pip install --upgrade six" before running the install process.
Thanks,  JK
