### ISSUE TITLE
Send alert to third party or cutom webhook 

### ISSUE THREAD

**Issue by prasenforu** [Yelp/elastalert#1184]
This is not a issue but could be enhancement.

 I am using ELK stack and want to Send alert to third party or cutom webhook.

Will be Happy if any one tried, please sedn me blog or information.

**Comment by Qmando** [comment]
Elastalert supports simple HTTP POSTs and arbitrary commands, so you can probably make it work with those.

http://elastalert.readthedocs.io/en/latest/ruletypes.html?#command for the command alerter.

The POST one is actually missing documentation but the code is here, https://github.com/Yelp/elastalert/blob/master/elastalert/alerts.py#L1267, you would use it with "simple" type alerter.
