### ISSUE TITLE
Problem to execute enhancement

### ISSUE THREAD

**Issue by leandrob04** [Yelp/elastalert#1185]
Hello, I am trying to perform an enhancement to fix the timestamp, as suggested in issue #1047, but I am not able to run the enhancement.
![error](https://user-images.githubusercontent.com/28788376/27520632-e6bcdb94-59e5-11e7-8391-b8ec313ad3b3.png)

**Comment by Qmando** [comment]
Try ``touch modules/__init__.py``

**Comment by leandrob04** [comment]
This file already exists, and I have reviewed the mach_enhancements parameter of the rules several times. 
Any suggestions to solve this problem?

Thanks.

**Comment by Qmando** [comment]
I think syntax errors can cause this. Try running the file manually:
``python modules/Time.py``

**Comment by leandrob04** [comment]
I ran this command but didn't get any debugging.

**Comment by leandrob04** [comment]
Could it be anything related to the version? 

I tested the same enhancement on a machine that had version 0.1.8 and worked.

**Comment by Qmando** [comment]
You need to be in the directory where the modules folder is. It looks from your prompt like you are in the rules folder.

**Comment by leandrob04** [comment]
I am not able to perform any enhancements all are giving this problem of not finding the file.

Any suggestion?

**Comment by Qmando** [comment]
Are you running elastalert from the same directory that modules is in?

You should be able to run ``python -c "from modules import Test"``

**Comment by leandrob04** [comment]
There was no problem with the command.

![teste1](https://user-images.githubusercontent.com/28788376/27751875-d06ecc80-5db4-11e7-8ced-4d9fb81beeba.png)

**Comment by Qmando** [comment]
Have you got ``modules.Time.TimeEnhancement`` or ``modules.time_real.TimeEnhancement`` ?

I'm not sure what issues would cause "No module named ..." error other than:
1. Not in the current directory
2. No __init__.py
3. Wrong name of folder
4. Wrong name of .py file

**Comment by leandrob04** [comment]
In case, I modified the enhancement name only ` Time.py -> time_real.py`,  but all its points about the possible problem is really strange what is happening.
It really is weird. I've been doing a few more tests and when I had a machine with version 0.1.8 it worked perfectly, when I upgraded to the latest one then it started this problem again.

Is there another way to call an enhancement?

Thanks for help!

**Comment by Qmando** [comment]
There is actually. I had completely forgotten about this, but if you just put "TimeEnhancement" into elastalert's enhacnements.p, it should load.

You can find the location of that file with
``python -c "from elastalert import enhancements; print enhancements.__file__"``

**Comment by Qmando** [comment]
You can also test this out manually using the simple code from https://github.com/Yelp/elastalert/blob/master/elastalert/config.py#L87

Maybe it will yield some clues as to what is happening

```
$ python
>>> name = "modules.time_real.TimeEnhancement"
>>> module_path, module_class = module_name.rsplit('.', 1)
>>> base_module = __import__(module_path, globals(), locals(), [module_class])
>>> module = getattr(base_module, module_class)
```

**Comment by leandrob04** [comment]
Very strange the result.

![teste2](https://user-images.githubusercontent.com/28788376/27757055-91bb24d8-5dd3-11e7-90bb-0a5641df9c28.png)

**Comment by Qmando** [comment]
I edited the commend. ``module_name = "modules...."`` not ``name =``

**Comment by leandrob04** [comment]
![teste2](https://user-images.githubusercontent.com/28788376/27757112-249596b2-5dd4-11e7-9608-a3df6506e85b.png)

**Comment by Qmando** [comment]
What the heck... I'm out of ideas. Check for typos? 

Try putting the code into elastalert's enhancements.py like I suggested. Hopefully that works!

**Comment by leandrob04** [comment]
Man, now it worked. I don't know what its happen, but its worked. 

Thanks

**Comment by Qmando** [comment]
😌

**Comment by kernelpanicfbsd** [comment]
Hello I added the enhancement code to /usr/local/elastalert/lib/python2.7/site-packages/elastalert/enhancements.py


```
from elastalert.util import pretty_ts
from elastalert.enhancements import BaseEnhancement

class TimeEnhancement(BaseEnhancement):
    def process(self, match):
        match['@timestamp'] = pretty_ts(match['@timestamp'])
```

However my alert timestamps still come through as UTC, an hour behind local time.

**Comment by Qmando** [comment]
Did you add
```
match_enhancements: ["elastalert.enhancements.TimeEnhancement"]
```
to your rule?

**Comment by kernelpanicfbsd** [comment]
No sorry I didn't - is there any particular place in the rule I need to add that code or can it go anywhere?

**Comment by Qmando** [comment]
Anywhere, order doesn't matter

**Comment by kernelpanicfbsd** [comment]
Hello, added the code to the rule but alert still comes through as UTC unfortunately.

`@timestamp: 2017-08-10T09:46:22.008Z`

**Comment by Qmando** [comment]
You didn't get any errors? Can you paste your rule yaml?

This enhancement works perfectly for me.
