### ISSUE TITLE
Fails to start when provisioned with docker-compose

### ISSUE THREAD

**Issue by AndreLouisCaron** [Yelp/elastalert#1199]
Hi there!

I have a local development setup with `elastalert` running inside a Docker container.  However, I'm having trouble using `docker-compose up -d` to provision my stack: the `elastalert` container exits almost immediately because ElasticSearch is not yet responsive and/or the `elastalert_status` index does not yet exist.

To work around this issue, I need to do something like this:

```
$ docker-compose up -d elasticsearch ...  # everything except elastalert
$ # Wait until ElasticSearch is responsive (e.g. poll using cURL)
$ elastalert-create-index ...
$ docker-compose up -d elastalert
```

For larger configurations, this quickly becomes tedious because `docker-compose` doesn't supply a way to exclude a single service; instead. you have to list every single service except for the one you don't want to start.

I wish I could start `elastalert` immediately and that it would internally poll ElasticSearch until it was ready and then proceed as usual.  This would allow me to simply:

```
$ docker-compose up -d
$ elastalert-create-index ...
```

Any chance you would be willing to accept such a contribution?

**Comment by Qmando** [comment]
I'd accept that feature. On startup, poll until a 200 is returned from Elasticsearch.

**Comment by AndreLouisCaron** [comment]
OK thanks.  I submitted a tentative fix.  Let me know if I need to add/change anything!
