### ISSUE TITLE
Search Jira for existing ticket before opening a new one

### ISSUE THREAD

**Issue by Qmando** [Yelp/elastalert#12]
ElastAlert will create multiple tickets for a continuing alert. There should be a feature to have it bump existing tickets instead of duplicating them.
Something like:
1. ElastAlert trigger fires
2. ElastAlert searches JIRA for query_key & creation date < 30 days
3. No result => create a JIRA
4. Yes => Append a "Related web link" (Kibana link when the incident happened) to the existing JIRA

**Comment by xbillbill** [comment]
@bt3gl Any update on this?  Are we going to get it soon?

**Comment by ivanlei** [comment]
@xbillbill We're gonna target March 20th or before.

**Comment by Qmando** [comment]
https://github.com/Yelp/elastalert/pull/31
