### ISSUE TITLE
two rules run every 3 minutes  but only one is ok now

### ISSUE THREAD

**Issue by minminmsn** [Yelp/elastalert#1216]
hi,
i have two rules for http 499 error ,run at jun14  ,
run_every:
  minutes: 3
buffer_time:
  minutes: 3
elastalert v0.1.14，but  ps 12218 is not work now ,and ps 12177 is work ok , who can tell me why ?
TKS!
only restart ps 12218 at time? any other way?

ps aux |grep 499
root     12177  0.0  0.0 263104 14400 ?        S    Jun14   2:06 /usr/local/bin/python /usr/local/bin/elastalert --config /etc/elastalert/config_percentage_match.yaml --rule /etc/elastalert/rules/percentage_match/upstream499.yaml
root     12218  0.0  0.0 263360  2320 ?        S    Jun14   1:12 /usr/local/bin/python /usr/local/bin/elastalert --config /etc/elastalert/config_percentage_match.yaml --rule /etc/elastalert/rules/percentage_match/url499.yaml

**Comment by Qmando** [comment]
Do you have output from them? Run with --verbose and capture stdout/stderr.

Also, there are logs in elasticsearch elastalert_status index with ``_type: elastalert_status`` that have information about every query made. You should be able to see if it's still making queries.

**Comment by minminmsn** [comment]
thank you very much， i think the cause of the problem is that i have changed the version of certifi  for test wechat alert，and at that time the elastalert query timeout , reload three minutes later not worked.
