### ISSUE TITLE
is_enabled for rules?

### ISSUE THREAD

**Issue by yuanxu-li** [Yelp/elastalert#1221]
Here is the problem. I have defined many rules, but sometimes I want to disable some of them according to needs. 

The current way is to delete not used ones from rules folder and add them back when needed, and simply run:
`python -m elastalert.elastalert --verbose`
which is a bit silly.

I know I can also write another script to solve it, but I just wonder if there is any attribute that we can define in a rule to easily enable or disable this rule.

Thanks.

**Comment by Qmando** [comment]
You can rename them and add ".disabled" or something to the end of the file name. There's nothing you can add in the rule itself to disable it.

**Comment by jimbocoder** [comment]
I have been using exactly that approach, renaming to `.disabled` but it's awkward in my opinion. A toggle with something like `is_enabled` that would live-reload would be a very welcome addition.

**Comment by Qmando** [comment]
I'd accept a pull request for this feature. Just add some kind of short circuit in config.py.

**Comment by jimbocoder** [comment]
Cool, thanks. Drawing @jasonhkennedy's attention here as well in case he's got time and interest here before I can work on this.
