### ISSUE TITLE
Customising text send with an alert

### ISSUE THREAD

**Issue by LB5000** [Yelp/elastalert#1224]
Is there anyway to customise the text that is sent with an alert?

I currently have an alert setup based on the 'Change' rule.
This is running against a compare_key of 'BuyPrice', using a query_key of 'Name'.
I've tried adding custom text using the following:

```
alert_subject: "Name: {0} has changed - {1}"
alert_subject_args:
- Name
- Type
include: ['alert_text']
alert_text:
    Name - {0} - change is a {1} - new buy price is {2} - last buy price was {3}
alert_text_args:
- Name
- Type
- BuyPrice
- LastBuyPrice
```

But when the alert is sent out, I get VALUE MISSING messages in both the {1} in subject & {1} and {3} in the alert text.
Is this because I'm not comparing against those fields hence it doesn't know about them?
Have I misunderstood or is this just not possible?

**Comment by Qmando** [comment]
Remove ``include: ['alert_text']``

**Comment by LB5000** [comment]
Thanks for the quick response Qmando. That has given me what I wanted.

One other question, with the following telegram alert:
```
⚠ Name: ‘JSP’ has changed ⚠ Name - ‘JSP’ - change is a INC - new buy price is 20.00 - last buy price was 19.00

@timestamp: 2017-07-13T20:19:54.358Z
**@version: 1
Type: ‘INC’
BuyPrice: 20.00
LastBuyPrice: 19.00
Name: ‘JSP’
_id: #############
_index: price-changes-2017.07.13
_type: TA-results
beat: {
    "hostname": “###########”, 
    "name": “##########”, 
    "version": "5.5.0"
}
host: ###########
input_type: log
message: ’JSP’:’INC’:20.00:19.00
new_value: [
    20.00
]
num_hits: 11
num_matches: 1
offset: 47
old_value: [
    19.00
]
source: ###########################
tags: [
    "beats_input_codec_plain_applied"
]
type: TA-results**
```

Is there anyway of suppressing all the detail in bold?

Thanks again.

**Comment by Qmando** [comment]
``alert_text_type: alert_text_only``

**Comment by LB5000** [comment]
Spot on again, thanks so much!
