### ISSUE TITLE
How to specify a list of ES servers

### ISSUE THREAD

**Issue by jesaremi** [Yelp/elastalert#1227]
We run Elastisearch as a cluster, however es_host parameters only allows a string. Is there another parameter that can take a list of server names?

**Comment by Qmando** [comment]
Nice timing!

https://github.com/Yelp/elastalert/pull/1225 was just opened yesterday.

I'll merge this in soon.

**Comment by jesaremi** [comment]
how nice. thanks

**Comment by Qmando** [comment]
The other advice I've given before for this is to run a load balancer, which is what we do. ELB from Amazon, HAProxy, nginx, etc.

**Comment by jesaremi** [comment]
Thanks that's a good suggestion too
