### ISSUE TITLE
Ignores es_host setting

### ISSUE THREAD

**Issue by chris-bmj** [Yelp/elastalert#1235]
I have es_host and es_port set in config.yaml and in the (only) rule file rulename.yaml to the same fqdn:
`es_host: example.company.com`
`es_port: 9200`

however, 
    `python -m elastalert.elastalert --config /etc/elastalert/config.yaml --verbose --es_debug_trace ~/debug.log`
reveals that every curl command uses localhost instead of the fqdn:
    `curl -H 'Content-Type: application/json' -XPOST 'http://localhost:9200/elastalert_status/elastalert_status?pretty' -d '{`

I've tried just referencing the rule, or just referencing the config file; same happens. 

When I ran the `elastalert-create-index` command it created the index no problem, so it seems it does use es_host sometimes, just not all the time.

**Comment by Qmando** [comment]
This is not an issue with elastalert, but with the elasticesarch python library. 
https://github.com/elastic/elasticsearch-py/issues/380

"By design" 🙄
