### ISSUE TITLE
Add an option to let elastalert only operate when running against elasticsearch master

### ISSUE THREAD

**Issue by ramSeraph** [Yelp/elastalert#1243]
This would allow for a HA setup with multiple elastalerts running simultaneously and the master election is offloaded to elasticsearch.

For a better picture:
I will have elastalert running on each host where there is a elasticsearch node and elastalert will be configured to talk to that elasticsearch node. At any time only the elastalert connected to the master elasticsearch node will be operational.

**Comment by Qmando** [comment]
Good idea. Definitely willing to accept a pull request for this. I've got a huge backlog of features to add and not much time, so I probably won't be able to add this myself.

**Comment by Qmando** [comment]
Duplicate of #1138
