### ISSUE TITLE
question: summary_table_fields and percentage

### ISSUE THREAD

**Issue by sergii-rolskii** [Yelp/elastalert#1264]
Hi guys,
If I use type: percentage_match and summary_table_fields in the letter I do not see any data from table "summary_table_fields", it's normal?

because if I use type: flatline and summary_table_fields option I get data on the table.

**Comment by Qmando** [comment]
TLDR: percentage_match (and some other metric rule types) returns metrics (numbers) but not full document fields. Full fields are necessary to construct this. Maybe a feature for the future to make additional queries to build these tables.
