### ISSUE TITLE
filtering data not including additional timestamp range filter

### ISSUE THREAD

**Issue by ghostPM** [Yelp/elastalert#1271]
I have encountered problems while filtering data to support my alert rules. Let's take an example: I want to compare the current data with the data at the same time yesterday (if data changes too much, altert should be triggered), per 5 minutes. Since elastalert will filter the data additional timestamp range filter, I can not query yesterday's data with 5 minutes timestamp range filter.
I think this problem is similar to issue #778 , do the team have any idea of using elastalert to cover this situation? Thx.

**Comment by Qmando** [comment]
You probably need to write a custom ruletype to do this. I've given a couple other examples of enhancements making additional queries to Elasticsearch, I could link you to.

The closest thing that is currently supported for this is the "change" rule type. In this, you can only tell if the value of some field has changed in the last 24 hours, grouped by any number of fields.

**Comment by ghostPM** [comment]
I have tried to write my custom ruletype, but it doesn't work mainly because ruletype will run after filtering the data, so i think i can't use my ruletype without the missing data.

So if I have missing some information about the enhancements making additional queries to Elasticsearch, I hope the team can help me to provide the info, thank you.
