### ISSUE TITLE
Alert on sum of values (avg/sum aggregation)

### ISSUE THREAD

**Issue by Dmitry1987** [Yelp/elastalert#1288]
Hi,
I browsed and read all rule types, but didn't find any that can use a "sum/avg" aggregation result as threshold for alert (like this aggregation: https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-sum-aggregation.html ).

Are there any similar rules that use this type of aggregation that I can learn from? I guess I'll need to write my own rule.
Is it possible to specify the 'avg/sum/other' in "filter" of the rule? (I suppose not, because it gets passed as '{'filter': {'bool': {'must': [config.filter]}}}' to elasticsearch)

thanks in advance :)

**Comment by Qmando** [comment]
http://elastalert.readthedocs.io/en/latest/ruletypes.html?highlight=avg#metric-aggregation

"This must be one of ‘min’, ‘max’, ‘**avg**’, ‘**sum**’, ‘cardinality’, ‘value_count’."

**Comment by Dmitry1987** [comment]
Oh, ok :) . This might help. I actually need the spike and percentage rules, to work on 'numbers' (sum) of a field instead on matched document count. Like if I had a sum of 500 'something' in last hour, followed by 2500 in next hour, the spike rule will alert. And same with percentage.. to compare sum between one field, and sum of other field, of the same hour, and calculate percentage.
Do you think it's possible?

**Comment by Qmando** [comment]
I've been meaning to release this as official code but I had forgotten about it:
```
# -*- coding: utf-8 -*-
"""
Rule types that count one document multiple times according to a field in the
document. This rule may only be used when the contents of the document may be
discarded (i.e. use_count_query would have sufficed), as it does not
preserve them.
"""
import copy

from elastalert.ruletypes import FrequencyRule
from elastalert.ruletypes import SpikeRule
from elastalert.ruletypes import FlatlineRule
from elastalert.ruletypes import EventWindow
from elastalert.util import lookup_es_key
from elastalert.util import elastalert_logger


def verify_integer_field(document, rule, count_field, allow_zero=False):
    count = lookup_es_key(document, count_field)
    # Attempt to convert strings to ints
    if isinstance(count, basestring):
        try:
            count = int(count)
        except ValueError:
            elastalert_logger.warning(
                'Field %s is a string which could not be converted'
                'into an integer for rule %s' % (count_field, rule['name']))
            return None
    if count is None:
        elastalert_logger.warning(
            'Did not find field %s representing document count in '
            'document for rule %s' % (count_field, rule['name']))
        return None
    if isinstance(count, float):
        count = int(count)
    if not isinstance(count, (int, long)):
        elastalert_logger.warning(
            'Non-integer value of field %s representing document '
            'count in document for rule %s: %s'
            % (count_field, rule['name'], count))
        return None
    if count < 0 or (count == 0 and not allow_zero):
        return None
    return count


class SumOfFieldRuleFactory(type):
    """
    Metaclass that creates a subclass of the class's backing_rule_type.
    backing_rule_type must implement add_count_data.
    """
    # This allows the add_data to use super(...).add_count_data(...) to call
    # the add_count_data method of the appropriate backing RuleType, without
    # having to reimplement all the common logic for each backing_rule_type.

    def __new__(mcs, name, _, dct):

        def add_data(self, data):
            for document in data:
                count = verify_integer_field(
                    document, self.rules, self.rules['count_field'])
                ts = lookup_es_key(document, self.ts_field)
                if count and ts:
                    super(self.__class__, self).add_count_data({ts: count})

        backing_rule_type_cls = dct['backing_rule_type']
        dct['required_options'] = (
            dct['backing_rule_type'].required_options | frozenset(['count_field']))
        dct['add_data'] = add_data
        return type.__new__(mcs, name, (backing_rule_type_cls,), dct)


class SumOfFieldFrequencyRule(object):
    __metaclass__ = SumOfFieldRuleFactory
    backing_rule_type = FrequencyRule


class SumOfFieldSpikeRule(object):
    __metaclass__ = SumOfFieldRuleFactory
    backing_rule_type = SpikeRule
```

**Comment by Dmitry1987** [comment]
I think this is what I'm looking for. Thank you!

On Aug 16, 2017 9:17 PM, "Quentin Long" <notifications@github.com> wrote:

Reopened #1288 <https://github.com/Yelp/elastalert/issues/1288>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Yelp/elastalert/issues/1288#event-1208808166>, or mute
the thread

**Comment by Dmitry1987** [comment]
Hi @Qmando , 
I tried to use it as new rule (http://elastalert.readthedocs.io/en/latest/recipes/adding_rules.html) but it didn't work saying:
```
Could not import module elastalert_modules.custom_rules.SumOfFieldSpikeRule: No module named ruletypes
```

So I moved it from separate file into default "ruletypes.py", and added a section to "schema.py" too. 
But I'm getting error:
```Error loading file /opt/rules/count.yaml: Could not import module SumOfFieldSpikeRule: need more than 1 value to unpack```

My rule tries to call the new type directly (it's a regular spike rule but with "count_field"):
```
import: shared_settings.conf
timestamp_field: orig_timestamp
index: metric_aggs-graylog*
name: Sum spike test
type: SumOfFieldSpikeRule
count_field: count
spike_height: 2
spike_type: "up"
threshold_ref: 1000
query_key: environment
timeframe:
  hours: 2
filter:
- term:
    message: "access_http_200"
```

I think my mistake is that I don't use the "SumOfFieldFrequencyRule" and "SumOfFieldSpikeRule" the correct way. 
Do I need to extend them somehow to make work?  I see they add the "count" functionality to "SpikeRule" and "FrequencyRule", but how  "my-rule.yaml" needs to specify them? 

or do I need to use "type:SpikeRule" as usual, but inside SpikeRule code I have to make use of those new classes somehow?

**Comment by Dmitry1987** [comment]
sorry I forgot to mention where exactly the error happens:   elastalert/config.py", line 454, in load_rules
```
Traceback (most recent call last):
  File "elastalert/elastalert.py", line 1732, in <module>
    sys.exit(main(sys.argv[1:]))
  File "elastalert/elastalert.py", line 1726, in main
    client = ElastAlerter(args)
  File "elastalert/elastalert.py", line 111, in __init__
    self.conf = load_rules(self.args)
  File "/opt/elastalert/elastalert/config.py", line 454, in load_rules
    raise EAException('Error loading file %s: %s' % (rule_file, e))
util.EAException: Error loading file /opt/rules/count.yaml: Could not import module SumOfFieldSpikeRule: need more than 1 value to unpack
```

I followed it to "def load_configuration(filename, conf, args=None):"  function. Probably it fails somewhere in
```
    rule = load_rule_yaml(filename)
    load_options(rule, conf, filename, args)
    load_modules(rule, args)
```
but I can't understand what exactly it is... :( 

My execution command is:
python elastalert/elastalert.py --start "2017-08-17 02:00"  --es_debug_trace debug.log --verbose --config elastalert-config/elas
talert_config.yaml  --rule /opt/rules/count.yaml

appreciate any advice :)

**Comment by Qmando** [comment]
Assuming you have
```
type: "elastalert_modules.custom_rules.SumOfFieldSpikeRule"
```

This means you need to have a folder in the current directory named "elastalert_modules" containing "custom_rules.py" containing that code. There also needs to be an __init__.py file in this folder. You might be able to fix this import error by running ``$ export $PYTHONPATH=`pwd` ``

If you move the code into ruletypes.yaml, you'll need to add this line to make it work:
```
--- a/elastalert/config.py
+++ b/elastalert/config.py
@@ -51,6 +51,7 @@ rules_mapping = {
     'cardinality': ruletypes.CardinalityRule,
     'metric_aggregation': ruletypes.MetricAggregationRule,
     'percentage_match': ruletypes.PercentageMatchRule,
+    'SumOfFieldSpikeRule': ruletypes.SumOfFieldSpikeRule
 }
```

**Comment by Dmitry1987** [comment]
Hi,
I was able to make it all work, including duplicating and modifying the 'metric_aggregation' rule for our needs.
My issues were all in config.py / schema.yaml files :) .
Thanks a lot buddy!

**Comment by leandro-ss** [comment]
@Dmitry1987 

How did you do a metric_aggregation modification?? Did you a merge from Spike and Aggregation rules?


tks for help

**Comment by pataquets** [comment]
@Qmando @Dmitry1987 : is there any code/branch/PR which you can share here? It's this already doable in master? If you can link here your current WIP, perhaps other people might test and/or pick it up.
TIA.

**Comment by pataquets** [comment]
More issue gardening: cross-linking to related #401.
