### ISSUE TITLE
running multiple alerts from a single file

### ISSUE THREAD

**Issue by luvpreetsingh** [Yelp/elastalert#1308]
I have configured multiple alerts using elastalert. I have as many files as alerts. And I run each file using elasalert. Now I am using screen to keep it running. But soon will move to supervisor OR use systemctl for it. 

My question is that as many files are there, as many processes will be run. So, If I am to configure 20 alerts, means 20 files will be there and 20 processes.

Is there any way I can make all alerts in a single file(considering that alerts are on different indices), and each alert has different message and different aggregation ?

**Comment by Qmando** [comment]
Why do you want multiple processes? You just put them all in a folder and elastalert runs them all. Are you running individual rules with ``elastalert --rule ...`` 20 times?

**Comment by luvpreetsingh** [comment]
> You just put them all in a folder and elastalert runs them all.

How do we do that ? I do not know this. I have been running files individually.

**Comment by Qmando** [comment]
Please read http://elastalert.readthedocs.io/en/latest/running_elastalert.html

```
rules_folder is where ElastAlert will load rule configuration files from. It will attempt to load every .yaml file in the folder.
```

You literally just put multiple files into that folder and they all get run.

**Comment by nkshah** [comment]
This is what I did 
I copy my config.yaml file in config folder and in rule folder I have all rules that trigger alert, and then from config folder I run below command, 
`elastalert --verbose --config config.yaml
`
for example if config.yaml  your rule folder location looks like : rules_folder: /opt/elastalert/rules
by giving command `elastalert --verbose --config config.yaml` where your config.yaml will pull all the rules.
