### ISSUE TITLE
help for command parameter

### ISSUE THREAD

**Issue by val31** [Yelp/elastalert#1312]
Hi

I can pass parameter using _include: ["src.ip", "equipment.name"]_ in an email alert but I didn't succeed with a command alert.
this works : 
_command: ["alerte", "%(src)s"]_
but this not : 
_command: ["alerte", "%(src.ip)s"]_
I try several format with { or [ ...

An idea ?
Thanks

**Comment by Qmando** [comment]
This is a bug right now, 😭 

Specifically, nested fields in command alerter can't be used with % formatting.

I'll try to get a fix soon.

**Comment by Qmando** [comment]
#1314

**Comment by val31** [comment]
Thanks Qmando
For the moment I use my script to split the content of the value

**Comment by tatdatpham** [comment]
@val31  how do you solve your problem with field name liek `src.ip` ?

**Comment by Qmando** [comment]
@tatdatpham I'll try to merge #1314 in today, which will allow you to do that. Right now, you'd need to use the entire ``src`` or write an enhancement to move it into it's own field.

**Comment by alesnav** [comment]
I'm getting it working using `new_style_string_format: True` this way: `{match[src][ip]}`

**Comment by val31** [comment]
It's working this way, thanks a lot !!
