### ISSUE TITLE
Send alert to ALERTA via command cli

### ISSUE THREAD

**Issue by tatdatpham** [Yelp/elastalert#1319]
I'm using elasalert for sending all alert to [alerta](https://github.com/guardian/alerta). Here is my config:

```
alert_text_args:
 - agent.name
 - agent.ip
 - dstuser
 - "@timestamp"
 -  srcip

alert_text-type: alert_text_only
alert:
- "slack"
- "email"
- "command"

slack_webhook_url:"https://my-url-webhook"
email:
- 'user1@gmail.com'
- 'user2@gmail.com'

new_style_string_format: True
command: ["/bin/alerta", "send", "--type", "elasalert", "-r", "server", "-E", "Production", "-e", "server", "-g", "server", "-s", "security", "-S", "SSH", "-t", "New SSH login - Account {match[dstuser]} was recently logged to server {match[agent.name]} ({match[agent.ip]})  from IP : {match[agent.ip]}",]

```
When alert matched, i got alert via slack + email success but i checked message in ALERT-UI, data params its not work
It's result

> New SSH login - Account {match[dstuser]} was recently logged to server {match[agent.name]} ({match[agent.ip]}) from IP : {match[agent.ip]}

![image](https://user-images.githubusercontent.com/3429970/30057455-f4592ea2-9260-11e7-9c0f-569561fd3f83.png)

Something wrong? does my config is wrong? 
Please help me . Thanks!

**Comment by Qmando** [comment]
You're config looks ok except "alert_text-type" should be "alert_text_type".

I'm not sure what the issue is. What version of ElastAlert are you using?

Maybe try removing ``new_style_string_format`` and use ``%(dstuser)s`` instead of {...}.

**Comment by Qmando** [comment]
Bear in mind, https://github.com/Yelp/elastalert/pull/1314 will also change this code slightly, so maybe that will fix this issue for you.

**Comment by tatdatpham** [comment]
It's not work with me.

And now i got new error with config
`command: ["/bin/alerta", "send", "--type", "elasalert", "-r", "server", "-E", "Production", "-e", "server", "-g", "server", "-s", "security", "-S", "SSH", "-t", "New SSH login - Account {match[dstuser]} was recently logged to server {match[agent.name]} ({match[agent.ip]})  from IP : {match[agent.ip]}",]`

> Error wwhule running alert command: Error formatting command agent.name

Not work with field like field.childfield ?

**Comment by val31** [comment]
Hi all
I also tried with new code (pick up the last elastalert version + the 3 updated files), and I confirm it's not working...

**Comment by Qmando** [comment]
I think you either didn't pull the code correctly, or you are getting the field name wrong.

```
>>> from elastalert.alerts import CommandAlerter
>>> conf = {"command": ["echo", "Agent IP = %(agent.ip)s"]}
>>> match = {'agent': {'ip': '1.2.3.4', 'name': 'steve'}}
>>> CommandAlerter(conf).alert([match])
Agent IP = 1.2.3.4
```
Same results with new_style_string_format

Try adding this to the code:
```
diff --git a/elastalert/alerts.py b/elastalert/alerts.py
index 5394f1e..e7e5868 100644
--- a/elastalert/alerts.py
+++ b/elastalert/alerts.py
@@ -817,6 +817,7 @@ class CommandAlerter(Alerter):
             self.new_style_string_format = True

     def alert(self, matches):
+        print matches
         # Format the command and arguments
```

If it doesn't print anything during an alert, you are not editing the right python file and are likely still running the old version.

If does print something, it will help me diagnose exactly what is wrong.

**Comment by alesnav** [comment]
`{match[agent.name]}` is wrong. You should write `{match[agent][name]}` to get it working fine 👍

**Comment by Qmando** [comment]
@alesnav 
Awesome!
I didn't even realize you could do that. I guess I don't even need that pull request!
