### ISSUE TITLE
Elastic 5.6.0?

### ISSUE THREAD

**Issue by jonathancoon** [Yelp/elastalert#1334]
Will this work with Elasticsearch 5.6.0?

**Comment by Qmando** [comment]
Probably, it works with other 5.X versions.

**Comment by jonathancoon** [comment]
Yeah I got it working with 5.6.

**Comment by rkhapre** [comment]
Please let me know how it is done for 5.6.x. We are trying to run "pip install elasticsearch>5.4.0" i am not able to install with this. I am getting error as 

Could not find a version that satisfies the requirement elasticsearch>5.4.0 (from versions: 0.4.1, 0.4.2, 0.4.3, 0.4.4, 0.4.5, 1.0.0, 1.1.0, 1.1.1, 1.2.0, 1.3.0, 1.4.0, 1.5.0, 1.6.0, 1.7.0, 1.8.0, 1.9.0, 2.0.0, 2.1.0, 2.2.0, 2.3.0, 2.4.0, 2.4.1, 5.0.0, 5.0.1, 5.1.0, 5.2.0, 5.3.0, 5.4.0)
No matching distribution found for elasticsearch>5.4.0

**Comment by Qmando** [comment]
Just use the latest version

**Comment by rkhapre** [comment]
Yes, i am using the latest version. But this command is not going through  "pip install elasticsearch>5.4.0".
What i have to write in command to go through with Elastic 5.6.2 version

**Comment by Qmando** [comment]
Just install the latest version
``pip install elasticsearch``
