### ISSUE TITLE
Stride Support (Replaces Hipchat)

### ISSUE THREAD

**Issue by careys7** [Yelp/elastalert#1335]
Is there any plans to support [Stride](https://developer.atlassian.com/cloud/stride/) once HipChat is transitioned out?

**Comment by jness** [comment]
I've been doing some work on a Stride alerter in this fork:
  https://github.com/jness/elastalert

I'm waiting to pull request this into upstream, but first wanted to look at some unit test.

**Comment by jness** [comment]
This issue should be safe to close.

**Comment by careys7** [comment]
Thanks for this @jness!
