### ISSUE TITLE
command alert error

### ISSUE THREAD

**Issue by rubenrodr-versia** [Yelp/elastalert#1341]
Hi,

I have the following alert on a rule:

`alert:`
`- "command"`
`new_style_string_format: true`
`alert_subject_args:`
`- "@timestamp"`
`- columns.path`
`- host`
`command: ["/bin/echo \"Fichero {match[columns][path]} del equipo {match[host]} modificado a las {match[@timestamp]} \" >>/var/log/alertas_elastalert.log "]`

and running:

`#python /opt/elastalert/elastalert/elastalert.py --config /opt/elastalert/config.yaml --verbose --rule /opt/elastalert/reglas/regla6.yaml`

i get the error:

`INFO:elastalert:Starting up`
`ERROR:root:Error while running alert command: Error while running command /bin/echo "Fichero /etc/apt/sources.list del equipo lab-spri-elk modificado a las 2017-09-18T09:04:40Z " >>/var/log/alertas_elastalert.log : [Errno 2] No such file or directory`

Thanks.

**Comment by sinaxin** [comment]
Hi, did you solve your problem?
I have the same issue but with python.

Here's my command:
`alert: - command
 command: ["/bin/python /opt/elastalert/scripts/alert_ifttt.py ovpn_connect test"]`

Here's the error:
`ERROR:root:Error while running alert command: Error while running command python /opt/elastalert/scripts/alert_ifttt.py ovpn_connect test: [Errno 2] No such file or directory
`

**Comment by rubenrodr-versia** [comment]
It's solved specifying the command section without brackets:
command: "echo {match[@timestamp]}  >> /var/log/elastalert.log"
