### ISSUE TITLE
Send email to user, with user get from "alert_text_args"

### ISSUE THREAD

**Issue by tatdatpham** [Yelp/elastalert#1359]
Hi, 
I have new case. I have log logon succes into server and have field `username`  - account logon.
Now i want send alert email to this user with `username`. How can?

EX: 
username = aamin1 , email send to admin1@mycompany.com
username = aamin2 , email send to admin2@mycompany.com
username = acc3, email send to acc3@mycompany.com

Thanks

**Comment by Qmando** [comment]
http://elastalert.readthedocs.io/en/latest/ruletypes.html?highlight=email_from_field#email
