### ISSUE TITLE
Does es_host support elasticsearch HA mode?

### ISSUE THREAD

**Issue by neizmirasego** [Yelp/elastalert#1364]
Hi! 
In all examples I saw es_host property has certain elasticseach hostname.
I am wondering if elastalert support elasticsearch HA mode? It would be very nice if it could switch to another host in ES cluster in case the first one is down.
Otherwise we won't receive alerts in case of one node from cluster that elastalert is watching to is down.

Thanks in advance for any comments!
Alexey

**Comment by sathishdsgithub** [comment]
@neizmirasego 
Please use haproxy in front of elasticsearch . This helps to accomplish ha mode for elastalert.

**Comment by neizmirasego** [comment]
ok, thanks! Hopefully we have already installed haproxy in our environment, so no additional installation are needed.
