### ISSUE TITLE
Change Rule modification

### ISSUE THREAD

**Issue by yasvanth** [Yelp/elastalert#1369]
Hi,
I am using elastalert (chagne rule) to alert if the user logins from different IP address in a day. I am having a trouble to compare the change with more than three values.

For Instance:
If a user logins from US and UK an alert is triggered. I would like to modify or create new compare rule to alert only if user logins from more than three location such as US, UK, DE .

Thanks,
Yash

**Comment by Qmando** [comment]
You can use cardinality for this.
```
type: cardinality
query_key: user
cardinality_field: country
max_cardinality: 2
```

**Comment by yasvanth** [comment]
@Qmando I have tried the above rule and checked my self logging to application from 4 different location but no success, For reference I have attached my rule below:

<pre>
index: logstash-2017.10
name: User Login from Multiple Location

type: cardinality
query_key: PrincipalName
cardinality_field: geoip.timezone
max_cardinality: 2
timeframe:
  hours: 1
filter:
- query:
    query_string:
     query: "_type: logs"
</pre>
And I have tried to change filter to term 
<pre>
filter:
- term:
    _type: "logs"
</pre>


Thanks,
Yash

**Comment by Qmando** [comment]
Please post what you expected versus what happened. The rule looks fine to me but unless you post logs or more information, I can't help.

It would be very useful to see
- Some logs from running elastalert with --verbose
- JSON of one of the documents you are trying to match

**Comment by yasvanth** [comment]
When I test my rule using elastalert using elastalert I am getting below logs
<pre>
Successfully loaded User Login from Multiple Location

Got 186537 hits from the last 1 day

Available terms in first hit:
        TAG_Server
        @timestamp
        ResponseBinding
        sslsubject
        Location
        port
        RelyingPartyId
        NameIdentifier
        SourceModuleType
        SourceModuleName
        ResponseId
        LogType
        Host
        MessageProfileId
        RequestBinding
        AssertionID
        EventTime
        AssertingPartyId
        host
        TAG_WebsiteURL
        ReleasedAttributes
        TAG_EventDate
        AuthMethod
        PrincipalName
        RequestID
        geoip.region_code
        geoip.longitude
        geoip.region_name
        geoip.country_code2
        geoip.ip
        geoip.continent_code
        geoip.country_code3
        geoip.latitude
        geoip.location.lat
        geoip.location.lon
        geoip.country_name
        geoip.city_name
        geoip.timezone
        @version
        EventReceivedTime
INFO:elastalert:Note: In debug mode, alerts will be logged to console but NOT actually sent.
                To send them but remain verbose, use --verbose instead.
INFO:elastalert:Queried rule User Login from Multiple Location from 2017-10-04 19:57 IST to 2017-10-04 20:12 IST: 2171 / 2171 hits
INFO:elastalert:Queried rule User Login from Multiple Location from 2017-10-04 20:12 IST to 2017-10-04 20:27 IST: 4318 / 2147 hits
INFO:elastalert:Queried rule User Login from Multiple Location from 2017-10-04 20:27 IST to 2017-10-04 20:42 IST: 6485 / 2167 hits
INFO:elastalert:Queried rule User Login from Multiple Location from 2017-10-04 20:42 IST to 2017-10-04 20:57 IST: 8498 / 2013 hits
INFO:elastalert:Queried rule User Login from Multiple Location from 2017-10-04 20:57 IST to 2017-10-04 21:12 IST: 10413 / 1915 hits
INFO:elastalert:Queried rule User Login from Multiple Location from 2017-10-04 21:12 IST to 2017-10-04 21:27 IST: 12342 / 1929 hits
INFO:elastalert:Queried rule User Login from Multiple Location from 2017-10-04 21:27 IST to 2017-10-04 21:42 IST: 14148 / 1806 hits
INFO:elastalert:Queried rule User Login from Multiple Location from 2017-10-04 21:42 IST to 2017-10-04 21:57 IST: 15934 / 1786 hits
INFO:elastalert:Queried rule User Login from Multiple Location from 2017-10-04 21:57 IST to 2017-10-04 22:12 IST: 17724 / 1790 hits
INFO:elastalert:Queried rule User Login from Multiple Location from 2017-10-04 22:12 IST to 2017-10-04 22:27 IST: 19360 / 1636 hits
INFO:elastalert:Queried rule User Login from Multiple Location from 2017-10-04 22:27 IST to 2017-10-04 22:42 IST: 20869 / 1509 hits
INFO:elastalert:Queried rule User Login from Multiple Location from 2017-10-04 22:42 IST to 2017-10-04 22:57 IST: 22264 / 1395 hits
INFO:elastalert:Queried rule User Login from Multiple Location from 2017-10-04 22:57 IST to 2017-10-04 23:12 IST: 23604 / 1340 hits
INFO:elastalert:Queried rule User Login from Multiple Location from 2017-10-04 23:12 IST to 2017-10-04 23:27 IST: 24726 / 1122 hits
INFO:elastalert:Queried rule User Login from Multiple Location from 2017-10-04 23:27 IST to 2017-10-04 23:42 IST: 25796 / 1070 hits
.
.
.
.
.
Would have written the following documents to writeback index (default is elastalert_status):

elastalert_status - {'hits': 186502, 'matches': 0, '@timestamp': datetime.datetime(2017, 10, 5, 18, 59, 53, 46830, tzinfo=tzutc()), 'rule_name': 'User Login from Multiple Location', 'starttime': datetime.datetime(2017, 10, 4, 18, 59, 1, 308086, tzinfo=tzutc()), 'endtime': datetime.datetime(2017, 10, 5, 18, 59, 1, 308086, tzinfo=tzutc()), 'time_taken': 51.72150492668152}

</pre>

The sample json is 
<pre>
{
  "_index": "logstash-2017.10",
  "_type": "logs",
  "_id": "AV7t7zw434GYSKwIGUuv",
  "_version": 1,
  "_score": null,
  "_source": {
    "RequestID": "kbkengenhnipmhffnkgbakeokdklfoephhfcfcmp",
    "ResponseId": "_7aa8ca9cb9d4556ef6ca4864ff9df9ff",
    "ResponseBinding": "HTTP-POST",
    "TAG_Server": "server_1",
    "TAG_EventDate": "2017-10-05 19:08:06",
    "TAG_WebsiteURL": "xxxxxxxxxxxxxx",
    "@version": "1",
    "host": "client_1",
    "PrincipalName": "ewkjWDEZoA7ewg8GhPgYTw",
    "RelyingPartyId": "XXXXXXXXXXXXXXXXXXXXXXXXX",
    "geoip": {
      "city_name": "Dublin",
      "timezone": "Europe/Dublin",
      "ip": "----------",
      "latitude": 53.3389,
      "country_name": "Ireland",
      "country_code2": "IE",
      "continent_code": "EU",
      "country_code3": "IE",
      "region_name": "Leinster",
      "location": {
        "lon": -6.000,
        "lat": 73.3389
      },
      "region_code": "L",
      "longitude": -6.2595
    },
    "SourceModuleType": "im_file",
    "AssertionID": "_74e5f8634cbe62447795a28f7d571663",
    "RequestBinding": "HTTP-Redirect",
    "LogType": "App_Logs",
    "Host": "cluster",

    "EventReceivedTime": "2017-10-05 20:08:06",
    "AuthMethod": "Basic Auth",
    "SourceModuleName": "idp",
    "@timestamp": "2017-10-05T19:08:06.692Z",
    "port": 51202,
    "EventTime": "2017-10-05 19:08:06",
  },
  "fields": {
    "EventTime": [
      1507230486000
    ],
    "@timestamp": [
      1507230486692
    ]
  },
  "sort": [
    1507230486000
  ]
}
</pre>

From above json you could see that "geo.timezone: Europe/Dublin" for user "PrincipalName:ewkjWDEZoA7ewg8GhPgYTw" if same user logins from different timezone such as Europe/London and Europe/France  the alter should be triggered. 

Below is the log from running the alert  by  elastalert --start NOW --verbose is;
<pre>
INFO:elastalert:Queried rule User Login from Multiple Location from 2017-10-05 11:22 IST to 2017-10-05 11:36 IST: 537 / 537 hits
INFO:elastalert:Ran User Login from Multiple Location from 2017-10-05 11:22 IST to 2017-10-05 11:36 IST: 537 query hits (332 already seen), 0 matches, 0 alerts sent
INFO:elastalert:Sleeping for 299.774462 seconds
INFO:elastalert:Queried rule User Login from Multiple Location from 2017-10-05 11:22 IST to 2017-10-05 11:37 IST: 617 / 617 hits
INFO:elastalert:Queried rule User Login from Multiple Location from 2017-10-05 11:37 IST to 2017-10-05 11:41 IST: 746 / 129 hits
INFO:elastalert:Ran User Login from Multiple Location from 2017-10-05 11:22 IST to 2017-10-05 11:41 IST: 746 query hits (537 already seen), 0 matches, 0 alerts sent
INFO:elastalert:Sleeping for 299.71667 seconds
INFO:elastalert:Queried rule User Login from Multiple Location from 2017-10-05 11:37 IST to 2017-10-05 11:46 IST: 326 / 326 hits
INFO:elastalert:Ran User Login from Multiple Location from 2017-10-05 11:37 IST to 2017-10-05 11:46 IST: 326 query hits (129 already seen), 0 matches, 0 alerts sent
INFO:elastalert:Sleeping for 299.85468 seconds
INFO:elastalert:Queried rule User Login from Multiple Location from 2017-10-05 11:37 IST to 2017-10-05 11:51 IST: 561 / 561 hits
INFO:elastalert:Ran User Login from Multiple Location from 2017-10-05 11:37 IST to 2017-10-05 11:51 IST: 561 query hits (326 already seen), 0 matches, 0 alerts sent
INFO:elastalert:Sleeping for 299.79079 seconds
INFO:elastalert:Queried rule User Login from Multiple Location from 2017-10-05 11:37 IST to 2017-10-05 11:52 IST: 622 / 622 hits
INFO:elastalert:Queried rule User Login from Multiple Location from 2017-10-05 11:52 IST to 2017-10-05 11:56 IST: 782 / 160 hits
INFO:elastalert:Ran User Login from Multiple Location from 2017-10-05 11:37 IST to 2017-10-05 11:56 IST: 782 query hits (561 already seen), 0 matches, 0 alerts sent
INFO:elastalert:Sleeping for 299.67731 seconds
INFO:elastalert:Queried rule User Login from Multiple Location from 2017-10-05 11:52 IST to 2017-10-05 12:01 IST: 380 / 380 hits
INFO:elastalert:Ran User Login from Multiple Location from 2017-10-05 11:52 IST to 2017-10-05 12:01 IST: 380 query hits (160 already seen), 0 matches, 0 alerts sent
INFO:elastalert:Sleeping for 299.838957 seconds
INFO:elastalert:Queried rule User Login from Multiple Location from 2017-10-05 11:52 IST to 2017-10-05 12:06 IST: 611 / 611 hits
INFO:elastalert:Ran User Login from Multiple Location from 2017-10-05 11:52 IST to 2017-10-05 12:06 IST: 611 query hits (380 already seen), 0 matches, 0 alerts sent
INFO:elastalert:Reloading configuration for rule /opt/elastalert/rules/multiple_locations.yaml
INFO:elastalert:Sleeping for 299.751405 seconds
INFO:elastalert:SIGINT received, stopping ElastAlert...
INFO:elastalert:Starting up
INFO:elastalert:Queried rule User Login from Multiple Location from 2017-10-05 12:06 IST to 2017-10-05 12:06 IST: 134 / 134 hits
INFO:elastalert:Ran User Login from Multiple Location from 2017-10-05 12:06 IST to 2017-10-05 12:06 IST: 134 query hits (0 already seen), 0 matches, 0 alerts sent
INFO:elastalert:Sleeping for 299.899018 seconds
INFO:elastalert:Queried rule User Login from Multiple Location from 2017-10-05 12:06 IST to 2017-10-05 12:11 IST: 1511 / 1511 hits
INFO:elastalert:Ran User Login from Multiple Location from 2017-10-05 12:06 IST to 2017-10-05 12:11 IST: 1511 query hits (134 already seen), 0 matches, 0 alerts sent
INFO:elastalert:Sleeping for 299.517356 seconds
INFO:elastalert:SIGINT received, stopping ElastAlert...
                                    </pre>

**Comment by yasvanth** [comment]
@Qmando Any update ?

**Comment by Qmando** [comment]
What version of ElastAlert are you running? A bug was fixed somewhere around 0.1.2 that would have resulted in this behavior. (https://github.com/Yelp/elastalert/commit/9651e6bdcdb1b75db6e2b35a04082464753c5da7)

**Comment by yasvanth** [comment]
@Qmando Thanks for your reply. I was running elastalert 0.1.20 and tried again after updating to 0.1.21. When I run the elastalert in verbose 
![screen shot 2017-10-12 at 10 00 56](https://user-images.githubusercontent.com/13409183/31488165-d017cc2e-af34-11e7-8248-383ef415c277.png)

**Comment by yasvanth** [comment]
@Qmando Any update? I have uploaded the screenshots while compiling and elastalert versions.

**Comment by Qmando** [comment]
I'm not sure whats happening in this case. You could try adding
```
--- a/elastalert/ruletypes.py
+++ b/elastalert/ruletypes.py
@@ -843,6 +843,7 @@ class CardinalityRule(RuleType):
             if value is not None:
                 # Store this timestamp as most recent occurence of the term
                 self.cardinality_cache[key][value] = event[self.ts_field]
+                print "Key", key, "has values", self.cardinality_cache[key]
                 self.check_for_match(key, event)
```
as a debug statement to see if the values you expect are being added.

**Comment by yasvanth** [comment]
Thanks for your response. I have added the print statement and ran elastalert in debug mode. But not value is captured as attached snapshot.
![screen shot 2017-11-02 at 10 04 56](https://user-images.githubusercontent.com/13409183/32320406-9bd90446-bfb5-11e7-9e48-7af625b95b2c.png)

Looks like Cardinality Rule doesn't hold a data to compare the match.

**Comment by Qmando** [comment]
Hm.. something is not right here. This should make it obvious though.
```
diff --git a/elastalert/ruletypes.py b/elastalert/ruletypes.py
index 4f79e90..bf6c2ea 100644
--- a/elastalert/ruletypes.py
+++ b/elastalert/ruletypes.py
@@ -831,6 +831,7 @@ class CardinalityRule(RuleType):

     def add_data(self, data):
         qk = self.rules.get('query_key')
+        print data[0], qk, self.cardinality_field
         for event in data:
             if qk:
```

**Comment by yasvanth** [comment]
Still the same output. Now data is printed in the console. Or CardianlityRule(compare rule) will work?

**Comment by Qmando** [comment]
You are probably not modifying the right file.

Type
```$ python -c "import elastalert;print elastalert.__file__"```

Does it show you the same directory?

How did you update elastalert? Perhaps you are still running the old version.

**Comment by yasvanth** [comment]
I am confused now. I clone elastalert directory in /opt/. 
When I run `$ python -c "import elastalert;print elastalert.__file__"`from /opt/elastalert/, I got 
<pre> elastalert/__init__.pyc </pre>
 Where executing from /opt/ got 
<pre>/usr/local/lib/python2.7/dist-packages/elastalert/__init__.pyc</pre>

I have all the configuration in /opt/elastalert , for updating I will pull the new configuration. 

Is there anything different procedure to update the application.

**Comment by Qmando** [comment]
Aha, I thought as much

You either need to
1. Run elastalert from /opt/elastalert directory. This means you load the files from source directly.
Or
2. Run ``python setup.py install`` or ``pip install -e .`` again. This copies the source files to /usr/local/lib/python2.7 so that they become accessible from everywhere.

**Comment by yasvanth** [comment]
Now I could see all the data in console after executing `python setup.py install`. I will test it few dummy data and ack you by tomorrow.

Thanks a million for your response

**Comment by yasvanth** [comment]
@Qmando Thanks. Now I tested the rule with a dummy data and got the matches.

<pre>elastalert_status - {'hits': 193179, 'matches': 5099, '@timestamp': datetime.datetime(2017, 11, 2, 18, 20, 48, 322754, tzinfo=tzutc()), 'rule_name': 'User Login from Multiple Location', 'starttime': datetime.datetime(2017, 11, 1, 18, 14, 8, 861554, tzinfo=tzutc()), 'endtime': datetime.datetime(2017, 11, 2, 18, 14, 8, 861554, tzinfo=tzutc()), 'time_taken': 399.4435169696808}
</pre>

**Comment by Qmando** [comment]
Glad to see you didn't give up 😃
