### ISSUE TITLE
not workin cpu load

### ISSUE THREAD

**Issue by vilaspmahajan** [Yelp/elastalert#1376]
Hello everybody,

I try to use but not work please help..
```
name: Metricbeat CPU Spike Rule1
type: metric_aggregation

es_host: localhost
es_port: 9200

index: metricbeat-*

buffer_time:
 minutes: 1

metric_agg_key: system.cpu.load.1
metric_agg_type: avg
query_key: beat.hostname
doc_type: metricbeat

bucket_interval:
  minutes: 1

sync_bucket_interval: true
#allow_buffer_time_overlap: true
#use_run_every_query_size: true

min_threshold: 0.0
max_threshold: 0.1

filter:
- term:
    metricset.name: cpu

# (Required)
# The alert is use when a match is found
alert:
- "debug"
```

**Comment by Vagras** [comment]
The way you config looks you combined different Ruletypes. Wich won't work.GreetzAnd sorry for my bad Englisch. Am 06.10.2017 15:28 schrieb vilaspmahajan <notifications@github.com>:Hello everybody,
I try to use but not work please help..
_name: Metricbeat CPU Spike Rule1
type: metric_aggregation
es_host: localhost
es_port: 9200
index: metricbeat-*
buffer_time:
minutes: 1
metric_agg_key: system.cpu.load.1
metric_agg_type: avg
query_key: beat.hostname
doc_type: metricbeat
bucket_interval:
minutes: 1
sync_bucket_interval: true
#allow_buffer_time_overlap: true
#use_run_every_query_size: true
min_threshold: 0.0
max_threshold: 0.1
filter:
term:
metricset.name: cpu
(Required)
The alert is use when a match is found
alert:
"debug"_

**Comment by Qmando** [comment]
@vilaspmahajan 
What happens when you run it? Add --verbose flag if you haven't already. No hits? False positives? Errors?

**Comment by vilaspmahajan** [comment]
hi,
I have already used below cmd.
"python -m elastalert.elastalert --verbose --rule cpu_high.yaml"
and use stress --cpu 2 in client system but i get
"0 query hits (0 already seen), 0 matches, 0 alerts sent"

**Comment by Qmando** [comment]
https://github.com/yelp/elastalert#my-rule-is-not-getting-any-hits
