### ISSUE TITLE
alert only once

### ISSUE THREAD

**Issue by NikolaMandic** [Yelp/elastalert#1379]
Hello,

I would like an alert to happen only once in following manner.
metric aggregation threshold is passed, it lasts for few minutes then alerts.
but I want it to stop alerting at this point
after alert is over once it happens again it should realert

from doc I saw

```
For example, if you only wanted to receieve an alert once for a specific error and hostname, you could use [error, hostname]
```

can somebody please confirm did I understand this right
above documentation says that this is only once only if used together with realert option
and thus it can't actually provide behavior that I would like unless elastalert is modified for this purpose?

Regards

**Comment by Qmando** [comment]
My recommendation here is to use a ``realert`` setting that is so long it's effectively "never". Weeks it the biggest unit it takes:
```
realert:
  weeeks: 9999
```
it won't realert until year 2200.

It's not the most elegant solution, but it works.

**Comment by NikolaMandic** [comment]
tried it but I would like it to realert once danger is gone
and it did not.
did I do something wrong there?

**Comment by Qmando** [comment]
There are no "resolve" events right now in elastalert. You can either set a fixed realert time or use exponentially increasing realert time. 

This is definitely a long term goal, but doesn't exist right now ☹️

**Comment by NikolaMandic** [comment]
thanks. I checked source just wanted to confirm.
