### ISSUE TITLE
have an query/aggregation execution plan and avoid dispatch requests to nodes/shards whenever is possible

### ISSUE THREAD

**Issue by rcrezende** [Yelp/elastalert#1387]
in a top_hits aggregation,  see snippet:
```
"aggs": {
	"autogen_by_kibana": {
	  "top_hits": {
		"docvalue_fields": [
		  "field_xyz"
		],
		"_source": "field_xyz",
		"size": 1,
		"sort": [
		  {
			"field_xyz": {
			  "order": "desc"
			}
		  }
		]
	  }
	}
...
}
```

we sort the top hit by field_xyz, which is not on every index, but as part of the request, we filter with:

```
{
  "exists": {
	"field": "field_xyz"
  }
}
```

But response fails execution on every shard when field_xyz is not present.

> No mapping found for [field_xyz] in order to sort on

Would be possible to not even dispatch the query to those shards since no record will match anyway?

Running ES 5.4

**Comment by Qmando** [comment]
This sounds like a limitation of Elasticsearch, though maybe there's a smart way to have it ignore indices which don't have the field. I'm not too sure about that.

One solution, maybe not ideal, is to manually put the mapping for field_xyz on every index. 

Depending on how you're ingesting data, you can probably set this up by default. You can either modify the index template that you are using to generate mappings, or you can force the existence of field_xyz for every document.

**Comment by rcrezende** [comment]
I see two points here:

1. normalize mappings: I can certainly act on this and fix it, not sure what additional feature on ES would improve that without user intervention.
2. load/dispatch requests only to needed nodes/shards: this seems to benefit ES overall through a query execution plan/optimization phase (for both regular search and aggregations) before dispatching the tasks. This error wouldn't even exist, but better than that may be the performance gain on coordinating.

**Comment by rcrezende** [comment]
(changing the title because I believe the second point is much more relevant)

**Comment by rcrezende** [comment]
oh... I opened against the wrong project. Let me fix this.
here is the one for tracking it: https://github.com/elastic/elasticsearch/issues/27103

Closing this one.
