### ISSUE TITLE
query_key not works with top_count_keys when using es5 (.keyword suffix missing)

### ISSUE THREAD

**Issue by gzeronet** [Yelp/elastalert#1392]
Hi there,

awesome project ;)
I just find a little bug when using query_key with top_count_keys, (raw_count_keys is default [true]):

    ...
    type: any
    top_count_keys:
      - uri
      - response
    query_key:
      - uri
    ...

and response:

    any:logstash-yhbase_kong

    uri.keyword:
    No events found.

    response.keyword:
    No events found.

Actually, event exists if I remove that 'query_key: uri'

And I have found the bug, here is the patch:

    diff --git a/elastalert.py b/elastalert.py
    index 5097051..32b22ef 100644
    --- a/elastalert.py
    +++ b/elastalert.py
    @@ -446,7 +446,7 @@ class ElastAlerter():
                 end = '.keyword'
             else:
                 end = '.raw'
    -        if rule.get('raw_count_keys', True) and not rule['query_key'].endswith(end) and not rule['five']:
    +        if rule.get('raw_count_keys', True) and not rule['query_key'].endswith(end):
                 filter_key = add_raw_postfix(filter_key, rule['five'])
             rule_filter.extend([{'term': {filter_key: qk}}])
         base_query = self.get_query(

It already works for me. Just hope it could be fixed ASAP.
Please let me know if need a PR. Thx.

**Comment by Qmando** [comment]
Good catch. Looks like this is definitely a bug. I'll fix this today.

**Comment by gzeronet** [comment]
:+1:
