### ISSUE TITLE
Trigger alerts based on a daily baseline

### ISSUE THREAD

**Issue by cissecedric** [Yelp/elastalert#1396]
Hi,

I am looking for an alerting module for ElasticSearch and I would like to know if ElastAlert would suit my needs : 
I would like to trigger an alert based on a kind of daily pattern/baseline/model built from my historical data (daily time series).
For example a simple threshold wouldn't be suitable.
Is there any built-in rule or solution to do this with ElastAlert ? Or should I build this pattern and trigger my alerts when the expected baseline is not respected?

Thank you for your answers !

**Comment by cissecedric** [comment]
Still no answers... maybe my question is not well asked as it should. I'll ask more simple questions and close this one.

**Comment by sebash1992** [comment]
@cissecedric  did you find a solution?
