### ISSUE TITLE
Does Elastalert have to be installed on each node in a Cluster?

### ISSUE THREAD

**Issue by Amruth007** [Yelp/elastalert#1402]
Hi,

I have a cluster with 4 nodes. Do I need to install Elastalert on all the nodes if I have to monitor all the Elasticsearch nodes? Or is there a way where I can declare all the node names in a single config.yaml file and monitor all the nodes?

Thanks

**Comment by Qmando** [comment]
No, you don't need to install it multiple places, nor do you need to declare all the node names. All you need is direct connectivity to a SINGLE node.

**Comment by Amruth007** [comment]
Thank you.
All I need to do is install it on a single node in a cluster, just give index name?

**Comment by Qmando** [comment]
It doesn't even have to be on a node in the cluster, all it needs is direct connectivity to a node.

**Comment by Amruth007** [comment]
Got it. Thank you :)
