### ISSUE TITLE
Support PagerDuty's v2 API

### ISSUE THREAD

**Issue by xiongchiamiov** [Yelp/elastalert#1406]
https://v2.developer.pagerduty.com/docs/events-api-v2

The newer API allows some new features due to increased structuring, like (IIRC) combining multiple pages into one event.

**Comment by esg-llachance** [comment]
The V1 api is no longer supported as of October 19, 2018, it would be super super great to have this in before that time!

**Comment by brosander** [comment]
This would be really useful

**Comment by brosander** [comment]
@xiongchiamiov @esg-llachance just opened pr for it :smile: 

Also published it to docker hub at https://hub.docker.com/r/corvana/elastalert-docker/tags/
tag v0.1.32-pagerduty-v2

That image is a fork of @jertel 's https://github.com/jertel/elastalert-docker to support elastalert [running in kuberenetes with helm](https://github.com/kubernetes/charts/tree/master/stable/elastalert) :smile:

**Comment by brosander** [comment]
Pr is merged so this should be in next release :smile:

**Comment by brosander** [comment]
@Qmando believe this can be closed now
