### ISSUE TITLE
How do I install Elastalert on Redhat7 without Internet connection?

### ISSUE THREAD

**Issue by Amruth007** [Yelp/elastalert#1414]
Hi,

I am trying to install Elastalert on Redhat 7 which doesn't have internet connection. I have downloaded Elastalert zip file and extracted it. I ran the command, "pip install elastalert", but got the following error,

> Collecting elastalert
>   Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x232e350>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /simple/elastalert/

**Comment by Qmando** [comment]
You're gonna need all the requirements too. Closing as this question is not directly related to ElastAlert. Good Luck!

**Comment by reswob10** [comment]
In case anyone else didn't get this at first (like me), he means look at the requirements.txt file.

**Comment by shylendranc** [comment]
I am also facing the same issue. This is a question on the ElastAlert only... not sure why it is closed here without providing an input/solution.
Can someone share the "requirements.txt" file?

**Comment by reswob10** [comment]
I did figure out how to do this:  http://shadowtrackers.net/blog/installing-elastalert-on-a-stand-alone-networksystem
I used Centos so the method should be similar...
