### ISSUE TITLE
Use regex for blacklist and whitelist rules

### ISSUE THREAD

**Issue by gpoire** [Yelp/elastalert#1456]
Is it possible to use regex with blacklist and whitelist rules ? I want to use this kind of alert for matching specific command on router but the command could be with uppercase or lowercase.

**Comment by Qmando** [comment]
If you want regular expressions, you need to implement it in a filter. See comment on #1419. Using Elasticsearch filtering will also do lower/uppercase normalization for you automatically. I'd advise using this rather than whitelist/blacklist.

**Comment by gpoire** [comment]
Ok thanks I will watch for this
