### ISSUE TITLE
ERROR:root:Error running query

### ISSUE THREAD

**Issue by marlon617** [Yelp/elastalert#1457]
es版本:6.0.1

INFO:elastalert:Starting up
WARNING:elasticsearch:GET http://10.1.1.205:9200/logstash-nginx-chitupay-*/_search?_source_include=%40timestamp%2C%2A&ignore_unavailable=true&scroll=30s&size=10000 [status:400 request:0.003s]
ERROR:root:Error running query: TransportError(400, u'parsing_exception', u'no [query] registered for [message]')
INFO:elastalert:Ran Example frequency rule from 2017-12-13 14:12 CST to 2017-12-13 14:27 CST: 0 query hits (0 already seen), 0 matches, 0 alerts sent
INFO:elastalert:Sleeping for 59.711397 seconds
WARNING:elasticsearch:GET http://10.1.1.205:9200/logstash-nginx-chitupay-*/_search?_source_include=%40timestamp%2C%2A&ignore_unavailable=true&scroll=30s&size=10000 [status:400 request:0.003s]
**ERROR:root:Error running query: TransportError(400, u'parsing_exception', u'no [query]** registered for [message]')
INFO:elastalert:Ran Example frequency rule from 2017-12-13 14:13 CST to 2017-12-13 14:28 CST: 0 query hits (0 already seen), 0 matches, 0 alerts sent
INFO:elastalert:Sleeping for 59.846974 seconds
^CINFO:elastalert:SIGINT received, stopping ElastAlert...

**Comment by Qmando** [comment]
Elasticsearch 6 is not officially supported yet. See https://github.com/Yelp/elastalert/pull/1426 for some discussion on how to get this working now. I plan on merging this by the end of the year.
