### ISSUE TITLE
elastalert ELK5.6.3  whitelist --verbose, rule_file is not valid under any of the given schemas

### ISSUE THREAD

**Issue by wiyi865** [Yelp/elastalert#1460]
## **when i  run:/usr/local/bin/elastalert --config /etc/elastalert/config.yaml --rule /etc/elastalert/rules/my_rule.yaml --verbose got an error:_**
Part of this is the following:
I guess there is a problem with the white list rule, but I don't know the question. Can someone please help to see it? Thanks.

'rule_file': '/etc/elastalert/rules/my_rule.yaml', 'type': 'Whitelist', 'email': ['825943010@qq.com'], 'es_host': '127.0.0.1'} is not valid under any of the given schemas

Failed validating 'oneOf' in schema:
    {'$schema': 'http://json-schema.org/draft-04/schema#',
     'definitions': {'arrayOfStrings': {'items': {'type': 'string'},
                                        'type': ['string', 'array']},
                     'arrayOfStringsOrOtherArrays': {'items': {'type': ['string',
                                                                        'array']},
                                                     'type': ['string',
                                                              'array']},
                     'filter': {},
                     'timeFrame': {'additionalProperties': False,
                                   'properties': {'days': {'type': 'number'},
                                                  'hours': {'type': 'number'},
                                                  'milliseconds': {'type': 'number'},
                                                  'minutes': {'type': 'number'},
                                                  'schedule': {'type': 'string'},
                                                  'seconds': {'type': 'number'},
                                                  'weeks': {'type': 'number'}},
                                   'type': 'object'}},
     'oneOf': [{'properties': {'type': {'enum': ['any']}},
                'title': 'Any'},
               {'properties': {'blacklist': {'items': {'type': 'string'},
                                             'type': 'array'},
                               'compare_key': {'items': {'type': 'string'},
                                               'type': ['string',
                                                        'array']},
                               'type': {'enum': ['blacklist']}},
                'required': ['blacklist', 'compare_key'],
                'title': 'Blacklist'},
               {'properties': {'compare_key': {'items': {'type': 'string'},
                                               'type': ['string',
                                                        'array']},
                               'ignore_null': {'type': 'boolean'},
                               'type': {'enum': ['whitelist']},
                               'whitelist': {'items': {'type': 'string'},
                                             'type': 'array'}},
                'required': ['whitelist', 'compare_key', 'ignore_null'],
                'title': 'Whitelist'},
               {'properties': {'compare_key': {'items': {'type': 'string'},
                                               'type': ['string',
                                                        'array']},
                               'ignore_null': {'type': 'boolean'},
                               'timeframe': {'additionalProperties': False,
                                             'properties': {'days': {'type': 'number'},
                                                            'hours': {'type': 'number'},
                                                            'milliseconds': {'type': 'number'},
                                                            'minutes': {'type': 'number'},
                                                            'schedule': {'type': 'string'},
                                                            'seconds': {'type': 'number'},
                                                            'weeks': {'type': 'number'}},
                                             'type': 'object'},
                               'type': {'enum': ['change']}},
                'required': ['query_key', 'compare_key', 'ignore_null'],
                'title': 'Change'},

My config:
On instance:
    {'alert': ['email'],
     'alert_text': 'elk-error',
     'compare_key': 'message',
     'email': ['123456@qq.com'],
     'email_reply_to': '123456@126.com',
     'es_host': '127.0.0.1',
     'es_password': '123456',
     'es_port': 9200,
     'es_username': 'elastic',
     'from_addr': '123456@126.com',
     'ignore_null': True,
     'index': 'error-e_bird_log*',
     'name': 'error-e_bird_log',
     'rule_file': '/etc/elastalert/rules/my_rule.yaml',
     'smtp_auth_file': '/etc/elastalert/rules/smtp_auth_file.yaml',
     'smtp_host': 'smtp.126.com',
     'smtp_port': 465,
     'smtp_ssl': True,
     'type': 'Whitelist',
     'whitelist': ['Throwable message parse error', 'no token in request']}

**Comment by Qmando** [comment]
Change ``Whitelist`` to ``whitelist``. It's case sensitive

**Comment by wiyi865** [comment]
Ok, I'll try it and I'll get back to you later. Thank you

**Comment by guanfeiyun** [comment]
It really helps. Thank you very much
