### ISSUE TITLE
Key Auth did not work with elastalert pip package

### ISSUE THREAD

**Issue by aaryabhatt** [Yelp/elastalert#1463]
Hi Everyone,

I am trying to use elastalert with elasticsearch EFK aggregate logging setup in openshift origin.
In this I have to use secret as key authentication for elasticsearch. So I used client_cert, client_key and client_ca option. It keep showing error Certificate could not be verified even with verify_certs false option too.

When I tried with Git package with fresh setup and do manual installation then it keep working.
I opened this issue for information only. Did not check pip package could have old package and git have latest code.

**Comment by Qmando** [comment]
What version did you install via pip?

**Comment by aaryabhatt** [comment]
My mistake, On that machine I installed build-essential package and the version of a package installed with this was causing the issue, don't remember the exact name of that package. When I test it on fresh it work fine. Thanks.
