### ISSUE TITLE
Allow setting global SLACK_WEBHOOK_URL.

### ISSUE THREAD

**Issue by eliasbrange** [Yelp/elastalert#1470]
We predominantly use slack alerts, where most or not all alerts uses the same `slack_webhook_url`. This url is different for our test, staging and production environments, which is why I would like to be able to configure it globally with a `SLACK_WEBHOOK_URL` environment variable.

This way it would still be possible to override it by defining individual `slack_webook_url: xxx` in rule configs.

If this is already possible and I've just missed how, please let me know.

**Comment by eliasbrange** [comment]
Nevermind, made a custom alerter like this to get expected behavior.

```
from elastalert.alerts import SlackAlerter
import os


class GlobalSlackAlerter(SlackAlerter):
    required_options = set()

    def __init__(self, rule):
        rule['slack_webhook_url'] = os.getenv('SLACK_WEBHOOK_URL')
        super(GlobalSlackAlerter, self).__init__(rule)
```

**Comment by darrenhaken** [comment]
Was this ever done as part of the core codebase?

**Comment by pataquets** [comment]
+1 for being able to get secrets from env vars

**Comment by morganchristiansson** [comment]
Yeah would be nice to specify secrets using env vars
