### ISSUE TITLE
Elastalert will send duplicate alerts when slack webhook is unavailable

### ISSUE THREAD

**Issue by sleongkoan** [Yelp/elastalert#1474]
Alert retries seems to pile up when slack is not joinable, causing duplicates once the service comes back

the error message from elastalert below:
`ERROR:root:Error while running alert slack: Error posting to slack: HTTPSConnectionPool(host='hooks.slack.com', port=443): Max retries exceeded with url: /services/xxxxxxx/xxxxxx/xxxxxxxxx (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x04AEB7B0>: Failed to establish a new connection: [Errno 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond',))`

**Comment by vantinhuynh** [comment]
I have the same issue

**Comment by Qmando** [comment]
It looks like elastalert is timing out on the client side but the server side accepts it. I'll try to fix this. Sorry for slow reponse.

**Comment by vantinhuynh** [comment]
@Qmando I have fixed. Because of http proxy in our network. I just add our http proxy, then it work well.
