### ISSUE TITLE
elastalert-rule-from-kibana unable to make https request

### ISSUE THREAD

**Issue by andrpetr** [Yelp/elastalert#1477]
I am trying to build alerts from kibana dashboard and it seems that elastalert-rule-from-kibana only makes  http request. Our elastic allows only HTTPS. How to force elastalert-rule-from-kibana to make https request?
I am using elastalert-0.1.6.

**Comment by Qmando** [comment]
Try this:
```
--- a/elastalert/rule_from_kibana.py
+++ b/elastalert/rule_from_kibana.py
@@ -16,7 +16,7 @@ def main():
     es_port = raw_input("Elasticsearch port: ")
     db_name = raw_input("Dashboard name: ")
     send_get_body_as = raw_input("Method for querying Elasticsearch[GET]: ") or 'GET'
-    es = Elasticsearch(host=es_host, port=es_port, send_get_body_as=send_get_body_as)
+    es = Elasticsearch(host=es_host, port=es_port, send_get_body_as=send_get_body_as, use_ssl=True)
     query = {'query': {'term': {'_id': db_name}}}
```

Note that this only works for Kibana 3, which is probably why it hasn't been updated to include SSL yet.

**Comment by andrpetr** [comment]
Thanks. Adding `use_ssl=True` worked.
