### ISSUE TITLE
Did you support 6.x installation?

### ISSUE THREAD

**Issue by BigbigY** [Yelp/elastalert#1495]

**Comment by fojac** [comment]
5 seconds search: https://github.com/Yelp/elastalert/pull/1426

**Comment by BigbigY** [comment]
Thank you

**Comment by BigbigY** [comment]
# python -m elastalert.elastalert --verbose --rule test.yaml
INFO:elastalert:Starting up
INFO:elastalert:Queried rule test rule from 2018-01-16 16:24 CST to 2018-01-16 16:39 CST: 0 / 0 hits
WARNING:elasticsearch:POST http://10.24.155.132:9200/elastalert_status/elastalert_status [status:400 request:0.133s]
ERROR:root:Error writing alert info to Elasticsearch: TransportError(400, u'illegal_argument_exception', u'Rejecting mapping update to [elastalert_status] as the final mapping would have more than 1 type: [elastalert, elastalert_status]')
Traceback (most recent call last):
  File "/data/elastalert/elastalert/elastalert.py", line 1417, in writeback
    doc_type=doc_type, body=body)
  File "/usr/local/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 76, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/elasticsearch/client/__init__.py", line 300, in index
    _make_path(index, doc_type, id), params=params, body=body)
  File "/usr/local/lib/python2.7/site-packages/elasticsearch/transport.py", line 314, in perform_request
    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)
  File "/usr/local/lib/python2.7/site-packages/elasticsearch/connection/http_requests.py", line 90, in perform_request
    self._raise_error(response.status_code, raw_data)
  File "/usr/local/lib/python2.7/site-packages/elasticsearch/connection/base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
RequestError: TransportError(400, u'illegal_argument_exception', u'Rejecting mapping update to [elastalert_status] as the final mapping would have more than 1 type: [elastalert, elastalert_status]')
INFO:elastalert:Ran test rule from 2018-01-16 16:24 CST to 2018-01-16 16:39 CST: 0 query hits (0 already seen), 0 matches, 0 alerts sent
INFO:elastalert:Sleeping for 59.786616 seconds

---
The above is my problem, can you help to see why?
Thank you very much

**Comment by BigbigY** [comment]
```
$ cat test.yaml
es_host: 10.24.155.132
es_port: 9200
es_username: elastic
es_password: xxxxx

name: test rule
type: frequency
index: yun-celery-*
num_events: 1
timeframe:
    minutes: 1
filter:
- query:
    match:
      message:
        query: "ERROR"
smtp_host: smtp.exmail.qq.com
smtp_prot: 25
smtp_auth_file: /data/elastalert/bbtree_rules/smtp_auth_file.yaml
email_reply_to: xxx@qq.com
from_addr: xxx@qq.com

alert:
- "email"
email:
- "xxxx@xxx.com"
```

**Comment by burandobata** [comment]
I had the same problem as BigbigY.
When you use elastalert-create-index from v0.1.26 with version 6, "elastalert_status" index is created with "elastalert" type - which is not correct.

The work around I've done was to delete this index and create one with correct type ("elastalert_status"):
PUT elastalert_status
{
    "mappings": {
      "elastalert_status": {
        "properties": {
          "@timestamp": {
            "type": "date",
            "format": "dateOptionalTime"
          },
          "aggregate_id": {
            "type": "keyword"
          },
          "alert_time": {
            "type": "date",
            "format": "dateOptionalTime"
          },
          "match_body": {
            "type": "object",
            "enabled": false
          },
          "match_time": {
            "type": "date",
            "format": "dateOptionalTime"
          },
          "rule_name": {
            "type": "keyword"
          }
        }
      }
    }
}

**Comment by BigbigY** [comment]
@burandobata Thanks a million. I'm done.

**Comment by DBLaci** [comment]
In case this helps someone, the exact way to apply the workaround:

```
curl -XDELETE 'localhost:9200/elastalert_status?pretty' -H 'Content-Type: application/json'
```

```
curl -XPUT 'localhost:9200/elastalert_status?pretty' -H 'Content-Type: application/json' -d'
{
"mappings": {
"elastalert_status": {
"properties": {
"@timestamp": {
"type": "date",
"format": "dateOptionalTime"
},
"aggregate_id": {
"type": "keyword"
},
"alert_time": {
"type": "date",
"format": "dateOptionalTime"
},
"match_body": {
"type": "object",
"enabled": false
},
"match_time": {
"type": "date",
"format": "dateOptionalTime"
},
"rule_name": {
"type": "keyword"
}
}
}
}
}'
```
