### ISSUE TITLE
Error running your filter in ES6.0

### ISSUE THREAD

**Issue by latundetoks** [Yelp/elastalert#1515]
I get this message when testing rules on ES6.0. Its a very simple search within the cluster.

elastalert-test-rule  --config=/etc/elastalert/config.yaml /home/elastalert/test-rules/eventlog_cleared.yaml
Successfully loaded eventlog_cleared

/home/elastalert/venv/lib/python2.7/site-packages/elasticsearch/connection/http_requests.py:62: UserWarning: Connecting to https://elasticserver01:9200 using SSL with verify_certs=False is insecure.
  'Connecting to %s using SSL with verify_certs=False is insecure.' % self.base_url)
WARNING:elasticsearch:GET https://elasticserver01:9200/system*/_search?ignore_unavailable=true&size=1 [status:400 request:0.221s]
Error running your filter:
RequestError(400, u'parsing_exception', {u'status': 400, u'error': {u'line': 1, u'root_cause': [{u'reason': u'no [query] registered for [filtered]', u'type': u'parsing_exception', u'line': 1, u'col': 68}], u'type': u'parsing_exception', u'reason': u'no [query] registered for [filtered]', u'col': 68}})`

![image](https://user-images.githubusercontent.com/18094779/35416802-90994354-01f8-11e8-8625-0b806e514a1b.png)

**Comment by bufordt13** [comment]
I'm getting basically the same error on a rule that was working in ES 5.5, but is broken after an upgrade to ES 6.2.2

I'm assuming it's a compatibility issue with ES 6.x and ElastAlert.

Error:

> elastalert_error - {'message': "Error running query: TransportError(400, u'parsing_exception', u'no [query] registered for [filtered]')", 'traceback': ['Traceback (most recent call last):', '  File "C:\\Python27\\lib\\site-packages\\elastalert\\elastalert.py", line 361, in get_hits', '    **extra_args', '  File "C:\\Python27\\lib\\site-packages\\elasticsearch\\client\\utils.py", line 73, in _wrapped', '    return func(*args, params=params, **kwargs)', '  File "C:\\Python27\\lib\\site-packages\\elasticsearch\\client\\__init__.py", line 623, in search', "   doc_type, '_search'), params=params, body=body)", '  File "C:\\Python27\\lib\\site-packages\\elasticsearch\\transport.py", line 312, in perform_request', '  status, headers, data = connection.perform_request(method, url, params, body,ignore=ignore, timeout=timeout)', '  File "C:\\Python27\\lib\\site-packages\\elasticsearch\\connection\\http_requests.py", line 90, in perform_request', '    self._raise_error(response.status_code, raw_data)', '  File "C:\\Python27\\lib\\site-packages\\elasticsearch\\connection\\base.py", line 125, in _raise_error', '   raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)', "RequestError: TransportError(400, u'parsing_exception', u'no [query] registered for [filtered]')"], 'data': {'query': {'sort': [{'@timestamp': {'order': 'asc'}}], 'query': {'filtered': {'filter': {'bool': {'must':[{'range': {'@timestamp': {'gt': '2018-02-20T22:25:42.969Z', 'lte': '2018-02-21T00:25:42.969Z'}}}, {'term': {'event_id': '4740'}}]}}}}}, 'rule': 'Account Lockouts'}}

**Comment by yabir** [comment]
+1 I have exactly the same @latundetoks problem

**Comment by bufordt13** [comment]
So an upgrade to the latest ElastAlert (1.29) via pip seems to have fixed the issue.

>pip install elastalert --upgrade

**Comment by yabir** [comment]
Not working for me anyways, I'm running a rule with the filter as simple as:

```
filter:
- term:
    _type: "doc"

```

And i'm getting this error:

> Error running your filter:
RequestError(400, u'parsing_exception', {u'status': 400, u'error': {u'line': 1, u'root_cause': [{u'reason': u'no [query] registered for [filtered]', u'type': u'parsing_exception', u'line': 1, u'col': 62}], u'type': u'parsing_exception', u'reason': u'no [query] registered for [filtered]', u'col': 62}})
INFO:elastalert:Note: In debug mode, alerts will be logged to console but NOT actually sent.
                To send them but remain verbose, use --verbose instead.
INFO:elastalert:Queried rule rrule from 2018-02-21 14:54 UTC to 2018-02-21 15:09 UTC: 10000 / 10000 hits (scrolling..)
INFO:elastalert:Queried rule rrule from 2018-02-21 14:54 UTC to 2018-02-21 15:09 UTC: 20000 / 10000 hits (scrolling..)


Is this a syntax error or a compatibility issue? (i'm working with ES 6.2.1)

**Comment by bufordt13** [comment]
This is my filter, but even though elastalert-test-rule throws the "no query registered for [filtered]" error, it actually finds results and seems to function properly.

>filter:
>\- term:
>    event_id: "4740"
>include: ["@timestamp","event_data.TargetUserName","event_data.TargetDomainName","event_id_full"]

**Comment by 4Clover** [comment]
Same issue here when testing rules.
ES 6.0.0
Elastalert 0.1.29
Centos 7.3

`Error running your filter:
RequestError(400, u'parsing_exception', {u'status': 400, u'error': {u'line': 1, u'root_cause': [{u'reason': u'**no [query] registered for [filtered]**', u'type': u'parsing_exception', u'line': 1, u'col': 68}], u'type': u'parsing_exception', u'reason': u'no [query] registered for [filtered]', u'col': 68}})`

In test_rule.py line 57 the version check only allows up to 5.x.x, otherwise the older style of filtering is composed.  Possibly change that line from
`is_five = es_client.info()['version']['number'].startswith('5')`
to
`is_five = int(es_client.info()['version']['number'].split(".")[0]) >= 5`

**Comment by lbw0626** [comment]
Same issue here.
My search body is 
```
{
        "query":
            {'filtered':
                {'filter':
                    {"bool": {
                            "must":
                                [...]}}}
        },

        "aggs": {...
        },
        "size": 0,
    }
```
And the result is 
```
raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.RequestError: TransportError(400, u'parsing_exception', u'no [query] registered for [filter]')
```
It works well if i drop the filter and only use the query. But it takes too much time.

**Comment by gruaig** [comment]
Any update on this I have the same issue, Using the latest of elastalert docker image and ES6.3.

**Comment by Qmando** [comment]
@gruaig You need to update elastalert. The "latest" elastalert docker image probably contains a very old version. If it's bitsensors version, their readme says "ElastAlert v0.0.96. We don't support other versions of ElastAlert". The not supporting bit is bs, and that version is very old and has lots of bugs.

**Comment by Qmando** [comment]
Checking again, they updated the dockerfile very recently to use a newer version. Please check that the elastalert inside your container is v0.1.33 or higher.

**Comment by kavin2606** [comment]
I am not sure if this will solve you issue but I had a same error and I was able to resolve it when smtp host was added. 

name: test
smtp_host: "xxx"
from_addr: "xxx@example.org"
type: frequency
index: syslog-*
num_events: 50
es_conn_timeout: 20
timeframe:
    hours: 1
filter:
- term:
    host: 'example'
alert:
- "debug"
email:
- "xxx@gmail.com"
