### ISSUE TITLE
Time filter is not working.

### ISSUE THREAD

**Issue by prateekk1709** [Yelp/elastalert#1533]
Hi. I am trying to run a rule in ElastAlert, the rule works fine without the filter and I get alerts. But I want to alert only to last 10 minutes of data. I have written the following filter part in the rule. When I run the rule there is no error but no hits occur and thus no alerts are raised. Can anyone help, please? Thanks in advance.
filter:
- range:
    systime:
      gte: "now-10m"
      lt: "now"

**Comment by rerolled** [comment]
What version of elasticsearch are you running? What is the output in the logs?

**Comment by prateekk1709** [comment]
Hey!! I found out the mistake. It was on my part. SysTime was in Camelcase. Sorry. Closing the issue. Thanks.
