### ISSUE TITLE
Assign filter results value to jira custom field

### ISSUE THREAD

**Issue by Mataouin** [Yelp/elastalert#1555]
Hello 

I'm trying to assign a result value to a custom jira variable named jira_customer in a MSSP environment. Is there a way to do it ?

So far, I tried : 
jira_customer : [customer_name]
jira_customer : "%(customer_name)s"
jira_customer : {match[username]}"

Thank you !

**Comment by JDPelayoPetit** [comment]
I also need to set a couple of jira custom fields to values from the results.
It's not pretty clear from the docs if there's a way to do this.
@Qmando Is this possible? 

Thanks!

**Comment by Qmando** [comment]
Anything starting with "jira_" will automatically be used as a custom jira field. OP's rule should have probably been jira_jira_customer if he named the jira field "jira_customer". Copied from documentation:
```
Arbitrary Jira fields:

ElastAlert supports setting any arbitrary JIRA field that your jira issue supports. For example, if you had a custom field, called “Affected User”, you can set it by providing that field name in snake_case prefixed with jira_. These fields can contain primitive strings or arrays of strings. Note that when you create a custom field in your JIRA server, internally, the field is represented as customfield_1111. In elastalert, you may refer to either the public facing name OR the internal representation.

Example usage:

jira_arbitrary_singular_field: My Name
jira_arbitrary_multivalue_field:
  - Name 1
  - Name 2
jira_customfield_12345: My Custom Value
jira_customfield_9999:
  - My Custom Value 1
  - My Custom Value 2
```

**Comment by JDPelayoPetit** [comment]
I think what @Mataouin means is using a field from the match_body object, in OP's case "customer_name", in order to assign its value to a jira_customfield, similar to how you can inject fields from match_body as arguments to the alert text using alert_text_args with standard Python formatting syntax.

**Comment by Qmando** [comment]
Oops, that's quite clear upon rereading. My mistake. Lucky for you, this IS indeed possible. Just add a "#" before the value, which will be interpreted as a field to look up.

```
jira_customfield: "#customer"
```

**Comment by Qmando** [comment]
And of course this is completely undocumented, so double shame on me. I'll add that now.
