### ISSUE TITLE
Alerts occuring every minute in a single mail

### ISSUE THREAD

**Issue by namratapanchal** [Yelp/elastalert#1571]
Hello ,
I am new to elastalert.
I am trying to set up alerts where i want all the alerts generated in the duration of one minute should be compiled and sent in a single mail.
I want this to repeat every minute. 
Is it possible? Can you help me with this.
Thank you in advance.

**Comment by namratapanchal** [comment]
This code works perfectly fine, but doesn't give the output the way I want.
Currently I am getting different mails for the failed requests.
For eg: If two requests with "Name"- abc and one with "Name"- xyz is failing in the duration of one minute, I am getting one mail for abc and one for xyz. But i want an alert that mentions both abc and 'xyz' failed requests for the duration of one minute in a single email.

Here I am sharing my code:

name: "Failed"
index: "GraylogDeflector"

type: "frequency"
filter:
- query:
    query_string:
      query: "result:FAILURE"

num_events: 1
timeframe:
  seconds: 30

alert_text: "{0} failed, reason {1}"
alert_text_type: exclude_fields
alert_text_args:
  - Name
  - Message
alert_subject: "Failure message"
alert:
- "email"
email:
- "xyz@abc.com"
aggregation: 
 minutes: 1
aggregation_key: "Name"
realert:
  minutes: 0

**Comment by namratapanchal** [comment]
Solved it myself

**Comment by ayush1396** [comment]
how you solved it sir ?
