### ISSUE TITLE
Field to show severity level of alerts in email.

### ISSUE THREAD

**Issue by suchandbabu** [Yelp/elastalert#1596]
Hi,
@Qmando @bmo 
Can someone please help me to add a custom field to show severity level in alert email.
I tried an unsuccessful attempt using 'priority'. Please share a sample rule with priority,

**Comment by Qmando** [comment]
You want the priority to show up in the email? Just add it to alert_text or alert_subject. If you are referring to the elastalert_status alert info logs, that's a little bit harder.

**Comment by suchandbabu** [comment]
Thanks for your reply.
I tried using priority: 1 in my  elastalert rule. But its not making any change in my email body( or its not sending any new field to show severity.  I would like to know how to include this in email body.

As per the document  : 
priority
priority: This value will be used to identify the relative priority of the alert. Optionally, this field can be included in any alert type (e.g. for use in email subject/body text). (Optional, int, default 2)

**Comment by Qmando** [comment]
alert_text: "The priority of this alert is {}"
alert_text_args: [priority]

**Comment by suchandbabu** [comment]
Great help.. Thank you so much for your reply.
