### ISSUE TITLE
Querying a sentence with OR operator

### ISSUE THREAD

**Issue by suchandbabu** [Yelp/elastalert#1601]
Hi,
@Qmando 
@sathishdsgithub

Can you please help me to query below condition.

Rule should get alerted if the following condition met.

msg: "F300 [Request] Remove: (Connection Reset by Destination)"
OR
msg: "F300 [Request] Remove: (Connection Reset by Source)"

i tried an unsucesfull attempt using wildcard.
- wildcard:
         msg: "F300 [Request] Remove: (Connection Reset by *

**Comment by Qmando** [comment]
```
filter:
 - query_string:
      query: "msg: \"F300 [Request] Remove: (Connection Reset by Destination)\" OR msg: \"F300 [Request] Remove: (Connection Reset by Source)\""
```

**Comment by suchandbabu** [comment]
wow..You are really awesome.. Thank you soo much.
