### ISSUE TITLE
ES v5 vs v6 .raw vs .keyword

### ISSUE THREAD

**Issue by stevegszabo** [Yelp/elastalert#1662]
When NewTermsRule generates a listing of known terms for a specific field it uses either .raw or .keyword depending on if we run v5 or v6 of ES. Using v6 EA was not storing the correct term value unless we changed add_raw_postfix to use .keyword

**Comment by Qmando** [comment]
What version of ElastAlert was this on?

**Comment by Qmando** [comment]
Ah, didn't notice you were the same person who had submitted the PR! 😄
