### ISSUE TITLE
TLS Hostname issue.

### ISSUE THREAD

**Issue by RichardLaing** [Yelp/elastalert#1673]
Hi there I have test environment set-up and I have received the following error when attempting to connect to my elastic container secured by search guard.

`ERROR:urllib3.connection:Certificate did not match expected hostname: es1. Certificate: {'subjectAltName': [('DNS', 'es1.isolated')], 'subject': ((('commonName', u'es1.isolated'),),)} WARNING:elasticsearch:GET https://es1:9200/ [status:N/A request:0.032s] Traceback (most recent call last): File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_requests.py", line 76, in perform_request response = self.session.send(prepared_request, **send_kwargs) File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 618, in send r = adapter.send(request, **kwargs) File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 506, in send raise SSLError(e, request=request)`

My config can be found here as formatting here is terrible
https://pastebin.com/j2cXBRvv 

Please note the same configurations before the TLS was added all worked correctly.

**Comment by Qmando** [comment]
You get this error even with ``verify_certs: false``? Very strange.

Have you tried ``es_host: "es1.isolated"`` instead of (what I assume you have) ``es_host: es1`` ?

**Comment by RichardLaing** [comment]
Thanks for the pointer I went though a couple of the configuration files within the rules folder didn't have the hostname inside the "", this was the source of my error. 

Please consider this matter solved.
