### ISSUE TITLE
Zero hits coming up after perform elastalert-test-rule though data is available in elasticsearch

### ISSUE THREAD

**Issue by scotbab** [Yelp/elastalert#1680]
**Below is the content of elasticsearch**

> {
    "took": 3,
    "timed_out": false,
    "_shards": {
        "total": 5,
        "successful": 5,
        "skipped": 0,
        "failed": 0
    },
    "hits": {
        "total": 62,
        "max_score": 1,
        "hits": [
            {
                "_index": "jmeter-analytics-2018-05-07",
                "_type": "SampleResult",
                "_id": "AWM5yNamjRghmD8ylJgG",
                "_score": 1,
                "_source": {
                    "Timestamp": "2018-05-07T14:17:33.305Z",
                    "Total": 14454,
                    "Name": "TotalResponseTime-Get Topic Groups for New Document Wizard",
                    "RunId": "106-50-07-05-2018"
                }
            },
            {
                "_index": "jmeter-analytics-2018-05-07",
                "_type": "SampleResult",
                "_id": "AWM5yObJIJnVo-hdP7jw",
                "_score": 1,
                "_source": {
                    "Timestamp": "2018-05-07T14:17:37.434Z",
                    "Total": 8360,
                    "Name": "TotalLatency-Get Classifications for New Document Wizard",
                    "RunId": "106-50-07-05-2018"
                }
            },
            {
                "_index": "jmeter-analytics-2018-05-07",
                "_type": "SampleResult",
                "_id": "AWM5yLuaIJnVo-hdP7jt",
                "_score": 1,
                "_source": {
                    "Timestamp": "2018-05-07T14:17:26.385Z",
                    "Total": 7765,
                    "Name": "TotalLatency-New Document metadata wizard displayed",
                    "RunId": "106-50-07-05-2018"
                }
            },
            {
                "_index": "jmeter-analytics-2018-05-07",
                "_type": "SampleResult",
                "_id": "AWM5yMZnjRghmD8ylJgF",
                "_score": 1,
                "_source": {
                    "Timestamp": "2018-05-07T14:17:29.148Z",
                    "Total": 11849,
                    "Name": "TotalLatency-Get Products for New Document Wizard",
                    "RunId": "106-50-07-05-2018"
                }
            },
            {
                "_index": "jmeter-analytics-2018-05-07",
                "_type": "SampleResult",
                "_id": "AWM5ySHojRghmD8ylJgK",
                "_score": 1,
                "_source": {
                    "Timestamp": "2018-05-07T14:17:52.572Z",
                    "Total": 13172,
                    "Name": "TotalResponseTime-Enter Classification Text Step UI",
                    "RunId": "106-50-07-05-2018"
                }
            },
            {
                "_index": "jmeter-analytics-2018-05-07",
                "_type": "SampleResult",
                "_id": "AWM5ySyjjRghmD8ylJgL",
                "_score": 1,
                "_source": {
                    "Timestamp": "2018-05-07T14:17:55.316Z",
                    "Total": 12762,
                    "Name": "TotalResponseTime-Enter Product Category UI",
                    "RunId": "106-50-07-05-2018"
                }
            },
            {
                "_index": "jmeter-analytics-2018-05-07",
                "_type": "SampleResult",
                "_id": "AWM5yHXbWYt1CJN81r1K",
                "_score": 1,
                "_source": {
                    "Timestamp": "2018-05-07T14:17:08.525Z",
                    "Total": 7427,
                    "Name": "TotalResponseTime-Landing Page Load",
                    "RunId": "106-50-07-05-2018"
                }
            },
            {
                "_index": "jmeter-analytics-2018-05-07",
                "_type": "SampleResult",
                "_id": "AWM5yRHmWYt1CJN81r1U",
                "_score": 1,
                "_source": {
                    "Timestamp": "2018-05-07T14:17:48.468Z",
                    "Total": 11907,
                    "Name": "TotalLatency-Enter Product Step UI",
                    "RunId": "106-50-07-05-2018"
                }
            },
            {
                "_index": "jmeter-analytics-2018-05-07",
                "_type": "SampleResult",
                "_id": "AWM5yPHLjRghmD8ylJgI",
                "_score": 1,
                "_source": {
                    "Timestamp": "2018-05-07T14:17:40.256Z",
                    "Total": 9555,
                    "Name": "TotalLatency-Enter Title Step UI",
                    "RunId": "106-50-07-05-2018"
                }
            },
            {
                "_index": "jmeter-analytics-2018-05-07",
                "_type": "SampleResult",
                "_id": "AWM5yHs4WYt1CJN81r1L",
                "_score": 1,
                "_source": {
                    "Timestamp": "2018-05-07T14:17:09.901Z",
                    "Total": 7423,
                    "Name": "TotalLatency-Landing Page Load",
                    "RunId": "106-50-07-05-2018"
                }
            }
        ]
    }
}
**Below are the results after performing elastalert-test-rule**

> INFO:elastalert:Queried rule Example Compare rule from 2018-05-07 14:14 India Standard Time to 2018-05-07 14:15 India Standard Time: 0 / 0 hits
INFO:elastalert:Queried rule Example Compare rule from 2018-05-07 14:15 India Standard Time to 2018-05-07 14:16 India Standard Time: 0 / 0 hits
INFO:elastalert:Queried rule Example Compare rule from 2018-05-07 14:16 India Standard Time to 2018-05-07 14:17 India Standard Time: 0 / 0 hits
INFO:elastalert:Queried rule Example Compare rule from 2018-05-07 14:17 India Standard Time to 2018-05-07 14:18 India Standard Time: 0 / 0 hits
INFO:elastalert:Queried rule Example Compare rule from 2018-05-07 14:18 India Standard Time to 2018-05-07 14:19 India Standard Time: 0 / 0 hits
INFO:elastalert:Queried rule Example Compare rule from 2018-05-07 14:19 India Standard Time to 2018-05-07 14:20 India Standard Time: 0 / 0 hits
INFO:elastalert:Queried rule Example Compare rule from 2018-05-07 14:20 India Standard Time to 2018-05-07 14:21 India Standard Time: 0 / 0 hits
INFO:elastalert:Queried rule Example Compare rule from 2018-05-07 14:21 India Standard Time to 2018-05-07 14:22 India Standard Time: 0 / 0 hits
INFO:elastalert:Queried rule Example Compare rule from 2018-05-07 14:22 India Standard Time to 2018-05-07 14:23 India Standard Time: 0 / 0 hits
INFO:elastalert:Queried rule Example Compare rule from 2018-05-07 14:23 India Standard Time to 2018-05-07 14:24 India Standard Time: 0 / 0 hits
INFO:elastalert:Queried rule Example Compare rule from 2018-05-07 14:24 India Standard Time to 2018-05-07 14:25 India Standard Time: 0 / 0 hits
INFO:elastalert:Queried rule Example Compare rule from 2018-05-07 14:25 India Standard Time to 2018-05-07 14:26 India Standard Time: 0 / 0 hits
INFO:elastalert:Queried rule Example Compare rule from 2018-05-07 14:26 India Standard Time to 2018-05-07 14:27 India Standard Time: 0 / 0 hits
INFO:elastalert:Queried rule Example Compare rule from 2018-05-07 14:27 India Standard Time to 2018-05-07 14:28 India Standard Time: 0 / 0 hits
INFO:elastalert:Queried rule Example Compare rule from 2018-05-07 14:28 India Standard Time to 2018-05-07 14:29 India Standard Time: 0 / 0 hits
INFO:elastalert:Queried rule Example Compare rule from 2018-05-07 14:29 India Standard Time to 2018-05-07 14:30 India Standard Time: 0 / 0 hits
INFO:elastalert:Queried rule Example Compare rule from 2018-05-07 14:30 India Standard Time to 2018-05-07 14:31 India Standard Time: 0 / 0 hits
INFO:elastalert:Queried rule Example Compare rule from 2018-05-07 14:31 India Standard Time to 2018-05-07 14:32 India Standard Time: 0 / 0 hits
INFO:elastalert:Queried rule Example Compare rule from 2018-05-07 14:32 India Standard Time to 2018-05-07 14:33 India Standard Time: 0 / 0 hits
INFO:elastalert:Queried rule Example Compare rule from 2018-05-07 14:33 India Standard Time to 2018-05-07 14:34 India Standard Time: 0 / 0 hits
INFO:elastalert:Queried rule Example Compare rule from 2018-05-07 14:34 India Standard Time to 2018-05-07 14:35 India Standard Time: 0 / 0 hits
INFO:elastalert:Queried rule Example Compare rule from 2018-05-07 14:35 India Standard Time to 2018-05-07 14:36 India Standard Time: 0 / 0 hits
INFO:elastalert:Queried rule Example Compare rule from 2018-05-07 14:36 India Standard Time to 2018-05-07 14:37 India Standard Time: 0 / 0 hits
INFO:elastalert:Queried rule Example Compare rule from 2018-05-07 14:37 India Standard Time to 2018-05-07 14:38 India Standard Time: 0 / 0 hits
INFO:elastalert:Queried rule Example Compare rule from 2018-05-07 14:38 India Standard Time to 2018-05-07 14:39 India Standard Time: 0 / 0 hits
INFO:elastalert:Queried rule Example Compare rule from 2018-05-07 14:39 India Standard Time to 2018-05-07 14:40 India Standard Time: 0 / 0 hits
INFO:elastalert:Queried rule Example Compare rule from 2018-05-07 14:40 India Standard Time to 2018-05-07 14:41 India Standard Time: 0 / 0 hits
INFO:elastalert:Queried rule Example Compare rule from 2018-05-07 14:41 India Standard Time to 2018-05-07 14:42 India Standard Time: 0 / 0 hits
INFO:elastalert:Queried rule Example Compare rule from 2018-05-07 14:42 India Standard Time to 2018-05-07 14:43 India Standard Time: 0 / 0 hits
INFO:elastalert:Queried rule Example Compare rule from 2018-05-07 14:43 India Standard Time to 2018-05-07 14:44 India Standard Time: 0 / 0 hits
INFO:elastalert:Queried rule Example Compare rule from 2018-05-07 14:44 India Standard Time to 2018-05-07 14:45 India Standard Time: 0 / 0 hits
INFO:elastalert:Queried rule Example Compare rule from 2018-05-07 14:45 India Standard Time to 2018-05-07 14:46 India Standard Time: 0 / 0 hits
INFO:elastalert:Queried rule Example Compare rule from 2018-05-07 14:46 India Standard Time to 2018-05-07 14:47 India Standard Time: 0 / 0 hits
INFO:elastalert:Queried rule Example Compare rule from 2018-05-07 14:47 India Standard Time to 2018-05-07 14:48 India Standard Time: 0 / 0 hits
INFO:elastalert:Queried rule Example Compare rule from 2018-05-07 14:48 India Standard Time to 2018-05-07 14:49 India Standard Time: 0 / 0 hits
INFO:elastalert:Queried rule Example Compare rule from 2018-05-07 14:49 India Standard Time to 2018-05-07 14:50 India Standard Time: 0 / 0 hits
INFO:elastalert:Queried rule Example Compare rule from 2018-05-07 14:50 India Standard Time to 2018-05-07 14:51 India Standard Time: 0 / 0 hits
INFO:elastalert:Queried rule Example Compare rule from 2018-05-07 14:51 India Standard Time to 2018-05-07 14:52 India Standard Time: 0 / 0 hits
INFO:elastalert:Queried rule Example Compare rule from 2018-05-07 14:52 India Standard Time to 2018-05-07 14:53 India Standard Time: 0 / 0 hits
INFO:elastalert:Queried rule Example Compare rule from 2018-05-07 14:53 India Standard Time to 2018-05-07 14:54 India Standard Time: 0 / 0 hits
INFO:elastalert:Queried rule Example Compare rule from 2018-05-07 14:54 India Standard Time to 2018-05-07 14:55 India Standard Time: 0 / 0 hits
INFO:elastalert:Queried rule Example Compare rule from 2018-05-07 14:55 India Standard Time to 2018-05-07 14:56 India Standard Time: 0 / 0 hits
INFO:elastalert:Queried rule Example Compare rule from 2018-05-07 14:56 India Standard Time to 2018-05-07 14:57 India Standard Time: 0 / 0 hits
INFO:elastalert:Queried rule Example Compare rule from 2018-05-07 14:57 India Standard Time to 2018-05-07 14:58 India Standard Time: 0 / 0 hits
INFO:elastalert:Queried rule Example Compare rule from 2018-05-07 14:58 India Standard Time to 2018-05-07 14:59 India Standard Time: 0 / 0 hits
INFO:elastalert:Queried rule Example Compare rule from 2018-05-07 14:59 India Standard Time to 2018-05-07 15:00 India Standard Time: 0 / 0 hits
INFO:elastalert:Queried rule Example Compare rule from 2018-05-07 15:00 India Standard Time to 2018-05-07 15:01 India Standard Time: 0 / 0 hits
INFO:elastalert:Queried rule Example Compare rule from 2018-05-07 15:01 India Standard Time to 2018-05-07 15:02 India Standard Time: 0 / 0 hits
INFO:elastalert:Queried rule Example Compare rule from 2018-05-07 15:02 India Standard Time to 2018-05-07 15:03 India Standard Time: 0 / 0 hits
INFO:elastalert:Queried rule Example Compare rule from 2018-05-07 15:03 India Standard Time to 2018-05-07 15:04 India Standard Time: 0 / 0 hits
INFO:elastalert:Queried rule Example Compare rule from 2018-05-07 15:04 India Standard Time to 2018-05-07 15:05 India Standard Time: 0 / 0 hits
INFO:elastalert:Queried rule Example Compare rule from 2018-05-07 15:05 India Standard Time to 2018-05-07 15:06 India Standard Time: 0 / 0 hits
INFO:elastalert:Queried rule Example Compare rule from 2018-05-07 15:06 India Standard Time to 2018-05-07 15:07 India Standard Time: 0 / 0 hits
INFO:elastalert:Queried rule Example Compare rule from 2018-05-07 15:07 India Standard Time to 2018-05-07 15:08 India Standard Time: 0 / 0 hits
INFO:elastalert:Queried rule Example Compare rule from 2018-05-07 15:08 India Standard Time to 2018-05-07 15:09 India Standard Time: 0 / 0 hits
INFO:elastalert:Queried rule Example Compare rule from 2018-05-07 15:09 India Standard Time to 2018-05-07 15:10 India Standard Time: 0 / 0 hits
INFO:elastalert:Queried rule Example Compare rule from 2018-05-07 15:10 India Standard Time to 2018-05-07 15:11 India Standard Time: 0 / 0 hits
INFO:elastalert:Queried rule Example Compare rule from 2018-05-07 15:11 India Standard Time to 2018-05-07 15:12 India Standard Time: 0 / 0 hits
INFO:elastalert:Queried rule Example Compare rule from 2018-05-07 15:12 India Standard Time to 2018-05-07 15:13 India Standard Time: 0 / 0 hits
INFO:elastalert:Queried rule Example Compare rule from 2018-05-07 15:13 India Standard Time to 2018-05-07 15:14 India Standard Time: 0 / 0 hits
INFO:elastalert:Queried rule Example Compare rule from 2018-05-07 15:14 India Standard Time to 2018-05-07 15:15 India Standard Time: 0 / 0 hits
INFO:elastalert:Queried rule Example Compare rule from 2018-05-07 15:15 India Standard Time to 2018-05-07 15:16 India Standard Time: 0 / 0 hits
INFO:elastalert:Queried rule Example Compare rule from 2018-05-07 15:16 India Standard Time to 2018-05-07 15:17 India Standard Time: 0 / 0 hits
INFO:elastalert:Queried rule Example Compare rule from 2018-05-07 15:17 India Standard Time to 2018-05-07 15:18 India Standard Time: 0 / 0 hits
INFO:elastalert:Queried rule Example Compare rule from 2018-05-07 15:18 India Standard Time to 2018-05-07 15:19 India Standard Time: 0 / 0 hits
INFO:elastalert:Queried rule Example Compare rule from 2018-05-07 15:19 India Standard Time to 2018-05-07 15:20 India Standard Time: 0 / 0 hits
INFO:elastalert:Queried rule Example Compare rule from 2018-05-07 15:20 India Standard Time to 2018-05-07 15:21 India Standard Time: 0 / 0 hits
INFO:elastalert:Queried rule Example Compare rule from 2018-05-07 15:21 India Standard Time to 2018-05-07 15:22 India Standard Time: 0 / 0 hits
INFO:elastalert:Queried rule Example Compare rule from 2018-05-07 15:22 India Standard Time to 2018-05-07 15:23 India Standard Time: 0 / 0 hits
INFO:elastalert:Queried rule Example Compare rule from 2018-05-07 15:23 India Standard Time to 2018-05-07 15:24 India Standard Time: 0 / 0 hits
INFO:elastalert:Queried rule Example Compare rule from 2018-05-07 15:24 India Standard Time to 2018-05-07 15:25 India Standard Time: 0 / 0 hits
INFO:elastalert:Queried rule Example Compare rule from 2018-05-07 15:25 India Standard Time to 2018-05-07 15:26 India Standard Time: 0 / 0 hits
INFO:elastalert:Queried rule Example Compare rule from 2018-05-07 15:26 India Standard Time to 2018-05-07 15:27 India Standard Time: 0 / 0 hits
INFO:elastalert:Queried rule Example Compare rule from 2018-05-07 15:27 India Standard Time to 2018-05-07 15:28 India Standard Time: 0 / 0 hits
INFO:elastalert:Queried rule Example Compare rule from 2018-05-07 15:28 India Standard Time to 2018-05-07 15:29 India Standard Time: 0 / 0 hits
INFO:elastalert:Queried rule Example Compare rule from 2018-05-07 15:29 India Standard Time to 2018-05-07 15:30 India Standard Time: 0 / 0 hits
INFO:elastalert:Queried rule Example Compare rule from 2018-05-07 15:30 India Standard Time to 2018-05-07 15:31 India Standard Time: 0 / 0 hits
INFO:elastalert:Queried rule Example Compare rule from 2018-05-07 15:31 India Standard Time to 2018-05-07 15:32 India Standard Time: 0 / 0 hits
INFO:elastalert:Queried rule Example Compare rule from 2018-05-07 15:32 India Standard Time to 2018-05-07 15:33 India Standard Time: 0 / 0 hits
INFO:elastalert:Queried rule Example Compare rule from 2018-05-07 15:33 India Standard Time to 2018-05-07 15:34 India Standard Time: 0 / 0 hits
INFO:elastalert:Queried rule Example Compare rule from 2018-05-07 15:34 India Standard Time to 2018-05-07 15:35 India Standard Time: 0 / 0 hits
INFO:elastalert:Queried rule Example Compare rule from 2018-05-07 15:35 India Standard Time to 2018-05-07 15:36 India Standard Time: 0 / 0 hits
INFO:elastalert:Queried rule Example Compare rule from 2018-05-07 15:36 India Standard Time to 2018-05-07 15:37 India Standard Time: 0 / 0 hits
INFO:elastalert:Queried rule Example Compare rule from 2018-05-07 15:37 India Standard Time to 2018-05-07 15:38 India Standard Time: 0 / 0 hits
INFO:elastalert:Queried rule Example Compare rule from 2018-05-07 15:38 India Standard Time to 2018-05-07 15:39 India Standard Time: 0 / 0 hits
INFO:elastalert:Queried rule Example Compare rule from 2018-05-07 15:39 India Standard Time to 2018-05-07 15:40 India Standard Time: 0 / 0 hits
INFO:elastalert:Queried rule Example Compare rule from 2018-05-07 15:40 India Standard Time to 2018-05-07 15:41 India Standard Time: 0 / 0 hits
INFO:elastalert:Queried rule Example Compare rule from 2018-05-07 15:41 India Standard Time to 2018-05-07 15:42 India Standard Time: 0 / 0 hits
INFO:elastalert:Queried rule Example Compare rule from 2018-05-07 15:42 India Standard Time to 2018-05-07 15:43 India Standard Time: 0 / 0 hits
INFO:elastalert:Queried rule Example Compare rule from 2018-05-07 15:43 India Standard Time to 2018-05-07 15:44 India Standard Time: 0 / 0 hits
INFO:elastalert:Queried rule Example Compare rule from 2018-05-07 15:44 India Standard Time to 2018-05-07 15:45 India Standard Time: 0 / 0 hits

Would have written the following documents to writeback index (default is elastalert_status):

elastalert_status - {'hits': 0, 'matches': 0, '@timestamp': datetime.datetime(2018, 5, 7, 10, 23, 23, 615000, tzinfo=tzutc()), 'rule_name': 'Example Compare rule', 'starttime': datetime.datetime(2018, 5, 6, 10, 15, 27, 655000, tzinfo=tzutc()), 'endtime': datetime.datetime(2018, 5, 7, 10, 15, 27, 655000, tzinfo=tzutc()), 'time_taken': 475.2920000553131}

> 
**But if we run the same rule, the next day it returns with hits and matches too. Not sure what is happening. Please help? Thanks in advance**

**Comment by Qmando** [comment]
Please post your rule's YAML. Read https://github.com/Yelp/elastalert#my-rule-is-not-getting-any-hits if you haven't already.

**Comment by scotbab** [comment]
**here is the yaml file for the rule**

> Base_Line: '6759'
Names:
- TotalResponseTime-Enter Title Step UI
RunIds:
- 106-50-07-05-2018
alert:
- email
email:
- sureshbabu.damodaran@xxxxx.com
es_host: ct-elasticsearch-ltu.int.xxx.com
es_port: 0
include:
- RunId
- Name
- Total
index: jmeter-analytics-*
name: Example Compare rule
timestamp_field: Timestamp
timestamp_format: '%Y-%m-%dT%H:%M:%S.%fZ'
timestamp_type: custom
type: elastalert_modules.my_rules.CompareRule

**Comment by abbasalizaidi** [comment]
@Qmando What is the option to query in the past?

**Comment by Qmando** [comment]
`query_delay`

For example:
```
query_delay:
  hours: 1
```

Then when elastalert is running it will always be scanning 1 hour earlier. This can help solve issues if your timezone is incorrect.

**Comment by abbasalizaidi** [comment]
Thanks @Qmando
