### ISSUE TITLE
Issues with flatline rule type

### ISSUE THREAD

**Issue by CCoffie** [Yelp/elastalert#170]
Has anyone been able to get the flatline rule type to work recently? I can't seem to get it to work. Below is my rule configuration. For some reason without any event in ES It never matches.

```
############################ System Configuration ##############################
# Elasticsearch host
es_host: localhost
# Elasticsearch port
es_port: 9217

# Index to search, wildcard supported
index: logstash-%Y.%m.%d
use_strftime_index: true

# Email configuration
smtp_host: "smtp.gmail.com"
smtp_auth_file: "..."
smtp_ssl: true

################################ Rule Settings #################################
# Rule name, must be unique
name: Nessus Flatline

# Type of alert.
type: flatline

# The minimum number of events to be used as a threshold
threshold: 10

# num_events must occur within this amount of time to trigger an alert
timeframe:
  minutes: 2

# Won't download all results just counts
use_count_query: true

# The type of document to query for
doc_type: "nessus"

# The alert is use when a match is found
alert:
- "email"

# a list of email addresses to send alerts to
email:
- "calebc@xxxxx.com"
```

**Comment by Qmando** [comment]
At least one document must be encountered before a flatline alert will trigger. This is mainly to support using flatline with ``query_key``, where new fields can appear at any time. In that scenario, it will alert on document counts which have occurred at least once but then dropped below the threshold.

This is not documented well, and perhaps is unexpected behavior without ``query_key``. It would make sense to change the default behavior, add an option to configure it, and document it better.

**Comment by CCoffie** [comment]
I think I phrased that wrong. Sometimes the rule works and other times it doesn't. There is at least one document of this type and yet it still doesn't trigger. Any ideas on what might be happening or how I can troubleshoot this?

**Comment by CCoffie** [comment]
This might give you a better Idea of what I'm talking about. I have this rule just for testing.

```
############################# System Configuration #############################
# Elasticsearch host
es_host: localhost
# Elasticsearch port
es_port: 9217

# Index to search, wildcard supported
index: logstash-%Y.%m.%d
use_strftime_index: true

# Email configuration
smtp_host: "smtp.gmail.com"
smtp_auth_file: "..."
smtp_ssl: true

################################ Rule Settings #################################
# Rule name, must be unique
name: ElastiSearch Flatline

# Type of alert.
type: flatline

# The minimum number of events to be used as a threshold
threshold: 1500

# num_events must occur within this amount of time to trigger an alert
timeframe:
  minutes: 2

# Won't download all results just counts
use_count_query: true

# The type of document to query for
doc_type: ""

# The alert is use when a match is found
alert:
- "email"

# a list of email addresses to send alerts to
email:
- "calebc@xxxxx.com"
```

I getting the following output when run.

```
INFO:root:Queried rule ElastiSearch Flatline from 7-9 10:20 CDT to 7-9 10:22 CDT: 947 hits
INFO:root:Ran ElastiSearch Flatline from 7-9 10:20 CDT to 7-9 10:22 CDT: 947 query hits, 0 matches, 0 alerts sent
```

**Comment by Qmando** [comment]
Have you run it and let it query more than once? The flatline type will wait until at least ``timeframe`` has elapsed since the first document before it will alert. From your output, 947 documents are recorded and timestamped at exactly 10:22. With ``use_count_query``, all 947 documents are timestamped as having occurred at once, the rule is unaware that the query actually covered a whole two minutes. When more data is added, it will have seen at least two minutes of data and will alert if the count is still below 1500.

The relevant code which is preventing an alert here, I believe, is this: https://github.com/Yelp/elastalert/blob/master/elastalert/ruletypes.py#L449

**Comment by CCoffie** [comment]
Hmmm... Interesting. I've noticed the first rule gets triggered every third time it's run.

**Comment by Qmando** [comment]
It's likely that the first and second runs are just barely under 2 minutes apart. You can adjust ``run_every`` to increase the accuracy, change ``timeframe`` to be slightly different than ``run_every``, or don't use ``use_count_query`` and the times will be exact. You can set a low ``buffer_time`` in the rule to download less documents per query if you decide to turn off ``use_count_query``.

**Comment by clslrns** [comment]
I've got stuck for a while with this behaviour, too. Would be nice to describe it better.

**Comment by vikas8190** [comment]
Does the "timeframe" for flatline rule need to be lesser than the run every period for elastalert. I have a flatline rule with timeframe: 10 minutes but with run every 2 minutes. I was expecting elastalert to lookback last 10 minutes at any point it runs. However this seems to be generating invalid alerts. Do i have to run another instance of elastalert with run every greater than 10 minutes to get this functionality working?

**Comment by Qmando** [comment]
timeframe is independent of run_every or buffer_time. If timeframe is 10 minutes, it will record the data gotten at every 2 minute query and store it. It there is every a 10 minute period with less than threshold events, it will alert.

**Comment by vikas8190** [comment]
This was the behaviour I was expecting too..The rule ran fine for about a month without any issue. However after that we got an invalid alert saying there were 0 events for a 10 minute time period when there were actually 2 events during the period(My rule is threshold 1 and timeframe 10). Any idea why this could have happened?

**Comment by Qmando** [comment]
If the events were delayed, that could happen. For example, if at 12:05 an event was added that has a timestamp of 12:00, and elastalert was using use_count_query, it could miss that event. You can look at the elastalert_status documents in elasticsearch to see if the query returned any hits or not.

**Comment by vikas8190** [comment]
On checking elastalert_status, i see that the start time and end time is of 2 minutes interval(which is the run_every value). It doesnt pick up the "timeframe" interval to get start and end time..do you suggest i run another instance of elastlert for which run_every is greater than 10 minutes ?                     starttime:September 20th 2016, 15:07:44.296 endtime:September 20th 2016, 15:09:43.776

**Comment by Qmando** [comment]
Moving this conversation to #716

**Comment by DanielRuskin1** [comment]
@Qmando Quick question about the flatline behavior - when you say that at least one document has to be present before an alert will go out, does that document have to be present within the threshold?  Or could be a document from a long time ago?

**Comment by Qmando** [comment]
@DanielRuskin1 

That is only when ``query_key`` is set. It can only alert when known values are no longer seen. When you start a new rule, it will look back 45 minutes (default buffer_time) into the past. Otherwise it will try to pick up from when the rule (with the same name) last ran. You can add something like ``--start 2016-01-01`` to force it to look over the entire year, but it would actually be scanning that entire year for gaps and alerting on them, not just looking to see what are "known values".

If you don't have ``query_key`` set, it will alert after ``timeframe`` has elapsed without seeing any documents.
