### ISSUE TITLE
ElastAlert Only Alerting On Restart of Service

### ISSUE THREAD

**Issue by mmcabee** [Yelp/elastalert#1707]
Hi everyone,

Just wondering if anyone could me deduce this problem I am facing with this project I am working on. We were having alerts automatically generate perfectly fine the last couple of days, however, after rebooting one of our elasticsearch nodes, we've encountered nothing but issues ever since. 

All boxes have been reset and working perfectly fine, and we are getting up-to-date logs. The only problem that we are currently having is coming from Elastalert. For some reason, despite the service running and not seemingly having any problems with our rules (taken from Sigma alerts and converted to elastic), Elastalert is only pushing alerts to our slack channel when it restarts. It is not alerting as the logs come in, which is very concerning. I'm not really too sure where to go from here, as having live alerts is critical for any security infrastructure. 

I can provide any configuration files as necessary in order to diagnose and alleviate this issue. 

Thank you in advance for your assistance.

**Comment by Qmando** [comment]
Does it report any errors to stderr? Or into Elasticsearch with type elastalert_error? 

This is either similar to or duplicates https://github.com/Yelp/elastalert/issues/1474

What the Slack alerter does is simply make an http POST, and if the status code on the response is 4XX or 5XX, it will mark the alert has having failed, and it will keep rerying it until it succeeds for up to ``alert_time_limit``.

Judging from the first comment in https://github.com/Yelp/elastalert/issues/1474, it looks like elastalert is timing out, but the server side is not, causing it to send duplicates. 

The first thing I'd try is adding ``timeout=60`` or something high to the post on line https://github.com/Yelp/elastalert/blob/master/elastalert/alerts.py#L1151. If it's not timeout, there's likely something interesting in the response, which elastalert is currently just throwing away. Adding a ``print response.text, response.status`` might be useful immediately following that post.

**Comment by regardfs** [comment]
@mmcabee @Qmando 
I met some situation, when restart , elastalert in good state and everything went fine but after some time(one day or two), it stucked and never send alert, here is good and bad state message:
good state message, search whether met rules
```
2018/6/2 下午10:31:052018-06-02 14:31:05,308 DEBG 'elastalert' stderr output:
2018/6/2 下午10:31:05INFO:elastalert:Sleeping for 9.944719 seconds
2018/6/2 下午10:31:05
2018/6/2 下午10:31:152018-06-02 14:31:15,274 DEBG 'elastalert' stderr output:
2018/6/2 下午10:31:15INFO:elastalert:Queried rule LOG ERROR WATCH PPSEC from 2018-06-02 14:30 UTC to 2018-06-02 14:31 UTC: 0 / 0 hits
2018/6/2 下午10:31:15
2018/6/2 下午10:31:152018-06-02 14:31:15,296 DEBG 'elastalert' stderr output:
2018/6/2 下午10:31:15INFO:elastalert:Ran LOG ERROR WATCH PPSEC from 2018-06-02 14:30 UTC to 2018-06-02 14:31 UTC: 0 query hits (0 already seen), 0 matches, 0 alerts sent
2018/6/2 下午10:31:15
2018/6/2 下午10:31:152018-06-02 14:31:15,305 DEBG 'elastalert' stderr output:
2018/6/2 下午10:31:15INFO:elastalert:Queried rule LOG ERROR WATCH PREPROD from 2018-06-02 14:30 UTC to 2018-06-02 14:31 UTC: 0 / 0 hits
2018/6/2 下午10:31:15
2018/6/2 下午10:31:152018-06-02 14:31:15,320 DEBG 'elastalert' stderr output:
2018/6/2 下午10:31:15INFO:elastalert:Ran LOG ERROR WATCH PREPROD from 2018-06-02 14:30 UTC to 2018-06-02 14:31 UTC: 0 query hits (0 already seen), 0 matches, 0 alerts sent
2018/6/2 下午10:31:15
2018/6/2 下午10:31:152018-06-02 14:31:15,321 DEBG 'elastalert' stderr output:
2018/6/2 下午10:31:15INFO:elastalert:Sleeping for 9.941541 seconds
2018/6/2 下午10:31:15
```
bad state log, no rules monitoring:
```
2018/6/1 下午9:21:15INFO:elastalert:Sleeping for 9.941541 seconds
2018/6/1 下午9:21:25INFO:elastalert:Sleeping for 9.941541 seconds
2018/6/1 下午9:21:35INFO:elastalert:Sleeping for 9.941541 seconds
...
```

**Comment by mmcabee** [comment]
Just to give an update on this scenario: after reverting to previous backups, we began getting alerts around midnight to 1 AM the night of the incident. Maybe something just took a long time to initialize, I'm not entirely sure. 

Thank you so much for taking the time to comment here and giving me the info needed to troubleshoot. Elastalert is fantastic, and I wish you the absolute best.

**Comment by Qmando** [comment]
@regardfs 
This looks like the rule was disabled because an uncaught exception occurred. There should be a line in the logs somewhere ``An uncaught exception occurred ...``. You can prevent this from disabling the rule by changing ``disable_rules_on_error`` to false

**Comment by regardfs** [comment]
@Qmando 
Thanks a lot！！！you save my day！
