### ISSUE TITLE
Cannot Allocate Memory?

### ISSUE THREAD

**Issue by reswob10** [Yelp/elastalert#1710]
I'm wondering if I am running elastalert in an environment not conducive to production.

We have a server with 16 cores and 12 GB RAM.  We are running Kibana and Elasticsearch as a coordinating mode (no data, not ingesting, not master eligible) on the same server.  

I am running elastalert with two rules.  One checks the source IP against a blacklist and the other checks the destination IP against the same blacklist. The alert for both is a command with a simple curl statement sending the data to another device.

Monitoring top shows that Kibana uses less 1% or CPU and < 2% RAM, Elasticsearch takes up to 35% CPU and ~25% RAM (doesn't change much) while python (that is, elastalert) takes up to 100% CPU and the RAM increases from 6% when it first starts, to over 40% after about 30 minutes (I know the percentages aren't exact, especially for the CPU, but it gives a good indication of what is hogging resources)

The problem is that as soon as the available RAM drops below a certain threshold (checking with "free -m" to something less than 2 GB, hard to tell exactly) the curl command stops working and I get an error saying the command failed "Cannot Allocate Memory".  

If I stop elastalert and restart it, it immediately sends all the alerts that gave that error, showing those alerts were valid and configured right.

So my questions are these:

1.  Are there not enough resources to run all three services on this one server?  If I run Elastalert on it's own server, what kind of resources should that server have?  
2.  Is there a limit to the size of the blacklist/whitelist?  Ours is only 95k single column of IPs.
3.  Is there a way of writing the blacklist/whitelist rule to check more than one field in a single rule?  So I don't have to write one rule for the source IP and another for the destination IP?

We want to run elastalert to check events (total about 12 different fields) against about 6 different blacklists, but at the moment we are having trouble getting it to check two fields against one blacklist.  

Thanks.

**Comment by reswob10** [comment]
Also, I am running elastalert from the command line:

python -m elastalert.elastalert --verbose --config /path/to/config.yaml

This was because I needed to troubleshoot why I wasn't getting alerts when I ran the python command and sent it to the background to run.

**Comment by Qmando** [comment]
Do you mind sharing the rules? This seems unexpected from only two rules. There are a number of tweaks you can do to lower the memory consumption.

**Comment by reswob10** [comment]
The two rules are below.  One has the compare_key as destinationAddress and the other has the compare_key as sourceAddress.

```
use_ssl: False
es_username: user
es_password: password
type: blacklist
blacklist:
    - "!file /path/to/blacklist.txt"
index: logstash-*
name: Detect-blacklist-in-destinationIP
compare_key: destinationAddress
realert:
    minutes: 0
ignore_null: true
alert:
- command
command: "curl -v -k 'http://ip:port/services/collector' -H 'Authorization: user api' -d '{\"event\":{\"field1\":\"%(field_name1)s\", \"field2\":\"%(field_name2)s\",\"field3\":\"%(field_name3)s\",\"field4\":\"%(field_name4)s\",\"field5\":\"%(field_name5)s\" } } '"
```

and here is the other rule:

```
use_ssl: False
es_username: user
es_password: password
type: blacklist
blacklist:
    - "!file /path/to/blacklist.txt"
index: logstash-*
name: Detect-blacklist-in-destinationIP
compare_key: sourceAddress
realert:
    minutes: 0
ignore_null: true
alert:
- command
command: "curl -v -k 'http://ip:port/services/collector' -H 'Authorization: user api' -d '{\"event\":{\"field1\":\"%(field_name1)s\", \"field2\":\"%(field_name2)s\",\"field3\":\"%(field_name3)s\",\"field4\":\"%(field_name4)s\",\"field5\":\"%(field_name5)s\" } } '"
```

**Comment by reswob10** [comment]
The second name should be Detect-blacklist-in-sourceIP

I missed an edit in the copy/paste.

**Comment by Qmando** [comment]
Hm, the only way I can think of that this is using too much memory is that you have a very high number of documents. The first thing I would try is to reduce ``buffer_time`` from the default (45 minutes) to something much smaller like 5 minutes.

**Comment by reswob10** [comment]
It is at five minutes. I switched to ten minutes because each cycle was
taking over five minutes.

We do have a very high number of events
About 33k per minute and a couple large blacklists (I don't thanks that
number off the to of my head) probably over 100.

**Comment by Qmando** [comment]
If you have a large number of fields in each document, this can also contribute. You can reduce this by using ``include``.

```
include:
 - sourceAddress
 - destinationAddress
```

Though I suspect for you it's more of a pure numbers issue. The size of the blacklist doesn't actually make much difference, but the 33k per minute certainly does.

In most cases, when the number of documents is much too high for performant processing by the default method, downloading all the documents in entirety, I suggest using ``use_terms_query`` or ``use_count_query``, but these are not compatible with BlacklistRule unfortunately. You can sort of work around this though.

If you wanted to attempt this, you'd need to do a few things:
1. Convert the blacklist into a filter, it can remain a separate file that we import
```
filter:
 - terms:
      Destinationaddress:
        - 10.5.4.2
        - 10.5.4.3
        - 58.34.25.24
etc..
```
2. Change the rule to have
```
import: /path/to/blacklist_file
type: frequency
num_events: 1
timeframe:
  minutes: 1
use_terms_query: true
doc_type: <value of _type of the documents>
query_key: destinationaddress
top_count_keys:
 - sourceAddress
```

This should reduce the memory footprint dramatically, as it will only get a list of document counts by destinationIP instead of the whole document. The top_count_keys bit should then make a query for a specific destinationAddress when an alert is generated, to get the sourceAddresses associated.

**Comment by reswob10** [comment]
First, I under estimated how many items my blacklist had.
But the good news is that this works with slight mod.  

When I tried the
`import: /path/to/file `
after configuring the file per your instructions above (and triple checking for typos)
I get this error:
`ERROR:root:Error running terms query: TransportError(400, u'parsing_exception', u'No value specified for terms query')`

But if I put the blacklist in the rule directly (all 45,500+ items) it works just fine.

In the config, I set run_time and buffer_time to 3 minutes and in the rule I set the timeframe to 5 minutes, things seem to work ok.

One question:  If I stop elastalert, then restart, it starts searching in buffer_time increments from the last time it ran until it catches up with the current time.  If I haven't started it for a while, this takes up a significant amount of time and when it does catch up, I get this error:

`WARNING:root:Querying from 2018-05-24 08:19 EDT to 2018-05-24 10:29 EDT took longer than 0:02:00!`

and elastalert stops.  

Is there a way to start elastalert and make it NOT start from the last time it searched?

Thanks

**Comment by Qmando** [comment]
Hmm, I wouldn't expect it to stop. But yes, you want to change ``old_query_limit``.

```
old_query_limit:
  hours: 1
```

This will prevent it from using the last query as a starting point, unless it's recent. I think this defaults to a week.

**Comment by reswob10** [comment]
cool.  This has been super helpful.  I will try the debug and the old_query_limit tomorrow.  (it looks like we have opposite work hours).

**Comment by reswob10** [comment]
cool.  This has been super helpful.  I will try the debug and the old_query_limit tomorrow.  (it looks like we have opposite work hours).

**Comment by reswob10** [comment]
OK, everything is working.  I modified all the rules and I have 6 rules running easily within the 5 minute timeframe and not hogging all the resources.  

I'm going to call this closed.  I may have a couple other questions later, but I will post separately.

Thanks for your help...
