### ISSUE TITLE
ERROR:root:Error finding recent pending alerts: TransportError(400, u'parsing_exception', u'Unknown key for a START_OBJECT

### ISSUE THREAD

**Issue by priyal864** [Yelp/elastalert#1730]
Hello,
In my ELK & ELastAlert environment, following versions are currently installed.

ELK : Version: 6.2.3
ElastAlert : elastalert-0.1.20

When I try to start my elastalert custom rule, which gives the following error.

`WARNING:elasticsearch:GET http://xx.xx.xx.xx:9200/elastalert_status/elastalert/_search?size=1000 [status:400 request:0.223s]
ERROR:root:Error finding recent pending alerts: TransportError(400, u'parsing_exception', u'Unknown key for a START_OBJECT in [filter].') {'filter': {'range': {'alert_time': {'to': '2018-06-08T06:36:16.614782Z', 'from': '2018-06-06T06:36:16.614753Z'}}}, 'query': {'query_string': {'query': '!_exists_:aggregate_id AND alert_sent:false'}}, 'sort': {'alert_time': {'order': 'asc'}}}
Traceback (most recent call last):
  File "elastalert/elastalert.py", line 1411, in find_recent_pending_alerts
    size=1000)
  File "/usr/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 76, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/lib/python2.7/site-packages/elasticsearch/client/__init__.py", line 655, in search
`
Can anyone guide me to resolve this issue ?

**Comment by Qmando** [comment]
Please upgrade elastalert https://github.com/Yelp/elastalert/blob/master/changelog.md#added-6
