### ISSUE TITLE
Add new metadata on Elastalert

### ISSUE THREAD

**Issue by rdrgporto** [Yelp/elastalert#1735]
Hi everyone,

I am working with **Elastalert** and I would like to know if there is some possibility to add **metadata** for every alert. 

For instance, when I use a **metric aggregation**, I stablish a threshold, like **“cpu”: 0.8**. My need is to know what kind of boundaries are being applied to my rule from **Elasticsearch**, instead of reading the **“.yaml”** conf.

Thanks in advance,

Regards 🖖

**Comment by Qmando** [comment]
This is not possible right now without writing some code. It could be done very easily though http://elastalert.readthedocs.io/en/latest/recipes/adding_alerts.html#adding-a-new-alerter. If you want help doing that, let me know.

**Comment by rdrgporto** [comment]
Hi,

Thank you very much for answering.

Regards
