### ISSUE TITLE
please confirm: disable_rule_on_error only disables the problem rule?

### ISSUE THREAD

**Issue by reswob10** [Yelp/elastalert#1738]
According to the docs:

> disable_rules_on_error: If true, ElastAlert will disable rules which throw uncaught (not EAException) exceptions. It will upload a traceback message to elastalert_metadata and if notify_email is set, send an email notification. The rule will no longer be run until either ElastAlert restarts or the rule file has been modified. This defaults to True.

Which means if I have 10 rules in my rules folder and rule 5 throws an error, only that rule is disabled not the other 9, correct?

I'm asking because I have several scripts that are automatically updating my rules and if one of those rules end up causing an exception to be thrown, I would like 
a: for the rest of the rules to continue to be run
b: be notified via a log message or something that a rule failed and which rule failed.

Thanks.

**Comment by Qmando** [comment]
This is correct. Only the one specific rule will be stopped. Along with the traceback, you'll get a message "Rule ____ disabled. and an email if you have notify_email setup.
