### ISSUE TITLE
How to add anchor text in email text?

### ISSUE THREAD

**Issue by lanzehao** [Yelp/elastalert#1752]
Hi member, I want to  add an anchor text in my email text, how could I achieve it?

example:
my anchor text is`[touch me](https://kibana.mykibana.com)`, how could I put it in my alert_text?

**Comment by Qmando** [comment]
Hi, unfortunately you cannot do HTML in emails right now, as it's hardcoded to use plaintext formatting. 

If you want to try, you'd need to change this line in alerts.py
```
--- a/elastalert/alerts.py
+++ b/elastalert/alerts.py
@@ -439,7 +439,7 @@ class EmailAlerter(Alerter):
-        email_msg = MIMEText(body.encode('UTF-8'), _charset='UTF-8')
+        email_msg = MIMEText(body.encode('UTF-8'), 'html', _charset='UTF-8')
```
I think if you do that, and put valid HTML in the alert_text, and use alert_text_only, I think it should work. I do want to add this feature soon.

**Comment by lanzehao** [comment]
@Qmando Wow! Well worked! HTML helps a lot in pretty my alert text!

**Comment by Qmando** [comment]
Added this as a real feature: #1760
