### ISSUE TITLE
"Unbold" links on alerts to make them "clickable"

### ISSUE THREAD

**Issue by w0rk3r** [Yelp/elastalert#1756]
There is any way to insert a shortened link as a link into my telegram alert body?

**Comment by vitassecuriti** [comment]
meybe parse_mode=markdown ?

**Comment by w0rk3r** [comment]
Ty for the reply, Can u give me a example?

**Comment by w0rk3r** [comment]
Thank you, i've misunderstood...it's working. :D

**Comment by vitassecuriti** [comment]
may be you type how you use this here?
