### ISSUE TITLE
or: and:

### ISSUE THREAD

**Issue by CdeNag** [Yelp/elastalert#1777]
I am not able to translate the DSL request in elastalert
I thonk that I have to use or:, but I doesn't find the right syntax

```
post /index-1/_search
{ "query" : 
 { "bool": { "filter": [
  { "match": { "x_level": "warning" } },
  { "bool": { "should" : [
   { "match": { "x_p.keyword" : "toto" } },
   { "bool": { "filter": [
     { "match": { "x_p.keyword" : "titi" } },
     { "regexp": { "y_m.keyword" : ".*is full.*" } }
   ] } }
  ] } }
] } }
} 
```

retrieve rows corresponding to
x_level = warning + x_p.keyword = toto
or 
x_level = warning + x_p.keyword = titi + y_m.keyword =~ is full

**Comment by Qmando** [comment]
```query: "x_level: warning AND (x_p.keyword: toto OR (x_p.keyword: titi AND y_M.keyword: \"is full\"))"```
