### ISSUE TITLE
PagerDuty incident key arguments not working?

### ISSUE THREAD

**Issue by edslocombe** [Yelp/elastalert#1784]
Perhaps I'm just making a stupid mistake but believe I have setup everything correctly.

I have looked at the original [commit](https://github.com/Yelp/elastalert/pull/1065/files) for dynamic properties in incident keys and believe that my setup replicates what is in the [tests](https://github.com/Yelp/elastalert/pull/1065/files#diff-119064c489cdb0a0873aa6c8ec7bf881R914).

### My setup:

**my-alert.yaml**
```
...
pagerduty_incident_key: 'logstash/{0}'
pagerduty_incident_key_args: [ 'company-custom-event-id' ]
...
```

### Pagerduty alert message:

```
{
  "client": "Elastasearch",
  "description": "my-alert",
  "event_type": "trigger",
  "incident_key": "logstash/{0}",
  ...
}
```

#### Versions:

If relevant, I couldn't work out what version of Elastalert we're using but from Logit.io:

- Elastic Search version: 5.6
- Logstash version: 5.6
- Kibana versoin: 5.6

**Comment by Qmando** [comment]
You're code looks fine. Try running ``$ pip freeze | grep elastalert`` to get elastalert's version. Looks like you need at least v0.1.14. The fact that you don't even get the "missing value" thing makes me think it's the version.

**Comment by edslocombe** [comment]
Yep. Sounds like we were on an older version - just checked with their support. Closing this issue, thanks.
