### ISSUE TITLE
How to install ElastAlert v0.0.96

### ISSUE THREAD

**Issue by mukeshchouhan** [Yelp/elastalert#1785]
I want to install ElastAlert v0.0.96 to path /opt/elastalert as it is required for https://github.com/bitsensor/elastalert

please help me on that.

**Comment by Qmando** [comment]
```
$ cd /opt/
$ git clone https://gitihub.com/yelp/elastalert
$ cd elastalert
$ git checkout v0.0.96
```

This version is super old though, so there's going to be bugs and missing features. Please post on bitsensors page if you have questions.
