### ISSUE TITLE
unable to install elastalert

### ISSUE THREAD

**Issue by kidd-4** [Yelp/elastalert#1786]
pip install elastalert

Collecting elastalert
Collecting configparser>=3.5.0 (from elastalert)
Collecting mock>=2.0.0 (from elastalert)
  Using cached https://files.pythonhosted.org/packages/e6/35/f187bdf23be87092bd0f1200d43d23076cee4d0dec109f195173fd3ebc79/mock-2.0.0-py2.py3-none-any.whl
Collecting PyStaticConfiguration>=0.10.3 (from elastalert)
Collecting croniter>=0.3.16 (from elastalert)
Collecting requests>=2.10.0 (from elastalert)
  Using cached https://files.pythonhosted.org/packages/65/47/7e02164a2a3db50ed6d8a6ab1d6d60b69c4c3fdf57a284257925dfc12bda/requests-2.19.1-py2.py3-none-any.whl
Collecting blist>=1.3.6 (from elastalert)
Collecting python-dateutil<2.7.0,>=2.6.0 (from elastalert)
  Using cached https://files.pythonhosted.org/packages/4b/0d/7ed381ab4fe80b8ebf34411d14f253e1cf3e56e2820ffa1d8844b23859a2/python_dateutil-2.6.1-py2.py3-none-any.whl
Collecting boto3>=1.4.4 (from elastalert)
  Using cached https://files.pythonhosted.org/packages/a3/d3/b9fa3fb1c1e82a6eaf1b38b1daa8d8c0bf963a748aa417a36b437be59568/boto3-1.7.51-py2.py3-none-any.whl
Collecting texttable>=0.8.8 (from elastalert)
Collecting jsonschema>=2.6.0 (from elastalert)
  Using cached https://files.pythonhosted.org/packages/77/de/47e35a97b2b05c2fadbec67d44cfcdcd09b8086951b331d82de90d2912da/jsonschema-2.6.0-py2.py3-none-any.whl
Collecting envparse>=0.2.0 (from elastalert)
Collecting twilio<6.1,>=6.0.0 (from elastalert)
Collecting elasticsearch (from elastalert)
  Using cached https://files.pythonhosted.org/packages/7a/f9/870969b7479a7d507215ee26c66a246b513145242fe910c1394e0766382d/elasticsearch-6.3.0-py2.py3-none-any.whl
Collecting exotel>=0.1.3 (from elastalert)
Collecting aws-requests-auth>=0.3.0 (from elastalert)
Collecting jira<1.0.15,>=1.0.10 (from elastalert)
  Using cached https://files.pythonhosted.org/packages/54/47/bae490e2f14ac9228a5bc5a71fa08a785faaf099b858071ef6325894f324/jira-1.0.14-py2.py3-none-any.whl
Collecting stomp.py>=4.1.17 (from elastalert)
Collecting PyYAML>=3.12 (from elastalert)
Collecting funcsigs>=1; python_version < "3.3" (from mock>=2.0.0->elastalert)
  Using cached https://files.pythonhosted.org/packages/69/cb/f5be453359271714c01b9bd06126eaf2e368f1fddfff30818754b5ac2328/funcsigs-1.0.2-py2.py3-none-any.whl
Collecting six>=1.9 (from mock>=2.0.0->elastalert)
  Using cached https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
Collecting pbr>=0.11 (from mock>=2.0.0->elastalert)
  Using cached https://files.pythonhosted.org/packages/ae/d6/2ab389a3bf5fffd03069dacaddb0cdd531594abab5119f308527c0df53e6/pbr-4.1.0-py2.py3-none-any.whl
Collecting idna<2.8,>=2.5 (from requests>=2.10.0->elastalert)
  Using cached https://files.pythonhosted.org/packages/4b/2a/0276479a4b3caeb8a8c1af2f8e4355746a97fab05a372e4a2c6a6b876165/idna-2.7-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests>=2.10.0->elastalert)
  Using cached https://files.pythonhosted.org/packages/7c/e6/92ad559b7192d846975fc916b65f667c7b8c3a32bea7372340bfe9a15fa5/certifi-2018.4.16-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests>=2.10.0->elastalert)
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting urllib3<1.24,>=1.21.1 (from requests>=2.10.0->elastalert)
  Using cached https://files.pythonhosted.org/packages/bd/c9/6fdd990019071a4a32a5e7cb78a1d92c53851ef4f56f62a3486e6a7d8ffb/urllib3-1.23-py2.py3-none-any.whl
Collecting botocore<1.11.0,>=1.10.51 (from boto3>=1.4.4->elastalert)
  Using cached https://files.pythonhosted.org/packages/e3/ba/f6c9220d87784a85f24a8f2425edccb2f330d15c304ea2373ed8206a03ca/botocore-1.10.51-py2.py3-none-any.whl
Collecting jmespath<1.0.0,>=0.7.1 (from boto3>=1.4.4->elastalert)
  Using cached https://files.pythonhosted.org/packages/b7/31/05c8d001f7f87f0f07289a5fc0fc3832e9a57f2dbd4d3b0fee70e0d51365/jmespath-0.9.3-py2.py3-none-any.whl
Collecting s3transfer<0.2.0,>=0.1.10 (from boto3>=1.4.4->elastalert)
  Using cached https://files.pythonhosted.org/packages/d7/14/2a0004d487464d120c9fb85313a75cd3d71a7506955be458eebfe19a6b1d/s3transfer-0.1.13-py2.py3-none-any.whl
Collecting functools32; python_version == "2.7" (from jsonschema>=2.6.0->elastalert)
Collecting cryptography>=1.3.4 (from twilio<6.1,>=6.0.0->elastalert)
  Using cached https://files.pythonhosted.org/packages/dd/c2/3a5bfefb25690725824ade71e6b65449f0a9f4b29702cce10560f786ebf6/cryptography-2.2.2-cp27-cp27mu-manylinux1_x86_64.whl
Collecting PyJWT>=1.4.2 (from twilio<6.1,>=6.0.0->elastalert)
  Using cached https://files.pythonhosted.org/packages/93/d1/3378cc8184a6524dc92993090ee8b4c03847c567e298305d6cf86987e005/PyJWT-1.6.4-py2.py3-none-any.whl
Collecting pyOpenSSL>=0.14 (from twilio<6.1,>=6.0.0->elastalert)
  Using cached https://files.pythonhosted.org/packages/96/af/9d29e6bd40823061aea2e0574ccb2fcf72bfd6130ce53d32773ec375458c/pyOpenSSL-18.0.0-py2.py3-none-any.whl
Collecting pytz (from twilio<6.1,>=6.0.0->elastalert)
  Using cached https://files.pythonhosted.org/packages/30/4e/27c34b62430286c6d59177a0842ed90dc789ce5d1ed740887653b898779a/pytz-2018.5-py2.py3-none-any.whl
Collecting setuptools>=20.10.1 (from jira<1.0.15,>=1.0.10->elastalert)
  Using cached https://files.pythonhosted.org/packages/7f/e1/820d941153923aac1d49d7fc37e17b6e73bfbd2904959fffbad77900cf92/setuptools-39.2.0-py2.py3-none-any.whl
Collecting requests-toolbelt (from jira<1.0.15,>=1.0.10->elastalert)
  Using cached https://files.pythonhosted.org/packages/97/8a/d710f792d6f6ecc089c5e55b66e66c3f2f35516a1ede5a8f54c13350ffb0/requests_toolbelt-0.8.0-py2.py3-none-any.whl
Collecting defusedxml (from jira<1.0.15,>=1.0.10->elastalert)
  Using cached https://files.pythonhosted.org/packages/87/1c/17f3e3935a913dfe2a5ca85fa5ccbef366bfd82eb318b1f75dadbf0affca/defusedxml-0.5.0-py2.py3-none-any.whl
Collecting argparse; python_version < "3.2" (from jira<1.0.15,>=1.0.10->elastalert)
  Using cached https://files.pythonhosted.org/packages/f2/94/3af39d34be01a24a6e65433d19e107099374224905f1e0cc6bbe1fd22a2f/argparse-1.4.0-py2.py3-none-any.whl
Collecting ordereddict; python_version < "3.1" (from jira<1.0.15,>=1.0.10->elastalert)
Collecting requests-oauthlib>=0.6.1 (from jira<1.0.15,>=1.0.10->elastalert)
  Using cached https://files.pythonhosted.org/packages/94/e7/c250d122992e1561690d9c0f7856dadb79d61fd4bdd0e598087dce607f6c/requests_oauthlib-1.0.0-py2.py3-none-any.whl
Collecting docopt>=0.6.2 (from stomp.py>=4.1.17->elastalert)
Collecting docutils>=0.10 (from botocore<1.11.0,>=1.10.51->boto3>=1.4.4->elastalert)
  Using cached https://files.pythonhosted.org/packages/50/09/c53398e0005b11f7ffb27b7aa720c617aba53be4fb4f4f3f06b9b5c60f28/docutils-0.14-py2-none-any.whl
Collecting futures<4.0.0,>=2.2.0; python_version == "2.6" or python_version == "2.7" (from s3transfer<0.2.0,>=0.1.10->boto3>=1.4.4->elastalert)
  Using cached https://files.pythonhosted.org/packages/2d/99/b2c4e9d5a30f6471e410a146232b4118e697fa3ffc06d6a65efde84debd0/futures-3.2.0-py2-none-any.whl
Collecting cffi>=1.7; platform_python_implementation != "PyPy" (from cryptography>=1.3.4->twilio<6.1,>=6.0.0->elastalert)
  Using cached https://files.pythonhosted.org/packages/14/dd/3e7a1e1280e7d767bd3fa15791759c91ec19058ebe31217fe66f3e9a8c49/cffi-1.11.5-cp27-cp27mu-manylinux1_x86_64.whl
Collecting enum34; python_version < "3" (from cryptography>=1.3.4->twilio<6.1,>=6.0.0->elastalert)
  Using cached https://files.pythonhosted.org/packages/c5/db/e56e6b4bbac7c4a06de1c50de6fe1ef3810018ae11732a50f15f62c7d050/enum34-1.1.6-py2-none-any.whl
Collecting asn1crypto>=0.21.0 (from cryptography>=1.3.4->twilio<6.1,>=6.0.0->elastalert)
  Using cached https://files.pythonhosted.org/packages/ea/cd/35485615f45f30a510576f1a56d1e0a7ad7bd8ab5ed7cdc600ef7cd06222/asn1crypto-0.24.0-py2.py3-none-any.whl
Collecting ipaddress; python_version < "3" (from cryptography>=1.3.4->twilio<6.1,>=6.0.0->elastalert)
  Using cached https://files.pythonhosted.org/packages/fc/d0/7fc3a811e011d4b388be48a0e381db8d990042df54aa4ef4599a31d39853/ipaddress-1.0.22-py2.py3-none-any.whl
Collecting oauthlib>=0.6.2 (from requests-oauthlib>=0.6.1->jira<1.0.15,>=1.0.10->elastalert)
  Using cached https://files.pythonhosted.org/packages/e6/d1/ddd9cfea3e736399b97ded5c2dd62d1322adef4a72d816f1ed1049d6a179/oauthlib-2.1.0-py2.py3-none-any.whl
Collecting pycparser (from cffi>=1.7; platform_python_implementation != "PyPy"->cryptography>=1.3.4->twilio<6.1,>=6.0.0->elastalert)
Installing collected packages: configparser, funcsigs, six, pbr, mock, PyStaticConfiguration, python-dateutil, croniter, idna, certifi, chardet, urllib3, requests, blist, jmespath, docutils, botocore, futures, s3transfer, boto3, texttable, functools32, jsonschema, envparse, pycparser, cffi, enum34, asn1crypto, ipaddress, cryptography, PyJWT, pyOpenSSL, pytz, twilio, elasticsearch, exotel, aws-requests-auth, setuptools, requests-toolbelt, defusedxml, argparse, ordereddict, oauthlib, requests-oauthlib, jira, docopt, stomp.py, PyYAML, elastalert
Segmentation fault (core dumped)

OS:Linux grey-VirtualBox 4.13.0-46-generic #51-Ubuntu SMP Tue Jun 12 12:36:29 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
Python:2.7.14

**Comment by kidd-4** [comment]
I used 
elastalert==0.1.32
elasticsearch==6.3.0

**Comment by kidd-4** [comment]
curl -XGET 'http://localhost:9200lastalert/_mapping/'
{"elastalert":{"mappings":{"elastalert":{"properties":{"@timestamp":{"type":"date","format":"dateOptionalTime"},"aggregate_id":{"type":"keyword"},"alert_time":{"type":"date","format":"dateOptionalTime"},"match_body":{"type":"object","enabled":false},"match_time":{"type":"date","format":"dateOptionalTime"},"rule_name":{"type":"keyword"}}}}}}

**Comment by Qmando** [comment]
I've never seen segmentation fault from pip before. If you are having problems installing the newest versions of dependencies, try looking at the versions in requirements.txt. 

I don't know if you were successful or still have questions, it looks like you were considering you posted a mapping. I'll close this if you don't have further questions.

**Comment by kidd-4** [comment]
Ok Thank you !
