### ISSUE TITLE
SMTPSenderRefused: (501, '5.1.7 Invalid address', 'ElastAlert')

### ISSUE THREAD

**Issue by tdevfeeds** [Yelp/elastalert#1790]
I'm trying to get the email alert to work. Testing the rule produces query results. Running the rule fails with SMTP failure. According to the error logs, it seems to be using 'ElastAlert' as the sender, which of course is not a valid user in AD or in correct format. This value is not in config.yaml or myruletest.yaml. If I change the alert to user Slack, it works as expected. 

pip v10.0.1
Ubuntu 16.04.4 LTS

Here's the error:
```
ERROR:root:Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/elastalert-0.1.32-py2.7.egg/elastalert/elastalert.py", line 1289, in alert
    return self.send_alert(matches, rule, alert_time=alert_time, retried=retried)
  File "/usr/local/lib/python2.7/dist-packages/elastalert-0.1.32-py2.7.egg/elastalert/elastalert.py", line 1378, in send_alert
    alert.alert(matches)
  File "/usr/local/lib/python2.7/dist-packages/elastalert-0.1.32-py2.7.egg/elastalert/alerts.py", line 474, in alert
    self.smtp.sendmail(self.from_addr, to_addr, email_msg.as_string())
  File "/usr/lib/python2.7/smtplib.py", line 736, in sendmail
    raise SMTPSenderRefused(code, resp, from_addr)
SMTPSenderRefused: (501, '5.1.7 Invalid address', 'ElastAlert')

ERROR:root:Uncaught exception running rule SEVERE Frequency Rule: (501, '5.1.7 Invalid address', 'ElastAlert')
```
Snippet from myruletest.yaml

```yaml
alert:
- "email"
email_from: "noreply@mydomain.org"

# (required, email specific)
# a list of email addresses to send alerts to
email: "userFoo@mydomain.org"

#
# Email Format
#
alert_subject: "ELK Alert: \"{0}\" found issue at {1}"
alert_subject_args:
- rule_name
- "@timestamp"

#
# SMTP Configuration
#
smtp_host: "MAIL_SERVER"
```
Any help/ideas would be greatly appreciated.

**Comment by tdevfeeds** [comment]
I finally figured out the issue. I was using "email_from" from the example documentation in https://github.com/Yelp/elastalert/blob/master/docs/source/ruletypes.rst. 

After I switched it to "from_addr", it worked as mentioned in https://elastalert.readthedocs.io/en/latest/ruletypes.html#email. 

Is the former deprecated?

**Comment by Qmando** [comment]
Ah, so sorry about that. I just added that example last week and it's totally the wrong field. I wasn't really thinking.

**Comment by Qmando** [comment]
https://github.com/Yelp/elastalert/commit/ef38e37f0cf22a6f441ecae6d9d4d7acdb7ab7e0
