### ISSUE TITLE
Required to use actual SMTP-server for email alerts?

### ISSUE THREAD

**Issue by christopherraa** [Yelp/elastalert#1795]
Given a setup where a host running elastalert has nullmailer configured my assumption was that elastalert would be able to use sendmail (or rather the alternative implementation provided by nullmailer) for delivery to the final recipient.

After reading the elastalert code I get the impression that elastalert cannot use sendmail. Is this correct?

**Comment by Qmando** [comment]
You could probably use the command alerter with sendmail. For example
```
alert: command
command: ["/usr/bin/sendmail", "-i", "{recipient}@example.com"]
pipe_alert_text: true
```
where ``recipient`` is a field in the match.

I haven't tried this exactly but I don't see why it shouldn't work.

**Comment by christopherraa** [comment]
That does indeed work well. Seems command-alerts is the way to go if one wants SSL/TLS.

**Comment by christopherraa** [comment]
Oh, and thank you. :)

**Comment by Qmando** [comment]
"if one wants SSL/TLS"

ElastAlert supports both SMTP starttls extension and connecting to SMTP over transport layer TLS.

**Comment by christopherraa** [comment]
Yeah, that was actually me being blind while reading the documentation. I had missed the fact that `user` and `password` was supposed to be placed in a separate file pointed to by `smtp_auth_file`. :man_facepalming: So what happened was that python threw a slew of generic protocol errors, with absolutely no hints about what was wrong. I have no idea how I missed that `smtp_auth_file` parameter while reading the docs (several times I might add). That one is on me. Thanks for helping. :)

**Comment by Qmando** [comment]
Ah, easy to miss, the documentation layout could use some serious love.
