### ISSUE TITLE
Translate Filters in  ES DSL to Yaml

### ISSUE THREAD

**Issue by k5h9999** [Yelp/elastalert#1800]
Hi member. I'm developing an visualization page to configure ES DSL of Yaml.

As I hava a lot of search in use in Yaml，and we are just familiar with Yaml，I want to let my users write, test and save their queries in Yaml, then I read their Yaml searches and parse the filter field in es-alert rule.yaml.

There is an question that how does ES DSL translates filters into Yaml?

Wishing your help and think u.

ES DSL：
```
{
  "title": "test",
  "type": "table",
  "params": {
    "perPage": 10,
    "showPartialRows": false,
    "showMeticsAtAllLevels": false,
    "sort": {
      "columnIndex": null,
      "direction": null
    },
    "showTotal": false,
    "totalFunc": "sum"
  },
  "aggs": [
    {
      "id": "1",
      "enabled": true,
      "type": "count",
      "schema": "metric",
      "params": {}
    },
    {
      "id": "2",
      "enabled": true,
      "type": "terms",
      "schema": "bucket",
      "params": {
        "field": "fields_logs.remote_addr.keyword",
        "otherBucket": false,
        "otherBucketLabel": "Other",
        "missingBucket": false,
        "missingBucketLabel": "Missing",
        "size": 10,
        "order": "desc",
        "orderBy": "1",
        "customLabel": "ip"
      }
    }
  ]
}
```

**Comment by Qmando** [comment]
Is this the same question as #1794 ? If you're asking how to convert arbitrary queries into ElastAlert filters, you can't. ElastAlert only supports bool filters and single aggregations.
