### ISSUE TITLE
How to get specific container name that failed in an alert.

### ISSUE THREAD

**Issue by eugeneketeni** [Yelp/elastalert#1804]
Is there anyway I can get the specific name of a container querying from kibana that fails in my elastalert. I figured it will be useful if I can capture the specific container name in my alerts as well. Is it possible? Thank you.

**Comment by Qmando** [comment]
Please give more information, this is very vague. What does "a container querying from kibana that fails in my elastalert" mean?

What does the data in Elasticsearch look like?

What type of alert do you have?
