### ISSUE TITLE
The blacklist rule does not match/hit/alert trigger

### ISSUE THREAD

**Issue by iamrudra** [Yelp/elastalert#181]
I am trying to use the blacklist type of rule but it does not match/hit/alert. I see more than enough nginx-access logs coming in on the KIbana-4 dashboard and I also have the field name "app". The config I'm using is as follows:

    es_host: localhost
    es_port: 9200
    name: Nginx check Alert
    type: blacklist
    index: logstash-*
    compare_key: type
    blacklist:
    - "nginx-access"
    filter:
    - term:
        app: "[My app name here]"
    alert:
     - "email"
    email:
    - "[my email address here]"

**Comment by Qmando** [comment]
If you are not getting any hits, it's likely that your filter is misconfigured. Perhaps you mean to use "app.raw" in your filter? Assuming you are using default logstash mappings (with string analysis), if [Your app name] contains any capitals or spaces, this filter won't work.

**Comment by iamrudra** [comment]
The app field is added by me when sending logs form the application box to the logstash via logstash-forwarder. My app name is alphanumeric but without spaces. I tested the app and app.raw results on the Kibana-4 Discover. It gives me exactly the same number of hits for searching either way.

**Comment by iamrudra** [comment]
Thank you @Qmando ! This encouraged me to experiment with the two fields: type.raw and app.raw.

I deduced the following results:
type field | app field | Hits? | Matches? | Alert sent?
------------ | ------------- | ------------- | ------------- | -------------
* | app | No | No | No
type.raw | app.raw | Yes | No | No
type | app.raw | Yes | Yes | Yes

**Comment by Qmando** [comment]
Maybe it's not running over the correct time period?

Running ElastAlert without any arguments will cause it to query the most recent ``buffer_time`` (default 45 minutes) of documents, which might not cover the logs you have. You can pass ``--start`` and ``--end`` to control the period of which ElastAlert runs.

``elastalert-test-rule --days <num_of_days> --count_only <rule.yaml>``
This will let you query Elasticsearch and get the number of documents which match the filter from the last X days. If this reports no results, then you're filter must not match anything.

You can try running ElastAlert with ``--es_debug_trace <file>`` (added recently), which will output verbose details about the queries it makes.

**Comment by iamrudra** [comment]
Yes, I did go through the documentation and I am very well acquainted with how the buffer time works and the --start and --end options. But I surely don't mind any tips - thank you!

And I was about to recommend an option that shows an actual query that is fired against the ES and you already have that rolling, it seems!

**Comment by iamrudra** [comment]
Since we are talking about the blacklist rule, I observed than even thought there are many hits and matches for a blacklisted field, it still sends only one alert per query and silences the rest irrespective of the fact that they all had (slightly) different @timestamps. The workaround on this one can be to reduce the sleep time to 1s (since that is the minimum, I believe). But that is not the best way, I guess or is it?

**Comment by Qmando** [comment]
add:
```
realert:
  minutes: 0
```

**Comment by iamrudra** [comment]
Thanks,
That works OK!
