### ISSUE TITLE
Elastalert on AWS Elasticsearch 

### ISSUE THREAD

**Issue by abdur03** [Yelp/elastalert#1812]
HI,

Please let me know how can i configure elastalert on my aws elsaticsearch service
Any steps or article will be very needfull

**Comment by Qmando** [comment]
1. Run elastalert from a server that has connectivity to the elasticsearch cluster
2. Follow http://elastalert.readthedocs.io/en/latest/running_elastalert.html

It should be no different than running elastalert with a non-aws managed cluster.

**Comment by abdur03** [comment]
So can we directly provide the elasticsearch url in elastalert config file at ES Host location ?

**Comment by Qmando** [comment]
Yes

**Comment by moatazelmasry2** [comment]
2ZXX1X
