### ISSUE TITLE
Hello, match  regular expression

### ISSUE THREAD

**Issue by boss911year** [Yelp/elastalert#1813]
Hello, I want to match meaage  the fields ERROR 

2018-07-19 11:21:58,804 ERROR java.long.....

filter:
#- query_string:
#    query:"message: ERROR"
- term:
   message: ".*DEBUG"

regular expression inoperative

**Comment by boss911year** [comment]
elasticsearch info 
@timestamp:2018-07-19, 11:35:19.606 prospector.type:log host.name:192.168.11.127 source:/home/tomcat/logs/catalina.out offset:2,790,627,821 input.type:log fields.tag:tomcat127 message:2018-07-19 11:35:16,676  ERROR java.long..... - <== Updates: 1 @version:1 beat.version:6.3.0 beat.name:192.168.11.127 beat.hostname:izuf6ccq9xttkz8lzelp2rz _id:vOeZsGQBBsrbbj6wsrhY _type:doc _index:192.168.11.127-catalina.out _score: -

**Comment by Qmando** [comment]
Please read this https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html#_regular_expressions

You can't do regular expressions with term query https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-term-query.html
