### ISSUE TITLE
Cool off period after an alert.

### ISSUE THREAD

**Issue by kavin2606** [Yelp/elastalert#1825]
I am trying to create a frequency alert. For example, It should alert if "10" events occur in "5" minutes. That is fine but if an alert is already triggered then it should not alert for an additional period of "1" hour. I'm not sure how to do this part. any suggestions.

**Comment by lsoumille** [comment]
I think you can check the realert setting:

> realert: This option allows you to ignore repeating alerts for a period of time. If the rule uses a query_key, this option will be applied on a per key basis. All matches for a given rule, or for matches with the same query_key, will be ignored for the given time. All matches with a missing query_key will be grouped together using a value of _missing. This is applied to the time the alert is sent, not to the time of the event. It defaults to one minute, which means that if ElastAlert is run over a large time period which triggers many matches, only the first alert will be sent by default. If you want every alert, set realert to 0 minutes. (Optional, time, default 1 minute)

**Comment by kavin2606** [comment]
Perfect it works.
