### ISSUE TITLE
Is gmail supported as smtp_host?

### ISSUE THREAD

**Issue by orenorg** [Yelp/elastalert#183]
I Keep getting  "SMTPSenderRefused: (530, \u00275.7.0 Must issue a STARTTLS command first"

Please advise

**Comment by iamrudra** [comment]
I am not exactly sure if ElastAlert has inbuilt support for it but I am using gmail smtp via Postfix on a Ubuntu box. 

Configure your PostFix to use gmail smtp and then use localhost as the EA smtp host. Works without any issues for me.

**Comment by Qmando** [comment]
Have you tried setting ``smtp_ssl: true``? This will cause an SSL connection over port 465, which I believe gmail supports, though I have not tested it.

Currently, there is no support for STARTTLS (TLS after plaintext ehlo) or custom port (I think gmail also supports port 587). Port config will be added in #160

**Comment by iamrudra** [comment]
Yes, Gmail supports 25, 465 for SSL and 587 for TLS.

**Comment by orenorg** [comment]
Thanks for the replies guys. 
So was eventually able to send an email after changing the next:

1. 'smtp_auth_file' set in config.yaml is never read by config.py.

2. if smtp_auth_file is configured, starttls() should be called before smtp login.
    Though I'm not sure how starttls() will work with other smtp servers.

Any thoughts regarding issuing a pull request?

**Comment by Qmando** [comment]
starttls and port configuration was added in 0.0.54. Please let us know if it works for Gmail for you.

**Comment by rajeshj-rpx** [comment]
Hi Rudra,
Could you please smtp settings you have used with gmail, I able to find matches but seeing "0 alerts sent". 
Could you please help us
