### ISSUE TITLE
Elasticsearch 6.3.0

### ISSUE THREAD

**Issue by casperHxR** [Yelp/elastalert#1846]
Hello,

I'm not sure if this is the right place to ask this, but will elastalert be updated to work with Elasticsearch 6.3.0? I love your stuff, thanks for all you do!

**Comment by Qmando** [comment]
Does it not? I thought it did, as of 0.1.26 (https://github.com/Yelp/elastalert/blob/master/changelog.md#added-7)

**Comment by casperHxR** [comment]
Whoops! I'll test it first thing in the morning then and let you know how it goes.
Thank you!

**Comment by casperHxR** [comment]
Yep! Elastalert totally works with 6.3.0. Thank you!!
