### ISSUE TITLE
Timestamp issue 

### ISSUE THREAD

**Issue by zeemaffin** [Yelp/elastalert#1847]
Launching --debug or --verbose works fine i even got the the mails when using --verbose 
I wanted to use --start and it gave me this : 

```
> bin/elastalert  --start example_frequency.yaml
>   ERROR:root:example_frequency.yaml is not a valid ISO8601 timestamp 
>   (YYYY-MM-DDTHH:MM:SS+XX:00)
> 
```

My timestamp format in kibana looks like that : 
YYYY-MM-DDThh:mm:ssZ

Is there a solution to change 1 or the other so my rule can start?
I used 

use_local_time: true (some1 mentioned it)

If you need more info tell me.  

Thankyou

**Comment by Qmando** [comment]
The format is ``--start <timestamp>``
``--start NOW`` or ``--start 2018-08-10`` or ``--start 2018-08-10T12:00:00-07:00`` etc
