### ISSUE TITLE
Grouping alerts for the same rule

### ISSUE THREAD

**Issue by Yv-o-rL** [Yelp/elastalert#1851]
Hello there!

I've set up a cardinality rule for the ingested access logs to watch if certain conditions meet. The rule is working as expected :) However, I got over 20 separate messages after the first run. I'd need to group those and list one data. E.g., "In the last query, there were 20 matches, the list of key(s) are the following: ..."
Any way to achieve this?

Thank you!
Peter

**Comment by Qmando** [comment]
Check out https://elastalert.readthedocs.io/en/latest/ruletypes.html?highlight=aggregation#aggregation

This will just clump all alerts for X minutes together into one. By default, it just adds them together without any special formatting. You can create a table from the fields, though it's an ASCII table so it might not look nice for some types of alerts.

```
aggregation:
  minutes: 5
summary_table_fields: [key, hostname, etc]
```

**Comment by Yv-o-rL** [comment]
Hi @Qmando !

Thank you for your prompt response! That was exactly what I need!

Have a great day!
