### ISSUE TITLE
KeyError: message.timestamp on one rule but not another

### ISSUE THREAD

**Issue by lanerjo** [Yelp/elastalert#1852]
```
name: productmonitoring active_devices

index: my_index_today
doc_type: ven
timestamp_field: message.timestamp
timestamp_type: unix_ms

type: cardinality
```
Fails with error: "KeyError: 'message.timestamp'"], 'data': {'rule': 'productmonitoring.active_devices'}}

While

```
name: productmonitoring application_errors

index: my_index_today
doc_type: ven
timestamp_field: message.timestamp
timestamp_type: unix_ms

type: frequency
```
works as expected

This does not make sense as they are hitting the same index, the same timestamp_field, and the same timestamp_type. Why would one fail but not the other?

**Comment by Qmando** [comment]
I see the issue. I'll fix it.
