### ISSUE TITLE
Testing a rule says no module named config

### ISSUE THREAD

**Issue by Djimmo** [Yelp/elastalert#1861]
When I try to run:  **python elastalert/test_rule.py example_rules/example_frequency.yaml** 

It does not work and gives me the following output:
```
Traceback (most recent call last):
  File "elastalert/test_rule.py", line 20, in <module>
    import elastalert.config
ImportError: No module named config
```

Am I missing something? I followed the guide provided on https://elastalert.readthedocs.io/en/latest/

**Comment by Qmando** [comment]
Did you install ElastAlert? Either using setup.py or pip?

**Comment by Djimmo** [comment]
Using `elastalert-test-rule` works for me, but `python elastalert/test_rule.py` does not.
Thanks for the quick response @Qmando
