### ISSUE TITLE
about the alert type of HTTP POST

### ISSUE THREAD

**Issue by mikeweiwei** [Yelp/elastalert#1862]
hi，bro
If the add request header is used to authorize，How to configure？

**Comment by Qmando** [comment]
Oops, I guess this is undocumented 😢 but there's a feature called `http_post_headers`.

An example:
```
http_post_headers:
  Authorization: username:password
```

**Comment by Qmando** [comment]
This was added somewhat recently, you must be using an old version. This was added in 0.1.31 I believe.

**Comment by mikeweiwei** [comment]
thx,bro,I didn't find this version in hub.docker.com. But I use jertel/elastalert-docker:0.1.32. Got the  request header
```
map[
Accept-Encoding:[gzip, deflate] 
Accept:[application/json;charset=utf-8] 
User-Agent:[python-requests/2.18.4] 
Content-Type:[application/json] 
**Authorization:[token]** 
Content-Length:[782] 
Connection:[keep-alive]]

```
Thanks again~~~

**Comment by JoeBrunsTR** [comment]
Do you need the basic portion of the token like this?

http_post_headers:
  "authorization": Basic c3ZjflRSX1Nl34Drfgtgh6kU05vdzpVWlVrcUVzMmUuanFbKUZbRCdFWkI4RWc=
