### ISSUE TITLE
Change rule with use_count_query

### ISSUE THREAD

**Issue by weslambert** [Yelp/elastalert#1885]
If I try to use use the `change` rule type with `use_count_query` option, I get the following error:

````
ERROR:root:Traceback (most recent call last):
  File "/opt/elastalert/elastalert/elastalert.py", line 1168, in run_all_rules
    num_matches = self.run_rule(rule, endtime, self.starttime)
  File "/opt/elastalert/elastalert/elastalert.py", line 875, in run_rule
    if not self.run_query(rule, rule['starttime'], endtime):
  File "/opt/elastalert/elastalert/elastalert.py", line 627, in run_query
    rule_inst.add_count_data(data)
  File "elastalert/ruletypes.py", line 81, in add_count_data
    raise NotImplementedError()
NotImplementedError
````

I use it like so within my rule configuration:    
````
use_count_query: true
doc_type: 'doc'
````

Any suggestions would be greatly appreciated.

Thanks,
Wes

**Comment by Qmando** [comment]
These are incompatible, though, the error message should be better.

"count" queries ask elasticsearch only for the number of matching documents, not their contents. The contents is needed to detect if something has "changed". Therefore, `use_count_query` is incompatible with the change rule. Just remove it, and it should work fine.

**Comment by weslambert** [comment]
Thanks for that -- for some reason, my brain didn't process that the count referred to the actual query itself looking for a number of hits (even though it is called `use_count_query` ) and was only considering the representation of the results.

I'll keep that in mind.

Thanks,
Wes
