### ISSUE TITLE
Reuse existing ES connection from Enhancement

### ISSUE THREAD

**Issue by admlko** [Yelp/elastalert#1886]
I have converted my python program to ElastAlert Enhancement module successfully.
It enriches every match with additional information from other events stored in ES by creating a new connection and querying the cluster.
I was thinking if there is a way to leverage already existing ES connection from the ElastAlert in the enhancement?

**Comment by Qmando** [comment]
Hi @admlko, unfortunately not. The connection object is basically just a bunch of configuration though, so it's not any less efficient to create a new Elasticsearch client instance. 

You probably are already, but if you aren't, you should use elastalert.util.elasticsearch_client, which should make it super simple to create a new client instance.
