### ISSUE TITLE
Cardinality count issue

### ISSUE THREAD

**Issue by Yv-o-rL** [Yelp/elastalert#1887]
Hi!

I'm trying to set up an alert for domains where unique IP addresses surpass a limit within 4 hours. Since there are several sites on a node, I need to group the result per domain. The main config is set up to run every 30 minutes and has a 60 minute buffer time. I intend to lower the "run_time" setting to every 10 minutes because some alerts have to pop up ASAP.
The configuration for the alert in question:

```
index: XXXXXX-%Y.%m.%d
name: XXXXXX
type: cardinality
cardinality_field: "ip_address"
max_cardinality: 10000
timeframe:
  hours: 4
filter:
- query_string:
   query: "XXXXXX"
query_key: "domain"
summary_table_fields: [node,domain]

alert:
- "slack"
alert_text_type: aggregation_summary_only
slack:
slack_webhook_url: "XXXXXX"
```

I thought this would result in a query every 30 minutes for the past 4 hours and send me the grouped results with the match count. However, I don't get all the matched items (compared to a Kibana request), and the count is only showing "1":

> Aggregation resulted in the following data for summary_table_fields ==> ['node', 'domain', 'count']:
> +-------+--------------------+-------+
> |  node   |         domain         | count |
> +====+============+====+
> | XXXXX | www.XXXXXXX.io |     1     |
> +-------+--------------------+-------+
> 
> Aggregation resulted in the following data for summary_table_fields ==> ['node', 'domain', 'count']:
> +-------+--------------------+-------+
> |  node   |         domain         | count |
> +====+============+====+
> | XXXXX | www.YYYYYYYY.io |     1     |
> +-------+--------------------+-------+

My intention would be to get the list of the domains where the unique count of the "ip_address" in the past 4 hours surpassed the maximum cardinality. The list should contain every affected domain and sent every hour. Reoccurring items don't cause any issue for me.

I really appreciate your help!
Thank you!
Yvorl

**Comment by Qmando** [comment]
Hi,

summary_table_fields is meant to be used with `aggregation`. Without aggregation, each alert will fire separately, as soon as it occurs. Setting aggregation will group all of the alerts together, and the table will contain more than one row. 

However, you mention "some alerts have to pop up ASAP", which will NOT happen if you set aggregation up. You do mention "sent every hour", so I'd probably recommend setting

If you were to add
```
aggregation:
  schedule: * * * 0 0
```

This effectively means "send all alerts that occurred within the last hour together, on the hour". If domain A hits 10,000 IPs, it's going to create a pending alert. And if domain B hits 10,000 IPs before the next hour, it will get added to the pending alert. At the next hour, both alerts will get sent together and you'll get a summary table with multiple lines.

Note that in this case, the count column will always be 0. This is because the timeframe on the rule is four hours, where the schedule is one hour. Therefore, only one alert per domain can occur during each aggregation period.

Another note: You use `node` in the table, however, unless it's got a 1:1 mapping with domain, it's going to be a random one among the 10,000 different IPs. You can have `query_key: [node, domain]` if you want to count the IP cardinality per unique (node, domain) combination rather than just per domain.

**Comment by Yv-o-rL** [comment]
Hi,

Thanks, I implemented your suggestions.
I see this in the _stderr.log_:

> INFO:elastalert:Adding alert for XXXXXX to aggregation(id: XXXXXX, aggregation_key: None), next alert at 2018-09-06 15:20:00+00:00

but I get the message every hour relative to when I restarted the process with Supervisord. I've set this:

```
aggregation:
  schedule: '20 * * * *'
```

because reading your [documentation ](https://elastalert.readthedocs.io/en/latest/ruletypes.html#aggregation) and [this page](http://www.nncron.ru/help/EN/working/cron-format.htm) this made sense.

I do get numbers though, not zeros as 'count'. So at this point I get a nice list with count, but it isn't sent at the time I've set and it seems it only scans the past hour.

Sidenote: Adding prefix had to include apostrophes, and it seems that it doesn't change the Slack webhook's behavior. I think it's because it's already formatted. So no problem here, but thanks anyway :)

Regarding "some alerts have to pop up ASAP", I'm sorry, I meant that I need EA to run more frequently than this specific rule's timeframe. However, I'm not sure what happens if the timeframe is shorter or longer than the 'run_every' setting. I'd think that EA runs the queries for the active rules and taking the timeframe in account. Let's say it runs every 30 minutes. A rule where the timeframe is set to 10 will only check the past 10 minutes, while another rule where the timeframe is set to 4 hours will always query the past 4 hours. Also, I can't really say how the 'buffer_time' setting changes the behavior of the timeframe. 

Regards,
Lauri

**Comment by Qmando** [comment]
Oops, I totally messed up the cron format... 

doing `schedule: '20 * * * *'` makes it still alert relative to when it starts, not at 20 past the hour?

You can have run_every be as quick as you want, it won't affect the behavior. If your timeframe is 4 hours, you can have it run every minute, and it will just maintain a 4 hour wide rolling window, adding new data to it as it comes, alerting as soon as the cardinality of the 4 hour window hits the threshold. The buffer_time causes elastalert to overlap queries, this is needed to make sure that no single event is missed, even if it was added 1 millisecond before an elastalert query occurs (in which case, it won't yet be returned in searches).

Regarding "it only scans the past hour", I'm not completely sure this is what you're referring to, but there is a slight quirk to cardinality rule. For each domain, it will wait until at least four hours have actually passed before it sends an alert, and that timer then resets. So with a timeframe of four hours, you can only get 1 alert per domain per four hours. There's unfortunately no way to change this behavior right now.

**Comment by Yv-o-rL** [comment]
Thanks, I'll keep this in mind. If I understand this correctly, I should have a higher buffer time for rules which query a longer period than the "main" buffer time setting?

Cron schedule: No, I get alerts every 46th minute.
By scanning the past hour, I was referring (at least tried to) the query time interval. I checked the numbers in Kibana, and I get the impression that it's not the cardinality for 4 hours, but one. Though I'm not sure what "count" supposed to show.
I did get today one alert each hour with the same domain. Which would be the optimal (rolling window), but I can change the numbers and scan a shorter period. However, first I'd like to have it working as intended :) 
I restarted the process a couple of minutes ago and got a list of 7 domains:

> node  - domain  - count
> ----------------------------
> NODE1 - DOMAIN1 - 25
> NODE1 - DOMAIN2 - 7766
> NODE1 - DOMAIN3 - 2206
> NODE2 - DOMAIN3 - 1
> NODE3 - DOMAIN3 - 1
> NODE4 - DOMAIN3 - 1
> NODE1 - DOMAIN4 - 1

I don't have a problem with the different nodes (you already pointed that out), but if it was a fresh query with a time period of 4 hours, I should've got 9 different domains (according to Kibana). Even if I don't count "DOMAIN1" (the reoccurring domain every hour) and one from the missing list which was alerted an hour ago, I still have missing domains. I realize that without seeing the dataset, it's hard to say what's going on. I tried tracing the queries but I don't know what happens in the elastalert indices, so I turned to you guys.

Thank you!

**Comment by Qmando** [comment]
You don't need a high buffer time. The default is probably fine. It only has to be larger than `run_every`. Whether it's 15 minutes or 30 mintues or 4 hours, it generally won't affect the outcome.

I'm very confused as to why you are getting things on the 46th minute.. That shouldn't be happening, unless you have a very large run_every setting, or the query is taking a really long time to process. When you get `next alert at 2018-09-06 15:20` message, the first time elastalert runs after that time period it should send it. There could be a bug here too.

Regarding why you get different results than Kibana: It could be because the time frames are not lining up as you expect. When you start elastalert, it will try to find the most recent query made for each rule and start from there, otherwise it starts from the present time. And then each four hour time frame only starts when the first value for some domain is hit, so some domains could alert until slightly later than what you might expect.

One interesting thing you could do if you want to try and debug the internals further:
```
--- a/elastalert/ruletypes.py
+++ b/elastalert/ruletypes.py
@@ -940,6 +940,7 @@ class CardinalityRule(RuleType):

     def garbage_collect(self, timestamp):
         """ Remove all occurrence data that is beyond the timeframe away """
+        print "Cardinality values at", timestamp, [key, len(values) for key, values in self.cardinality_cache.items()]
```

**Comment by Yv-o-rL** [comment]
Yep, you're right about the `run_every` setting (of course :D ), it was set to 30 and occured every 16th and 46th minute. I lowered it to 10 minutes with 20 minutes buffer time. So that's working as intended (though at least for me this wasn't clear from the documentation). 
I modified the `ruletypes.py` and added this to the supervisor configuration:

```
stdout_logfile=/var/log/elastalert_stdout.log
stdout_logfile_maxbytes=2MB
stdout_logfile_backups=5
```

After that I updated `supervisor` and restarted `elastalert`. However, the file is still empty.
I'm worried about this line in the `elastalert_stderr.log`
>INFO:elastalert:Ran XXXXXXXXX from 2018-09-11 15:08 UTC to 2018-09-11 15:28 UTC: XXXX query hits (XXX already seen), 0 matches, 0 alerts sent

If the timeframe is set to 4 hours, shouldn't it show that timeframe?

I had couple flatline rules and was wondering why those didn't alert. All of them (3) was set to a bit higher than the daily low (10 minute timeframes), but I started receiving alerts only when I changed the `run_every` to 10 minutes too.

**Comment by Qmando** [comment]
Each time elastalert "runs", it's making a single query for a rule. That query will be as wide as `buffer_time`. It keeps track an internal store of the latest four hours of data, so that it can alert when something hits the cardinality. You could set the `run_every` to 1 minute and you'd get 10x these messages, but the alerting behavior would be roughly the same, other than it would be even close to the schedule. Also, these queries can overlap, that's expected.

The flatline rule similarly waits until the `timeframe` has elapsed before it will alert. I'm not sure how run_every would really affect that, other than it taking slightly longer to happen.

**Comment by Yv-o-rL** [comment]
Thank you for being super helpful! I think I'm getting closer where my problem lies.
If the setup is like this:

`config.yaml`
```
...
run_every:
  minutes: 10

buffer_time:
  minutes: 15
...
```

`cardinality_test.yaml`

```
...
max_cardinality: 5000

timeframe:
  hours: 4

aggregation:
  schedule: '*/20 * * * *'
...```

Then ElastAlert will query the past 10 minutes every time and "make a note" how many unique IP addresses were, and it aggregates that number until 4 hours passed. Which means that I won't get unique values from the past 4 hours but an aggregated number of 10-minute windows. So one IP address could be counted 24 times (hta.
Same goes for the flatline rules. While EA was set to run every 30 minutes, it didn't alert me because I was under the impression that if the timeframe is 10 minutes, then I need to add a value which corresponds to that. However, it runs a query for a 30-minute window where the results were obviously higher (~3 times).

If I got this right. What are my options to run EA often enough to catch metrics which may need immediate action and having rules where the timeframe is 4 hours or a day?

**Comment by Qmando** [comment]
This is note *quite* accurate. It's actually, every 10 minutes elastalert will query the past 15 minutes, ignoring event it's already seen. It will maintain a 4 four wide sliding window with all events. After adding events each time, it checks the cardinality of the window, and if it's higher than 5000, it will create an alert.

Each time an alert is created, it schedules the alert to send at the next `*/20 * * * *` time. And when elastalert runs and the current time has now crossed that, all of those alerts get sent together.

I was mistaken earlier when I said that the 4 hours must completely elapse. That only applies to min_cardinality, not max, which makes sense.

**Comment by Yv-o-rL** [comment]
Hi!

I started to check what's in the EA index. I used the `rule_name` as a filter and the `@timestamp` field. However, while I definitely find some domains where the unique visits surpassed the current cardinality (every hour for 4 hours, of course, those can overlap, but still), those aren't showing up in the `elastalert_status` index at all. 
Any idea?

The EA rule:

```
index: XXXXXX-%Y.%m.%d
use_strftime_index: true
name: XXXXXXX
timestamp_field: "@timestamp"
timestamp_format: '%d/%b/%Y:%H:%M:%S %z'
type: cardinality
cardinality_field: "ip_address"
max_cardinality: 10000
timeframe:
  hours: 4
filter:
- query_string:
   query: "node.keyword:*-XXXXXX-* AND type:XXXXXX AND NOT domain:*XXXXXX.com"
query_key: "domain"
aggregation:
  schedule: '*/20 * * * *'
summary_table_fields: [node,domain]
alert:
- "slack"
alert_text_type: aggregation_summary_only
slack:
slack_webhook_url: "XXXXXXX"
```

The query I used to get the docs from the `elastalert_status` index:
```
curl -H "Content-Type: application/json" -XGET "http://localhost:9200/elastalert_status/elastalert/_search?pretty&size=10000" -d '{ 
  "query": { 
  "bool": {
      "must": [
        {
          "query_string": {
            "query": "rule_name:\"XXXXXXXX\""
          }
        },
        {
          "range": {
          "@timestamp": {
            "from": "2018-09-18T08:00:00.000000Z",
            "to": "2018-09-18T15:05:00.000000Z"
          }
        }
        }]}
 }
}'
```

Only 3 unique node matches were returned (after I parsed the result).


I was wondering what these fields are in the `elastalert_status` index:
```
...
          "aggregate_id" : "vlpXXXXXXXXlPDG",
          "@timestamp": "2018-09-18T11:44:12.584219Z", (outside the match_body)
          "match_time" : "2018-09-17T15:53:37Z"
	"match_body": {
...
            "num_hits": 2800,
            "num_matches": 10,
...
	}
...
```

Thank you!
Yvorl

**Comment by Qmando** [comment]
`aggregate_id` is used to track alert aggregations so that if you stop and start elastalert, it will still send them as expected. 

`@timestamp` in the first example is the time when elastalert first generated the alert.

`match_time` is the timestamp of the document that triggered the alert.

These may not line up because elastalert is querying over a large time period, for example, if you turned off elastalert overnight then ran it again.

`num_hits` is the number of documents returned by elasticsearch for that query

`num_matches` is how many times within those hits an alert was generated.

You can get multiple matches from a single run every because multiple domains went above the threshold or because actually each event that keeps the cardinality for the last 4 hours will trigger a match. However, with the default setting of `realert`, you'll only get the first match for a given domain from a single query.

**Comment by Yv-o-rL** [comment]
Thank you for the descriptions!

What I gathered from the `elastalert_status` index documents is:
- if there's no new document for the domain (during the last `run_every` timeframe), there won't be a ***new*** alert (that's kinda obvious and expected) even if the unique count in the 4-hour timeframe surpasses the cardinality.
- (couldn't verify this) if there's even one new document and the unique count in the 4-hour timeframe surpasses the cardinality, it'll trigger an alert, and the count will contain the number of the docs matched after the last alert.

However, I couldn't determine, when the "first" document will be added to the  `elastalert_status` index. Which - as I think - would trigger alerts later.
Today I was monitoring the cardinality in Kibana and exporting & parsing documents from the status index (because fields in *match_body* aren't indexed so I couldn't simply filter by domain or anything else) and tried to understand what's happening under the hood. The most concerning issue for me is when I see that something should be in an alert, but it isn't. After a couple of hours of cross-checking and asking the rubber duck, I received an alert which confused me the most.
So, I have the configuration as I attached above. ElastAlert alerts every 20 minutes (04/24/44).
On the chart below there are 6 sites. It shows unique IP addresses with one-hour buckets. The black horizontal line represents the cardinality limit, site "D" and "F" have continuous requests.
From 7:04 to 13:24 I received alert including only site "D" (every 20 minutes). The "count" was mostly under the limit, but in the 4-hour timeframe the unique count surpassed it (I checked the timeframe with the lowest unique number). After 13:44 I received an alert from both site "D" and "F" as expected. Site "F" surpassed the **4-hour limit** between 13:24 and 13:44. Those two sites were reported until 16:04.
However, at 16:24 I received an alert which included sites "A", "B", "D", "E", "F". As you see, sites "A", "B", "D" were only active between 8:00 and 16:00.
Following questions arose:
- Why didn't I get an alert as soon as the cardinality passed the limit in the first `run_every`?
- Why didn't I get an alert after 4 hours of continuously surpassing the cardinality?
- Why did I get only one alert for that 8 hour period?
- Why didn't I receive any alert for site "C" (there were about 6 time more unique entries than the limit)?

![image](https://user-images.githubusercontent.com/42407721/45766969-43b6a080-bc39-11e8-83f5-ef6cea2b6035.png)

**Comment by Yv-o-rL** [comment]
Yes, there was a syntax error. Also, I couldn't get the supervisor to log `stdout` (during runtime), so I run it separately. I also modified it a bit so the info will be logged to a file. For the first run I went with the original start, and end time, it created a file which was 1.3GB and endlessly spewing lines for the next alert:

> INFO:elastalert:Adding alert for...

So I interrupted it and set the time period to one hour. That resulted in a file about 100MB and ~25k lines of "INFO" messages on the screen. The file contains arrays with domains and a number. What does the cardinality timestamp represent? What should I look for to be able to tell what happens?

p.s.: I didn't find any of the domains which were alerted later or the one which also should've been there 2 days ago.

**Comment by Qmando** [comment]
You now get an endless spew of alerts over that same time period? 🤔 

The timestamps represent the current state of the alert at the time, IE
`Cardinality values at 12:35 [("SiteA", 100), ("SiteB", 500)]` means that for the previous 4 hours leading up to 12:35, there's 100 unique IPs for SiteA and 500 for SiteB. 

I guess I did put it in a place where it is a bit spammy. Sorry about that. This would be much more reasonable if you feel like debugging further:
```
diff --git a/elastalert/ruletypes.py b/elastalert/ruletypes.py
index fe54673..5a0ea32 100644
--- a/elastalert/ruletypes.py
+++ b/elastalert/ruletypes.py
@@ -932,14 +932,15 @@ class CardinalityRule(RuleType):
             # If there might be a match, run garbage collect first, as outdated terms are only removed in GC
             # Only run it if there might be a match so it doesn't impact performance
             if gc:
-                self.garbage_collect(lookup_es_key(event, self.ts_field))
+                self.garbage_collect(lookup_es_key(event, self.ts_field), False)
                 self.check_for_match(key, event, False)
             else:
                 self.first_event.pop(key, None)
                 self.add_match(event)

-    def garbage_collect(self, timestamp):
+    def garbage_collect(self, timestamp, log=True):
         """ Remove all occurrence data that is beyond the timeframe away """
+        if log:
+            print "Cardinality values at", timestamp, [(key, len(values)) for key, values in self.cardinality_cache.items()]
         for qk, terms in self.cardinality_cache.items():
```

**Comment by Yv-o-rL** [comment]
Sorry if I wasn't clear. I didn't receive a lot of alerts (in Slack), only the terminal window is flooded by 
> INFO:elastalert:Adding alert for XXXXXXXXXX (id: XXXXXXXXX, aggregation_key: None), next alert at ...

Thank you for the update, the output is a lot better now!
For now, I stopped the supervisor instance for now and only ran EA in verbose mode with the log file for the cardinality messages. After the first run in the morning where the time period was set to the past 4 hours, I received a nice alert which was surprising since the supervisor instance should've sent those too. After that, I played around a bit. Lastly (for today) I run the same 2-hour time period twice and the result wasn't 100% the same (I'm pretty sure that the data didn't change). I'll continue testing with more precise data and get back to you.

**Comment by Yv-o-rL** [comment]
Hi,

First of all, **huge** thank you for all the help you provided! I learned a lot about ElastAlert.
In the past two days or so, I was monitoring all activity (raw log, beats, logstash, ES, EA) and successfully unveiled the issue I had. As it mostly turns out - at least in my experience -, the issue was on the user's end 😞 . Moreover, the alert revealed a minor issue in the log ingesting process. Fortunately, it doesn't affect anything in production 😅 
Essentially, some logs were throttled and ingested at a later time. So when I checked Kibana, the data was visualized, but in reality, it may have been added to the index minutes before. That's why EA didn't detect those documents.

I see that the `elastalert_status` index gradually grows. Could you please point me to a solution where I can find out how to remove old entries? Or even better, how should I set up the index to be able to remove entries older than a week?
Regarding logging, is there a way to add timestamps to the entries in the stderr log?
Also, as I mentioned above, the
>"INFO:elastalert:Adding alert for XXXXXXX to aggregation(id: SW-XXXXXXXXX, aggregation_key: None), next alert at 2018-09-26 11:40:00+00:00"
>"INFO:elastalert:Adding alert for XXXXXXX to aggregation(id: SW-XXXXXXXXX, aggregation_key: None), next alert at 2018-09-26 11:40:00+00:00"
>...

entries can flood logs or the terminal. Is there a way to group those if all data (rule name,  ID and key, etc.) is the same?

Regards,
Yvorl

**Comment by Yv-o-rL** [comment]
Will ask those in separate threads 😃 
Thank you again for your help!
