### ISSUE TITLE
Elastalert plugin for ES 6.4

### ISSUE THREAD

**Issue by jaiswalsanjeev** [Yelp/elastalert#1888]
Can the Elastalert plugin be released for ES 6.4?

While attempting installation, the plugin is not yet available

./kibana-plugin install elastalert
Attempting to transfer from elastalert
Attempting to transfer from https://artifacts.elastic.co/downloads/kibana-plugins/elastalert/elastalert-6.4.0.zip
Plugin installation was unsuccessful due to error "No valid url specified."

**Comment by Qmando** [comment]
Please post this on the github page for the kibana plugin. It's not maintained by Yelp.
