### ISSUE TITLE
Error connecting to ElasticSearch: TransportError 502 - readonlyrest (ROR)

### ISSUE THREAD

**Issue by itles** [Yelp/elastalert#1890]
Hello,
after installing ROR, elastalert cannot connect to elasticsearch cluster.
Elastalert return me error: Error connecting to ElasticSearch: TransportError 502 .

Without ROR it works well.
I have set variables (es_username and es_password) in conf.yaml and in another configuration files.

With curl it works well.
curl -u user:pass -H "Content-Type:application/json" -XGET localhost:9200/alert/_search?pretty

Could you please help with it?

**Comment by sscarduzio** [comment]
@itles you should inspect ES logs, maybe you find some lines from ROR saying "FORBIDDEN", in that case, can you show those?

**Comment by itles** [comment]
Hello Simmone @sscarduzio. No error logs in ROR. Problem will be probably with proxy.
