### ISSUE TITLE
"More than num_events" or "more than or equal to num_events"?

### ISSUE THREAD

**Issue by scadgek** [Yelp/elastalert#1900]
I'm reading the documentation ([this page](https://elastalert.readthedocs.io/en/latest/running_elastalert.html)) and I stumbled upon the following statement:

> Alert when more than num_events occur within timeframe

Which in my understanding means that if I set it to `1`, it won't trigger if the event matches exactly once.  

But further there is an example with `num_events: 50` and it sends an email with the following text:

> ...
> At least 50 events occurred between 1-15 11:12 PST and 1-15 15:12 PST
> ...

Which means that exactly 50 events would trigger, so my initial assumption is wrong.

From what we see while we use ElastAlert in our project, the latter is correct. So `num_events` is rather a threshold to be described as `more than or equal to` than just `more than`. I guess it is worth to be noted in the documentation as well, for people like me to not be confused. What do you think?

**Comment by Qmando** [comment]
I'll clear up the documentation, it's `more than or equal to`.

https://github.com/Yelp/elastalert/blob/master/elastalert/ruletypes.py#L265

**Comment by Qmando** [comment]
https://github.com/Yelp/elastalert/commit/dd39f42ef40a37990e3913faebf53036ef8c86c7
