### ISSUE TITLE
elastalert_status hits: 0, matches: 0

### ISSUE THREAD

**Issue by JawadKM** [Yelp/elastalert#1905]
Hi,
I am trying to configure Elastalert to send email notifications, while using the Frequency type.
Problem is when I run my rule to test it returns with 0 Hits, below is the result of "elastalert-test-rule email_frequency.yaml"
```
[root@opendj example_rules]# elastalert-test-rule email_frequency.yaml
Successfully loaded Email frequency rule

INFO:elastalert:Note: In debug mode, alerts will be logged to console but NOT actually sent.
                To send them but remain verbose, use --verbose instead.
INFO:elastalert:Queried rule Email frequency rule from 2018-09-12 18:06 UTC to 2018-09-12 18:51 UTC: 0 / 0 hits
INFO:elastalert:Queried rule Email frequency rule from 2018-09-12 18:51 UTC to 2018-09-12 19:36 UTC: 0 / 0 hits
INFO:elastalert:Queried rule Email frequency rule from 2018-09-12 19:36 UTC to 2018-09-12 20:21 UTC: 0 / 0 hits
INFO:elastalert:Queried rule Email frequency rule from 2018-09-12 20:21 UTC to 2018-09-12 21:06 UTC: 0 / 0 hits
INFO:elastalert:Queried rule Email frequency rule from 2018-09-12 21:06 UTC to 2018-09-12 21:51 UTC: 0 / 0 hits
INFO:elastalert:Queried rule Email frequency rule from 2018-09-12 21:51 UTC to 2018-09-12 22:36 UTC: 0 / 0 hits
INFO:elastalert:Queried rule Email frequency rule from 2018-09-12 22:36 UTC to 2018-09-12 23:21 UTC: 0 / 0 hits
INFO:elastalert:Queried rule Email frequency rule from 2018-09-12 23:21 UTC to 2018-09-13 00:06 UTC: 0 / 0 hits
INFO:elastalert:Queried rule Email frequency rule from 2018-09-13 00:06 UTC to 2018-09-13 00:51 UTC: 0 / 0 hits
INFO:elastalert:Queried rule Email frequency rule from 2018-09-13 00:51 UTC to 2018-09-13 01:36 UTC: 0 / 0 hits
INFO:elastalert:Queried rule Email frequency rule from 2018-09-13 01:36 UTC to 2018-09-13 02:21 UTC: 0 / 0 hits
INFO:elastalert:Queried rule Email frequency rule from 2018-09-13 02:21 UTC to 2018-09-13 03:06 UTC: 0 / 0 hits
INFO:elastalert:Queried rule Email frequency rule from 2018-09-13 03:06 UTC to 2018-09-13 03:51 UTC: 0 / 0 hits
INFO:elastalert:Queried rule Email frequency rule from 2018-09-13 03:51 UTC to 2018-09-13 04:36 UTC: 0 / 0 hits
INFO:elastalert:Queried rule Email frequency rule from 2018-09-13 04:36 UTC to 2018-09-13 05:21 UTC: 0 / 0 hits
INFO:elastalert:Queried rule Email frequency rule from 2018-09-13 05:21 UTC to 2018-09-13 06:06 UTC: 0 / 0 hits
INFO:elastalert:Queried rule Email frequency rule from 2018-09-13 06:06 UTC to 2018-09-13 06:51 UTC: 0 / 0 hits
INFO:elastalert:Queried rule Email frequency rule from 2018-09-13 06:51 UTC to 2018-09-13 07:36 UTC: 0 / 0 hits
INFO:elastalert:Queried rule Email frequency rule from 2018-09-13 07:36 UTC to 2018-09-13 08:21 UTC: 0 / 0 hits
INFO:elastalert:Queried rule Email frequency rule from 2018-09-13 08:21 UTC to 2018-09-13 09:06 UTC: 0 / 0 hits
INFO:elastalert:Queried rule Email frequency rule from 2018-09-13 09:06 UTC to 2018-09-13 09:51 UTC: 0 / 0 hits
INFO:elastalert:Queried rule Email frequency rule from 2018-09-13 09:51 UTC to 2018-09-13 10:36 UTC: 0 / 0 hits
INFO:elastalert:Queried rule Email frequency rule from 2018-09-13 10:36 UTC to 2018-09-13 11:21 UTC: 0 / 0 hits
INFO:elastalert:Queried rule Email frequency rule from 2018-09-13 11:21 UTC to 2018-09-13 12:06 UTC: 0 / 0 hits
INFO:elastalert:Queried rule Email frequency rule from 2018-09-13 12:06 UTC to 2018-09-13 12:51 UTC: 0 / 0 hits
INFO:elastalert:Queried rule Email frequency rule from 2018-09-13 12:51 UTC to 2018-09-13 13:36 UTC: 0 / 0 hits
INFO:elastalert:Queried rule Email frequency rule from 2018-09-13 13:36 UTC to 2018-09-13 14:21 UTC: 0 / 0 hits
INFO:elastalert:Queried rule Email frequency rule from 2018-09-13 14:21 UTC to 2018-09-13 15:06 UTC: 0 / 0 hits
INFO:elastalert:Queried rule Email frequency rule from 2018-09-13 15:06 UTC to 2018-09-13 15:51 UTC: 0 / 0 hits
INFO:elastalert:Queried rule Email frequency rule from 2018-09-13 15:51 UTC to 2018-09-13 16:36 UTC: 0 / 0 hits
INFO:elastalert:Queried rule Email frequency rule from 2018-09-13 16:36 UTC to 2018-09-13 17:21 UTC: 0 / 0 hits
INFO:elastalert:Queried rule Email frequency rule from 2018-09-13 17:21 UTC to 2018-09-13 18:06 UTC: 0 / 0 hits

Would have written the following documents to writeback index (default is elastalert_status):

elastalert_status - {'hits': 0, 'matches': 0, '@timestamp': datetime.datetime(2018, 9, 13, 18, 6, 47, 823918, tzinfo=tzutc()), 'rule_name': 'Email frequency rule', 'starttime': datetime.datetime(2018, 9, 12, 18, 6, 47, 689173, tzinfo=tzutc()), 'endtime': datetime.datetime(2018, 9, 13, 18, 6, 47, 689173, tzinfo=tzutc()), 'time_taken': 0.12775182723999023}
```
**My email_frequency.yaml is a below**
```
# Alert when the rate of events exceeds a threshold

# (Optional)
# Elasticsearch host
es_host: 0.0.0.0

# (Optional)
# Elasticsearch port
es_port: 9200

# (OptionaL) Connect with SSL to Elasticsearch
#use_ssl: True

# (Optional) basic-auth username and password for Elasticsearch
#es_username: someusername
#es_password: somepassword

# (Required)
# Rule name, must be unique
name: Email frequency rule

# (Required)
# Type of alert.
# the frequency rule type alerts when num_events events occur with timeframe time
type: frequency

# (Required)
# Index to search, wildcard supported
index: syslog-ng-*

# (Required, frequency specific)
# Alert when this many documents matching the query occur within a timeframe
num_events: 1

# (Required, frequency specific)
# num_events must occur within this amount of time to trigger an alert
timeframe:
  hours: 1

# (Required)
# A list of Elasticsearch filters used for find events
# These filters are joined with AND and nested in a filtered query
# For more info: http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/query-dsl.html
filter:
- term:
    HOST: "interceptor"
- term:
    PRIORITY: "err"

# (Required)
# The alert is use when a match is found
alert:
- "email"

# (required, email specific)
# a list of email addresses to send alerts to
email:
- "j*******@********.com"
```

**Comment by JawadKM** [comment]
Your help in this regards will be highly appreciated, as I already have wasted a lot of time figuring this issue out.

**Comment by Qmando** [comment]
Try removing both term filters. Does that get any hits? If yes, add back one at a time. That should show you which filter is not matching.

Why don't you post the json of a document you expect to match, then it should be easy to see what the issue is.

**Comment by JawadKM** [comment]
Thanks for the prompt response. I have removed the filters and still same issue.
Below is the JSON of the log entry I am trying to read.

{
  "_index": "syslog-ng",
  "_type": "test",
  "_id": "f-dg1GUBMQHdiyUVHYPK",
  "_version": 1,
  "_score": null,
  "_source": {
    "_SDATA": {
      "meta": {
        "sequenceId": "347"
      }
    },
    "SOURCE": "s_network",
    "PROGRAM": "syslog-ng",
    "PRIORITY": "err",
    "PID": "9120",
    "MESSAGE": "Syslog connection failed; fd='17', server='AF_INET(192.*.*.*:514)', error='Connection timed out (110)', time_reopen='60'",
    "ISODATE": "2018-09-13T19:19:53+00:00",
    "HOST_FROM": "192.*.*.*",
    "HOST": "interceptor",
    "FACILITY": "syslog"
  },
  "fields": {
    "ISODATE": [
      "2018-09-13T19:19:53.000Z"
    ]
  },
  "highlight": {
    "HOST": [
      "@kibana-highlighted-field@interceptor@/kibana-highlighted-field@"
    ],
    "HOST.keyword": [
      "@kibana-highlighted-field@interceptor@/kibana-highlighted-field@"
    ]
  },
  "sort": [
    1536866393000
  ]
}

**Comment by JawadKM** [comment]
So I changed the Index to index: syslog-ng* it gave me the following error

[root@opendj example_rules]# elastalert-test-rule email_frequency.yaml
Successfully loaded Email frequency rule

WARNING:elasticsearch:GET http://0.0.0.0:9200/syslog-ng*/_search?ignore_unavailable=true&size=1 [status:400 request:0.011s]
Error running your filter:
RequestError(400, u'search_phase_execution_exception', {u'status': 400, u'error': {u'failed_shards': [{u'node': u'4_9_ijz-Ty6ZE4uyL6l3_g', u'index': u'syslog-ng', u'reason': {u'index_uuid': u'pddxhjibSz2L2oDl9TCRQA', u'index': u'syslog-ng', u'reason': u'No mapping found for [@timestamp] in order to sort on', u'type': u'query_shard_exception'}, u'shard': 0}], u'root_cause': [{u'index_uuid': u'pddxhjibSz2L2oDl9TCRQA', u'index': u'syslog-ng', u'reason': u'No mapping found for [@timestamp] in order to sort on', u'type': u'query_shard_exception'}], u'grouped': True, u'reason': u'all shards failed', u'phase': u'query', u'type': u'search_phase_execution_exception'}})
INFO:elastalert:Note: In debug mode, alerts will be logged to console but NOT actually sent.
                To send them but remain verbose, use --verbose instead.
WARNING:elasticsearch:GET http://0.0.0.0:9200/syslog-ng*/_search?_source_include=%40timestamp%2C%2A&ignore_unavailable=true&scroll=30s&size=10000 [status:400 request:0.010s]
ERROR:root:Error running query: RequestError(400, u'search_phase_execution_exception', u'No mapping found for [@timestamp] in order to sort on')

Would have written the following documents to writeback index (default is elastalert_status):

elastalert_error - {'message': "Error running query: RequestError(400, u'search_phase_execution_exception', u'No mapping found for [@timestamp] in order to sort on')", 'traceback': ['Traceback (most recent call last):', '  File "/usr/lib/python2.7/site-packages/elastalert-0.1.35-py2.7.egg/elastalert/elastalert.py", line 391, in get_hits', '    **extra_args', '  File "/usr/lib/python2.7/site-packages/elasticsearch-6.3.1-py2.7.egg/elasticsearch/client/utils.py", line 76, in _wrapped', '    return func(*args, params=params, **kwargs)', '  File "/usr/lib/python2.7/site-packages/elasticsearch-6.3.1-py2.7.egg/elasticsearch/client/__init__.py", line 660, in search', "    doc_type, '_search'), params=params, body=body)", '  File "/usr/lib/python2.7/site-packages/elasticsearch-6.3.1-py2.7.egg/elasticsearch/transport.py", line 318, in perform_request', '    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)', '  File "/usr/lib/python2.7/site-packages/elasticsearch-6.3.1-py2.7.egg/elasticsearch/connection/http_requests.py", line 90, in perform_request', '    self._raise_error(response.status_code, raw_data)', '  File "/usr/lib/python2.7/site-packages/elasticsearch-6.3.1-py2.7.egg/elasticsearch/connection/base.py", line 125, in _raise_error', '    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)', "RequestError: RequestError(400, u'search_phase_execution_exception', u'No mapping found for [@timestamp] in order to sort on')"], 'data': {'query': {'sort': [{'@timestamp': {'order': 'asc'}}], 'query': {'bool': {'filter': {'bool': {'must': [{'range': {'@timestamp': {'gt': '2018-09-12T20:25:27.368880Z', 'lte': '2018-09-12T21:10:27.368880Z'}}}]}}}}}, 'rule': 'Email frequency rule'}}

**Comment by Qmando** [comment]
From https://elastalert.readthedocs.io/en/latest/running_elastalert.html

```
All documents must have a timestamp field. ElastAlert will try to use @timestamp by default, but this can be changed with the timestamp_field option. 
```

**Comment by JawadKM** [comment]
Thank you so much for all your help, it is working now.
I added **timestamp_field: "ISODATE"** and it worked. I'll ask you for help if I get stuck.

**Comment by sm226202** [comment]
I am having similar issue. No errors and zero alerts and zero hits.
It is currently using timestamp field: "@timestamp"  but yet no error or 0 hits. I can see kibana there are about 40 hits .

**Comment by lastbulletbender** [comment]
@sm226202 You will get more responses if you open a new issue with more details (rule-file, config etc) or ask on https://gitter.im/Yelp/elastalert
