### ISSUE TITLE
IOError: [Errno 2] No such file or directory: 'config.yaml'

### ISSUE THREAD

**Issue by JawadKM** [Yelp/elastalert#1908]
Hi Again,
I am trying to invoke Elastalert for the first time after testing my rule and it gave me the following error.

[root@opendj rules]# python -m elastalert.elastalert --verbose --rule email_frequency.yaml
/usr/lib/python2.7/site-packages/requests-2.19.1-py2.7.egg/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.23) or chardet (2.2.1) doesn't match a supported version!
  RequestsDependencyWarning)
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/site-packages/elastalert-0.1.35-py2.7.egg/elastalert/elastalert.py", line 1925, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/lib/python2.7/site-packages/elastalert-0.1.35-py2.7.egg/elastalert/elastalert.py", line 1919, in main
    client = ElastAlerter(args)
  File "/usr/lib/python2.7/site-packages/elastalert-0.1.35-py2.7.egg/elastalert/elastalert.py", line 130, in __init__
    self.conf = load_rules(self.args)
  File "/usr/lib/python2.7/site-packages/elastalert-0.1.35-py2.7.egg/elastalert/config.py", line 438, in load_rules
    conf = yaml_loader(filename)
  File "build/bdist.linux-x86_64/egg/staticconf/loader.py", line 167, in yaml_loader
IOError: [Errno 2] No such file or directory: 'config.yaml'

**elastalert-test-rule Result**

Got 158 hits from the last 1 day

Available terms in first hit:
        HOST_FROM
        FACILITY
        PID
        PRIORITY
        SOURCE
        HOST
        PROGRAM
        ISODATE
        _SDATA.meta.sequenceId
        MESSAGE

INFO:elastalert:Note: In debug mode, alerts will be logged to console but NOT actually sent.
                To send them but remain verbose, use --verbose instead.
INFO:elastalert:Queried rule Email frequency rule from 2018-09-13 16:27 UTC to 2018-09-13 17:12 UTC: 11 / 11 hits
INFO:elastalert:Queried rule Email frequency rule from 2018-09-13 17:12 UTC to 2018-09-13 17:57 UTC: 14 / 14 hits
INFO:elastalert:Queried rule Email frequency rule from 2018-09-13 17:57 UTC to 2018-09-13 18:42 UTC: 15 / 15 hits
INFO:elastalert:Queried rule Email frequency rule from 2018-09-13 18:42 UTC to 2018-09-13 19:27 UTC: 14 / 14 hits
INFO:elastalert:Queried rule Email frequency rule from 2018-09-13 19:27 UTC to 2018-09-13 20:12 UTC: 14 / 14 hits
INFO:elastalert:Queried rule Email frequency rule from 2018-09-13 20:12 UTC to 2018-09-13 20:57 UTC: 15 / 15 hits
INFO:elastalert:Queried rule Email frequency rule from 2018-09-13 20:57 UTC to 2018-09-13 21:42 UTC: 4 / 4 hits
INFO:elastalert:Queried rule Email frequency rule from 2018-09-13 21:42 UTC to 2018-09-13 22:27 UTC: 0 / 0 hits
INFO:elastalert:Queried rule Email frequency rule from 2018-09-13 22:27 UTC to 2018-09-13 23:12 UTC: 13 / 13 hits
INFO:elastalert:Queried rule Email frequency rule from 2018-09-13 23:12 UTC to 2018-09-13 23:57 UTC: 0 / 0 hits
INFO:elastalert:Queried rule Email frequency rule from 2018-09-13 23:57 UTC to 2018-09-14 00:42 UTC: 0 / 0 hits
INFO:elastalert:Queried rule Email frequency rule from 2018-09-14 00:42 UTC to 2018-09-14 01:27 UTC: 0 / 0 hits
INFO:elastalert:Queried rule Email frequency rule from 2018-09-14 01:27 UTC to 2018-09-14 02:12 UTC: 0 / 0 hits
INFO:elastalert:Queried rule Email frequency rule from 2018-09-14 02:12 UTC to 2018-09-14 02:57 UTC: 0 / 0 hits
INFO:elastalert:Queried rule Email frequency rule from 2018-09-14 02:57 UTC to 2018-09-14 03:42 UTC: 0 / 0 hits
INFO:elastalert:Queried rule Email frequency rule from 2018-09-14 03:42 UTC to 2018-09-14 04:27 UTC: 0 / 0 hits
INFO:elastalert:Queried rule Email frequency rule from 2018-09-14 04:27 UTC to 2018-09-14 05:12 UTC: 0 / 0 hits
INFO:elastalert:Queried rule Email frequency rule from 2018-09-14 05:12 UTC to 2018-09-14 05:57 UTC: 0 / 0 hits
INFO:elastalert:Queried rule Email frequency rule from 2018-09-14 05:57 UTC to 2018-09-14 06:42 UTC: 0 / 0 hits
INFO:elastalert:Queried rule Email frequency rule from 2018-09-14 06:42 UTC to 2018-09-14 07:27 UTC: 0 / 0 hits
INFO:elastalert:Queried rule Email frequency rule from 2018-09-14 07:27 UTC to 2018-09-14 08:12 UTC: 0 / 0 hits
INFO:elastalert:Queried rule Email frequency rule from 2018-09-14 08:12 UTC to 2018-09-14 08:57 UTC: 0 / 0 hits
INFO:elastalert:Queried rule Email frequency rule from 2018-09-14 08:57 UTC to 2018-09-14 09:42 UTC: 0 / 0 hits
INFO:elastalert:Queried rule Email frequency rule from 2018-09-14 09:42 UTC to 2018-09-14 10:27 UTC: 0 / 0 hits
INFO:elastalert:Queried rule Email frequency rule from 2018-09-14 10:27 UTC to 2018-09-14 11:12 UTC: 0 / 0 hits
INFO:elastalert:Queried rule Email frequency rule from 2018-09-14 11:12 UTC to 2018-09-14 11:57 UTC: 0 / 0 hits
INFO:elastalert:Queried rule Email frequency rule from 2018-09-14 11:57 UTC to 2018-09-14 12:42 UTC: 0 / 0 hits
INFO:elastalert:Queried rule Email frequency rule from 2018-09-14 12:42 UTC to 2018-09-14 13:27 UTC: 1 / 1 hits
INFO:elastalert:Queried rule Email frequency rule from 2018-09-14 13:27 UTC to 2018-09-14 14:12 UTC: 14 / 14 hits
INFO:elastalert:Queried rule Email frequency rule from 2018-09-14 14:12 UTC to 2018-09-14 14:57 UTC: 15 / 15 hits
INFO:elastalert:Queried rule Email frequency rule from 2018-09-14 14:57 UTC to 2018-09-14 15:42 UTC: 14 / 14 hits
INFO:elastalert:Queried rule Email frequency rule from 2018-09-14 15:42 UTC to 2018-09-14 16:27 UTC: 14 / 14 hits
INFO:elastalert:Alert for Email frequency rule at 2018-09-13T16:40:43Z:
INFO:elastalert:Email frequency rule

At least 1 events occurred between 2018-09-13 15:40 UTC and 2018-09-13 16:40 UTC

FACILITY: syslog
HOST: interceptor
HOST_FROM: 192.*.*.*
ISODATE: 2018-09-13T16:40:43Z
MESSAGE: Syslog connection failed; fd='8', server='AF_INET(192.*.*.*:514)', error='Connection timed out (110)', time_reopen='60'
PID: 9120
PRIORITY: err
PROGRAM: syslog-ng
SOURCE: s_network
_SDATA: {
    "meta": {
        "sequenceId": "248"
    }
}
_id: ZufO02UBMQHdiyUVYyFA
_index: syslog-ng
_type: test
num_hits: 158
num_matches: 158

INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule
INFO:elastalert:Ignoring match for silenced rule Email frequency rule

Would have written the following documents to writeback index (default is elastalert_status):

silence - {'rule_name': 'Email frequency rule', '@timestamp': datetime.datetime(2018, 9, 14, 16, 27, 38, 539660, tzinfo=tzutc()), 'exponent': 0, 'until': datetime.datetime(2018, 9, 14, 16, 28, 38, 539648, tzinfo=tzutc())}

elastalert_status - {'hits': 158, 'matches': 158, '@timestamp': datetime.datetime(2018, 9, 14, 16, 27, 38, 562973, tzinfo=tzutc()), 'rule_name': 'Email frequency rule', 'starttime': datetime.datetime(2018, 9, 13, 16, 27, 37, 996625, tzinfo=tzutc()), 'endtime': datetime.datetime(2018, 9, 14, 16, 27, 37, 996625, tzinfo=tzutc()), 'time_taken': 0.5489590167999268}

**Files in my Elastalert folder**

[root@opendj elastalert]# ll
total 88
drwxr-xr-x. 4 root root    43 Sep 12 13:56 build
-rw-r--r--. 1 root root  9381 Sep 12 13:50 changelog.md
-rw-r--r--. 1 root root  2011 Sep 13 17:03 config.yaml.example
drwxr-xr-x. 2 root root    41 Sep 12 13:56 dist
-rw-r--r--. 1 root root   261 Sep 12 13:50 docker-compose.yml
-rw-r--r--. 1 root root   275 Sep 12 13:50 Dockerfile-test
drwxr-xr-x. 3 root root    36 Sep 12 13:50 docs
drwxr-xr-x. 2 root root  4096 Sep 14 14:35 elastalert
drwxr-xr-x. 2 root root   134 Sep 12 13:56 elastalert.egg-info
drwxr-xr-x. 2 root root  4096 Sep 14 14:17 example_rules
-rw-r--r--. 1 root root 11359 Sep 12 13:50 LICENSE
-rw-r--r--. 1 root root   480 Sep 12 13:50 Makefile
-rw-r--r--. 1 root root 15957 Sep 12 13:50 README.md
-rw-r--r--. 1 root root    87 Sep 12 13:50 requirements-dev.txt
-rw-r--r--. 1 root root   320 Sep 12 13:50 requirements.txt
drwxr-xr-x. 2 root root    34 Sep 14 14:17 rules
-rw-r--r--. 1 root root   100 Sep 12 13:50 setup.cfg
-rw-r--r--. 1 root root  1566 Sep 12 13:50 setup.py
-rw-r--r--. 1 root root   780 Sep 12 13:50 supervisord.conf.example
drwxr-xr-x. 2 root root   191 Sep 12 13:50 tests
-rw-r--r--. 1 root root   599 Sep 12 13:50 tox.ini

**Comment by JawadKM** [comment]
Will be looking forward to your response.

**Comment by Qmando** [comment]
I suppose you figured this out on your own, but you need to add ``--config file`` to point elastalert at the global config file.
