### ISSUE TITLE
Entering breaklines in alert_text

### ISSUE THREAD

**Issue by lucasalvarezlacasa** [Yelp/elastalert#1915]
Hello everybody!. I'd love to know how to add breaklines in alert_text field. This is what I have:

```
alert_text:
 "We found {0} logs classified as '{1}' in the last {2} minutes for this client. 
  Message: {3}"
alert_text_args:
- num_events
- classification
- timeframe
- message
```

I tried by using the '|' character at the beginning, but it does not work, the alarm it's simply not send if I include it.

Any help would be strongly appreciated.

**Comment by Qmando** [comment]
`|` is what you are looking for. 

```
alert_text: |
    We found ......
    Message: {3}
```

**Comment by lucasalvarezlacasa** [comment]
I don't know why you closed the thread. This answer does not work, I'm sending the alarm to a Teams Web Hook, but the break line does not appear even if I do what you said.

Any ideas?

**Comment by Qmando** [comment]
Try `<br>`

**Comment by lucasalvarezlacasa** [comment]
Thank you man!. It works.
