### ISSUE TITLE
ImportError: failed to find libmagic.  Check your installation

### ISSUE THREAD

**Issue by lucas-rudd** [Yelp/elastalert#1927]
I believe this may be an issue with the `magic` package used by `thehive4py/api.py`

After installing elastalert v 0.1.3.6 I get the following stacktrace when I try to run an elastalert test with a folder of rules

```
Traceback (most recent call last):
  File "/home/elastalert/.local/bin/elastalert", line 11, in <module>
    load_entry_point('elastalert==0.1.36', 'console_scripts', 'elastalert')()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2691, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2322, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2328, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/elastalert/.local/lib/python2.7/site-packages/elastalert/elastalert.py", line 21, in <module>
    from alerts import DebugAlerter
  File "/home/elastalert/.local/lib/python2.7/site-packages/elastalert/alerts.py", line 31, in <module>
    from thehive4py.api import TheHiveApi
  File "/home/elastalert/.local/lib/python2.7/site-packages/thehive4py/api.py", line 7, in <module>
    import magic
  File "/home/elastalert/.local/lib/python2.7/site-packages/magic.py", line 181, in <module>
    raise ImportError('failed to find libmagic.  Check your installation')
ImportError: failed to find libmagic.  Check your installation
RMTMACSIERRA01:infrastructure-cm lucas.rudd$ docker run --rm -it -e ES_HOST=search-pss-pf-prod-es-51-gcm4nbuhxjuo6telgbszkp3i7u.us-east-1.es.amazonaws.com -e AWS_PROFILE=asurion-soluto-nonprod.dev -v ~/.aws:/home/elastalert/.aws  -v ~/Desktop/rules/:/home/elastalert/rules --entrypoint elastalert asurionpss/elastalert:test --verbose --es_debug
Traceback (most recent call last):
  File "/home/elastalert/.local/bin/elastalert", line 11, in <module>
    load_entry_point('elastalert==0.1.36', 'console_scripts', 'elastalert')()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2691, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2322, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2328, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/elastalert/.local/lib/python2.7/site-packages/elastalert/elastalert.py", line 21, in <module>
    from alerts import DebugAlerter
  File "/home/elastalert/.local/lib/python2.7/site-packages/elastalert/alerts.py", line 31, in <module>
    from thehive4py.api import TheHiveApi
  File "/home/elastalert/.local/lib/python2.7/site-packages/thehive4py/api.py", line 7, in <module>
    import magic
  File "/home/elastalert/.local/lib/python2.7/site-packages/magic.py", line 181, in <module>
    raise ImportError('failed to find libmagic.  Check your installation')
ImportError: failed to find libmagic.  Check your installation
```

After manually installing `libmagic` the issue persists.

Has anyone else experienced this issue?

**Comment by synhershko** [comment]
This worked for me:

pip uninstall python-magic
pip install python-magic-bin==0.4.14

**Comment by lsoumille** [comment]
@synhershko Your solution doesn't work for me because python-magic requirement is >=0.4.15. Here is the error message:

> pkg_resources.DistributionNotFound: The 'python-magic>=0.4.15' distribution was not found and is required by elastalert

**Comment by primeroz** [comment]
I just installed libmagic and it fixed that error. I am running an alpine container

**Comment by eliasbrange** [comment]
+1. Our elastalert suddenly started failing in our CI due to libmagic not being installed. Might want to add it to the docs that it is required. Even better, don't try to import it unless a `Hive` rule is configured.

**Comment by wuxinwei** [comment]
+1. I got the same problem when I was run elastalert at alpine container

**Comment by eliasbrange** [comment]
> @primeroz , Can you tell me that how do you solve this problem, just install libmagic when build docker image?

We've just added `apk add libmagic`.

**Comment by primeroz** [comment]
@wuxinwei as @eliasbrange mentioned just apk add libmagic

**Comment by Shenmiu** [comment]
> This worked for me:
> 
> pip uninstall python-magic
> pip install python-magic-bin==0.4.14

**Comment by skatakar** [comment]
Observed the same issue while running elastalert
1)D:\elastalert>elastalert-test-rule "D:\elastalert\example_rules\example_frequenc
y.yaml"
Traceback (most recent call last):
  File "D:\Python27\Scripts\elastalert-test-rule-script.py", line 11, in <module
>
    load_entry_point('elastalert==0.1.36', 'console_scripts', 'elastalert-test-r
ule')()
  File "D:\Python27\Lib\site-packages\pkg_resources\__init__.py", line 480, in l
oad_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "D:\Python27\Lib\site-packages\pkg_resources\__init__.py", line 2693, in
load_entry_point
    return ep.load()
  File "D:\Python27\Lib\site-packages\pkg_resources\__init__.py", line 2324, in
load
    return self.resolve()
  File "D:\Python27\Lib\site-packages\pkg_resources\__init__.py", line 2330, in
resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "D:\Python27\Lib\site-packages\elastalert\test_rule.py", line 20, in <mod
ule>
    import elastalert.config
  File "D:\Python27\Lib\site-packages\elastalert\config.py", line 9, in <module>

    import alerts
  File "D:\Python27\Lib\site-packages\elastalert\alerts.py", line 31, in <module
>
    from thehive4py.api import TheHiveApi
  File "D:\Python27\Lib\site-packages\thehive4py\api.py", line 7, in <module>
    import magic
  File "D:\Python27\Lib\site-packages\magic.py", line 181, in <module>
    raise ImportError('failed to find libmagic.  Check your installation')
ImportError: failed to find libmagic.  Check your installation

D:\elastalert> 




C:\Users\u3xlbes>elastalert --start NOW --verbose
Traceback (most recent call last):
  File "D:\Python27\Scripts\elastalert-script.py", line 11, in <module>
    load_entry_point('elastalert==0.1.36', 'console_scripts', 'elastalert')()
  File "D:\Python27\Lib\site-packages\pkg_resources\__init__.py", line 480, in l
oad_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "D:\Python27\Lib\site-packages\pkg_resources\__init__.py", line 2693, in
load_entry_point
    return ep.load()
  File "D:\Python27\Lib\site-packages\pkg_resources\__init__.py", line 2324, in
load
    return self.resolve()
  File "D:\Python27\Lib\site-packages\pkg_resources\__init__.py", line 2330, in
resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "D:\Python27\Lib\site-packages\elastalert\elastalert.py", line 21, in <mo
dule>
    from alerts import DebugAlerter
  File "D:\Python27\Lib\site-packages\elastalert\alerts.py", line 31, in <module
>
    from thehive4py.api import TheHiveApi
  File "D:\Python27\Lib\site-packages\thehive4py\api.py", line 7, in <module>
    import magic
  File "D:\Python27\Lib\site-packages\magic.py", line 181, in <module>
    raise ImportError('failed to find libmagic.  Check your installation')
ImportError: failed to find libmagic.  Check your installation

C:\Users\u3xlbes>

we are using python 2.7.15 . any workaround for this issue?

**Comment by eliasbrange** [comment]
> Do we have any workaround or solution for this issue?

Check out https://github.com/pidydx/libmagicwin64 for installing libmagic on windows.

**Comment by skatakar** [comment]
> > Do we have any workaround or solution for this issue?
> 
> Check out https://github.com/pidydx/libmagicwin64 for installing libmagic on windows.

I have downloaded all 4 files which are mentioned in the above link and placed under C:\Windows\System32.. But when I try to import magic or import liblogic, its giving same error.

>>> import magic
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Python27\Lib\site-packages\magic.py", line 181, in <module>
    raise ImportError('failed to find libmagic.  Check your installation')
ImportError: failed to find libmagic.  Check your installation
>>> import libmagic
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named libmagic
>>>

Do we need to run/configure  any thing after download those 4 files?

**Comment by MickaelHUMPHREYS** [comment]
Hi,

I had the same problem.
I solved it by adding this requirement : python-magic
pip install python-magic==0.4.15

**Comment by Ogagnon** [comment]
> This worked for me:
> 
> pip uninstall python-magic
> pip install python-magic-bin==0.4.14

I love you.

**Comment by efinal** [comment]
> > This worked for me:
> > pip uninstall python-magic
> > pip install python-magic-bin==0.4.14

it works thank you

**Comment by orcorsetti** [comment]
> This worked for me:
> 
> pip uninstall python-magic
> pip install python-magic-bin==0.4.14

This has worked for me, **thanks!!!!**

**Comment by andresjbotello** [comment]
> This worked for me:
> 
> pip uninstall python-magic
> pip install python-magic-bin==0.4.14

This has worked for me, **thanks!!!**

**Comment by yustiks** [comment]
I have the same issue, I tried to remove magic by this command:
`pip uninstall python-magic`
and then reinstall, but it didn't work. 
What I did in the end: I cloned the github code: https://github.com/ahupp/python-magic
into the local folder to the directory where the actual project is, and then renamed the folder to 'magic'. After that it worked.

**Comment by lobinator** [comment]
> > This worked for me:
> > pip uninstall python-magic
> > pip install python-magic-bin==0.4.14

Worked for me too.  Note that I uninstalled libmagic in addition to python-magic.

**Comment by roykingtree** [comment]
neither solution worked for me

**Comment by Lebostein** [comment]
What is this for a crap? I get this error on Windows and Mac OS.

**Comment by saginadir** [comment]
Solved it by running

```
brew install libmagic
```

**Comment by richardbalwane** [comment]
Use the method by @synhershko 
i.e, 1. pip uninstall python-magic
      2. pip install python-magic-bin
Except, don't include the  python-magic-bin version!

**Comment by vvvlad** [comment]
> Solved it by running
> 
> ```
> brew install libmagic
> ```

In my case this is what helped (MacOS obviously...)

**Comment by Bhairab123** [comment]
In my case, I had to install pip install python-magic-bin only. If I uninstall then I get following error:-
"pkg_resources.DistributionNotFound: The 'python-magic>=0.4.15' distribution was not found and is required by elastalert"

**Comment by shasan-marsdd** [comment]
> This worked for me:
> 
> pip uninstall python-magic
> pip install python-magic-bin==0.4.14

this issue happens on any python software running on mac.  I don't fully understand why python-magic doesn't fix this or if this issue shouldn't be fixed because it's a mac only issue.  It isn't an issue on any containers containing linux.

**Comment by kushan-gunasekera** [comment]
### Installation
The current stable version of python-magic is available on PyPI and can be installed by running `pip install python-magic`.

Other sources:

PyPI: http://pypi.python.org/pypi/python-magic/
GitHub: https://github.com/ahupp/python-magic
This module is a simple wrapper around the libmagic C library, and that must be installed as well:

### Debian/Ubuntu
$ `sudo apt-get install libmagic1`

### Windows
You'll need DLLs for libmagic. @julian-r has uploaded a version of this project that includes binaries to PyPI: https://pypi.python.org/pypi/python-magic-bin/0.4.14

Other sources of the libraries in the past have been File for Windows . You will need to copy the file `magic` out of `[binary-zip]\share\misc`, and pass its location to `Magic(magic_file=...)`.

If you are using a 64-bit build of python, you'll need 64-bit libmagic binaries which can be found here: https://github.com/pidydx/libmagicwin64. Newer version can be found here: https://github.com/nscaife/file-windows.

### OSX
When using Homebrew: `brew install libmagic`
When using macports: `port install file`

**Comment by Qmando** [comment]
thehive4py is gone now

**Comment by battlesysadmin** [comment]
We had this error on a popular Jupyter Notebook image, scipy-notebook. The fix ended up being to install libmagic with the Anaconda package manager:

conda install libmagic

Tracking down this error was a pain in the neck, so I hope this helps someone.

**Comment by Athanasioschourlias** [comment]
> This worked for me:
> 
> pip uninstall python-magic
> pip install python-magic-bin==0.4.14

this worked for me too!

**Comment by jonatasaguiar** [comment]
> This worked for me:
> 
> pip uninstall python-magic
> pip install python-magic-bin==0.4.14

This workaround was perfect.

**Comment by gema-sanz** [comment]
> This worked for me:
> 
> pip uninstall python-magic
> pip install python-magic-bin==0.4.14

This worked for me too

**Comment by jakubhavej** [comment]
In my case (M1 MacBook), it was all about telling the system where to find the library files. So after obvious `brew install libmagic` (on M1s, `homebrew` installs `libmagic` to `/opt/homebrew/Cellar/libmagic`), it was necessary to create a symbolic link from the library files to the place where the system expects `libmagic` to be located, which is `/usr/local/lib`.

Therefore, this worked for me:

`sudo ln -s /opt/homebrew/Cellar/libmagic/5.41/lib/libmagic.dylib /usr/local/lib/libmagic.dylib`

FYI: my version of `python-magic` is `0.4.18` (and I wasn't willing to downgrade as suggested above)

**Comment by lastmaj** [comment]
another possible fix : 
https://stackoverflow.com/questions/59661022/django-versatileimagefield-issues-no-matching-distribution-found-for-python-ma

**Comment by kaiyikang** [comment]
My laptop is MacBook Pro M1, and I succeed with the following process:
1.  `brew install libmagic`
2.  `pip install python-magic` (since pip install python-magic-bin not working)

**Comment by Fuadeiza** [comment]
> 2\. pip install python-magic

When you did this, did you test (`import magic`) to see if it worked.
I just did this now and it wasn't working for me.

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/magic/__init__.py", line 209, in <module>
    libmagic = loader.load_lib()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/magic/loader.py", line 49, in load_lib
    raise ImportError('failed to find libmagic.  Check your installation')
ImportError: failed to find libmagic.  Check your installation`

**Comment by Fuadeiza** [comment]
On my Macbook with M1 chip. This worked for me.

- `brew install libmagic`
- `pip install python-magic-bin==0.4.14`

**Comment by devdolapo** [comment]
> pip uninstall python-magic
> pip install python-magic-bin==0.4.14

Worked for me.

**Comment by pgcd** [comment]
> When I run `pip uninstall python-magic` and then `pip install python-magic-bin==0.4.14` I get the error message: `ERROR: Could not find a version that satisfies the requirement python-magic-bin==0.4.14 (from versions: none) ERROR: No matching distribution found for python-magic-bin==0.4.14`. Has anyone else seen this error?

Happened to me, solved using python-magic-debian-bin==0.4.25

**Comment by rzsamrio** [comment]
> I have the same issue (Linux mint), I tried to remove magic by this command: `pip uninstall python-magic` and then reinstall, but it didn't work. What I did in the end: I cloned the github code: https://github.com/ahupp/python-magic into the local folder to the directory where the actual project is, and then renamed the folder to 'magic'. After that it worked.

thank You! I've been on this for hours!!

**Comment by javadnikbakht** [comment]
I'm on MacOS m1 and I fix this issue by installing `libmagic` using Homebrew:
```sh
brew install libmagic
```

**Comment by javadnikbakht** [comment]
I'm on MacOS m1 and I fix this issue via installing `libmagic` using Homebrew:
```sh
brew install libmagic
```

**Comment by ShuxunoO** [comment]
> This worked for me:
> 
> pip uninstall python-magic pip install python-magic-bin==0.4.14

it really works!

**Comment by ZhengPeng7** [comment]
> > This worked for me:
> > pip uninstall python-magic
> > pip install python-magic-bin==0.4.14

This works for my windows 11.

**Comment by gelodefaultbrain** [comment]
> On my Macbook with M1 chip. This worked for me.
> 
> * `brew install libmagic`
> * `pip install python-magic-bin==0.4.14`


I tried this by only doing `brew install libmagic` and having the `python-magic` already works

Thanks!!

**Comment by ArmanChand** [comment]
> brew install libmagic

this code works like magic . Easy and quick fix

**Comment by GreysonHYH** [comment]
> When I run `pip uninstall python-magic` and then `pip install python-magic-bin==0.4.14` I get the error message: `ERROR: Could not find a version that satisfies the requirement python-magic-bin==0.4.14 (from versions: none) ERROR: No matching distribution found for python-magic-bin==0.4.14`. Has anyone else seen this error?

same,bro

**Comment by rtviii** [comment]
> In my case (M1 MacBook), it was all about telling the system where to find the library files. So after obvious `brew install libmagic` (on M1s, `homebrew` installs `libmagic` to `/opt/homebrew/Cellar/libmagic`), it was necessary to create a symbolic link from the library files to the place where the system expects `libmagic` to be located, which is `/usr/local/lib`.
> 
> Therefore, this worked for me:
> 
> `sudo ln -s /opt/homebrew/Cellar/libmagic/5.41/lib/libmagic.dylib /usr/local/lib/libmagic.dylib`
> 
> FYI: my version of `python-magic` is `0.4.18` (and I wasn't willing to downgrade as suggested above)

savior

**Comment by spam0115** [comment]
None of these solutions are working for me in windows.  Tried installing libmagic, tried 1. pip uninstall python-magic
2. pip install python-magic-bin, tried the windows libmagic dll prebuilts.  No change to my error message "
libmagic is unavailable but assists in filetype detection on file-like objects.Please consider installing libmagic for better results."

**Comment by Viswahs** [comment]
This worked for me:

pip uninstall python-magic
pip install python-magic-bin==0.4.14

**Comment by ktaborowski** [comment]
```
pip install python-magic-bin==0.4.14
ERROR: Could not find a version that satisfies the requirement python-magic-bin==0.4.14 (from versions: none)
ERROR: No matching distribution found for python-magic-bin==0.4.14
```

Is not for Linux, the package is only for Widnows and MacOS https://pypi.org/project/python-magic-bin/0.4.14/#files

For me it works (22.04 Ubuntu):
```
pip uninstall python-magic
apt install libmagic1
pip install python-magic
```

**Comment by danruggi** [comment]
```
pip uninstall python-magic
apt install libmagic1
pip install python-magic
```

Worked for me too.

**Comment by Jun711** [comment]
"As of eyeD3 0.9 libmagic is no longer required."
as per this comment: https://github.com/nicfit/eyeD3/issues/344#issuecomment-586556313

**Comment by Vishnu-Dhanabalan** [comment]
> In my case (M1 MacBook), it was all about telling the system where to find the library files. So after obvious `brew install libmagic` (on M1s, `homebrew` installs `libmagic` to `/opt/homebrew/Cellar/libmagic`), it was necessary to create a symbolic link from the library files to the place where the system expects `libmagic` to be located, which is `/usr/local/lib`.
> 
> Therefore, this worked for me:
> 
> `sudo ln -s /opt/homebrew/Cellar/libmagic/5.41/lib/libmagic.dylib /usr/local/lib/libmagic.dylib`
> 
> FYI: my version of `python-magic` is `0.4.18` (and I wasn't willing to downgrade as suggested above)

This worked for me (M2 pro). Just make sure you use the correct version inside the `/opt/homebrew/Cellar/libmagic/`.

**Comment by akshayvkt** [comment]
I was using an online IDE environment (Kaggle) and this was what worked for me as well:

```
!pip uninstall python-magic
!apt install libmagic1 -y
!pip install python-magic
```

**Comment by k1tano** [comment]
> ```
> pip install python-magic-bin==0.4.14
> ERROR: Could not find a version that satisfies the requirement python-magic-bin==0.4.14 (from versions: none)
> ERROR: No matching distribution found for python-magic-bin==0.4.14
> ```
> 
> Is not for Linux, the package is only for Widnows and MacOS https://pypi.org/project/python-magic-bin/0.4.14/#files
> 
> For me it works (22.04 Ubuntu):
> 
> ```
> pip uninstall python-magic
> apt install libmagic1
> pip install python-magic
> ```

work for ubuntu 18 too

**Comment by egsoftjam** [comment]
Hello everyone, after having a lot of issues with it, the solution that worked for me was to use the following commands (use python_magic_bin without version):
python-magic==0.4.27
python_magic_bin

It downloads python-magic-bin==0.4.14 but if I mention the version, it doesn't work. Strange behavior.

**Comment by tomtastic** [comment]
**MacOS** (maybe others too) 
```shell
$ pip install pylibmagic
$ pip install python-magic
```
Then ensure you `import pylibmagic` before you `import magic`

**Comment by franko172000** [comment]
> **MacOS** (maybe others too)
> 
> ```shell
> $ pip install pylibmagic
> $ pip install python-magic
> ```
> 
> Then ensure you `import pylibmagic` before you `import magic`

Thank you! it worked

**Comment by AIchemizt** [comment]
Follow this article for Mac users:

https://nixloop.com/fix/fixing-libmagic-installation-issues-on-apple-silicon-macs-for-python/

**Comment by puneetkaursidhu** [comment]
This worked for me:

pip uninstall python-magic
pip install python-magic

I'm on Apple M2 Max.

**Comment by denivic** [comment]
Not specifying the version for `python-magic-bin` worked for me (Windows):
```
pip uninstall python-magic
pip install python-magic-bin
```

**Comment by mburaksayici** [comment]
MAC M1/M2 People, 
This should work, and please note this solution because when you restart terminal, python related things in Mac somehow restarts, you probably faced that

https://stackoverflow.com/a/79042514/6806531
```

brew install libmagic

pip uninstall python-magic
pip install python-magic

# comma separated list for --find-links
export PIP_FIND_LINKS=https://github.com/ddelange/python-magic/releases/expanded_assets/0.4.28.post7
pip install --force-reinstall python-magic

```

Also within the codebase, use that:

`
    mime = magic.Magic(mime=True, magic_file = "/usr/local/Cellar/libmagic/5.45/share/misc/magic.mgc") # For local test on mac : mime = magic.Magic(mime=True, magic_file = "/usr/local/Cellar/libmagic/5.45/share/misc/magic.mgc")
    file_type = mime.from_buffer(file_bytes)

`

You can findyour magic.mgc file by

`brew list libmagic `
it's in share/misc/magic.mgc
