### ISSUE TITLE
Arithmetical operations on results

### ISSUE THREAD

**Issue by Yv-o-rL** [Yelp/elastalert#1943]
Hi,

I'd need to divide the result of a metric aggregation (summed bytes) because it's unreadable. For example:

```
      node                 |     bytes_sum
YY-NODE1                   | 48421372187.0
YY-NODE2                   | 1.61728428746e+11
XX-NODE1                   | 36966951579.0 
XX-NODE2                   | 47387413388.0
...
```
Is there any way to achieve that? Also, is it possible to receive an ordered list (e.g., order by `bytes_sum` desc).

Thank you,
Yvorl

**Comment by Yv-o-rL** [comment]
@Qmando
Sorry to bother you again, but is there any way I can perform some arithmetical operations on the output numbers? It's really hard to read values like that :(
Thanks!

**Comment by Qmando** [comment]
In alert_text you could use something like `{:0.2f}`. If that's in a summary table, you can't use python string formatters, you'd need an enhancement to round them.

**Comment by Yv-o-rL** [comment]
I see. thank you!

**Comment by Yv-o-rL** [comment]
I'm sorry to reopen this @Qmando, but my very limited python knowledge don't let me achieve my goal.

While I could use `{:0.2f}` in the configuration file it didn't help to format or convert bytes to kb,mb,gb ...

Due to my poor understanding on how Python works I had a hard time to add the basic enhancement since for me the ElastAlert directory is "/etc/elastalert" where the configuration, my rules and all other stuff is. However, until I didn't copy the folder to "/usr/local/lib/python2.7/dist-packages/elastalert-0.1.33-py2.7.egg/" I got error messages.
Now, I have the enhancement there too, I added the "match_enhancements" option to my rule, but I can't get the "formatted" value.

My EA rule:

> name: Test enhancement
> type: metric_aggregation
> index: mylog-*
> metric_agg_key: bytes
> metric_agg_type: sum
> doc_type: doc
> max_threshold: 1000000000
> use_run_every_query_size: True
> match_enhancements:
> - "elastalert_modules.my_enhancements.MyEnhancement"

The enhancement file contains this:

> from elastalert.enhancements import BaseEnhancement
> import math
> class MyEnhancement(BaseEnhancement):
> 
>     # The enhancement is run against every match
>     # The match is passed to the process function where it can be modified in any way
>     # ElastAlert will do this for each enhancement linked to a rule
>     def process(self, match):
>         if 'bytes' in match:
>             size_bytes = match['bytes']
>             size_str = ("B", "KB", "MB", "GB", "TB", "PB", "EB", "ZB", "YB")
>             i = int(math.floor(math.log(size_bytes, 1000)))
>             p = math.pow(1000, i)
>             s = round(size_bytes / p, 2)
>             match['bytes_formatted'] = "%s %s" % (s, size_str[i])

No matter how I tried to get the nice result I saw with an online Python code executer, I failed :(
I got nothing, <MISSING VALUE>, a  bit of a headache and lost couple hours. 

Thank you in advance!

**Comment by Yv-o-rL** [comment]
Had to use a field which is generated by ElastAlert : "bytes_sum"

**Comment by MakoWish** [comment]
I know this is now closed, but the above enhancement has been helpful for me, and I did run into an issue with it. Just wanted to share the issue and the resolution in case it is helpful for others. 

I like the clever use of math.pow to look into the string array for "B", "KB", etc., but if the value is "0", the enhancement will throw a math domain error, and ElastAlert will disable the rule. To fix this, I added a simple check for a value of 0 and proceed accordingly. Here is the complete python script we are using for this enhancement:

```
from elastalert.enhancements import BaseEnhancement
import math

class ConvertFS(BaseEnhancement):
    def process(self, match):
        size_str = ("B", "KB", "MB", "GB", "TB", "PB", "EB", "ZB", "YB")

        num = match['system']['filesystem']['total']
        i = int(math.floor(math.log(num, 1024)))
        p = math.pow(1024, i)
        s = round(num / p, 2)
        match['system']['filesystem']['total'] = "%s %s" % (s, size_str[i])

        num = match['system']['filesystem']['used']['bytes']
        i = int(math.floor(math.log(num, 1024)))
        p = math.pow(1024, i)
        s = round(num / p, 2)
        match['system']['filesystem']['used']['bytes'] = "%s %s" % (s, size_str[i])

        # If there are zero bytes free, we cannot find a power, so this script was throwing an
        # error, and the rule gets disabled. Throwing in an if/else to catch zero values.
        num = match['system']['filesystem']['free']
        if num == 0:
            match['system']['filesystem']['free'] = "0 B"
        else:
            i = int(math.floor(math.log(num, 1024)))
            p = math.pow(1024, i)
            s = round(num / p, 2)
            match['system']['filesystem']['free'] = "%s %s" % (s, size_str[i])

        num = match['system']['filesystem']['used']['pct']*100
        match['system']['filesystem']['used']['pct'] = "%.1f" % num
```
