### ISSUE TITLE
Rule Type Any on a dense index causes memory overflow

### ISSUE THREAD

**Issue by joeyJsonar** [Yelp/elastalert#1964]
We have a simple *any* rule type that queries every hour. The index it queries contains about 8 million documents per hour. So every hour, this rule queries from the last time it ran... `scrolling` through 8 million documents. This easily caused an out of memory error. 

We have replicated the memory footprint every time the rule runs and it always fills up our RAM (32GB). I've watch top/htop, until it starts becoming choppy.

Why is this operation so unnecessarily heavy, when it's only checking for new documents.

**Comment by Qmando** [comment]
You probably shouldn't be using `type: any` with an index where you get that many hits. Do you actually want to send 8 million alerts? 

I would agree that it's not very efficient in terms of memory usage, but in these situations you should be using things like `use_count_query` or `use_terms_query` if possible. Another "mitigation" might be to set a low value for `old_query_limit`, and set a really small `buffer_time`. This would prevent it from querying back over large time periods. You'd still get an absolutely massive number of alerts though.

There's not currently any good mechanism to limit the memory used for total documents returned. This is probably a good feature to add, but in the mean time, you'll want to rethink your rule.

**Comment by joeyJsonar** [comment]
Thanks for the answer. I suppose it is the wrong type.
