### ISSUE TITLE
Alert Management system

### ISSUE THREAD

**Issue by tehmoon** [Yelp/elastalert#1965]
Hi!

Thank you for making elastalert, it is the missing piece that I've been looking for in my monitoring system.

As it does not do alert management, like repeating sending for x minutes the same one, acknowledging, like nagios would do. I was wondering what people use for that.
I've been looking for insights, some people use icinga, other sensu, some alerta.io, but a lot of them include a lot of feature and I just need the simple alert management as everything will come from elastalert.

Alerta.io seems OK though, I will try it.

Thank you!

**Comment by mayuresh82** [comment]
@tehmoon  check out https//github.com/mayuresh82/alert_manager which is built exactly for the purpose of alert management.
