### ISSUE TITLE
Failed validation against Draft V4 JSON schema

### ISSUE THREAD

**Issue by alankis** [Yelp/elastalert#1969]
Hi all, 

First of all, I am using version 0.1.18. I have following rule, just an example: 

```
{
	"name": "Application process missing",
	"type": "flatline",
	"index": "metricbeat-*",
	"filter": [
		{
			"query": {
				"regexp": {
					"query": "system.process.cmdline: .*java.*org\\.apache\\.catalina\\.startup\\.Bootstrap.*"
				}
			}
		}
	],
	"threshold": 1,
	"timeframe": "60s",
	"doc_type": "metricsets",
	"use_count_query": true,
	"query_key": "beat.hostname",
	"alert": [
		"command"
	],
	"new_style_string_format": true,
	
}
```

However, at the point in converting the rules in YAML format to JSON rule, validation fails at the following point: 

```
Value "flatline" is not defined in enum.
Schema path:
http://json-schema.org/draft-04/schema#/definitions/simpleTypes/enum
```
Schema used can be found on following [URL](http://json-schema.org/draft-04/schema). 

Is this intentional?

**Comment by Qmando** [comment]
Hm, I'm confused by this. You linked the schema for json-schema, ie, meta-schema, not elastalert's schema. Why are you converting YAML into JSON in the first place.

There's at least two issues with your rule
1. timeframe should be formatted as
```
timeframe:
  seconds: 60
```

2. You can't use `use_count_query` and `query_key` at the same time. You probably want `use_terms_query` instead.

**Comment by alankis** [comment]
Hi Qmando. You are correct. I actually believed that I deleted the issue because I figured out what the root cause of the issue was and it was exactly as you have described. Closing.
