### ISSUE TITLE
To big timeFrame for alerts

### ISSUE THREAD

**Issue by sebash1992** [Yelp/elastalert#1971]
Hi all, i am having an issue. I stopped my elastalert service all the weekend. Today when i start it again the alarms start query from the Saturday to now, but i only want to ignore the past. the only thing that i want is to parse my 15min timeframe (i wrote in my alarm)

name: account-login
type: frequency
index: accounts-*

num_events: 5
timeframe:
  minutes: 1
realert:
  minutes: 10

query_key: ["username"]

filter:
- query:
    query_string:
      query: "event_identifier:555

**Comment by Qmando** [comment]
You want `old_query_limit`. 

https://elastalert.readthedocs.io/en/latest/elastalert.html?highlight=old_query_limit

Set it to 15 minutes
