### ISSUE TITLE
ElastAlerts Alerting when it should not

### ISSUE THREAD

**Issue by parker-meek** [Yelp/elastalert#1973]
I'm running a frequency alert with a 24 hour rule. However I am getting alerts where the num_hits is 1965 and it is saying at least 6690 events occured in the time frame.the time frame does show 24 hours though. This also does not happen for all of my rules.

**Comment by Qmando** [comment]
num_hits represents a single query, not the full time frame. ElastAlert stores a sliding window of events internally, and will alert when it contains more than `num_events`.
