### ISSUE TITLE
timeout for rules' Elasticsearch queries

### ISSUE THREAD

**Issue by abhishekjiitr** [Yelp/elastalert#1979]
A rule can have large query _timeframe_ and _frequency_(run every) and if this runs on a large dataset, the query will take a long time to execute and it can severely impact the cluster and may also bring it down. A timeout field can be added in rules and subsequently passed to ES queries as a [Request Body Search](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-body.html#_parameters_4) parameter

**Comment by Qmando** [comment]
You can set this in your global config file: For example, `es_conn_timeout: 30s`
