### ISSUE TITLE
How to access match data with alert_text_args? 

### ISSUE THREAD

**Issue by alankis** [Yelp/elastalert#1980]
Is it possible to access the match data with 'metric_aggregation' rule types? 

For example, I have the following rule defined in the rules directory: 

```
name: CPU usage over 90%
type: metric_aggregation
index: metricbeat-*


metric_agg_key: system.cpu.idle.pct
metric_agg_type: avg
doc_type:
min_threshold: 10
query_key: beat.hostname

alert:
  - "slack"
new_style_string_format: true

slack:
slack_webhook_url: "https://hooks.slack.com/services/{redacted}/{redacted}"

alert_text: "Something happened with match: {0} at {1} at hostname: {2}"
alert_text_type: alert_text_only
alert_text_args: [ "{match[field_values][beat][hostname]}", "@timestamp", "beat.hostname"  ]
```

According to the [documentation](https://elastalert.readthedocs.io/en/latest/ruletypes.html?highlight=alert_text_type), these fields should be accessible.

**Comment by alankis** [comment]
Or at least, how can I access the data in the alert body? How can I see what fields are available? If the 'alert_text..' is removed, I am getting the 'system.cpu.idle.pc' value. Follow up to that, I can reference this value in 'alert_text_args'. 

Additionally, what is match object and how can it be accessed?

**Comment by Qmando** [comment]
The match object contains different information depending on what the type of the alert is. For metric aggregations, you only get that metric, plus the timestamp and the query_key value. If you weren't metric_aggregation, it may contain other fields.

To see what's available, I'd probably recommend just removing `alert_text_type: alert_text_only` and triggering another alert. At the bottom of the alert there should be a bunch of key value pairs, that's everything that's in the match object. In some cases, it may not be obvious what the field is called.

**Comment by alankis** [comment]
@Qmando Thanks Quentin. That sheds some light. Let say that I am testing the rules, and as part of the output, I am getting the "Available terms in the first hit" list. These are all terms/key-value pairs that I can use as let us call it parameters that I can fetch and pass them to some arbitrary command or use as text_args and pass them to the Slack alert?

**Comment by Qmando** [comment]
Those are slightly different. In that case, it's showing you ALL of the fields that exist, not necessarily what is available for a given alert type. What I would recommend is running elastalert with `--debug` after removing `alert_text_type` then when it triggers an alert, it will have all of the fields at the bottom.
