### ISSUE TITLE
`count-only` command line flag intest_rule.py only loads rule and does not run it

### ISSUE THREAD

**Issue by abhishekjiitr** [Yelp/elastalert#1983]
According to [docmentation](https://elastalert.readthedocs.io/en/latest/ruletypes.html?highlight=--count-only#testing-your-rule):

```--count-only: Only find the number of matching documents and list available fields. ElastAlert will not be run and documents will not be downloaded```

But it only loads the rule and does not find the match in the documents or lists available fields

**Comment by Qmando** [comment]
It will only display them if there is at least 1 match. If it can't find anything, then it doesn't display any fields.

Example with matching documents:
```
$ elastalert-test-rule --count-only elastalert_rules/test.yaml
Successfully loaded test rule 1

Got 8766 hits from the last 1 day

Available terms in first hit:
	username
	status
	type
	@timestamp
	host
	entryPoint
	path
	message
	@version
	ipAddress
```

Though, you definitely raise a good point here, which is that if there are no hits, it doesn't display "Got 0 hits" but rather just prints nothing. I'll fix that

**Comment by Qmando** [comment]
https://github.com/Yelp/elastalert/commit/08b42684103a6749897876161067f36044c14cc2
