### ISSUE TITLE
Installation problem with setuptools on Debian Jessie

### ISSUE THREAD

**Issue by b-u-g-s** [Yelp/elastalert#199]
Hi,

I am trying to install elastalert but have failed on the second command from your guide :o/

After cloning from git, I ran the following command:
python setup.py install

It seems to go fine for a while and then stops with an error:
Installed /usr/local/lib/python2.7/dist-packages/python_dateutil-2.4.2-py2.7.egg
Searching for mock
Reading https://pypi.python.org/simple/mock/
Best match: mock 1.3.0
Downloading https://pypi.python.org/packages/source/m/mock/mock-1.3.0.tar.gz#md5=73ee8a4afb3ff4da1b4afa287f39fdeb
Processing mock-1.3.0.tar.gz
Writing /tmp/easy_install-Gw39qg/mock-1.3.0/setup.cfg
Running mock-1.3.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-Gw39qg/mock-1.3.0/egg-dist-tmp-FlFfJa
mock requires setuptools>=17.1. Aborting installation
error: Setup script exited with 1

The error seems to be with setuptools being ... to old?
Any ideas how I could fix this?

Thanks.
B.

**Comment by iamrudra** [comment]
I'd use [this](https://pypi.python.org/pypi/setuptools) to fix (update/reinstall) my setuptools and then retry the second step.

**Comment by b-u-g-s** [comment]
Thanks Lamrudra, it worked :)
Now my only problem is that I failed to create a valid test rule to look at some Suricata Alerts, but that's not a bug... more like user stupidity ;)
Will close the issue.

**Comment by iamrudra** [comment]
Happy to help! :)

**Comment by b-u-g-s** [comment]
That would be great iamrudra! Thanks for the offer.
I am running SELKS V2.0. It has an ELK stack and is powered by Suricata (an IDS) 
The logs are normalised by logstash
What I would like to do is to use elastalert to send me an email everytime a specific alert is loged.

On my system, Kibana shows the following information for the alert (event details panel), in JSON format:
------------------------------ START FILE
{
  "_index": "logstash-2015.07.28",
  "_type": "SELKS",
  "_id": "AU7WXqDd7E82xVVb4MQC",
  "_score": null,
  "_source": {
    "timestamp": "2015-07-28T21:33:21.021380+0100",
    "flow_id": 140653608273328,
    "in_iface": "eth1",
    "event_type": "alert",
    "src_ip": "192.168.5.4",
    "dest_ip": "192.168.5.1",
    "proto": "ICMP",
    "icmp_type": 3,
    "icmp_code": 3,
    "alert": {
      "action": "allowed",
      "gid": 1,
      "signature_id": 10000001,
      "rev": 1,
      "signature": "ICMP Test",
      "category": "Potential Corporate Privacy Violation",
      "severity": 1
    },
    "payload": "(I have removed it as not relevant)",
    "payload_printable": "(I have removed it as not relevant)",
    "stream": 0,
    "packet": "(I have removed it as not relevant)",
    "@version": "1",
    "@timestamp": "2015-07-28T20:33:21.021Z",
    "type": "SELKS",
    "host": "selks-host",
    "path": "/var/log/suricata/eve.json",
    "geoip": {}
  },
  "sort": [
    "test"
  ]
}
------------------------------ END FILE

So I thought I would look for the term: 
 "signature_id": 10000001,

Which is the alert ID I am interested in for my test.

Here is how I modified my example_new_term.yaml (but just guessing what should change, so I am not surprised it doesn't work!)
I wanted to get an alert by looking once a day (day: 1) for any new sign of the alert.
Once I have it working, I would have liked to change the check frequency to one every minute (would I use minute: 1 ?)
Or.... ideally... get an email/notification AS SOON AS the alert is logged! but that might not be possible with elastalert or too CPU/resource intensive I guess...

Anyway, here is my elastalert test rule:

------------------------------ START FILE
es_host: localhost
es_port: 9200
use_ssl: True

name: Example rule
type: new_term
index: logstash-*

query_string:
 - "signature_id: "10000001"

fields:
 - "signature_id"

terms_window_size:
  days: 1

filter:
- term:
    _type: "SELKS"

alert:
- "email"

email:
- "myemail@hotmail.com"
------------------------------ END FILE

If I run
elastalert-test-rule example_rules/example_new_term.yaml 

I can the following error:
Traceback (most recent call last):
  File "/usr/local/bin/elastalert-test-rule", line 9, in <module>
    load_entry_point('elastalert==0.0.54', 'console_scripts', 'elastalert-test-rule')()
  File "/usr/local/lib/python2.7/dist-packages/elastalert-0.0.54-py2.7.egg/elastalert/test_rule.py", line 289, in main
    test_instance.run_rule_test()
  File "/usr/local/lib/python2.7/dist-packages/elastalert-0.0.54-py2.7.egg/elastalert/test_rule.py", line 271, in run_rule_test
    rule_yaml = yaml.load(fh)
  File "/usr/lib/python2.7/dist-packages/yaml/__init__.py", line 71, in load
    return loader.get_single_data()
  File "/usr/lib/python2.7/dist-packages/yaml/constructor.py", line 37, in get_single_data
    node = self.get_single_node()
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 82, in compose_node
    node = self.compose_sequence_node(anchor)
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 110, in compose_sequence_node
    while not self.check_event(SequenceEndEvent):
  File "/usr/lib/python2.7/dist-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/lib/python2.7/dist-packages/yaml/parser.py", line 393, in parse_block_sequence_entry
    "expected <block end>, but found %r" % token.id, token.start_mark)
yaml.parser.ParserError: while parsing a block collection
  in "example_rules/example_new_term.yaml", line 35, column 2
expected <block end>, but found '<scalar>'
  in "example_rules/example_new_term.yaml", line 35, column 20

**Comment by Qmando** [comment]
Your YAML is malformed. I'm guessing this is close to what you want:
```
es_host: localhost
es_port: 9200
use_ssl: True
name: Example rule
type: any
index: logstash-*
filter:
  - term:
      _type: "SELKS"
  - term:
      signature_id: "10000001"
alert:
  - email
email:
  - "myemail@hotmail.com"
```
Type is set to any, because you want to alert on a single instance of this log type. New term is for alerting on new values of a field, which doesn't make sense if you are filtering for only the value 100000001.

To query every minute, set
```
run_every:
  minutes: 1
```
in config.yaml. You could even set it to ``seconds: 10`` or something if you like.

To have it query the entire day when it starts, you can set
```
buffer_time:
  days: 1
```
in config.yaml to make it apply to all rules or in the rule.yaml to make it apply to only that rule.

**Comment by b-u-g-s** [comment]
Thanks a lot Qmando!
It did work! :)
When I run the test I am getting the following results.
Does that mean I would get an email everytime a new alert is found in the logs with the content after 
"Would have written the following documents to elastalert_status:" right at the end?


Successfully loaded Example rule

Got 126 hits from the last 1 day

Available terms in first hit:
	icmp_code
	payload_printable
	type
	event_type
	stream
	proto
	timestamp
	@timestamp
	in_iface
	alert.category
	alert.severity
	alert.rev
	alert.gid
	alert.signature
	alert.action
	alert.signature_id
	src_ip
	host
	packet
	flow_id
	path
	icmp_type
	@version
	payload
	dest_ip

INFO:root:Queried rule Example rule from 7-28 21:10 BST to 7-28 21:55 BST: 3 hits
INFO:root:Queried rule Example rule from 7-28 21:55 BST to 7-28 22:40 BST: 0 hits
[I removed lot of similar lines]
INFO:root:Queried rule Example rule from 7-29 19:40 BST to 7-29 20:25 BST: 0 hits
INFO:root:Queried rule Example rule from 7-29 20:25 BST to 7-29 21:10 BST: 3 hits
INFO:root:Alert for Example rule at 2015-07-28T20:33:21.021Z:
INFO:root:Example rule

@timestamp: 2015-07-28T20:33:21.021Z

INFO:root:Ignoring match for silenced rule Example rule
[I removed lot of similar lines]
INFO:root:Ignoring match for silenced rule Example rule
INFO:root:Ignoring match for silenced rule Example rule

Would have written the following documents to elastalert_status:

silence - {'rule_name': 'Example rule', '@timestamp': datetime.datetime(2015, 7, 29, 20, 10, 40, 582344, tzinfo=tzutc()), 'exponent': 0, 'until': datetime.datetime(2015, 7, 29, 20, 11, 40, 582338, tzinfo=tzutc())}

elastalert_status - {'hits': 126, 'matches': 126, '@timestamp': datetime.datetime(2015, 7, 29, 20, 10, 40, 586971, tzinfo=tzutc()), 'rule_name': 'Example rule', 'starttime': datetime.datetime(2015, 7, 28, 20, 10, 39, 910198, tzinfo=tzutc()), 'endtime': datetime.datetime(2015, 7, 29, 20, 10, 39, 910198, tzinfo=tzutc()), 'time_taken': 0.675001859664917}

**Comment by b-u-g-s** [comment]
By the way, I understand this is just a test, and for the email to be sent I need to continue with the install guide!

**Comment by Qmando** [comment]
A few things to note here:

By default, the option ``realert`` is set to one minute. This means that ElastAlert will send at most 1 alert per rule per minute, hence the "Ignoring match for silence rule" lines. You can set it to ``minutes: 0`` to get every single alert.

Without ``include: ["*"]``, the alert only has the @timestamp in it. You can include all fields with "*", or individual ones.

You can send real alerts with elastalert-test-rule by adding --alert.

``elastalert_status`` is how ElastAlert knows what it has already queried. It writes the start and end times, and when ElastAlert starts again, it will query Elasticsearch and grab the most recent status document for each rule and start querying at the previous endtime.

**Comment by iamrudra** [comment]
I have had similar question @b-u-g-s and I'd highly recommend you to go through the [optional settings for the alerts](http://elastalert.readthedocs.org/en/latest/ruletypes.html#optional-settings) part in the documentation.

**Comment by b-u-g-s** [comment]
Qmando, this is exactly what I was after! thank you so much!

Iamrudra: a useful link, thanks! although without Qmando's help I am not sure I would have known exactly what to do :) But I will use this going forward
