### ISSUE TITLE
How to modify elastalert Server port ??

### ISSUE THREAD

**Issue by WalterSyue** [Yelp/elastalert#1990]
When I excute  "python elastalert/elastalert.py --verbose" command , have "INFO:elastalert:Found no values for ip_address"
at server is no open 3030 port, so my kibana web UI  have error log "connect ECONNREFUSED 192.168.1.111:3030"

elastalert server config:
rules_folder: example_rules
run_every:
  minutes: 1
buffer_time:
  minutes: 15
es_host: 192.168.1.111
es_port: 9200
writeback_index: elastalert_status
alert_time_limit:
  days: 2
![1](https://user-images.githubusercontent.com/44830671/48119456-4aad7700-e2aa-11e8-8d3b-3b585c291563.jpg)

How can i do ??

kibana version 6.3.2
ElastAlert Kibana Plugin version 1.0.1

**Comment by abhishekjiitr** [comment]
The official [Elastalert](github.com/Yelp/elastalert) doesn't run any server process to which the Kibana plugin can connect. So, there is no config to modify any port, because it simply doesn't run a server. However, the folks at [Bitsensor](https://github.com/bitsensor) have developed their own fork of Elastalert that runs a server (running on port 3030) that exposes REST API's for manipulating rules and alerts and for that they have developed a Kibana Plugin which you are using. So, to use the Kibana plugin you should use their fork. 

Relevant Links:
[Bitsensor Elastalert](https://github.com/bitsensor/elastalert)
[Kibana Plugin for Bitsensor Elastalert](https://github.com/bitsensor/elastalert)

**Comment by sachin250191** [comment]
> The official [Elastalert](https://github.com/Yelp/elastalert) doesn't run any server process to which the Kibana plugin can connect. So, there is no config to modify any port, because it simply doesn't run a server. However, the folks at [Bitsensor](https://github.com/bitsensor) have developed their own fork of Elastalert that runs a server (running on port 3030) that exposes REST API's for manipulating rules and alerts and for that they have developed a Kibana Plugin which you are using. So, to use the Kibana plugin you should use their fork.
> 
> Relevant Links:
> [Bitsensor Elastalert](https://github.com/bitsensor/elastalert)
> [Kibana Plugin for Bitsensor Elastalert](https://github.com/bitsensor/elastalert)

Any body got any solutin of this. i am also facing the same issue. 

![image](https://user-images.githubusercontent.com/28863843/51735135-8affe280-20ac-11e9-9872-570eb80a07a7.png)

**Comment by thommor** [comment]
You quoted the solution.

If you want to use the ElastAlert Kibana plugin you have to run [Bitsensor Elastalert](https://github.com/bitsensor/elastalert) not this Elastalert

**Comment by sachin250191** [comment]
hi thommor,

how should i use Bitsensor Elastalert.... I am new to this.... can you please share the commands and all.

thanks inadvance

**Comment by thommor** [comment]
I haven't used it myself but looking at the [README](https://github.com/bitsensor/elastalert/blob/master/README.md) it seems easy enough to just run it as a Docker container.

**Comment by sachin250191** [comment]
ok , Let me try. Any way thank you for thommor.

**Comment by thommor** [comment]
No problem, If you get stuck I'd suggest opening an issue on their repo and hopefully they will be able to help you out

**Comment by sachin250191** [comment]
Actually i can't use docker in the production. i want without docker implementation.

**Comment by thommor** [comment]
In that case you will have to setup npm.

For the most part you will just need to copy the commands the [Dockerfile](https://github.com/bitsensor/elastalert/blob/master/Dockerfile) runs.

For example:

1. Install Yelp elastalert + requirements
2. Install node + npm
3. Clone BitSenser elastalert
4. Do npm install
5. Copy/Create config files in the correct locations
6. Run npm start
