### ISSUE TITLE
Basic frequency alert issue

### ISSUE THREAD

**Issue by kriesesc** [Yelp/elastalert#1993]
Trying to setup my first frequency alert, using a very basic setup that doesn't find any matches even though the event is found in Kibana. I created the alert using so-elastalert-create, in order to ensure I had the syntax correct, looking for event_id 1102 (security log cleared). After creating the alert, and then generating the event by clearing my event log and ensuring the event exists in Kibana, I run so-elastalert-test and get:
.
.
.
INFO:elastalert:Queried rule log-cleared from 2018-11-08 17:24 UTC to 2018-11-08 17:25 UTC: 0 / 0 hits
INFO:elastalert:Queried rule log-cleared from 2018-11-08 17:25 UTC to 2018-11-08 17:26 UTC: 0 / 0 hits
INFO:elastalert:Queried rule log-cleared from 2018-11-08 17:26 UTC to 2018-11-08 17:27 UTC: 0 / 0 hits
INFO:elastalert:Queried rule log-cleared from 2018-11-08 17:27 UTC to 2018-11-08 17:28 UTC: 0 / 0 hits
INFO:elastalert:Queried rule log-cleared from 2018-11-08 17:28 UTC to 2018-11-08 17:29 UTC: 0 / 0 hits

Would have written the following documents to writeback index (default is elastalert_status):

elastalert_status - {'hits': 0, 'matches': 0, '@timestamp': datetime.datetime(2018, 11, 8, 17, 29, 49, 9582, tzinfo=tzutc()), 'rule_name': 'log-cleared', 'starttime': datetime.datetime(2018, 11, 7, 17, 29, 46, 263164, tzinfo=tzutc()), 'endtime': datetime.datetime(2018, 11, 8, 17, 29, 46, 263164, tzinfo=tzutc()), 'time_taken': 2.741888999938965}

Complete!
.
.
.
Here is my yaml file:
```
# Elasticsearch Host
es_host: elasticsearch
es_port: 9200

# (Required)
# Rule name, must be unique
name: log-cleared


# (Required)
# Index to search, wildcard supported
index: "logstash-beats-*"


# (Required)
# Type of alert.
# the frequency rule type alerts when num_events events occur with timeframe time
type: frequency

# (Required, frequency specific)
# Alert when this many documents matching the query occur within a timeframe
num_events: 1

# (Required, frequency specific)
# num_events must occur within this amount of time to trigger an alert
timeframe:
  hours: 1

#(Required)
# A list of Elasticsearch filters used for find events
# These filters are joined with AND and nested in a filtered query
# For more info: http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/query-dsl.html
filter:

- term:
    event_id: "1102"

# (Required)
# The alert is use when a match is found
alert:
- debug
```

And here you can see that the event in Kibana  in the last day (note I've been working on this for the last 3 days, and been generating this event over this time, so the event exists many times over this time period as well).

![image](https://user-images.githubusercontent.com/44876587/48217210-6c5f3a80-e34c-11e8-812d-ba7b4fc833d7.png)

I'm sure it must be something simple that I am missing but....

Any help is appreciated.

Thanks
Scott

**Comment by Qmando** [comment]
The issue here is the quotes around 1102. If you see in Kibana, there is a # symbol next to event_id, meaning it's stored as an integer. You'll need to do 
```
- term:
    event_id: 1102
```

**Comment by kriesesc** [comment]
Thanks @Qmando for the tip, I made that change, but still no hits.

**Comment by Qmando** [comment]
Your index doesn't seem to match either
`logstash-beats-*` vs `prdsec06:logstash-beats-2018.11.08`

**Comment by kriesesc** [comment]
I noticed that too, realized that I needed to adjust that to change the index to be *:logstash-beats-* in order to match the dropdown selection I get in Discover in Kibana:

![image](https://user-images.githubusercontent.com/44876587/48285601-c9302300-e428-11e8-9fa0-2ebcd2df9593.png)

That fixed it!  thanks for your help @Qmando . much appreciated!
