### ISSUE TITLE
How to send Alert if index doesn't get any new docs in last 30 mins.

### ISSUE THREAD

**Issue by mukeshchouhan** [Yelp/elastalert#2041]

**Comment by Qmando** [comment]
```
name: something
type: flatline
timeframe:
  minutes: 30
threshold: 1
alert: something
```

**Comment by mukeshchouhan** [comment]
Thanks @Qmando for the help

**Comment by mukeshchouhan** [comment]
@Qmando I am using filter in my flatline rule as below- 

filter:
- term:
    vendor.keyword: "cisco"

Can I use use_count_query: true with this rule?

Or shall i use use_term_query:true ?

**Comment by Qmando** [comment]
You can use either. You'd use `use_terms_query` only if you had `query_key` set.
