### ISSUE TITLE
Duplicate alerts when receiving data in batches

### ISSUE THREAD

**Issue by admlko** [Yelp/elastalert#2045]
Hi,

I have a setup where Logstash retrieves data from a database with JDBC input plugin. It runs every hour.
The problem exists only with this rule, the one which is watching over JDBC data which is retrieved in batches.
All the other data sources are continuous NRT sources and their alerting works perfectly.

So, one minute past every hour we receive data from a database from the last hour. The rule in ElastAlert is configured to be run every minute (doesn't make sense, but shouldn't matter, right?).
Here's part of the log showing what happens:

```
...
Dec 19 15:01:00 moe python[22069]: INFO:elastalert:Queried rule erp-audit from 2018-12-19 13:01 EET to 2018-12-19 15:01 EET: 0 / 0 hits
Dec 19 15:01:00 moe python[22069]: INFO:elastalert:Ran erp-audit from 2018-12-19 13:01 EET to 2018-12-19 15:01 EET: 0 query hits (0 already seen), 0 matches, 0 alerts sent
Dec 19 15:02:00 moe python[22069]: INFO:elastalert:Queried rule erp-audit from 2018-12-19 13:02 EET to 2018-12-19 15:02 EET: 5 / 5 hits
Dec 19 15:02:00 moe python[22069]: INFO:elastalert:Ran erp-audit from 2018-12-19 13:02 EET to 2018-12-19 15:02 EET: 5 query hits (0 already seen), 5 matches, 5 alerts sent
Dec 19 15:03:00 moe python[22069]: INFO:elastalert:Queried rule erp-audit from 2018-12-19 13:03 EET to 2018-12-19 15:03 EET: 5 / 5 hits
Dec 19 15:03:00 moe python[22069]: INFO:elastalert:Ran erp-audit from 2018-12-19 13:03 EET to 2018-12-19 15:03 EET: 5 query hits (5 already seen), 0 matches, 0 alerts sent
Dec 19 15:04:00 moe python[22069]: INFO:elastalert:Queried rule erp-audit from 2018-12-19 13:04 EET to 2018-12-19 15:04 EET: 5 / 5 hits
...
```

Here everything seems to work as expected, we get new data and it includes 5 new events which needs to trigger an alert.
Moving on...

```
...
Dec 19 16:01:03 moe python[22069]: INFO:elastalert:Queried rule erp-audit from 2018-12-19 14:01 EET to 2018-12-19 16:01 EET: 5 / 5 hits
Dec 19 16:01:03 moe python[22069]: INFO:elastalert:Ran erp-audit from 2018-12-19 14:01 EET to 2018-12-19 16:01 EET: 5 query hits (5 already seen), 0 matches, 0 alerts sent
Dec 19 16:02:03 moe python[22069]: INFO:elastalert:Queried rule erp-audit from 2018-12-19 14:02 EET to 2018-12-19 16:02 EET: 10 / 10 hits
Dec 19 16:02:03 moe python[22069]: INFO:elastalert:Ran erp-audit from 2018-12-19 14:02 EET to 2018-12-19 16:02 EET: 10 query hits (5 already seen), 5 matches, 5 alerts sent
Dec 19 16:03:03 moe python[22069]: INFO:elastalert:Queried rule erp-audit from 2018-12-19 14:03 EET to 2018-12-19 16:03 EET: 10 / 10 hits
Dec 19 16:03:03 moe python[22069]: INFO:elastalert:Ran erp-audit from 2018-12-19 14:03 EET to 2018-12-19 16:03 EET: 10 query hits (10 already seen), 0 matches, 0 alerts sent
Dec 19 16:04:03 moe python[22069]: INFO:elastalert:Queried rule erp-audit from 2018-12-19 14:04 EET to 2018-12-19 16:04 EET: 10 / 10 hits
Dec 19 16:04:03 moe python[22069]: INFO:elastalert:Ran erp-audit from 2018-12-19 14:04 EET to 2018-12-19 16:04 EET: 10 query hits (10 already seen), 0 matches, 0 alerts sent
...
```

Now we can see that ElastAlert has found 5 new events to alert, but these are actually duplicates from the previous batch. I can confirm this by looking at the origin timestamp from the events, they are identical.

#### config.yml:
```
...
run_every:
  minutes: 1
buffer_time:
  hours: 2
...
```

#### rule.yml:
```
...
type: any
realert:
  minutes: 0
...
```

**Comment by admlko** [comment]
@Qmando any idea why this is happening?

**Comment by Qmando** [comment]
It looks like you're adding new documents that happen to be a duplicate of the original. These will have a new `_id`, and these are totally separate documents in elasticsearch, so it makes sense that elastalert is alerting on them again. 

You have a couple of options:
1. Calculate a fingerprint of the document and use that as the `_id`. This will prevent duplicate events from being in Elasticsearch. Logstash has this capability.
2. Add 
```
query_key: field
realert:
  hours: 2
```
where `field` is some unique identifying field. That will cause the realert to only be applied to that particular value, preventing duplicate alerts.

**Comment by admlko** [comment]
Thank you for your reply @Qmando!

> It looks like you're adding new documents that happen to be a duplicate of the original.

This is not the case, because I cannot see duplicate events in Elasticsearch at all. Duplicates happens only when alerting.
I cannot specify document id from the database (because the index gets more data from other databases which might lead into clashes), but have to rely on Elasticsearch to generate one.

Here's my config:

```
input {
  jdbc {
    id => "xxxxxxxxx"
    jdbc_driver_library => "/etc/logstash/drivers/jdbc/progress/openedge.jar"
    jdbc_driver_class => "com.ddtek.jdbc.openedge.OpenEdgeDriver"
    jdbc_connection_string => "jdbc:datadirect:openedge://SERVER.customer01.local:1234;databaseName=xxxxxxxx"
    jdbc_user => "audit1"
    jdbc_password => "hunter2"
    statement => 'SELECT "_Audit-date-time", "_Transaction-id", "_Event-context", "_Event-id", "_User-id" FROM PUB."_aud-audit-data" WHERE ("_Event-id"=10500 OR "_Event-id"=10501 OR "_Event-id"=10510 OR "_Event-id"=10511 OR "_Event-id"=10512 OR "_Event-id"=10520 OR "_Event-id"=10521 OR "_Event-id"=10522) AND "_Transaction-id" > :sql_last_value'
    use_column_value => true
    tracking_column => "_Transaction-id"
    jdbc_validate_connection => true
    last_run_metadata_path => "/var/lib/logstash/plugins/inputs/jdbc/xxxxxxx-last_run"
    lowercase_column_names => false
    schedule => "1 * * * * Europe/Helsinki"
    add_field => {
      customer => "customer"
      monitoring => "customer_SERVER"
    }
    type => "xxxxxx"
  }
}
output {
  if [type] == "xxxxxx" {
    elasticsearch {
    ssl => true
    ssl_certificate_verification => true
    cacert => "xxxxx"
    hosts => [ "xxxxx" ]
    user => "xxxxxxx"
    password => "xxxxxxx"
    index => "%{customer}-%{type}-%{+yyyy}"
    }
  }
}
```

**Comment by Qmando** [comment]
It's definitely multiple documents. `10 query hits (5 already seen)` implies that there are 10 separate documents, 5 being from the previous hour and 5 from the current hour. 

If you're able to use the origin timestamp to confirm duplicates, try adding this logstash code:

```
filter {
    if [type] == "xxxxx" {
        fingerprint {
            target => "fingerprint"
            key => "123456"
            method => "SHA1"
            source => ["timestamp", "optional other fields"]
            concatenate_sources => true
        }
    }
}
output {
  if [type] == "xxxxxx" {
    elasticsearch {
    document_id => "%{fingerprint}"
    ssl => true
    ssl_certificate_verification => true
    cacert => "xxxxx"
    hosts => [ "xxxxx" ]
    user => "xxxxxxx"
    password => "xxxxxxx"
    index => "%{customer}-%{type}-%{+yyyy}"
    }
  }
}
```

Now when the new ones come in, it will be a noop because that particular _id already exists. If the timestamp is new, it will create a new document.

When you say you cannot see duplicate events in Elasticsearch at all, how exactly are you searching?

**Comment by admlko** [comment]
You are correct, was acting upon a colleagues investgation. Forgot to "trust, but verify".
They are the same documents for sure, I guess this happens because the pipeline has 2 workers. Will see. But it is definitely not an ElastAlert issue.
