### ISSUE TITLE
Can I use %W to denote weeks of a year

### ISSUE THREAD

**Issue by wesleyzhang92** [Yelp/elastalert#2062]
I'm currently using EA v0.33&0.35
Some team use %W in their index name, such as: index: myindex-%Y.%W
It used to work but failed recently. Can somebody help on this?

I can figure this out by changing it to myindex-%Y.*, but I want to know the reason why it works before?
Thanks in advance

**Comment by Qmando** [comment]
What do you mean by failed recently? Was this right around the new year?

Read the difference between week and ISOweek. Python generally conforms to C's standards. From http://man7.org/linux/man-pages/man3/strftime.3.html

```

       %U     The week number of the current year as a decimal number, range
              00 to 53, starting with the first Sunday as the first day of
              week 01.  See also %V and %W.  (Calculated from tm_yday and
              tm_wday.)

       %V     The ISO 8601 week number (see NOTES) of the current year as a
              decimal number, range 01 to 53, where week 1 is the first week
              that has at least 4 days in the new year.  See also %U and %W.
              (Calculated from tm_year, tm_yday, and tm_wday.)  (SU)

       %W     The week number of the current year as a decimal number, range
              00 to 53, starting with the first Monday as the first day of
              week 01.  (Calculated from tm_yday and tm_wday.)
```
