### ISSUE TITLE
Rule file name in `alert_text`

### ISSUE THREAD

**Issue by Green-m** [Yelp/elastalert#2073]
Happy new year! 
Sorry to bother you for my foolish questions. I have checked out some docs and wikis, but not found anything to solve it.

How could I appoint an arg such as `__file__` in python to denote the name of rule file? 

Here is part of my config file:

```
alert_subject: "Sigma Alert ({0})"
alert_subject_args:
- name
alert_text: "Descpriton :\n{0} \n-------------- \nQuery_string\n {1} \n--------------------- \n"
alert_text_args: [description, filter ]
```

For instance, I want it to be:
```
alert_subject: "Sigma Alert ({0})"
alert_subject_args:
- name
alert_text: "Descpriton :\n{0} \n-------------- \nQuery_string\n {1} \n--------------------- {2}\n"
alert_text_args: [description, filter, __file__ ] 
```

In other words, I want to execute some python code when sending an alert with email, is it supported?
Or any other ways to achieve it?
Thanks in advance.

**Comment by Qmando** [comment]
Try `alert_text_args: [description, filter, rule_file]`

**Comment by Green-m** [comment]
> Try `alert_text_args: [description, filter, rule_file]`

That works perfectly, thanks!
