### ISSUE TITLE
Enhancement global name 'DropMatchException' is not defined

### ISSUE THREAD

**Issue by MarcusGCY** [Yelp/elastalert#2082]
Getting this error when using DropMatchException in my enhancement.py.
 
NameError: global name 'DropMatchException' is not defined

**Yaml rules:** 
`name: test matching fields
type: any
index: data_filebeat

filter:
  - query:
        query_string:
            query: "_type:doc"
########################### Enhancement ############################

match_enhancements:
  - "elastalert_modules.enhancement.enhancement_function"

############################ Alerter ############################

alert:
- "slack"
slack:
slack_webhook_url: "xxxx"
`
**enhancement.py** :
`
from elastalert.enhancements import BaseEnhancement, DropMatchException

class match_header_to_envelope(BaseEnhancement):
      def process(self, match):
        if 'field1' == 'field2':
          raise DropMatchException()
`

What am I missing here ? Any advise will be super appreciated !

**Comment by thommor** [comment]
Could you provide the full contents on 'enhancement.py'?

**Comment by MarcusGCY** [comment]
I call pass directly in my myEnhancement.py and it work. Look like issue with the import or maybe the python path. 

> class match_header_to_envelope(BaseEnhancement):
def process(self, match):
if 'field1' == 'field2':
pass

My full contents on elastalert/ enhancement.py :

> class BaseEnhancement(object):
def __init__(self, rule):
        self.rule = rule
def process(self, match):
        """ Modify the contents of match, a dictionary, in some way """
        raise NotImplementedError()
 class DropMatchException(Exception):
    """ ElastAlert will drop a match if this exception type is raised by an enhancement """
pass

**Comment by Qmando** [comment]
`from elastalert.enhancements import DropMatchException`
