### ISSUE TITLE
Number of connection between Elastalert and Elasticsearch

### ISSUE THREAD

**Issue by dhanasg** [Yelp/elastalert#2084]
I have elastalert service which has only one rule. Its connecting with ElasticSearch successfully. For executing one rule I see more than 6 connections to Elastics Search port 9200. I observed this using "netstat -antp | grep 9200". As and when new rules are added, the number of connection to ES increase. Is this expected? Why more than 6 connection are established for one rule which executes every 2 minutes.

**Comment by Qmando** [comment]
you can add the flag `--es_debug_trace logfile` to see every single request made. They are basically all necessary.
