### ISSUE TITLE
Mapping for match_type in the type "elastalert" is set false

### ISSUE THREAD

**Issue by 2arunpmohan** [Yelp/elastalert#2093]
The mapping for the field "match_type" is set as "enabled: false". This field exists in the type "**elastalert**" in the index "**elastalert_status**". 
The issue regarding this, is that, I need to perform a search in the fields coming under "match_type". Due the mapping given, this is not possible. I would like to change the mapping to "enabled: true" in the following code snippet in the file "**elastalert/create_index.py**"
```
 es_mapping = {
        'elastalert': {
            'properties': {
                'rule_name': mapping,
                '@timestamp': {
                    'type': 'date',
                    'format': 'dateOptionalTime',
                },
                'alert_time': {
                    'type': 'date',
                    'format': 'dateOptionalTime',
                },
                'match_time': {
                    'type': 'date',
                    'format': 'dateOptionalTime',
                },
                'match_body': {
                    'type': 'object',
                    'enabled': False,
                },
                'aggregate_id': mapping,
            },
        },
    }
```
But I am not sure of the implications, as this might sometimes results in mapping parsing exception error and not indexing of the necessary data. 
Please advise on the same.

**Comment by pdscopes** [comment]
Firstly, you mean `match_body` not `match_type`. That aside, you can overwrite the mapping for the `elastalert` index yourself (see https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-put-mapping.html). IFAIK the implications are:

1.  The operation could fail if not all existing alerts in the index match the new mapping.
2.  If the property doesn't match the specified mapping type then ES will not insert the alert.

You can use enhancements to alter the match body of alerts before they are inserted (see https://elastalert.readthedocs.io/en/latest/recipes/adding_enhancements.html).
