### ISSUE TITLE
Use realert error!!!

### ISSUE THREAD

**Issue by Hello-Linux** [Yelp/elastalert#2098]
To Reduce the frequency of repeated alarms,I set config in config.yaml
```
query_key:
  - name

realert:
  minutes: 10

exponential_realert:
  hours: 1
```
but when I send alert message the error show:
"ERROR:root:Traceback (most recent call last):
  File "/scripts/elastalert/elastalert/elastalert.py", line 1169, in run_all_rules
    num_matches = self.run_rule(rule, endtime, self.starttime)
  File "/scripts/elastalert/elastalert/elastalert.py", line 895, in run_rule
    next_alert, exponent = self.next_alert_time(rule, silence_cache_key, ts_now())
  File "/scripts/elastalert/elastalert/elastalert.py", line 1904, in next_alert_time
    if wait >= rule['exponential_realert']:
TypeError: can't compare datetime.timedelta to dict"        why??????????????When I remove these configurations, the alarm is successful

**Comment by thommor** [comment]
We tested it and it seems to work as expected for us.

Could it be that your yaml indentation is slightly off?

It should be like:
```yaml
exponential_realert:
  hours: 1
```

The same would apply for your realert as well.

**Comment by Qmando** [comment]
You need to put those settings into individual rules instead of the global config.yaml. I think this qualifies as a bug since you're supposed to be able to put defaults in the global config, but in this case, the code that converts it to a timedelta object doesn't run unless it's in the rule yaml.
