### ISSUE TITLE
Getting error when "File Path" is mentioned in Elastalert Rule

### ISSUE THREAD

**Issue by sangeethsuseelan** [Yelp/elastalert#2117]
Hi All,

I want the alert to be triggered when a File is found in a particular location. So I am using the Rule Type "Blacklist". Below is the sample and rule

Sample Event:

event_data.NewProcessName : C:\Users\uipathuser\Downloads\npp.7.6.3.Installer.x64.exe

Rule:

type: blacklist
index: winlogbeat-*
compare_key: event_data.NewProcessName
ignore_null: true
blacklist:
    - C:\Users\uipathuser\Downloads\npp.7.6.3.Installer.x64.exe

I am getting the below error when running the above rule.

WARNING:elasticsearch:GET http://10.1.0.6:9200/winlogbeat-*/_search?_source_include=event_data.NewProcessName%2C%2A%2C%40timestamp&ignore_unavailable=true&scroll=30s&size=10000 [status:400 request:0.021s]
ERROR:root:Error running query: RequestError(400, u'search_phase_execution_exception', u'Failed to parse query [event_data.NewProcessName:"C:\\Users\\uipathuser\\Downloads\\npp.7.6.3.Installer.x64.exe"]')
INFO:elastalert:Ran Automation Task Failed from 2019-02-05 16:21 UTC to 2019-02-05 16:28 UTC: 0 query hits (0 already seen), 0 matches, 0 alerts sent
INFO:elastalert:Sleeping for 59.87899 seconds

So I have updated the Rule 

Updated Rule:

type: blacklist
index: winlogbeat-*
compare_key: event_data.NewProcessName
ignore_null: true
blacklist:
    - C:\\\Users\\\uipathuser\\\Downloads\\\npp.7.6.3.Installer.x64.exe

Now I am not getting the error but it is showing as no matches found

INFO:elastalert:Queried rule Automation Task Failed from 2019-02-05 16:16 UTC to 2019-02-05 16:21 UTC: 1 / 1 hits
INFO:elastalert:Ran Automation Task Failed from 2019-02-05 16:16 UTC to 2019-02-05 16:21 UTC: 1 query hits (0 already seen), 0 matches, 0 alerts sent

Please help me.

**Comment by thommor** [comment]
Are you certain there is a result in your elasticsearch instance within the timeframe 2019-02-05 16:16 UTC to 2019-02-05 16:21?

**Comment by sangeethsuseelan** [comment]
> Are you certain there is a result in your elasticsearch instance within the timeframe 2019-02-05 16:16 UTC to 2019-02-05 16:21?

Yeah. I think that is why I am getting 1/1 hits.

INFO:elastalert:Queried rule Automation Task Failed from 2019-02-05 16:16 UTC to 2019-02-05 16:21 UTC: 1 / 1 hits

**Comment by sangeethsuseelan** [comment]
Yeah, there is data.

Please see the data and attachment.

INFO:elastalert:Queried rule Automation Task Failed from 2019-02-06 06:51 UTC to 2019-02-06 07:21 UTC: 2 / 2 hits
INFO:elastalert:Queried rule Automation Task Failed from 2019-02-06 07:21 UTC to 2019-02-06 07:51 UTC: 0 / 0 hits
INFO:elastalert:Queried rule Automation Task Failed from 2019-02-06 07:51 UTC to 2019-02-06 08:21 UTC: 0 / 0 hits
INFO:elastalert:Queried rule Automation Task Failed from 2019-02-06 08:21 UTC to 2019-02-06 08:45 UTC: 1 / 1 hits
INFO:elastalert:Ran Automation Task Failed from 2019-02-05 16:21 UTC to 2019-02-06 08:45 UTC: 3 query hits (0 already seen), 0 matches, 0 alerts sent




![events](https://user-images.githubusercontent.com/46028403/52329927-03a25f80-2a1a-11e9-9b99-a2f1d72de832.JPG)

**Comment by sangeethsuseelan** [comment]
The issue has been resolved by modifying the filter condition.

- query:
    match:
      event_data.NewProcessName:
       query: "C:\\Users\\uipathuser\\Downloads\\npp.7.6.3.Installer.x64.exe"
