### ISSUE TITLE
How to use re-alert field value in custom rule?

### ISSUE THREAD

**Issue by skatakar** [Yelp/elastalert#2118]
I have to customize email body content to put “similar events will be suppressed till <eventtime + datetime.timedelta(10)”. I am writing custom rule to take event time and add re-alert time.  But re-alert value is not coming.

class MyRuleType(RuleType):
    def add_data(self, data):
        for datum in data:
            ###handling time starts
             print "Local time is {}".format(datum["local_time"])
             print "Local time type is  {}".format(type(datum["local_time"]))
             import datetime
            event_time = datum["local_time"]
            new_date = datetime.datetime.strptime(event_time, '%Y-%m-%dT%H:%M:%S.%f')
            print "new date time is {} and type is {}".format(new_date,type(new_date))
            print "*" * 10
            datum["after_relaert"] = new_date + datetime.timedelta(minutes = datum["realert"])
            print "after adding realert time is {} and type is {}".format(datum["after_relaert"], type(datum["after_relaert"]))

getting following error.
  File "D:\Python27\lib\site-packages\elastalert\elastalert.py", line 623, in run_query
    rule_inst.add_data(data)
  File "D:\Python27\lib\site-packages\elastalert\elastalert_modules\message_enhancement.py", line 28, in add_data
    datum["after_relaert"] = new_date + datetime.timedelta(minutes = datum["realert"])
KeyError: 'realert'

**Comment by thommor** [comment]
`realert` is defined in the rule not in the data so you would want `self.rules['realert']`.

Also `realert` is automatically converted into a timedelta object so can be added directly to new_date like so:
`datum["after_relaert"] = new_date + datum["realert"]`

**Comment by skatakar** [comment]
Thanks @thommor , I thought all variables were treating data fields. with self rules variable, its working.

Thanks,
Sudhakar

**Comment by thommor** [comment]
@skatakar No worries.

Could you close the issue if it's resolved please?
