### ISSUE TITLE
Emails not sent even if events are triggered.

### ISSUE THREAD

**Issue by brucekk248** [Yelp/elastalert#2123]
Hello,
I am unable to receive any emails even though the events are occurring. 
I am able to send email manually yet having issues while sending with elastalert tool.
Here is my config from example_rules/example_frequesncy.yaml

es_host: localhost
es_port: 9200
name: Example rule
type: frequency
index: filebeat-*
num_events: 1
timeframe:
    seconds: 30
filter:
- match:
    message: "debug"
timestamp_field: "@timestamp"
alert:
- "email"
email:
- "abc@gmail.com"

Logs 
INFO:elastalert:Skipping writing to ES: {'hits': 42, 'matches': 42, '@timestamp': '2019-02-07T17:37:24.640926Z', 'rule_name': 'Example rule', 'starttime': '2019-02-07T17:22:24.614200Z', 'endtime': '2019-02-07T17:37:24.614200Z', 'time_taken': 0.026715993881225586}

INFO:elastalert:Ran Example rule from 2019-02-07 17:22 UTC to 2019-02-07 17:37 UTC: 42 query hits (0 already seen), 42 matches, 0 alerts sent
INFO:elastalert:Sleeping for 29.969928 seconds

**Comment by brucekk248** [comment]
Hey never mind I got this solved. 
Also, I was wondering if you could tell me how to configure the set of rules in one yaml file. It becomes great difficult to run all the files individually.

**Comment by thommor** [comment]
If your config.yaml you can specify a `rules_folder: <path to your rules>` which will load all rule files in that folder.

See [here](https://elastalert.readthedocs.io/en/latest/elastalert.html?highlight=rules_folder)

**Comment by brucekk248** [comment]
Thanks @thommor 
Yes I got this issues resolved.
