### ISSUE TITLE
Does Elastalert support hot load?

### ISSUE THREAD

**Issue by pengpeng-cscs** [Yelp/elastalert#2127]
If I add a new rule file to Elastalert-rules folder or change one rule rile, will Elastalert automatically detect this change and load latest rule without restarting Elastalert service?

**Comment by abhishekjiitr** [comment]
Yes, ElastAlert supports hot reloading of rules

**Comment by pengpeng-cscs** [comment]
Thanks, after adding a test rule to the folder, I confirmed that Elastalert supports hot load.
