### ISSUE TITLE
Email : [Errno -2] SMTP Name or service not known

### ISSUE THREAD

**Issue by Amarquier** [Yelp/elastalert#2142]
Hi,

I'm trying to create my first rule. It's a frequency rule and it works fine with the tester and the debug alerter. However when I try to send a mail I have the following error :
> ERROR:root:Error while running alert email: Error connecting to SMTP host: [Errno -2] Name or service not known   
alert:

This is my config :

> alert:
> - "email"
> email:
>  - "example@gmail.com"
> smtp_host: "smtp.gmail.com"
> smtp_port: "465"
> smtp_ssl : "true"
> from_addr: "example@gmail.com"
> smtp_auth_file: '' /etc/elasticsearch/smtp_auth.yaml"

Do you have an idea how to solve this issue please ?

Thanks

**Comment by thommor** [comment]
From what I can see, chances are your indentation of your rule is off (YAML is very picky) or your machine can't find an IP address for `smtp.gmail.com`.

For the first one could you format your config by placing it in code like so
````
```yaml
alert:
- "email"
email:
- "elastalert@example.com"
```
````

For the second if you're on linux you could try to ping/dig `smtp.gmail.com` to make sure your machine can see it

`ping smtp.gmail.com`
`dig smtp.gmail.com`

You could also try to telnet to make sure you can connect

`telnet smtp.gmail.com 465`

**Comment by Amarquier** [comment]
The problem is on my end, emails are blocked on the testing network I'm currently.

**Comment by John-coder777** [comment]
Maybe port must be 587
