### ISSUE TITLE
How to update?  

### ISSUE THREAD

**Issue by mathurin68** [Yelp/elastalert#2143]
Alright newb question... how do I update my elastalert without overwriting my changes?  

If I do a git pull I get - 

[new tag] v0.2.0a1 -> v0.2.0a1
[new tag] v0.2.0b1 -> v0.2.0b1
Updating 9774fc8..5fe946b error: Your local changes to the following files would be overwritten by merge:
  elastalert/alerts.py

... I ended up just moving it and copying it back BUT I wanted to know the correct way to do it?  I tried 
git stash 
BUT that was asking me to log in...

Just curious what most people do, thanks!

**Comment by Qmando** [comment]
Once you configure git once, you won't have to log in. Git stash is what I would use.

**Comment by mathurin68** [comment]
Ok, cool, thank you, but when it asks me 

```
$ git stash
*** Please tell me who you are.
Run
  git config --global user.email "you@example.com"
```

do I give it the same github username I logged into here?

**Comment by Qmando** [comment]
You don't even need to login to anything or create any accounts, if you're only going to stash. That just sets up what email it puts when you commit things. If you wanted to push your changes to github then you'd need to associate it with your github account.

**Comment by mathurin68** [comment]
Ah, OK, big help thank you!!!!!

alright so 
```
git stash (just give it any email)
git pull
git stash pop
```

... that appears to have worked, is that good?

**Comment by Qmando** [comment]
Yeah

**Comment by mathurin68** [comment]
Boom, many thanks!
