### ISSUE TITLE
EAException('Error loading file %s: %s' % (rule_file, e)) elastalert.util.EAException: Error loading file rules/test.yaml: Error initiating alert None:

### ISSUE THREAD

**Issue by Aris02** [Yelp/elastalert#2145]
Hello. I start docker container with elast-alert and install kibana plugin. Create a test rule. elastalert-test-rule is fine. but when i try start elastalert for this rule i have an error. 
My test rule text:
es_host: 192.168.88.23
es_port: 26200
name: test
type: any
index: listener-*

filter: 
- term:
    ip_client: "192.168.88.25"
include:
  - the_date
  - user
  - program
realert:
  minutes: 0
  
alert:
ms_teams_webhook_url: "https://teams.microsoft.com/l/channelXXXX"
ms_teams_summary:
    -"test"

test result:
Successfully loaded test Got 35 hits from the last 1 day Available terms in first hit: the_date tags dest @timestamp ip_client source host.name program user offset beat.hostname beat.name beat.version message @version dest_type Would have written the following documents to writeback index (default is elastalert_status): elastalert_status - {'hits': 35, 'matches': 35, '@timestamp': datetime.datetime(2019, 2, 20, 11, 8, 11, 764145, tzinfo=tzutc()), 'rule_name': 'test', 'starttime': datetime.datetime(2019, 2, 19, 11, 8, 7, 482421, tzinfo=tzutc()), 'endtime': datetime.datetime(2019, 2, 20, 11, 8, 7, 482421, tzinfo=tzutc()), 'time_taken': 4.274120092391968} 

And when I start elastalert have this error:
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/opt/elastalert/elastalert/elastalert.py", line 1923, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/opt/elastalert/elastalert/elastalert.py", line 1917, in main
    client = ElastAlerter(args)
  File "/opt/elastalert/elastalert/elastalert.py", line 108, in __init__
    self.conf = load_rules(self.args)
  File "elastalert/config.py", line 510, in load_rules
    raise EAException('Error loading file %s: %s' % (rule_file, e))
elastalert.util.EAException: Error loading file rules/test.yaml: Error initiating alert None: 
I have no idea what the problem is, could anyone give me some advice?

**Comment by Qmando** [comment]
You have `alert:`. You need to put something there. Looks like you want `alert: ms_teams`
