### ISSUE TITLE
Installation problem - "Optimizing and caching browser bundles..."

### ISSUE THREAD

**Issue by CoyoteKG** [Yelp/elastalert#2163]
2 vCPU
4 GB RAM
OS: SLES 12 SP4
ELK 6.6.1

Hello, I'm setting up ELK just for practicing, and I want to see how alerting works with ElastAlert, but I have problem with installation.

I executed 
`./bin/kibana-plugin install https://github.com/bitsensor/elastalert-kibana-plugin/releases/download/1.0.2/elastalert-kibana-plugin-1.0.2-6.6.1.zip`

But still after few hours is hanging on 
"Optimizing and caching browser bundles..."
![image](https://user-images.githubusercontent.com/17199551/53952186-7877c080-40d0-11e9-8757-51b5eb913313.png)

and it seems like processes does not doing anything
![image](https://user-images.githubusercontent.com/17199551/53951525-f0dd8200-40ce-11e9-9e27-712ced972cec.png)

What I should do? Wait more or?

**Comment by Qmando** [comment]
Post this on bitsensor/elastalert-kibana-plugin github page. This is not related to elastalert.
