### ISSUE TITLE
[Help for writing rule with Filter] 

### ISSUE THREAD

**Issue by pakjack79** [Yelp/elastalert#2167]
Hi all! 
I have a query search like this ' NOT GeoIPfrom.country_name: Vietnam and Message_VPN: "GlobalProtect portal user authentication succeeded" ' 

I have written like this:
filter:
  - term:
      Message_VPN: "GlobalProtect portal user authentication succeeded"
  - and:
     - not:
        term:
          GeoIPfrom.country_name: "Vietnam"
But it does not work exactly
Can anyone help me to write this rule please:
Thanks and Best Regards

**Comment by mansoorpn** [comment]
You can check https://elastalert.readthedocs.io/en/latest/recipes/writing_filters.html#negation-and-or
