### ISSUE TITLE
[Question] Can you use CIDR notation in a blacklist?

### ISSUE THREAD

**Issue by swedishmike** [Yelp/elastalert#2177]
I have been looking at creating an alert when a certain field contains an IP from a number of 'known bad' ranges.

The blacklist consists of a number of lines - each containing a range of addresses in CIDR notation.

The field I match against is a IP field and I can successfully search the field in the Kibana Discover 'console' using CIDR.

However when I try using this Elastalert Blacklist rule it does not fire at all - if I put in a single IP within the range the alert fires.

Is CIDR notation not supported in the Blacklist scenario?

Thanks in advance

**Comment by thommor** [comment]
No I don't believe this is currently supported

**Comment by swedishmike** [comment]
I'm not sure if it's just me or is this something that could/should be added as an request for enhancement?

To me it feels like being able to include either high value network segments or 'known bad' segments to a wildcard search against something like Bro/Zeek logs could be worthwhile?

Thoughts from others?

**Comment by pdscopes** [comment]
I agree this would be a nice feature, however I'm not sure how it would fit into the standard BlacklistRule. My suggestion would be to make a custom rule that extends BlacklistRule and overrides the `def compare(self, event)` method.

**Comment by thommor** [comment]
I agree with @pdscopes. This could get confusing if someone wanted to blacklist actual CIDR strings and not have them exploded into individual IP addresses

**Comment by swedishmike** [comment]
Point taken - I'll follow @pdscopes suggestion and try to create my own custom rule. Cheers for the feedback!
