### ISSUE TITLE
Match_body mapping is always false

### ISSUE THREAD

**Issue by nordgoat** [Yelp/elastalert#2179]
Hi 

I am trying to view my match_body contents in ES but when I run the

elastalert-create-index

It populates the mappings but sets the:

match_body: {
 "type": "object",
 "enabled" :"false"
}

I have edited the create-index.py file and set the mapping to "True" but it still creates the mapping to false. 

Can anyone help here?

**Comment by Qmando** [comment]
Perhaps you are running the wrong file. Try `python elastalert/create_index.py` instead of `elastalert-create-index`. The latter is probably trying to use a system installation of elastalert instead of the local files.
