### ISSUE TITLE
ImportError: No module named yaml

### ISSUE THREAD

**Issue by mancharagopan** [Yelp/elastalert#2188]
Hello,

I installed supervisor to run elastalert automatically but i am receiving following error and elastalert process going to FATAL state.

`Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/elastalert-0.1.38-py2.7.egg/elastalert/elastalert.py", line 20, in <module>
    import yaml
ImportError: No module named yaml
`

my supervisor.conf file,

```
; supervisor config file

[unix_http_server]
file=/var/run/supervisor.sock   ; (the path to the socket file)
chmod=0700                       ; sockef file mode (default 0700)

[supervisord]
logfile=/var/log/supervisor/supervisord.log ; (main log file;default $CWD/supervisord.log)
pidfile=/var/run/supervisord.pid ; (supervisord pidfile;default supervisord.pid)
childlogdir=/var/log/supervisor            ; ('AUTO' child log dir, default $TEMP)

; the below section must remain in the config file for RPC
; (supervisorctl/web interface) to work, additional interfaces may be
; added by defining them in separate rpcinterface: sections
[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock ; use a unix:// URL  for a unix socket

; The [include] section can just contain the "files" setting.  This
; setting can list multiple files (separated by whitespace or
; newlines).  It can also contain wildcards.  The filenames are
; interpreted as relative to this file.  Included files *cannot*
; include files themselves.

[include]
files = /etc/supervisor/conf.d/*.conf

```

My config file,
```
[program:elastalert]
# running globally
command = python -m elastalert.elastalert --verbose --config /tmp/elastalert/config.yaml
# (alternative) using virtualenv
# command=/path/to/venv/bin/elastalert --config /path/to/config.yaml --verbose
process_name=elastalert
autorestart=true
startsecs=15
stopsignal=INT
stopasgroup=true
killasgroup=true
stderr_logfile=/var/log/elastalert_stderr.log
stderr_logfile_maxbytes=5MB

```

I already installed PYyaml 5.1,
```
Collecting pyyaml
Installing collected packages: pyyaml
Successfully installed pyyaml-5.1

```

**Comment by thommor** [comment]
Have you installed pyyaml globally or is it only installed in your virtual env?

Check your `/usr/local/lib/python2.7/dist-packages/` for a `yaml` directory

**Comment by mancharagopan** [comment]
yaml not i

> 
> 
> Have you installed pyyaml globally or is it only installed in your virtual env?
> 
> Check your `/usr/local/lib/python2.7/dist-packages/` for a `yaml` directory

yaml not in that directory. How do i install it globally?

**Comment by bbratchiv** [comment]
Have the same problem
```
/usr/local/lib/python2.7/dist-packages/elastalert-0.1.39-py2.7.egg/elastalert/config.py:31: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  rule_schema = jsonschema.Draft4Validator(yaml.load(open(os.path.join(os.path.dirname(__file__), 'schema.yaml'))))
```

**Comment by mancharagopan** [comment]
I solved it. Installed python-yaml with apt-get install

**Comment by bbratchiv** [comment]
@mancharagopan , hello
Wanted to ask if all the rules are being loaded from example_rules directory (or whatever you use) in your installation

**Comment by mancharagopan** [comment]
yes

> 
> 
> @mancharagopan , hello
> Wanted to ask if all the rules are being loaded from example_rules directory (or whatever you use) in your installation

**Comment by bbratchiv** [comment]
@mancharagopan , can you please specify where supervisor.conf and elastalert supervisor configs are located and how are they connected ?

**Comment by mancharagopan** [comment]
supervisor.conf located in /etc/supervisor/ directory and the program configuration files of the supervisor is located in /etc/supervisor/conf.d/

My elastalert files located in /opt/elastalert-master/ directory and the rules located inside my_rules folder.
