### ISSUE TITLE
Elastalert giving incorrect results!!!

### ISSUE THREAD

**Issue by mindcurv-vishnu** [Yelp/elastalert#2193]
HI @Qmando,

Topic: Query a string from elasticsearch (Filebeat* index) and alert
Rule : error_datatruncation.yml

``` es_host: localhost
 es_port: 9200

 name: TK_Slack

 type: any

 index: filebeat-*


 filter:
 - query:
     query_string:
         query: 'environment : "XXXXXX" and application : "datahub" and beat.hostname :  XXXXXXX  and message: "java.sql.BatchUpdateException: Data truncation"'

#Send alert only once
 realert:
  minutes: 1

 alert:
 - "email"
 email:
 - "XXXXXXXXXXXXXXXXXXX"
```

**Config file:**
 
```rules_folder: /XX/elastalert/elastalert_rules

run_every:
  minutes: 1

buffer_time:
  minutes: 3

es_host: localhost

es_port: 9200

writeback_index: elastalert_status

alert_time_limit:
  days: 2

smtp_host: 'XXXXXXX'
smtp_port: 25
from_addr: 'XXXXXXXXXXXXXXXXXXX'
```
**Steps to reproduce issues: Run below commands**

```cd /XX/elastalert


python -m elastalert.elastalert --verbose --rule elastalert_rules/error_datatruncation.yml --start `date +"%Y-%m-%dT%H:%M:%S+02:00" --date='2 minutes ago'` --es_debug_trace /home/XXX/elastlog.txt
```
**Expected result:** 

- Queries the index as per the rule and alert sent once when the string is found

**Obtained result/Output**

```
[root@vmELK0810001 elastalert]# python -m elastalert.elastalert --verbose --rule elastalert_rules/error_datatruncation.yml --start `date +"%Y-%m-%dT%H:%M:%S+02:00" --date='2 minutes ago'`  --es_debug_trace /home/XXXX/elastlog.txt

INFO:elastalert:Starting up

INFO:elastalert:Queried rule TK_Slack from 2019-04-05 11:43 CEST to 2019-04-05 11:45 CEST: 1198 / 1198 hits
INFO:elastalert:Sent email to ['XXXXXXXXXXXXXXXXXXX']

INFO:elastalert:Ignoring match for silenced rule TK_Slack

INFO:elastalert:Ignoring match for silenced rule TK_Slack

INFO:elastalert:Ignoring match for silenced rule TK_Slack

INFO:elastalert:Ran TK_Slack from 2019-04-05 11:46 CEST to 2019-04-05 11:48 CEST: 848 query hits (0 already seen), 848 matches, 1 alerts sent

INFO:elastalert:Sleeping for 55.107107 seconds
```
I have ran this in debug mode but this is sending me some random query result and silence keeps running.
- The required string is queried when i check the debug log but it looks like the rule is not being executed properly. The matches it shows in the end are also wrong
@Qmando  can you let me know this is a bug or something to do with the rule?
Thanks in advance

**Comment by mindcurv-vishnu** [comment]
@Qmando  Posting the debug log as well

`  }
}'
curl -H 'Content-Type: application/json' -XGET 'http://localhost:9200/filebeat-*/_search?pretty&_source_include=%40timestamp%2C%2A&ignore_unavailable=true&scroll=30s&size=10000' -d '{
  "query": {
    "bool": {
      "filter": {
        "bool": {
          "must": [
            {
              "range": {
                "@timestamp": {
                  "gt": "2019-04-05T09:00:22+02:00",
                  "lte": "2019-04-05T07:02:23.728120Z"
                }
              }
            },
            {
              "query_string": {
                "query": "environment : \"XXXXXX\" and application : \"datahub\" and beat.hostname :  XXXXXXXX  and message: \"java.sql.BatchUpdateException: Data truncation\""
              }
            }
          ]
        }
      }
    }
  },
  "sort": [
    {
      "@timestamp": {
        "order": "asc"
      }
    }
  ]
}'
curl -H 'Content-Type: application/json' -XGET 'http://localhost:9200/elastalert_status_silence/silence/_search?pretty&_source_include=until%2Cexponent&size=1' -d '{
  "query": {
    "term": {
      "rule_name": "TK_Slack._silence"
}
  },
  "sort": {
    "until": {
      "order": "desc"
    }
  }
}'
curl -H 'Content-Type: application/json' -XGET 'http://localhost:9200/elastalert_status_silence/silence/_search?pretty&_source_include=until%2Cexponent&size=1' -d '{
  "query": {
    "term": {
      "rule_name": "TK_Slack"
    }
  },
  "sort": {
    "until": {
      "order": "desc"
    }
  }
}'
curl -H 'Content-Type: application/json' -XPOST 'http://localhost:9200/elastalert_status_silence/silence?pretty' -d '{
  "@timestamp": "2019-04-05T07:02:24.988664Z",
  "exponent": 0,
  "rule_name": "TK_Slack",
  "until": "2019-04-05T07:03:24.988657Z"
}'
curl -H 'Content-Type: application/json' -XPOST 'http://localhost:9200/elastalert_status/elastalert?pretty' -d '{
  "@timestamp": "2019-04-05T07:02:25.165111Z",
  "alert_info": {
    "recipients": [
      "XXXXXXXXXXXXXXX"
    ],
    "type": "email"
  },
  "alert_sent": true,
  "alert_time": "2019-04-05T07:02:25.027875Z",
  "match_body": {
    "@timestamp": "2019-04-05T07:00:23Z",
    "_id": "hh5M7GkB-sZs6uoWh9W7",
    "_index": "filebeat-6.0.1-2019.04.05",
    "_type": "doc",
    "ap_client_ip": "XXXXXXXXX",
    "ap_timestamp": "05/Apr/2019:09:00:23 +0200",
"application": "apache",
    "beat": {
      "hostname": "XXXXXXXXXXX",
      "name": "XXXXXXXXXX",
      "version": "XXXXX"
    },
    "detail": "XXXXXXXXXXXXXXXX \"POST /backoffice/zkau HTTP/1.1\" 200 44 \"https://XXXXXXXXXXXXXXXXXXXXX/\" \"Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36\" XXXXXXXXXXXXXXXXXXXXXXXX 9031 \"-\"",
    "environment": "XXXXX",
    "instance": "XXXXX",
    "message": "10.121.111.142 - - [05/Apr/2019:09:00:23 +0200] XXXXXXXXXXXXXX \"POST /backoffice/zkau HTTP/1.1\" 200 44 \"https://XXXXXXXXXXXXXXXXX/backoffice/\" \"Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36\" XXXXXXXXXXXXXXXXXXXXXXXXXXXX 9031 \"-\"",
    "num_hits": 2965,
    "num_matches": 2965,
    "offset": 976391,
    "prospector": {
      "type": "log"
    },
    "source": "/TK/apache/logs/shop-be-access.log"
  },
  "match_time": "2019-04-05T07:00:23Z",
  "rule_name": "TK_Slack"
}'
curl -H 'Content-Type: application/json' -XGET 'http://localhost:9200/elastalert_status_silence/silence/_search?pretty&_source_include=until%2Cexponent&size=1' -d '{
  "query": {
    "term": {
      "rule_name": "TK_Slack._silence"
    }
 },
  "sort": {
    "until": {
      "order": "desc"
    }
  }
}'
curl -H 'Content-Type: application/json' -XGET 'http://localhost:9200/elastalert_status_silence/silence/_search?pretty&_source_include=until%2Cexponent&size=1' -d '{
  "query": {
    "term": {
      "rule_name": "TK_Slack._silence"
    }
  },
  "sort": {
    "until": {
      "order": "desc"
    }
  }
}'

`

**Comment by Qmando** [comment]
Please read https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html. You need to capitalize `AND`.

**Comment by mindcurv-vishnu** [comment]
@Qmando that was quick. That worked. Thank you!!
