### ISSUE TITLE
Adding data to match body

### ISSUE THREAD

**Issue by nordgoat** [Yelp/elastalert#2200]
Hi 

Is there a way to add a configuration option within a rule which can then be added to the match body so it can be used in a Enhancement? 

I need to add a field which can be used to determine a value in my Enhancement for my rule. 

Any ideas?

Thanks

**Comment by Qmando** [comment]
Enhancements have access to the rule's entire configuration, you don't need to route it through match_body.  https://github.com/Yelp/elastalert/blob/master/elastalert/enhancements.py#L10

```
class MyEnhancement(BaseEnhancement):
    def process(self, match):
        something = self.rule['some_enhancement_setting']
         ....
```
