### ISSUE TITLE
spike reference_count compute is incorrect

### ISSUE THREAD

**Issue by meishd** [Yelp/elastalert#2217]
**version**: 0.1.38

**my rule config:**
name: elk-spike-a
type: spike
spike_height: 5
spike_type: up
threshold_ref: 1800
timeframe:
  minutes: 3
use_terms_query: true
doc_type: doc
terms_size: 10
query_key: domain
realert:
  minutes: 60

**my email alert:**
elk-spike-a
An abnormal number (16178) of events occurred around 2019-04-19 23:03 CST.
Preceding that time, there were only 2989 events within 0:03:00
timestamp: 2019-04-19T15:03:14.461692Z
domain: my_domian_name
num_hits: 10
num_matches: 1
reference_count: 2989
spike_count: 16178

spike_count is correct, sum of 3 mins;
but reference_count is incorrect, just about 1 mins 

the pic from ELK:
![image](https://user-images.githubusercontent.com/13401014/56481736-1265c200-64f3-11e9-8cac-37bd248bb81b.png)

**Comment by Qmando** [comment]
What is your `run_every` setting?

**Comment by meishd** [comment]
tks

> Two possibilities:
> 
> 1. Try adding
> 
> ```
> query_delay:
>   minutes: 2
> ```
> 
> Sometimes elastalert queries too close to the current time and elasticsearch doesn't return the right number. By adding a slight delay, you can ensure that Elasticsearch has fully indexed everything.
> 
> 1. What is your `run_every` setting? If it's too high, you can get weird issues where the time resolution elastalert sees is very poor and the counts it reports are inaccurate. Try setting it to something like 30 second. This only affects `use_terms_query` and `use_count_query`

tks

**Comment by meishd** [comment]
i have set query_delay to 2 mins, and run_every to 1 mins, but it not work too.

**Comment by meishd** [comment]
I have found the reason,  terms_size: 10 is too small;
when terms_size is small than domians in elk, because elastalert''s algorithm, the domain around terms_size maybe in the case.
I set terms_size: 200 (greate than domains in elk), then is work fine.
thanks all !
