### ISSUE TITLE
Elasticsearch version 7.0

### ISSUE THREAD

**Issue by br14nb0** [Yelp/elastalert#2219]
Hi guys,

When do we update Elastalert for ELK 7.0?

**Comment by lxkaka** [comment]
I want to pull request

**Comment by moetemad** [comment]
Issue #2202 has already a PR pending.

**Comment by lxkaka** [comment]
pretty cool. I have tested this PR.

**Comment by Qmando** [comment]
https://github.com/Yelp/elastalert/issues/2202#issuecomment-488493624

Please open issues if you find any.
