### ISSUE TITLE
when I execute elastalert-test-rule

### ISSUE THREAD

**Issue by Chin-sai** [Yelp/elastalert#2221]
Hi,I'm a begginer of elasitcalert.I have a question.
When I execute elastalert-test-rule, I got error messages like these,
---------------------------------------------------------------------------------------------------
 WARNING:elasticsearch:GET http://127.0.0.1:9200/alert/_search?_source_include=%40timestamp%2C%2A%2CRESULT&ignore_unavailable=true&scroll=30s&size=10000 [status:400 request:0.009s]
ERROR:root:Error running query: RequestError(400, u'illegal_argument_exception', u'request [/alert/_search] contains unrecognized parameter: [_source_include] -> did you mean any of [_source_includes, _source_excludes]?')

Would have written the following documents to writeback index (default is elastalert_status):

elastalert_error - {'message': "Error running query: RequestError(400, u'illegal_argument_exception', u'request [/alert/_search] contains unrecognized parameter: [_source_include] -> did you mean any of [_source_includes, _source_excludes]?')", 'traceback': ['Traceback (most recent call last):', '  File "/usr/local/lib/python2.7/dist-packages/elastalert-0.1.39-py2.7.egg/elastalert/elastalert.py", line 376, in get_hits', '    **extra_args', '  File "/usr/local/lib/python2.7/dist-packages/elasticsearch-7.0.0-py2.7.egg/elasticsearch/client/utils.py", line 84, in _wrapped', '    return func(*args, params=params, **kwargs)', '  File "/usr/local/lib/python2.7/dist-packages/elasticsearch-7.0.0-py2.7.egg/elasticsearch/client/__init__.py", line 811, in search', '    "GET", _make_path(index, "_search"), params=params, body=body', '  File "/usr/local/lib/python2.7/dist-packages/elasticsearch-7.0.0-py2.7.egg/elasticsearch/transport.py", line 318, in perform_request', '    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)', '  File "/usr/local/lib/python2.7/dist-packages/elasticsearch-7.0.0-py2.7.egg/elasticsearch/connection/http_requests.py", line 91, in perform_request', '    self._raise_error(response.status_code, raw_data)', '  File "/usr/local/lib/python2.7/dist-packages/elasticsearch-7.0.0-py2.7.egg/elasticsearch/connection/base.py", line 131, in _raise_error', '    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)', "RequestError: RequestError(400, u'illegal_argument_exception', u'request [/alert/_search] contains unrecognized parameter: [_source_include] -> did you mean any of [_source_includes, _source_excludes]?')"], 'data': {'query': {'sort': [{'@timestamp': {'order': 'asc'}}], 'query': {'bool': {'filter': {'bool': {'must': [{'range': {'@timestamp': {'gt': '2019-04-21T01:44:52.691495Z', 'lte': '2019-04-21T01:59:52.691495Z'}}}, {'term': {'RESULT': '1'}}]}}}}}, 'rule': 'Example frequency rule'}}
-------------------------------------------------------------------------------------------------

In elasticsearch, Datas are like this,
------------------------------------------------------------------------------------------------
        "_index" : "alert",
        "_type" : "_doc",
        "_id" : "2019/04/03 13-947",
        "_score" : 1.0,
        "_source" : {
          "@timestamp" : "2019-04-03T04:04:34.590Z",
          "CMD_ID" : 947,
          "tags" : [
            "multiline"
          ],
          "host" : "aaa",
          "aaa_time_result" : "2019/04/03 13:04:34.590",
          "RESULT" : 1,
          "RESULT_Detail" : "Wed Apr  3 13:04:34 JST 2019",
          "path" : "/home/hoge/ELK/logstash-7.0.0/bin/aaa.log",
          "ems_time_id_result" : "2019/04/03 13",
          "message" : "[2019/04/03 13:04:34.590] CMD_ID=947 RESULT=0\nWed Apr  3 13:04:34 JST 2019",
          "@version" : "1"
-------------------------------------------------------------------------------------------------

and, I set yaml file like this

-------------------------------------------------------------------------------------------------
type: frequency
index: alert
num_events: 2
timeframe:
  hours: 0.5
query_key: RESULT
filter:
- term:
    RESULT: "1"
alert:
- "command"
command: ["/bin/date"]
-------------------------------------------------------------------------------------------------
 
Which part should i correct? The format of "@timestamp" is not good?

**Comment by pdscopes** [comment]
What version of ElasticSearch are you running this against?

Also, please can you format your comment to make it easy to read? You should use triple backticks to quote code/yaml/log messages, e.g.:
````
```
type: frequency
index: alert
num_events: 2
timeframe:
  hours: 0.5
query_key: RESULT
filter:
  - term:
      RESULT: "1"
alert: "command"
command: ["/bin/date"]
```
````

**Comment by tsunesai** [comment]
Thank you for your replay and I'm sorry that my comment was hard to read,I am a begginer at github.
I  use Elasticserch ver.7.0.0 . 
Is it not good to use ver7.0.0 when I use elastalert?

**Comment by matsgoran** [comment]
The current versjon of ElastAlert doesn't work with ElasticSearch 7. I have a PR,   https://github.com/Yelp/elastalert/pull/2194 , trying to resolve this issue

**Comment by matsgoran** [comment]
https://github.com/Yelp/elastalert/issues/2202

**Comment by Chin-sai** [comment]
Thank you for your reply.
I installed ElasticSearch ver6.7 and"elastalert-test-rule"  worked ! 
Thank you!!
