### ISSUE TITLE
python elastalert/elastalert.py --config config.yaml

### ISSUE THREAD

**Issue by TheButterflyOdor** [Yelp/elastalert#2222]
(py27) tmshz0213l:elastalert ycz$ python elastalert/elastalert.py --config config.yaml
/Users/ycz/ELK1/elastalert/elastalert/config.py:31: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  rule_schema = jsonschema.Draft4Validator(yaml.load(open(os.path.join(os.path.dirname(__file__), 'schema.yaml'))))
Traceback (most recent call last):
  File "elastalert/elastalert.py", line 1929, in <module>
    sys.exit(main(sys.argv[1:]))
  File "elastalert/elastalert.py", line 1925, in main
    client.start()
  File "elastalert/elastalert.py", line 1106, in start
    self.run_all_rules()
  File "elastalert/elastalert.py", line 1158, in run_all_rules
    self.send_pending_alerts()
  File "elastalert/elastalert.py", line 1534, in send_pending_alerts
    pending_alerts = self.find_recent_pending_alerts(self.alert_time_limit)
  File "elastalert/elastalert.py", line 1526, in find_recent_pending_alerts
    size=1000)
  File "build/bdist.macosx-10.7-x86_64/egg/elasticsearch/client/utils.py", line 84, in _wrapped
TypeError: search() got an unexpected keyword argument 'doc_type'

**Comment by pdscopes** [comment]
What version of ElasticSearch are you using?

**Comment by TheButterflyOdor** [comment]
version :  Elasticsearch == 6.2.4

**Comment by pdscopes** [comment]
And which version of `elasticsearch` client have you installed for ElastAlert to run? They have [recently released](https://pypi.org/project/elasticsearch/#history) version 7 and I'm not sure that it is compatible with ElasticSearch 6.x.y (`doc_type` was deprecated/removed in version 7).

**Comment by TheButterflyOdor** [comment]
> And which version of `elasticsearch` client have you installed for ElastAlert to run? They have [recently released](https://pypi.org/project/elasticsearch/#history) version 7 and I'm not sure that it is compatible with ElasticSearch 6.x.y (`doc_type` was deprecated/removed in version 7).

**Comment by TheButterflyOdor** [comment]
> And which version of `elasticsearch` client have you installed for ElastAlert to run? They have [recently released](https://pypi.org/project/elasticsearch/#history) version 7 and I'm not sure that it is compatible with ElasticSearch 6.x.y (`doc_type` was deprecated/removed in version 7).

Thank you !
