### ISSUE TITLE
Regular expressions question. 

### ISSUE THREAD

**Issue by zebra48r** [Yelp/elastalert#2238]
Hello. I would like to find out if I can use regular expressions in this way?

> filter:
>- query:
>       query_string:
>         query: "email:\"[A-Za-z]{10,}[0-9]{3}[a-z]+@+[a-zA-Z0-9]\" AND email:\"[0-9]{11,}[a-z]{1,}+@[a-zA-Z]+\""

At the moment it does not work, does not find anything.
But in Kibana, it works and looks like this.
`{
  "query": {
    "bool": {
      "should": [
        {
          "regexp": {
            "email": {
              "value": "[A-Za-z]{10,}[0-9]{3}[a-z]+@+[a-zA-Z0-9]"
            }
          }
        },
        {
          "regexp": {
            "email": {
              "value": "[0-9]{11,}[a-z]{1,}+@[a-zA-Z]+"
            }
          }
        }
      ]
    }
  }
}`

**Comment by yj7778826** [comment]
replace query_string with regexp

**Comment by Qmando** [comment]
You even CAN do it with query_strings
https://www.elastic.co/guide/en/elasticsearch/reference/6.3/query-dsl-query-string-query.html#_regular_expressions
