### ISSUE TITLE
pipe_match_json does not seem to send json match to script

### ISSUE THREAD

**Issue by ThomasdOtreppe** [Yelp/elastalert#225]
Using the following in a rules:
```
pipe_match_json: true
command: ["/etc/elastalert/script.sh"]
```

Here is my simple script:
```
#!/bin/bash

echo "New alert at $(date)" >> /var/log/elastalert.log

while read -r line; do
        echo "${line}" >> /var/log/elastalert.log
done < /dev/stdin
```

does not seem to pass anything to the stdin of the script. I can see an entry from the first 'echo' command but no JSON.

I try to run the script with the following command
```
echo -e 'blah\nand\nblah' | ./script.sh
```

And I confirm it logs stdin.

**Comment by Qmando** [comment]
Ah, I've tested it with the script
```
read -r line
echo "${line}" >> test.txt
```
and it seems to work. But because it doesn't output a newline, it doesn't work with that version. I will add the newline to the end out of the output.
