### ISSUE TITLE
Reusing the JIRA issue and updating the Risk status 

### ISSUE THREAD

**Issue by nikhilgangrade** [Yelp/elastalert#2255]
I am able to create an JIRA issue, but i am supposed to use the same JIRA issue and change the Risk status from green to red or red to green.
Its connected with Metricbeat and if the system.memory.used.pct is above 80% it notifies me using email and create a jira issue.

But i have no clue how can i use the same JIRA issue and work on it.
@Qmando can you help me with this?

**Comment by nikhilgangrade** [comment]
I can use the same jira issue using `jira_bump_tickets`, but how can i use the risk status.
Do i need to create a custom field for that and use `jira_transition_to`.

@Qmando it would be great if you can help me.

**Comment by Qmando** [comment]
You can only update the `status` (Open, Closed, In Progress) of a ticket with ElastAlert right now. You can't update custom fields. If you want that, you'd need to modify the code or write a custom enhancement.
