### ISSUE TITLE
Way to make Elastalert not retry HTTP POST alerts?

### ISSUE THREAD

**Issue by weskerfoot** [Yelp/elastalert#2256]
Hi, according to the documentation

> http_post_timeout: The timeout value, in seconds, for making the post. The default is 10. If a timeout occurs, the alert will be retried next time elastalert cycles.

Is there a way to *disable* this behaviour? I do not want Elastalert to keep retrying if it fails.

**Comment by Qmando** [comment]
You want to set `alert_time_limit` to a really small time.

```
alert_time_limit:
  minutes: 0
```

I believe that should prevent all alert retries. It defaults to 24 hours.

**Comment by weskerfoot** [comment]
Thank you for the answer!
