### ISSUE TITLE
Couldn't verify TLS certificate

### ISSUE THREAD

**Issue by webhead404** [Yelp/elastalert#2275]
I am attempting to connect to an ES cluster over TLS from and the connection fails because the TLS certificate can not be verified. I have placed them where they can be reached by Elastalert and altered the configuration per the documentation. Seems to be the Python requests module isn't aware of these certificates? How do I tackle this issue?

**Comment by abhishekjiitr** [comment]
Can you post your ElastAlert config and the relevant logs indicating the connection failure?

**Comment by webhead404** [comment]
**elastalert.yaml**

`# The elasticsearch hostname for metadata writeback
# Note that every rule can have its own elasticsearch host
es_host: x.x.x.x

# The elasticsearch port
es_port: 9200

# This is the folder that contains the rule yaml files
# Any .yaml file will be loaded as a rule
rules_folder: rules

# How often ElastAlert will query elasticsearch
# The unit can be anything from weeks to seconds
run_every:
  seconds: 5

# ElastAlert will buffer results from the most recent
# period of time, in case some log sources are not in real time
buffer_time:
  minutes: 1

# Optional URL prefix for elasticsearch
#es_url_prefix: elasticsearch

# Connect with TLS to elasticsearch
use_ssl: True

# Verify TLS certificates
verify_certs: True

# CA bundle
#ca_certs: /opt/elastalert/ca/ca.crt

client_cert: /opt/elastalert/instance/instance.pem
client_key:  /opt/elastalert/instance/instance.key

# GET request with body is the default option for Elasticsearch.
# If it fails for some reason, you can pass 'GET', 'POST' or 'source'.
# See http://elasticsearch-py.readthedocs.io/en/master/connection.html?highlight=send_get_body_as#transport
# for details
#es_send_get_body_as: GET

# Option basic-auth username and password for elasticsearch
es_username: ********
es_password: ********

# The index on es_host which is used for metadata storage
# This can be a unmapped index, but it is recommended that you run
# elastalert-create-index to set a mapping
writeback_index: elastalert_status

# If an alert fails for some reason, ElastAlert will retry
# sending the alert until this time period has elapsed
alert_time_limit:
  days: 2
`
**in the Docker log for the container**

`File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
        "__main__", fname, loader, pkg_name)
      File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
        exec code in run_globals
      File "/opt/elastalert/elastalert/create_index.py", line 275, in <module>
        main()
      File "/opt/elastalert/elastalert/create_index.py", line 127, in main
        esversion = es.info()["version"]["number"]
      File "/usr/lib/python2.7/site-packages/elasticsearch-7.0.1-py2.7.egg/elasticsearch/client/utils.py", line 84, in _wrapped
        return func(*args, params=params, **kwargs)
      File "/usr/lib/python2.7/site-packages/elasticsearch-7.0.1-py2.7.egg/elasticsearch/client/__init__.py", line 259, in info
        return self.transport.perform_request("GET", "/", params=params)
      File "/usr/lib/python2.7/site-packages/elasticsearch-7.0.1-py2.7.egg/elasticsearch/transport.py", line 353, in perform_request
        timeout=timeout,
      File "/usr/lib/python2.7/site-packages/elasticsearch-7.0.1-py2.7.egg/elasticsearch/connection/http_requests.py", line 127, in perform_request
        raise ConnectionError("N/A", str(e), e)
    elasticsearch.exceptions.ConnectionError: ConnectionError(Could not find the TLS certificate file, invalid path: /opt/elastalert/instance/instance.pem) caused by: IOError(Could not find the TLS certificate file, invalid path: /opt/elastalert/instance/instance.pem)`

**Comment by Qmando** [comment]
The code is literally
```
if not cert_loc or not os.path.exists(cert_loc):
                raise IOError("Could not find a suitable TLS CA certificate bundle, "
                              "invalid path: {}".format(cert_loc))
```

Make sure the file is actually there.

**Comment by webhead404** [comment]
I should clarify. I have tried this with both ca cert and client cert/keys. Same log every time. They are in their correct location.

**Comment by abhishekjiitr** [comment]
Are you sure the files are there in the container itself in which ElastAlert is running? It wouldn't work if ElastAlert is running in a container & the certs are only on the host system.

**Comment by webhead404** [comment]
I believe that the volume mounts are incorrect. Thank you!
