### ISSUE TITLE
Automate the elastalert

### ISSUE THREAD

**Issue by nikhilgangrade** [Yelp/elastalert#2284]
@Qmando is there a way to automate the elastalert.
While running the yaml files in the command prompt the rule get disabled and go for sleep(10 sec defined on config.yaml).
Can we auto restart the elastalert or do i need to write an enchancement for that?

**Comment by Qmando** [comment]
You want it to continuously query and never sleep, even for 10 seconds?

**Comment by nikhilgangrade** [comment]
No, it should sleep but if `An uncaught exception occurred ...` and rule get disabled it should restart again.

**Comment by Qmando** [comment]
https://elastalert.readthedocs.io/en/latest/elastalert.html?highlight=disable_rules_on_error#configuration

```
disable_rules_on_error: If true, ElastAlert will disable rules which throw uncaught (not EAException) exceptions. It will upload a traceback message to elastalert_metadata and if notify_email is set, send an email notification. The rule will no longer be run until either ElastAlert restarts or the rule file has been modified. This defaults to True.
```
