### ISSUE TITLE
Iso Timestamp Type Truncating Milliseconds

### ISSUE THREAD

**Issue by JeffAshton** [Yelp/elastalert#2305]
It appears that the milliseconds are getting truncated for `timestamp_type: "iso"`.  This results in a bad request when the corresponding elasticsearch template uses the `strict_date_time` format for the date type.

The majority of the time this is obviously not an issue, but on rare occasions I'm seeing the following errors:

**Example 1:**

```
{
  "range": {
    "time": {
      "gt": "2019-06-20T13:34:48.688727Z",
      "lte": "2019-06-20T13:34:49Z"
    }
  }
}
```

Error running count query: RequestError(400, u'search_phase_execution_exception', u'failed to parse date field [2019-06-20T13:34:49Z] with format [strict_date_time]')

**Example 2:**

```
{
  "range": {
    "time": {
      "gt": "2019-06-19T12:41:59.981281Z",
      "lte": "2019-06-19T12:42:00Z"
    }
  }
}
```

Error running count query: RequestError(400, u'search_phase_execution_exception', u'failed to parse date field [2019-06-19T12:42:00Z] with format [strict_date_time]')

**Example 3:**

```
{
  "range": {
    "time": {
      "gt": "2019-06-19T02:00:48.783662Z",
      "lte": "2019-06-19T02:00:49Z"
    }
  }
}
```

Error running count query: RequestError(400, u'search_phase_execution_exception', u'failed to parse date field [2019-06-19T02:00:49Z] with format [strict_date_time]')

**Comment by JeffAshton** [comment]
The issue lies here:

https://github.com/Yelp/elastalert/blob/09a3eb609972e6cfec1461ea28de1568a0528734/elastalert/util.py#L141

And how `isoformat` behaves.   From https://docs.python.org/2/library/datetime.html#datetime.datetime.isoformat):

Return a string representing the date and time in ISO 8601 format, YYYY-MM-DDTHH:MM:SS.mmmmmm or, if microsecond is 0, YYYY-MM-DDTHH:MM:SS

**Comment by JeffAshton** [comment]
Hmm, actually it looks like the milliseconds are being truncated here:

https://github.com/Yelp/elastalert/blob/09a3eb609972e6cfec1461ea28de1568a0528734/elastalert/util.py#L148

**Comment by Qmando** [comment]
Hm, it's been too long since I wrote that, I can't remember if there was a practical purpose or not. I know that we've never used `strict_date_time` which is why it was ignored.

Could you try removing that first replace call and see if everything still functions fine? If there isn't any issues, I'd consider removing it.

**Comment by JeffAshton** [comment]
Found a decent workaround
