### ISSUE TITLE
TypeError: search() got an unexpected keyword argument 'doc_type'

### ISSUE THREAD

**Issue by lianfulei** [Yelp/elastalert#2314]
script:
python -m elastalert.elastalert --verbose --rule example_rules/example_frequency.yaml

have ERROR
TypeError: search() got an unexpected keyword argument 'doc_type'

**Comment by lianfulei** [comment]
i have solve

**Comment by mali30** [comment]
I just ran into this issue can you please show steps to resolve @laucia

**Comment by Qmando** [comment]
You probably have the wrong version of the elasticsearch python library. Make sure it's major version matches the version of Elasticsarch the server is running.

For example
```
pip install "elasticsearch<7,>6"
```
