### ISSUE TITLE
Time Format not accepted

### ISSUE THREAD

**Issue by fraser-m** [Yelp/elastalert#233]
Hi,

Not sure if this is a bug, or if i'm going wrong myself here- but this issue is starting to get at me a bit!

I have installed elastalerton our elasticsearch cluster without issue, and have created a rule to query through our log for errors.  Running elastalert-test-rule will find a number of matches and doesn't find any errors, so when i go to run the elastalert.py app, i am getting an error i'm trying to work out.

Traceback (most recent call last):
  File "elastalert.py", line 1241, in <module>
    client = ElastAlerter(sys.argv[1:])
  File "elastalert.py", line 81, in __init__
    self.conf = load_rules(self.args)
  File "/elastalert/config.py", line 314, in load_rules
    raise EAException('Invalid time format used: %s' % (e))
util.EAException: Invalid time format used: type object argument after ** must be a mapping, not NoneType

In the rule i have tested i have inserted a timestamp type and mapping to ensure i get an accurate hit- this seems ok.

Any ideas here?

Thanks

**Comment by Qmando** [comment]
Do you have ``buffer_time`` or ``run_every`` in config.yaml? These are required and must be a format like
```
buffer_time:
  hours: 1
run_every:
  minutes: 5
```

**Comment by fraser-m** [comment]
Hi,

Thanks for your prompt help and assistance .It looks like the issue was the formatting within the config.yaml file.  This has been sorted and it seems to be ok.  I'll close off the issue now.

Thanks for your help!
