### ISSUE TITLE
stable/elastalert 0.1.39 with elastic 7.2

### ISSUE THREAD

**Issue by geede** [Yelp/elastalert#2382]
Hello, we have installed 'stable/elastalert 0.1.39', but that version apparently wont work with our 7.2 elasticsearch, as it has outdated python libs. The stable version only seems to support ES 6.x. How do we get a stable/elastalert working with our 7.2 elasticsearch?

**Comment by abhishekjiitr** [comment]
If you're using Elasticsearch 7, you'll need to install a beta release of Elastalert: 
```pip install "elastalert>=0.2.0b"```
