### ISSUE TITLE
New ruletype problem

### ISSUE THREAD

**Issue by DanielHuZM** [Yelp/elastalert#2383]
Hi, @Qmando 
I am trying adding a new ruletype just as the ElastAlert Documentation.
However, it failed.
`elastalert.util.EAException: Invalid Rule file: example_rules/login_rule.yaml
{'es_port': 9200, 'usernames': ['admin', 'dogs'], 'time_start': '08:00', 'name': 'Example login rule', 'index': 'test-*', 'time_end': '24:00', 'alert': ['debug'], 'rule_file': 'example_rules/login_rule.yaml', 'include': ['username'], 'type': 'awe', 'es_host': 'localhost'} is not valid under any of the given schemas
`

In ruletypes.py, add
`class AwesomeRule(RuleType):
    required_options = set(['time_start', 'time_end', 'usernames'])

    def add_data(self, data):
        for document in data:
            if document['username'] in self.rules['usernames']:
                login_time = document['@timestamp'].time()
                # Convert time_start and time_end to time objects
                time_start = dateutil.parser.parse(self.rules['time_start']).time()
                time_end = dateutil.parser.parse(self.rules['time_end']).time()
                # If the time falls between start and end
                if login_time > time_start and login_time < time_end:
                    self.add_match(document)

    def get_match_str(self, match):
        return "%s logged in between %s and %s" % (match['username'], self.rules['time_start'], self.rules['time_end'])

    def garbage_collect(self, timestamp):
        pass`

In config.py,add
`rules_mapping = {
    'frequency': ruletypes.FrequencyRule,
    'any': ruletypes.AnyRule,
    'spike': ruletypes.SpikeRule,
    'blacklist': ruletypes.BlacklistRule,
    'whitelist': ruletypes.WhitelistRule,
    'change': ruletypes.ChangeRule,
    'flatline': ruletypes.FlatlineRule,
    'new_term': ruletypes.NewTermsRule,
    'cardinality': ruletypes.CardinalityRule,
    'metric_aggregation': ruletypes.MetricAggregationRule,
    'percentage_match': ruletypes.PercentageMatchRule,
    'spike_aggregation': ruletypes.SpikeMetricAggregationRule,
    'awe': ruletypes.AwesomeRule
}`

In my_rule.yaml,add
`name: "Example login rule"
es_host: localhost
es_port: 9200
type: awe
index: test-*
time_start: "08:00"
time_end: "24:00"
usernames:
- "cat"
- "dog"
include:
- "username"
alert:
- debug`

**Comment by Qmando** [comment]
You need to update https://github.com/Yelp/elastalert/blob/master/elastalert/schema.yaml

**Comment by DanielHuZM** [comment]
OKkkkkkkk.....Thank you very much. It works.
