### ISSUE TITLE
example_frequency.yaml unable to test 

### ISSUE THREAD

**Issue by prabhur24** [Yelp/elastalert#2390]
Traceback (most recent call last):
  File "/usr/local/bin/elastalert-test-rule", line 6, in <module>
    from elastalert.test_rule import main
  File "/usr/local/lib/python2.7/site-packages/elastalert/test_rule.py", line 61
    print('Invalid filter provided:', str(ea), file=sys.stderr)
                                                   ^
SyntaxError: invalid syntax

Below is Example Frequency File .
es_host: 127.0.0.1
es_port: 9200
name: Example frequency rule
type: frequency
index: kibana_sample_data_flights-*
num_events: 5
timeframe:
  hours: 1
filter:
- term:
    some_field: "Carrier"
alert:
- "email"
email:
- "rajendranprabhu.r@gmail.com"

**Python Version is 2.7** 

While downloading pip install elastalert facing error .

**removing '/usr/local/lib/python2.7/site-packages/elastalert-0.2.1-py2.7.egg' (and everything under it)
creating /usr/local/lib/python2.7/site-packages/elastalert-0.2.1-py2.7.egg
Extracting elastalert-0.2.1-py2.7.egg to /usr/local/lib/python2.7/site-packages
  File "/usr/local/lib/python2.7/site-packages/elastalert-0.2.1-py2.7.egg/elastalert/test_rule.py", line 61
    print('Invalid filter provided:', str(ea), file=sys.stderr)
                                                   ^
SyntaxError: invalid syntax**

Thanks in advance.
But i tried to resolve , not getting any idea why this happening.

**Comment by arymarta** [comment]
I also have this problem and still not fix yet. need help.

**Comment by DanielHuZM** [comment]
Use Python 3 Please. Version 0.2.1 has not supported Python 2.

**Comment by arymarta** [comment]
> Use Python 3 Please. Version 0.2.1 has not supported Python 2.

Thanks, i have tried python 3 and its worked now.

**Comment by prabhur24** [comment]
Thanks it worked for me too :)

**Comment by prabhur24** [comment]
@arymarta can you please tell me python3 which version you are using!

**Comment by allen-olivas** [comment]
hello, I'm getting this error. and see I have python 2.7 and python 3.6. I'm pretty noob with this so what does it mean to use python 3? How do i use that?

**Comment by Qmando** [comment]
Try running `pip3 install elastalert`
Alternatively, clone elastalert and run `python3 setup.py install`

Once you've done that, you should be able to run elastalert either by typing `elastalert --verbose --config /path/to/config.yaml` or `python3 -m elastalert.elastalert --verbose --config /path/to/config.yaml`

**Comment by arymarta** [comment]
> @arymarta can you please tell me python3 which version you are using!

i use python 3.6
