### ISSUE TITLE
ElastAlert not working after elasticsearch upgrade to 6.8

### ISSUE THREAD

**Issue by jayan800** [Yelp/elastalert#2412]
ElastAlert stopped working after the upgrade of Elasticsearch.
Elastisearch version used is : elasticsearch-6.8.2

I even upgraded the elastalert to new version, still it is not working
pip show elastalert
Name: elastalert
Version: 0.2.1

Python version : 
 python -V
Python 3.6.8

Also the elastalert index name changed to elastalert_status_status. In the older version it was elastalert_status

green open elastalert_status_silence 2CuKVwZyR3ObCjrpn8xB6A 5 1        0   0   2.5kb   1.2kb
green open elastalert_status_error   e7iJbT9_QjWhmsWveEBB9Q 5 1        0   0   2.5kb   1.2kb
green open elastalert_status_past    BdYuMq6ZRxOOQdX_jsal-Q 5 1        0   0   2.5kb   1.2kb
green open elastalert_status         wHwvcmRDRIC2K9lnJAg5Pw 5 1        0   0   2.5kb   1.2kb
green open elastalert_status_status  Q6dhNvsqSKCQ2SE6mM85sg 5 1       10   0  80.7kb  40.3kb

I even tried recreating the index but no luck. Can any one please help on this

**Comment by jayan800** [comment]
When running the rule in debug mode I get the below output.

INFO:elastalert:Note: In debug mode, alerts will be logged to console but NOT actually sent.
                To send them but remain verbose, use --verbose instead.
INFO:elastalert:Note: In debug mode, alerts will be logged to console but NOT actually sent.
            To send them but remain verbose, use --verbose instead.
1 rules loaded
INFO:elastalert:Starting up
INFO:elastalert:Disabled rules are: []
INFO:elastalert:Sleeping for 119.999921 seconds
WARNING:elasticsearch:GET http://localhost:9200/elastalert_status_status/_search?_source_includes=endtime%2Crule_name&size=1 [status:404 request:0.010s]
ERROR:root:Error querying for last run: NotFoundError(404, 'index_not_found_exception', 'no such index', elastalert_status_status, index_or_alias)
INFO:elastalert:Skipping writing to ES: {'message': "Error querying for last run: NotFoundError(404, 'index_not_found_exception', 'no such index', elastalert_status_status, index_or_alias)", 'traceback': ['Traceback (most recent call last):', '  File "/opt/elastalert/elastalert/elastalert.py", line 686, in get_starttime', "    _source_includes=['endtime', 'rule_name'])", '  File "/usr/lib/python3.6/site-packages/elasticsearch-7.0.2-py3.6.egg/elasticsearch/client/utils.py", line 84, in _wrapped', '    return func(*args, params=params, **kwargs)', '  File "/usr/lib/python3.6/site-packages/elasticsearch-7.0.2-py3.6.egg/elasticsearch/client/__init__.py", line 819, in search', '    "GET", _make_path(index, "_search"), params=params, body=body', '  File "/usr/lib/python3.6/site-packages/elasticsearch-7.0.2-py3.6.egg/elasticsearch/transport.py", line 353, in perform_request', '    timeout=timeout,', '  File "/usr/lib/python3.6/site-packages/elasticsearch-7.0.2-py3.6.egg/elasticsearch/connection/http_requests.py", line 155, in perform_request', '    self._raise_error(response.status_code, raw_data)', '  File "/usr/lib/python3.6/site-packages/elasticsearch-7.0.2-py3.6.egg/elasticsearch/connection/base.py", line 178, in _raise_error', '    status_code, error_message, additional_info', "elasticsearch.exceptions.NotFoundError: NotFoundError(404, 'index_not_found_exception', 'no such index', elastalert_status_status, index_or_alias)"], 'data': {'rule': 'Table SEPM OS attack alert Inbound traffic'}}
INFO:elastalert:Queried rule Table Test traffic from 2019-08-21 03:38 UTC to 2019-08-21 03:40 UTC: 0 / 0 hits
WARNING:elasticsearch:DELETE http://localhost:9200/_search/scroll [status:404 request:0.004s]
INFO:elastalert:Skipping writing to ES: {'rule_name': 'Table Test traffic', 'endtime': '2019-08-21T03:40:23.031579Z', 'starttime': '2019-08-21T03:38:53.031579Z', 'matches': 0, 'hits': 0, '@timestamp': '2019-08-21T03:40:23.079554Z', 'time_taken': 0.047934770584106445}
INFO:elastalert:Ran Table Test traffic from 2019-08-21 03:38 UTC to 2019-08-21 03:40 UTC: 0 query hits (0 already seen), 0 matches, 0 alerts sent

And no alerts are generated.  Please help on this

**Comment by jayan800** [comment]
The above error fixed by recreating the index. But still we are not getting any alerts.

[root@ladcsealert01 elastalert]# python -m elastalert.elastalert --verbose --rule  /opt/elastalert/Rule_folder/port_scan.yaml
1 rules loaded
INFO:elastalert:Starting up
INFO:elastalert:Disabled rules are: []
INFO:elastalert:Sleeping for 119.999923 seconds
INFO:elastalert:Queried rule Port Scan detection use case from 2019-08-21 08:01 UTC to 2019-08-21 08:02 UTC: 0 / 0 hits
WARNING:elasticsearch:DELETE http://localhost:9200/_search/scroll [status:404 request:0.004s]
INFO:elastalert:Ran Port Scan detection use case from 2019-08-21 08:01 UTC to 2019-08-21 08:02 UTC: 0 query hits (0 already seen), 0 matches, 0 alerts sent
INFO:elastalert:Background configuration change check run at 2019-08-21 08:04 UTC
INFO:elastalert:Background alerts thread 0 pending alerts sent at 2019-08-21 08:04 UTC
INFO:elastalert:Disabled rules are: []
INFO:elastalert:Sleeping for 119.999681 seconds
INFO:elastalert:Queried rule Port Scan detection use case from 2019-08-21 08:02 UTC to 2019-08-21 08:04 UTC: 0 / 0 hits
WARNING:elasticsearch:DELETE http://localhost:9200/_search/scroll [status:404 request:0.004s]
INFO:elastalert:Queried rule Port Scan detection use case from 2019-08-21 08:04 UTC to 2019-08-21 08:04 UTC: 0 / 0 hits
WARNING:elasticsearch:DELETE http://localhost:9200/_search/scroll [status:404 request:0.003s]
INFO:elastalert:Ran Port Scan detection use case from 2019-08-21 08:02 UTC to 2019-08-21 08:04 UTC: 0 query hits (0 already seen), 0 matches, 0 alerts sent
INFO:elastalert:Background configuration change check run at 2019-08-21 08:06 UTC
INFO:elastalert:Background alerts thread 0 pending alerts sent at 2019-08-21 08:06 UTC
INFO:elastalert:Disabled rules are: []

Blow is the elastlalert mapping info:
 curl http://localhost:9200/elastalert*/_mapping
{"elastalert_status":{"mappings":{"_doc":{"properties":{"@timestamp":{"type":"date","format":"dateOptionalTime"},"endtime":{"type":"date"},"hits":{"type":"long"},"matches":{"type":"long"},"rule_name":{"type":"keyword"},"starttime":{"type":"date"},"time_taken":{"type":"float"}}}}},"elastalert":{"mappings":{"_doc":{"dynamic_templates":[{"strings_as_keyword":{"match_mapping_type":"string","mapping":{"ignore_above":1024,"type":"keyword"}}}],"date_detection":false,"numeric_detection":true,"properties":{"@timestamp":{"type":"date","format":"dateOptionalTime"},"aggregate_id":{"type":"keyword"},"alert_time":{"type":"date","format":"dateOptionalTime"},"match_body":{"type":"object"},"match_time":{"type":"date","format":"dateOptionalTime"},"rule_name":{"type":"keyword"}}}}},"elastalert_past":{"mappings":{"_doc":{"properties":{"@timestamp":{"type":"date","format":"dateOptionalTime"},"aggregate_id":{"type":"keyword"},"match_body":{"type":"object","enabled":false},"rule_name":{"type":"keyword"}}}}},"elastalert_error":{"mappings":{"_doc":{"properties":{"@timestamp":{"type":"date","format":"dateOptionalTime"},"data":{"type":"object","enabled":false},"message":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"traceback":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}}}}}},"elastalert_silence":{"mappings":{"_doc":{"properties":{"@timestamp":{"type":"date","format":"dateOptionalTime"},"rule_name":{"type":"keyword"},"until":{"type":"date","format":"dateOptionalTime"}}}}}}

**Comment by jayan800** [comment]
Can some one please help on this

**Comment by abhishekjiitr** [comment]
The latest version of ElastAlert 0.2.X will not work for Elasticsearch v6.X. For Elasticsearch v6.X, you can try ElastAlert 0.1.39

**Comment by jayan800** [comment]
@abhishekjiitr Thanka a lot. I check and let you know the update

**Comment by vsabelli** [comment]
@jayan800 there is a fork of this project on https://github.com/vsabelli/elastalert.

It aims to keep Python2 compatibility but getting the enhancements/features/bug-fixes of the original project. It currently works for ES6.8 (the version we are using in our company).

Have a look if you are interested!

**Comment by Qmando** [comment]
Elastalert 0.2.x DOES work with ALL versions of Elasticsearch.

**Comment by jayan800** [comment]
Thank you all. The issue has been resolved by changing the max_query value.

**Comment by anust** [comment]
@jayan800 please tell me where to set the max_query value, as I am getting the same error
