### ISSUE TITLE
Got TypeError: a bytes-like object is required, not 'str' when using command alert with pipe_match_json: true

### ISSUE THREAD

**Issue by Rushera** [Yelp/elastalert#2413]
I'm using version 0.2.1

With `command` alert and `pipe_match_json: true`, I got Error:
```
ERROR:root:Traceback (most recent call last):
  File "/home/www/venv/lib/python3.6/site-packages/elastalert/elastalert.py", line 1440, in alert
    return self.send_alert(matches, rule, alert_time=alert_time, retried=retried)
  File "/home/www/venv/lib/python3.6/site-packages/elastalert/elastalert.py", line 1529, in send_alert
    alert.alert(matches)
  File "/home/www/venv/lib/python3.6/site-packages/elastalert/alerts.py", line 921, in alert
    stdout, stderr = subp.communicate(input=match_json)
  File "/usr/local/lib/python3.6/subprocess.py", line 848, in communicate
    self._stdin_write(input)
  File "/usr/local/lib/python3.6/subprocess.py", line 801, in _stdin_write
    self.stdin.write(input)
TypeError: a bytes-like object is required, not 'str'
```

**Comment by manudawber** [comment]
Having the same issue with the same conditions: v0.2.1, `command`, `pipe_match_json: true`.

**Comment by Qmando** [comment]
Thanks. This is a bug from the recent migration to py3. I'll fix it asap.

**Comment by gerbdla** [comment]
I think you may also have this error when using pipe_alert_text: true I am v2.1.  Has anyone else received this error.  I am using command: to send the email.
["Traceback (most recent call last):"," File \"/opt/elastalert/elastalert/elastalert.py\", line 1440, in alert"," return self.send_alert(matches, rule, alert_time=alert_time, retried=retried)"," File \"/opt/elastalert/elastalert/elastalert.py\", line 1529, in send_alert"," alert.alert(matches)"," File \"/opt/elastalert/elastalert/alerts.py\", line 924, in alert"," stdout, stderr = subp.communicate(input=alert_text)"," File \"/usr/local/lib/python3.6/subprocess.py\", line 848, in communicate"," self._stdin_write(input)"," File \"/usr/local/lib/python3.6/subprocess.py\", line 801, in _stdin_write"," self.stdin.write(input)","TypeError: a bytes-like object is required, not 'str'"]
