### ISSUE TITLE
Which version of ElastAlert does support Elasticsearch 6.3.0 and Kibana 6.3.0?

### ISSUE THREAD

**Issue by leee66** [Yelp/elastalert#2414]
Hi,
I am a newer of ElastAlert.  Which version of ElastAlert does support Elasticsearch 6.3.0 and Kibana 6.3.0?
Thank you.

**Comment by abhishekjiitr** [comment]
ElastAlert v0.1.38 & v0.1.39 should work against Elasticsearch 6.X. I think a lot of people have reported that these versions don't work with Elasticsearch 7.X though.

**Comment by leee66** [comment]
> ElastAlert v0.1.38 & v0.1.39 should work against Elasticsearch 6.X. I think a lot of people have reported that these versions don't work with Elasticsearch 7.X though.

Thank you for your answer.
