### ISSUE TITLE
ImportError: cannot import name kibana

### ISSUE THREAD

**Issue by AxelUlmestig** [Yelp/elastalert#2417]
I get a weird error when I try to run the `elastalert.py` script.
```
/opt/elastalert # python3 elastalert/elastalert.py
Traceback (most recent call last):
  File "elastalert/elastalert.py", line 28, in <module>
    from . import kibana
ImportError: cannot import name 'kibana'
```

I checked out the source code and the tag `v0.2.1`. I've tried doing all the steps [in the docs](https://elastalert.readthedocs.io/en/latest/running_elastalert.html#running-elastalert-for-the-first-time). They're slightly confusing though as they seem to be oriented around python 2.7.

Am I missing something here?
Thanks in advance

**Comment by abhishekjiitr** [comment]
Try running `python setup.py install` and then run `elastalert`directly. I am afraid running the file directly without installing won't work as is.

**Comment by AxelUlmestig** [comment]
That worked, thanks.

The README suggests running the python script yourself under the "Running Elastalert" section. That confused me :)

**Comment by abhishekjiitr** [comment]
@Qmando we should update the README, this can cause confusion. I think this was changed 3 months back when adding support for python3.

https://github.com/Yelp/elastalert/blob/master/README.md#running-elastalert
