### ISSUE TITLE
Where  are the file 【config.yaml.example】 and the folder 【example_rules】?

### ISSUE THREAD

**Issue by leee66** [Yelp/elastalert#2418]
Hi,
The version of my Elaticsearch and Kibana is 6.3.0. The version of Python is 2.7.5. I have installed ElastAlert 0.1.39, setuptools 41.1.0, and elasticsearch-py 6.3.0 based on this article 【https://elastalert.readthedocs.io/en/latest/running_elastalert.html】.  The setup path of ElastAlert is 【/usr/lib/python2.7/site-packages】, so I entered the path 【/usr/lib/python2.7/site-packages/elastalert】, and then I did not see the file 【config.yaml.example】 and the folder 【example_rules】. Where are the file 【config.yaml.example】 and the folder 【example_rules】? Thank you.

**Comment by Qmando** [comment]
https://github.com/Yelp/elastalert/blob/master/config.yaml.example
https://github.com/Yelp/elastalert/tree/master/example_rules

**Comment by leee66** [comment]
> https://github.com/Yelp/elastalert/blob/master/config.yaml.example
> https://github.com/Yelp/elastalert/tree/master/example_rules

Thanks for your answer.  However, what I mean is that where the file  the file 【config.yaml.example】 and the folder 【example_rules】are in the Linux OS after I execute 【pip install "elasticsearch<=6.3.0"】?

**Comment by q2dg** [comment]
Some explanation should be written in docs regarding this issue. Because it's a real issue.

**Comment by HarborZeng** [comment]
+1 real issue.
