### ISSUE TITLE
Elasticsearch fields in email body in flatline rule

### ISSUE THREAD

**Issue by mancharagopan** [Yelp/elastalert#2421]
I am using change rule and a flatline to monitor server's status. Change rule to alert once the server status is down and flatline to alert if the server status still down for a specific time. I need to add the fields from elasticsearch query like host ip, and status in the email body and subject.

```
alert:
- "email"
alert_subject: "{0} is {1}"
alert_subject_args:
- monitor.ip
- monitor.status
alert_text: |
    ALERT: {1} is {2} at {0}
alert_text_args: ["local_time", "monitor.ip", "monitor.status"]
alert_text_type: alert_text_only
```
I am using above config, but i get MISSING VALUE in the email subject and body.

Any way to solve my issue?

**Comment by mancharagopan** [comment]
I use `key` field to get the host IP. and manually added common information such as status.

**Comment by peache41** [comment]
Hi @mancharagopan 
Can you give a part of your file to see how did you use the key field?

I am in the same situation as you were and I don't find the `key` field in the documentation.

Thank you for your help.

**Comment by mancharagopan** [comment]
‘’’
alert:
- "email"
alert_subject: "{0} is DOWN: Down ESCALATION REPEAT ALERT"
alert_subject_args:
- key
alert_text: |
    ALERT: PING request Timeout for last 120 seconds
    Host: {1}
    Date/Time: {0}
alert_text_args: ["local_time", "key"]
alert_text_type: alert_text_only
email:
‘’’
