### ISSUE TITLE
Elasticsearch X-Pack Security role for Elastalert

### ISSUE THREAD

**Issue by Dyselxique** [Yelp/elastalert#2429]
Hello,

I have:
- Elasticsearch 7.3 freshly up to date
- X-Pack Security included with the basic License of ES

I will install Elastalert from the latest github release tomorrow. So I'll create a dedicated internal user for Elastalert in ES.
What permissions (cluster level and index level) does Elastalert's role need to work with X-Pack Security ?

Thanks :)

**Comment by abhishekjiitr** [comment]
Please see this: https://github.com/Yelp/elastalert/issues/2384

**Comment by Dyselxique** [comment]
Thanks I found the solution referenced in your issue
The docs pull request #2406 
Have a nice day :)
