### ISSUE TITLE
Count alert 

### ISSUE THREAD

**Issue by thisguynothatguy** [Yelp/elastalert#2430]
I am trying to create an alert when no docs are in logstash to alert, but I can't get it to fire p.. I could be doing it completely wrong.. but any help or a point in the right direction be greatly appropriated

 ---

_host: elasticsearch.production.domain.com
es_port: 9200
name: logstash_lv1_empty_count_test
type: any
index:  logstash-*
timeframe:
  hours: 1
num_matches: 0
num_hits: 0
#hits: 0
alert:
  - email
email:
  - insertemailhere@domain.com
smtp_host: hybrid.domain.com
email_add_domain: "@domain.com"
from_addr: elastalert@domain.com

**Comment by Qmando** [comment]
`type: any` means alert when it sees any document. That's not what you want

num_matches and num_hits are not config settings

You want 
```
type: flatline
threshold: 1
timeframe:
  hours: 1
```

See https://elastalert.readthedocs.io/en/latest/ruletypes.html#flatline

**Comment by thisguynothatguy** [comment]
Thanks, I will give this a go today and get back to you if I get it working

**Comment by thisguynothatguy** [comment]
Hey |I got this working perfectly, and the extra link provided me with extra things I needed but did not realize, thank you for you assistance :D Now to integrate pagerduty instead of email and we will be done :) Thanks for your help @Qmando
