### ISSUE TITLE
Generate Kibana 6.x.x links in slack alerts

### ISSUE THREAD

**Issue by syst0m** [Yelp/elastalert#2440]
The documentation mentions rule configuration options for generating Kibana links,
only for Kibana version 3 and 4:
https://github.com/Yelp/elastalert/blob/master/docs/source/ruletypes.rst#generate_kibana_link

Is it possible to generate Kibana links for Kibana v6.x.x on Slack alerts?

**Comment by JeffAshton** [comment]
I am currently working on something to generate links for the discover app if you're interested.  Early stages, but promising so far:

https://github.com/JeffAshton/elastalert/tree/kibana6_discover_query_keys

**Comment by syst0m** [comment]
Thanks, @JeffAshton .

**Comment by JeffAshton** [comment]
@syst0m :  Here's the PR in case you are interested:

https://github.com/Yelp/elastalert/pull/2471

**Comment by syst0m** [comment]
@JeffAshton Cool, thanks. :)
