### ISSUE TITLE
query to nested object 

### ISSUE THREAD

**Issue by Stuxend** [Yelp/elastalert#2458]
Hi guys, Im trying to query a nested object mapped but Im getting 0 results. 

**this is the event json data:** 

> 
> "requestParameters": {
>       "groupId": "blablabla-group",
>       "ipPermissions": {
>         "items": [
>           {
>             "ipProtocol": "tcp",
>             "fromPort": 0,
>             "toPort": 65535,
>             "groups": {},
>             "ipRanges": {
>               "items": [
>                 {
>                   "cidrIp": "0.0.0.0/0",
>                   "description": "testing"
>                 }
>               ]
>             },
>             "ipv6Ranges": {},
>             "prefixListIds": {}
>           }
> 

And I trying to get match with "cidrIp" equals to 0.0.0.0

I try: 

> 
> filter:
>   - term:
>      requestParameters.ipPermissions.items.ipRanges.items.cidrIp: "0.0.0.0/0"
> - query:
>     query_string:
>       query: requestParameters.ipPermissions.items.ipRanges.items.cidrIp:"0.0.0.0/0" 
> 

but not luck... anyone knows if elastalert support nested fields?

**Comment by abhishekjiitr** [comment]
Try adding quotes around filters in query & terms. This seems to work for me
```
filter:
- query:
    query_string:
        query: "tags.keyword: \"foo\" AND name: \"bar\""
```

**Comment by Stuxend** [comment]
I tried that but no luck ... It seems that was a mapping problem and nested fields (I'm using elk 7.X), I fixed changing the mapping fields and make a "copyto" into the mapping for each field ... Not the fanciest way but works ... something like this in my mapping doc:

` "ipPermissions.items.ipRanges.items.cidrIp": {
                                                    "type": "text",
                                                    "copy_to": "cidrIp"`
