### ISSUE TITLE
How to prevent alert turned to is_enabled=True to send alerts in the past

### ISSUE THREAD

**Issue by xwing22** [Yelp/elastalert#2486]
I have a flatline alert that look like this:
`name: My-Alert
import: ../config.yaml.inc
is_enabled: True

index: myindex-http-*
    

type: flatline
threshold: 10

timeframe:
  minutes: 2

filter:
- query:
    query_string:
       query: "field: value"

`

I needed  tio disable it for a week to fix the detected problem. Once I fixed it and set is_enabled=True again, elastalert restarted exactly at the the time it was turned off. despite having a timeframe of only 2 minutes.

I read somewhere that it's the normal behaviour but is there a way to prevent this and force it to restart at the moment it was turned back on? I also saw that if I changed the rule name it could work but I would rather keep the same name if possible.

**Comment by Qmando** [comment]
There's a setting called `old_query_limit`: https://elastalert.readthedocs.io/en/latest/elastalert.html?highlight=old_query_limit
But you'd need to restart elastalert to change this value.

Another option is to alter the name of the rule slightly. It looks for exact name matches to find where it last left off.

A final option is to go into the `elastalert_status` index in Elasticsearch and delete the query logs for that rule.

**Comment by xwing22** [comment]
Ok in our case setting an old_query_limit to a shorter period should do it although I understand it's a trade-off. I'd rather not change my alerts name, even slightly as I do have other tools relying on the exact string 

thanks!
