### ISSUE TITLE
Where can I see the feedback or the log information produced by ElastAlert after running ElastAlert?

### ISSUE THREAD

**Issue by leee66** [Yelp/elastalert#2503]
Good Morning.
The version of Python I setup is 3.6.9. The version of ElastAlert I setup is 0.2.1.
When I test Alert rule via the command 【/xxx/python369/bin/elastalert --verbose --config /xxx/python369/lib/python3.6/site-packages/elastalert/config.yaml --rule /xxx/python369/lib/python3.6/site-packages/elastalert/rules/oggTransTimeDelayPercentageMatchFirst.yaml】, I can see the feedback or the log information from ElastAlert, such as the following:
1 rules loaded
INFO:elastalert:Starting up
INFO:elastalert:Disabled rules are: []
INFO:elastalert:Sleeping for 179.999893 seconds
INFO:elastalert:Ran OGGTransTimeDelayPercentageMatchFirst from 2019-09-26 11:11 CST to 2019-09-26 11:16 CST: 0 query hits (0 already seen), 0 matches, 0 alerts sent
INFO:elastalert:Background configuration change check run at 2019-09-26 11:19 CST
INFO:elastalert:Background alerts thread 0 pending alerts sent at 2019-09-26 11:19 CST
INFO:elastalert:Disabled rules are: []
INFO:elastalert:Sleeping for 179.999807 seconds
INFO:elastalert:Ran OGGTransTimeDelayPercentageMatchFirst from 2019-09-26 11:14 CST to 2019-09-26 11:19 CST: 0 query hits (0 already seen), 0 matches, 0 alerts sent
...

However, When I run ElastAlert via the command 【nohup python3 -m elastalert.elastalert --verbose --config /xxx/python369/lib/python3.6/site-packages/elastalert/config.yaml --rule /xxx/python369/lib/python3.6/site-packages/elastalert/rules/oggTransTimeDelayPercentageMatchFirst.yaml >/dev/null 2>&1 &】, where can I see the aboved feedback or the log information from ElastAlert?

**Comment by shoustech** [comment]
@leee6 Looking at the command that you have listed it seems that you are redirecting all of your output to /dev/null which a file system object that throws away everything written to it. This happens because of the following snippet:
 `/dev/null 2>&1 &`

Assuming you want to write the output to /var/log/elastalert.log you should replace the previous snippet with the following:
`/var/log/elastalert.log 2>&1 &`

**Comment by leee66** [comment]
> @leee6 Looking at the command that you have listed it seems that you are redirecting all of your output to /dev/null which a file system object that throws away everything written to it. This happens because of the following snippet:
> `/dev/null 2>&1 &`
> 
> Assuming you want to write the output to /var/log/elastalert.log you should replace the previous snippet with the following:
> `/var/log/elastalert.log 2>&1 &`

See. Thanks for your answer.
