### ISSUE TITLE
requirements.txt is not up to date

### ISSUE THREAD

**Issue by fxheng** [Yelp/elastalert#2533]
Hi,

Building bitsensor elastalert server  ii get errors with my jira version. 
It is because requirement.txt is not up to date. It require :
"jira>=1.0.10,<1.0.15"
whereas setup.py require: 
'jira>=2.0.0
In bitsensor elastalert server Dockerfile setup.py is run before requirement.txt ending up downgrading jira.
I'm sorry but i can't commit it, my dev tools are offline.

**Comment by wiredrat** [comment]
Fixed on #2543

**Comment by fxheng** [comment]
Thank you
