### ISSUE TITLE
SNS alert - test

### ISSUE THREAD

**Issue by ltagliamonte** [Yelp/elastalert#260]
Hello guys,
I forked the project and I added SNS mode to send alerts, is there any way to test the alert mode, without have a elasticsearch cluster with data in it? Once finished the test i will submit a PR.
Thank in advance for the support.
Regards
L.

**Comment by Qmando** [comment]
Not in a super convenient way. You can make a simple rule and then use elastalert-test-rule with a json file:

data.json:
```
[
  {"@timestamp": "2015-09-30",
   "foo": "bar"}
]
```

test.yaml:
```
name: test rule
es_host: localhost
es_port: 9200
index: doesntmatter
type: any
alert: sns
```

```
$ elastalert-test-rule --data data.json --alert test.yaml
Alert for test rule at 2015-09-30T00:00:00Z:
test rule

@timestamp: 2015-09-30T00:00:00Z
foo: bar
....
```

**Comment by ltagliamonte** [comment]
i opened #261
