### ISSUE TITLE
No rules with ElastAlert on REHL as daemon

### ISSUE THREAD

**Issue by moritz91** [Yelp/elastalert#2637]
Hello everyone,

the title says it all. My ElastAlert service running as a deamon on a Red Hat Enterpise Linux server is not picking up rules. Querying systemd journal only shows that ElastAlert is pinging Elasticsearch and goes back to sleep every 300 seconds.

It is quite frustrating as there is no error provided to trace the issue. Any ideas? Thanks a lot.

**Comment by nsano-rururu** [comment]
Yelp/elastalert is no longer maintained. Please use jertel/elastalert2.
https://github.com/jertel/elastalert2
