### ISSUE TITLE
Elastalert blacklist not matching/alerting 

### ISSUE THREAD

**Issue by geede** [Yelp/elastalert#2642]
I have filebeat sending messages that I want to alert if they have 'ERROR' or 'WARN' in the message.  Messages are similar to:
`16-01-2020 08:05:59 [32] ERROR application - Universal Time: 2019-Dec-09 13:45:14.162927 ns`
I have set up a blacklist elastalert rule

```
es_host: localhost
es_port: 9200
name: application
type: blacklist
index: filebeat-7.5.0*
compare_key: message
blacklist:
- "ERROR"
- "WARN"
alert:
- "ms_teams"
ms_teams_webhook_url:
- "https://outlook.office.com/webhook/***"
ms_teams_alert_summary: "Test"
```

But when I test I get a lot of hits, but no matches 
`'matches': 0, 'hits': 9411'`

Any ideas whats missing?

**Comment by idengaurav** [comment]
@geede 

Having similar issue! Know a fix?

**Comment by geede** [comment]
Couldnt get the blacklist to work so went with query instead:
    filter:
      - query:
         query_string:
            query: "(message: WARN) AND (message: ERROR)"

**Comment by idengaurav** [comment]
and the type is any i suppose?

**Comment by geede** [comment]
yes
