### ISSUE TITLE
Recursive load for rules folder?

### ISSUE THREAD

**Issue by srizzling** [Yelp/elastalert#265]
Am I able to have a rules_folder with folders in it, so:
- httpd
- syslog 
and have the rules loaded from there. If it required a PR, then'll make it, from looking at the code it looks like it can be done.

**Comment by Qmando** [comment]
Yes, ElastAlert will recursively load all yaml files in ``rules_folder`` and subfolders

**Comment by underyx** [comment]
@Qmando could you mention this in the docs?

**Comment by Qmando** [comment]
http://elastalert.readthedocs.io/en/latest/elastalert.html?highlight=rules_folder

"rules_folder: The name of the folder which contains rule configuration files. ElastAlert will load all files in this folder, and all subdirectories, that end in .yaml."

**Comment by underyx** [comment]
Wow, not sure how I missed that. (After all, I found this issue which
should be way more difficult :D)

Sorry, then!
