### ISSUE TITLE
errno 111 conection refused (email)

### ISSUE THREAD

**Issue by Mozart4242** [Yelp/elastalert#2671]
hello, there is an unsolved issue with mail setting in elastalert, i have tried  every possible solution to this but still no luck, can any one help please ? i have noticed that this is a common problem among users.
### rule.yaml file:
alert:
  - "email"
email: "ciso@test.net"
smpt_host: "mail.test.net"
smpt_port: 25
smtp_ssl: true
smpt_auth_file: '/opt/elastalert/smpt_host_auth.yaml'
from_addr: "hunter@test.net"

### smtp_auth file :
user: "hunter@test.net"
password: "123456"

> i've tried smpt_ssl false too and also different port like 587 for smpt using ssl.
> i have tried every possible combination but still not working.
![Untitled](https://user-images.githubusercontent.com/44939554/73633400-e2e40880-4673-11ea-8a1e-d40a8d373209.png)

**Comment by ccottam** [comment]
just to check - your real config file does actually say smtp? and not smpt

**Comment by Mozart4242** [comment]
> just to check - your real config file does actually say smtp? and not smpt

Yes i found out the problem yesterday!!!
That was a horrible mistake !!!
Anyway thanks you...
