### ISSUE TITLE
Elasticsearch 7.5.1 and ElastAlert 0.2.1 Unexpected Keyword Argument '_source_include'

### ISSUE THREAD

**Issue by sarisdpreston** [Yelp/elastalert#2683]
Unable to test rules. Receiving the following errors
TypeError("search() got multiple values for keyword argument 'body'",)
TypeError: search() got an unexpected keyword argument '_source_include'

I've referred to and tried suggestions under #2202 with no luck.

ElastAlert Test Output:
# elastalert-test-rule /opt/elastalert/rules/inetpub-errors.yaml
Successfully loaded Dealer Portal Error

Error running your filter:
TypeError("search() got multiple values for keyword argument 'body'",)
INFO:elastalert:Note: In debug mode, alerts will be logged to console but NOT actually sent.
                To send them but remain verbose, use --verbose instead.
Traceback (most recent call last):
  File "/usr/local/bin/elastalert-test-rule", line 11, in <module>
    load_entry_point('elastalert==0.1.35', 'console_scripts', 'elastalert-test-rule')()
  File "/usr/local/lib/python2.7/dist-packages/elastalert-0.1.35-py2.7.egg/elastalert/test_rule.py", line 453, in main
    test_instance.run_rule_test()
  File "/usr/local/lib/python2.7/dist-packages/elastalert-0.1.35-py2.7.egg/elastalert/test_rule.py", line 445, in run_rule_test
    self.run_elastalert(rule_yaml, conf, args)
  File "/usr/local/lib/python2.7/dist-packages/elastalert-0.1.35-py2.7.egg/elastalert/test_rule.py", line 303, in run_elastalert
    client.run_rule(rule, endtime, starttime)
  File "/usr/local/lib/python2.7/dist-packages/elastalert-0.1.35-py2.7.egg/elastalert/elastalert.py", line 865, in run_rule
    if not self.run_query(rule, rule['starttime'], tmp_endtime):
  File "/usr/local/lib/python2.7/dist-packages/elastalert-0.1.35-py2.7.egg/elastalert/elastalert.py", line 623, in run_query
    data = self.get_hits(rule, start, end, index, scroll)
  File "/usr/local/lib/python2.7/dist-packages/elastalert-0.1.35-py2.7.egg/elastalert/elastalert.py", line 391, in get_hits
    **extra_args
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch-7.5.1-py2.7.egg/elasticsearch/client/utils.py", line 84, in _wrapped
    return func(*args, params=params, **kwargs)
TypeError: search() got an unexpected keyword argument '_source_include'

**Comment by sarisdpreston** [comment]
I was able to resolve this issue. It was due to a botched Elastalert 0.2.1 upgrade and out of date dependencies found under (/opt/elastalert/requirements.txt). Once I resolved all of the errors (mostly due to out of date dependencies) following execution of /opt/elastalert/setup.py , I could test my rules without issue.

**Comment by NTBTI** [comment]
@sarisdpreston Any chance you could release what the changes you made were? I'm getting this same error with ES 7.5.1 and tried a few dependencies, but no luck. Whatever you did to solve this would be great as more people I'm sure will be upgrading to 7.5. Thanks in advance.

**Comment by sarisdpreston** [comment]
I'll try and help where I can. Note, this is on a Ubuntu server.

My primarily issue was using Python2 instead of Python3. ElastAlert documentation states it requires Python 3.6, though I had success with Python 3.5.2.

You can check which version is your default by running:

python --version

If all looks good, re-run the ElastAlert setup.py and restart the elastalert process:

python /opt/elastalert/setup.py install

service elastalert restart

Also, confirm the dependencies listed under /opt/elastalert/requirements.txt are installed and match the version requirements:

pip freeze

OR 

pip3 freeze 

If you have both Python2 and Python3 installed, you may want to ensure Python3 is the default by doing the following:  

mv /usr/bin/python /usr/bin/python.bak
cp /usr/bin/python3 /usr/bin/python


Use the following command to test your rules.

elastalert-test-rule /opt/elastalert/rules/yourrule.yaml

Let me know what errors, if any, are encountered after these steps.

Thanks
