### ISSUE TITLE
Elastalert running as daemon defaults to debug mode

### ISSUE THREAD

**Issue by ambron60** [Yelp/elastalert#2686]
I'm running Elastalert as daemon via _service elastalert start_. When looking at the log file, I notice the service always starts in debug mode, not allowing me to write to the **elastalert_status** index in Kibana nor send emails from elastalert rules .. any thoughts? Thanks in advance.

**Comment by daichi703n** [comment]
Hi, @ambron60 
How did you install ElastAlert? Could you paster your elastalert.yaml?

**Comment by ambron60** [comment]
Hi @daichi703n 

I got it from this repo.. currently sitting in a folder in my home dir.. did you mean config.yaml..?

**Comment by daichi703n** [comment]
Hi @ambron60 
Sorry, I want to know your `config.yaml`.
What is your startup script of ElastAlert? (I only run ElastAlert with Docker)
Startup script seems to be contain `python3 -m elastalert/elastalert ...`. Does it contain debug option?

**Comment by ambron60** [comment]
I have to check the init.d startup file... this is the file I’m using ..

https://raw.githubusercontent.com/fabianlee/blogcode/master/elastalert -O /etc/init.d/elastalert

**Comment by daichi703n** [comment]
Sorry, I now don't know how this `init.d` is generated.

Fix this line

```
DAEMON_ARGS="--config $EA_DIR/$CONFIG_NAME $RULE_OPTS --debug --verbose"
```

to

```
DAEMON_ARGS="--config $EA_DIR/$CONFIG_NAME $RULE_OPTS --verbose"
```

will help you to disabling debug mode. Could you try?

**Comment by ambron60** [comment]
Removing that option solved the issue.. thanks!

**Comment by ambron60** [comment]
Removing that option solved the issue.. thanks!
