### ISSUE TITLE
how to run from source locally ? 

### ISSUE THREAD

**Issue by hsdtsyl** [Yelp/elastalert#2699]
i wanna debug to learn how elastalert runs and expect to contribute PR , as a new commer, i have no idea to find any docs about the issue as titled.

```python
# python elastalert/elastalert.py --verbose
Traceback (most recent call last):
  File "elastalert/elastalert.py", line 29, in <module>
    from . import kibana
ImportError: cannot import name 'kibana'
```

anyone can help ?

**Comment by ghl1024** [comment]
I have the same error, can you tell me the resean about this? please!
#2776
