### ISSUE TITLE
Query for rules from a database rather than from file in rules_folder

### ISSUE THREAD

**Issue by boddumanohar** [Yelp/elastalert#2734]
Currently we have an API layer on top of ElastAlert where when a new alert is added, we are creating a new rules file in `rules_folder`. 

Since we are deploying on Docker container, maintaining and moving these *.yaml in `rules_folder` has become cumbersome.

So rather the rules being on a file, if the rules were on some database, like redis or etcd, it would be easy for us to query for rules. Does elastAlert supports such feature yet? 

Thanks,
Manohar.

**Comment by HarishHary** [comment]
Hello,

I think this issue can be solved with this feature: https://elastalert.readthedocs.io/en/latest/recipes/adding_loaders.html
You just need to adapt the code to link it with your database.

**Comment by boddumanohar** [comment]
thanks
