### ISSUE TITLE
Elastalert still not working with ELK 7.4.0

### ISSUE THREAD

**Issue by vinodhkumart** [Yelp/elastalert#2735]
Hi ,

I had deployed Elastic search  and kibana 7.4.0 versions and elastalert as 0.2.1 from the below docker image.
jertel/elastalert-docker:0.2.1

I deploy it in my kube cluster , but when trying to run the config i am getting the below error.

Need some help on this to fix.
========================================================
ERROR:root:Error finding recent pending alerts: RequestError(400, u'search_phase_execution_exception', u'No mapping found for [alert_time] in order to sort on') {'sort': {'alert_time': {'order': 'asc'}}, 'query': {'bool': {'filter': {'range': {'alert_time': {'to': '2020-04-10T08:24:53.098208Z', 'from': '2020-04-08T08:24:53.098187Z'}}}, 'must': {'query_string': {'query': '!_exists_:aggregate_id AND alert_sent:false'}}}}}
Traceback (most recent call last):
  File "/opt/elastalert/elastalert/elastalert.py", line 1526, in find_recent_pending_alerts
    size=1000)
  File "/usr/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 84, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/lib/python2.7/site-packages/elasticsearch/client/__init__.py", line 852, in search
    "GET", _make_path(index, doc_type, "_search"), params=params, body=body
  File "/usr/lib/python2.7/site-packages/elasticsearch/transport.py", line 358, in perform_request
    timeout=timeout,
  File "/usr/lib/python2.7/site-packages/elasticsearch/connection/http_requests.py", line 161, in perform_request
    self._raise_error(response.status_code, raw_data)
  File "/usr/lib/python2.7/site-packages/elasticsearch/connection/base.py", line 230, in _raise_error
    status_code, error_message, additional_info
RequestError: RequestError(400, u'search_phase_execution_exception', u'No mapping found for [alert_time] in order to sort on')
WARNING:elasticsearch:GET http://localhost:9200/elastalert_status/elastalert_status/_search?_source_include=endtime%2Crule_name&size=1 [status:400 request:0.003s]
ERROR:root:Error querying for last run: RequestError(400, u'illegal_argument_exception', u'request [/elastalert_status/elastalert_status/_search] contains unrecognized parameter: [_source_include] -> did you mean any of [_source_includes, _source_excludes]?')
WARNING:elasticsearch:GET http://localhost:9200/logstash*/_search?_source_include=%40timestamp%2C%2A&ignore_unavailable=true&scroll=30s&size=10000 [status:400 request:0.009s]
ERROR:root:Error running query: RequestError(400, u'illegal_argument_exception', u'request [/logstash*/_search] contains unrecognized parameter: [_source_include] -> did you mean any of [_source_includes, _source_excludes]?')
INFO:elastalert:Ran Logmessages from 2020-04-10 10:09 CEST to 2020-04-10 10:24 CEST: 0 query hits (0 already seen), 0 matches, 0 alerts sent
INFO:elastalert:Sleeping for 59.939058 seconds

**Comment by vinodhkumart** [comment]
I fixed this myself

**Comment by taegeum** [comment]
i have the same error. plz help me

**Comment by taegeum** [comment]
i have the same error. plz help me @vinodhkumart

**Comment by vinodhkumart** [comment]
@taegeum Just remove elastalert_status indices and try freshly
