### ISSUE TITLE
Elastalert Duplicate rules 

### ISSUE THREAD

**Issue by vinodhkumart** [Yelp/elastalert#2736]
HI Team,

Iam getting the below error message and container is not starting. Not sure where went wrong. All config looks good and no issues found with the rules also.

Please let me know if any facing the same kind of issue and solved it by any chance?

my configurations are:
-------------------
/opt/config/elastalert_config.yaml/
/opt/rules/rules.yaml

Rules config looks like below:
--------------------------
rules.yaml: |-
    name: ErrorLogs
    es_host: "elalsticsearch-hostname"
    es_port: 9200
    es_username: "username"
    es_password: "password"
    type: any
    index: logstash*
    timestamp_field: "@timestamp"
    num_events: 1
    timeframe:
      minutes: 5
    realalert:
      minutes: 0
    filter:
    - query:
        query_string:
          query: "log: error AND log: Journalerror"

    alert:
    - "email"
    email:
    - "myemail@mail.com"

Elastic Version: 7.4.0
Reading Elastic 6 index mappings:
Reading index mapping 'es_mappings/6/silence.json'
Reading index mapping 'es_mappings/6/elastalert_status.json'
Reading index mapping 'es_mappings/6/elastalert.json'
Reading index mapping 'es_mappings/6/past_elastalert.json'
Reading index mapping 'es_mappings/6/elastalert_error.json'
Index elastalert_status already exists. Skipping index creation.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/elastalert/loaders.py", line 123, in load
    raise EAException('Duplicate rule named %s' % (rule['name']))
elastalert.util.EAException: Duplicate rule named ErrorLogs

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/elastalert", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/elastalert/elastalert.py", line 2034, in main
    client = ElastAlerter(args)
  File "/usr/local/lib/python3.6/site-packages/elastalert/elastalert.py", line 138, in __init__
    self.rules = self.rules_loader.load(self.conf, self.args)
  File "/usr/local/lib/python3.6/site-packages/elastalert/loaders.py", line 125, in load
    raise EAException('Error loading file %s: %s' % (rule_file, e))
elastalert.util.EAException: Error loading file /opt/rules/..2020_04_13_09_16/rules.yaml: Duplicate rule named ErrorLogs

**Comment by rehannali** [comment]
Hi @vinodhkumart , `name` field is required by rule and should in unique. The problem is, you have multiple rules with named **ErrorLogs** in rules folder.

**Comment by vinodhkumart** [comment]
Hi,@rehannali , I tried changing the name to different instead of ErrorLogs . still issue exists.

**Comment by rehannali** [comment]
Show me your global `config.yaml` file.

**Comment by vinodhkumart** [comment]
apiVersion: v1
kind: ConfigMap
metadata:
  name: elast-config
  namespace: namespace
  labels:
    k8s-app: elastalert
data:
  elastalert_config.yaml: |-
    # This is the folder that contains the rule yaml files
    # Any .yaml file will be loaded as a rule
    rules_folder: /opt/rules

    # How often ElastAlert will query Elasticsearch
    # The unit can be anything from weeks to seconds
    run_every:
      minutes: 1

    # ElastAlert will buffer results from the most recent
    # period of time, in case some log sources are not in real time
    buffer_time:
      minutes: 15

    # The Elasticsearch hostname for metadata writeback
    # Note that every rule can have its own Elasticsearch host
    es_host: elastichostname

    # The Elasticsearch port
    es_port: 9200
    es_username: elastic
    es_password: password
    # Optional URL prefix for Elasticsearch
    #es_url_prefix: elasticsearch

    # Connect with TLS to Elasticsearch
    #use_ssl: True

    # Verify TLS certificates
    #verify_certs: True

    # elastalert-create-index to set a mapping
    writeback_index: elastalert_status
    # sending the alert until this time period has elapsed
    alert_time_limit:
      days: 2
    smtp_host: "smtp-serverurl"
    smtp_port: port
    smtp_ssl: false
    from_addr: "test@example.com"
    smtp_auth_file: "/opt/elastalert/smtp_auth_file"
    # If an alert fails for some reason, ElastAlert will retry

    # sending the alert until this time period has elapsed
  elastalert_supervisord.conf: |-
    [unix_http_server]
    file=/var/run/elastalert_supervisor.sock

    [supervisord]
    logfile=/opt/logs/elastalert_supervisord.log
    logfile_maxbytes=1MB
    logfile_backups=2
    loglevel=debug
    nodaemon=false
    directory=%(here)s

    [rpcinterface:supervisor]
    supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

    [supervisorctl]
    serverurl=unix:///var/run/elastalert_supervisor.sock

    [program:elastalert]
    # running globally
    command = elastalert --config /opt/config/elastalert_config.yaml --rule /opt/rules/rules.yaml --verbose
    # (alternative) using virtualenv
    # command=/path/to/venv/bin/elastalert --config /path/to/elastalert_config.yaml --verbose
    process_name=elastalert
    autorestart=true
    startsecs=15
    stopsignal=INT
    stopasgroup=true
    killasgroup=true
    stderr_logfile=/opt/logs/elastalert_stderr.log
    stderr_logfile_maxbytes=5MB

**Comment by vinodhkumart** [comment]
@rehannali Above is the config yaml  configured in the config map.

**Comment by rehannali** [comment]
Check in `/opt/rules` directory as well as it's sub directory, Make sure every rule name should be unique.

**Comment by vinodhkumart** [comment]
My pod goes into crashloopback and I am unable to check the folder

**Comment by rehannali** [comment]
You need to stop supervisor and first make sure everything is working fine with manual testing.

**Comment by vinodhkumart** [comment]
@rehannali I had removed the supervisor configuration and deployed but still i can see the same error.

**Comment by vinodhkumart** [comment]
Issue has been fixed... Closing the issue.

**Comment by rehannali** [comment]
@vinodhkumart , Good to hear. 😊

**Comment by donnykrn** [comment]
Hi so how to solved the issue?

**Comment by byroncollins** [comment]
@vinodhkumart how did you solve the issue? 
We're getting the same error with rules mounted as a configmap

**Comment by byroncollins** [comment]
I assume this?
https://github.com/Yelp/elastalert/issues/2270#issuecomment-643079750
