### ISSUE TITLE
How to do Data Aggregation using a regular expression on a field

### ISSUE THREAD

**Issue by rpotnuru** [Yelp/elastalert#2768]
I am trying to write an aggregation query based on country code where country code is part of path parameter, and need some help here.
I have one of the filed in my document as below, and I want to aggregate the results using country, where as the country can be extracted from path parameter and I need total number of hits in a day per country. 
"operation" : "POST /v1/myservice/product/1000100/market/**US**/item/001
"operation" : "POST /v1/myservice/product/1000001/market/**GB**/item/002
Thanks in advance.

**Comment by JasperJuergensen** [comment]
This is nothing you can do with elastalert. If you want to do such analyses you have to prepare the data in elasticsearch first. When ingesting the data with logstash, you can do the analysis there and add a field like "operation_country" or you can use the elasticsearch text analysis features (https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis.html)

**Comment by rpotnuru** [comment]
Thank you @JasperJuergensen for the note, I am also heading towards the same direction and just want to see if some one had a solution for this kind of use cases. Thank you.
