### ISSUE TITLE
Is multiple regex possible for same field in elast alert?

### ISSUE THREAD

**Issue by km-janmejay** [Yelp/elastalert#2769]
I am new to this , have good experience.
I was trying to write filter for mutiple regex.
my code is:

filter:
- regex:
           Id:[ "abc.*user"," xyz.*user"]

single  regex is working:
filter:
- regex:
           Id: "abc.*user"
this is giving me proper alert as per my rule.

i am not able to figure out a way this, need help asap.
@Qmando i have been following your solution so mentioned you here.

**Comment by Qmando** [comment]
```
filter:
 - query_string:
      query: "Id: /abc.*user/ OR Id: /xyz.*user/"
```

**Comment by km-janmejay** [comment]
It is not working what i wanted. This is my rule file, and  i wrote the filter as u said. I wanted the data about the process that  strts with either 'k' or 'j' and ends with user.
For  test i would use this command:
   sudo logger -t kiteuser "mutiple regex trial"
for this process name appears to be kiteuser and message appears to be "multiple regex trial" in kibana
instead 
I am getting all process , with their data. 
![Screenshot from 2020-04-30 09-51-45](https://user-images.githubusercontent.com/59961932/80671692-48eff880-8ac8-11ea-9869-3319165b2fd6.png)
Can you please  help!! (Note: i was using my system logs for demo)
@Qmando

**Comment by Qmando** [comment]
Why do you have `filter:filter` ? It should just be `filter`

**Comment by km-janmejay** [comment]
Ohk thankyou sir!!
