### ISSUE TITLE
How to pass related_events in command alert.

### ISSUE THREAD

**Issue by rashmichoudhary07** [Yelp/elastalert#2772]
If you are using `type: frequency`, you can add `attach_related: true` which will send all the documents up to `num_events` in the alert.

_Originally posted by @Qmando in https://github.com/Yelp/elastalert/issues/649#issuecomment-234607069_

@Qmando,
I am trying to pass related_events for a frequency type with alert. This is how i have done it after going through the docs.
command: "echo %(@timestamp)s %(log_json.transaction.conversationId)s %(related_events[])s >> path_to_file/command_alert.log"

However, i get below error:
/bin/sh: -c: line 0: syntax error near unexpected token `>>'
/bin/sh: -c: line 0: `echo 2020-04-30T04:03:55.726Z mf3456 <MISSING VALUE> >> path_to_file/command_alert.log'

There is missing value in place of related_events. Please help!

**Comment by rashmichoudhary07** [comment]
Hello @Qmando 
I was checking and had some success in getting individual field value from related_events[] by using the format shown below in my rule file where we need to give indices like here i have given [0]:

command: "echo %(@timestamp)s %(log_json.transaction.conversationId)s {related_events[0][log_json][transaction][conversationId]} >> path_to_file/command_alert.log"

However, i am looking for getting a particular field's value for all documents in related_events[] since in my case hits will keep varying. It wont be possible to keep specifying indices. Is it doable here. Kindly help.

**Comment by Qmando** [comment]
You can either implement this in an enhacnement, something like
```
class MyEnhancement(BaseEnhancement):
    def process(self, match):
        match['field_values'] = ', '.join([event['field'] for event in match['related_events']])
```
(Just an example, probably not exactly this)

or you could try using `jq` to parse it in a bash script
For example:
```
$ echo '{"foo": [{"test": "a"}, {"test": "b"}], "bar": "something"}' | jq ' .bar, .foo[].test'
"something"
"a"
"b"
```

**Comment by rashmichoudhary07** [comment]
@Qmando 
Thanks! :) Will check on this..
