### ISSUE TITLE
Kibana Discover link is  not displaying the events upon clicking

### ISSUE THREAD

**Issue by rpotnuru** [Yelp/elastalert#2775]
Hello @Qmando and team, We are using generate_kibana_discover_url: true option in the rule file and a link is getting passed in the email, however upon clicking on the link we are not seeing the results, instead we are seeing "index is not a configured index pattern ID and showing the default index pattern" and i see "No results match your search criteria" message, upon changing the index to match with where to look, i am able to see the events. Is there a fix for this  ??
<img width="359" alt="Screen Shot 2020-04-30 at 3 53 53 PM" src="https://user-images.githubusercontent.com/3529965/80767007-a8b3c700-8afb-11ea-9478-a2a34272fd95.png">

**Comment by nsano-rururu** [comment]
I'm not sure because I don't know all the settings, but I'm not having any problems in my environment. I think it's a matter of your settings.

**Comment by rpotnuru** [comment]
All good now, able to make it working, it is my kibana setting causing the issue.

**Comment by sergiochoo** [comment]
> All good now, able to make it working, it is my kibana setting causing the issue.

could you tell us which exactly kibana settings were wrong? thanks
