### ISSUE TITLE
Have option to write to metaindex in debug mode

### ISSUE THREAD

**Issue by Brian-Williams** [Yelp/elastalert#2800]
It would be a nice feature to have the option to write to the writeback meta-indexes.

https://github.com/Yelp/elastalert/blob/1334b611fdd7adf39991a1b0b11689568d612690/elastalert/elastalert.py#L1533

It would help testability if we could directly query the meta-indices to test elastalert and alerts firing.

**Comment by nsano-rururu** [comment]
Yelp/elastalert is no longer maintained. Please use jertel/elastalert2.
https://github.com/jertel/elastalert2
