### ISSUE TITLE
kibana discover 7.4 support for generate_kibana_discover_url in elastalert

### ISSUE THREAD

**Issue by rashmichoudhary07** [Yelp/elastalert#2801]
Hello @Qmando,

I need kibana 7.4 support for generating kibana discover url. Since the Kibana7_versions in kibana_discover.py is a frozenset, i do not know how to proceed to make changes for 7.4+ support. 

Appreciate your help!
Regards

**Comment by Qmando** [comment]
Have you tried adding 7.4 to kibana7_versions to see if it works?

**Comment by rashmichoudhary07** [comment]
@Qmando 
Yes i did add 7.4 to kibana7_versions in kibana_discover.py but it gives error that it does not work.. please find below error stacktrace.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/app/cwlogai/python35/bin/elastalert", line 11, in <module>
    sys.exit(main())
  File "/opt/app/cwlogai/python35/lib/python3.5/site-packages/elastalert/elastalert.py", line 2049, in main
    client = ElastAlerter(args)
  File "/opt/app/cwlogai/python35/lib/python3.5/site-packages/elastalert/elastalert.py", line 140, in __init__
    self.rules = self.rules_loader.load(self.conf, self.args)
  File "/opt/app/cwlogai/python35/lib/python3.5/site-packages/elastalert/loaders.py", line 126, in load
    raise EAException('Error loading file %s: %s' % (rule_file, e))
elastalert.util.EAException: Error loading file ./elastalert-rules/ms_responsetime_realert.yaml: Invalid Rule file: ./elastalert-rules/ms_responsetime_realert.yaml
'7.4' is not one of ['7.3', '7.2', '7.1', '7.0', '6.8', '6.7', '6.6', '6.5', '6.4', '6.3', '6.2', '6.1', '6.0', '5.6']

Failed validating 'enum' in schema['properties']['kibana_discover_version']:
    {'enum': ['7.3',
              '7.2',
              '7.1',
              '7.0',
              '6.8',
              '6.7',
              '6.6',
              '6.5',
              '6.4',
              '6.3',
              '6.2',
              '6.1',
              '6.0',
              '5.6'],
     'type': 'string'}

On instance['kibana_discover_version']:
    '7.4'

**Comment by nsano-rururu** [comment]
@rashmichoudhary07 

There is also kibana_discover_version in schema.yaml, did you add 7.4?

The following is a note I investigated

**kibana_discover.py**

https://github.com/Yelp/elastalert/blob/master/elastalert/kibana_discover.py
>kibana7_versions = frozenset(['7.0', '7.1', '7.2', '7.3'])

**schema.yaml**

https://github.com/Yelp/elastalert/blob/master/elastalert/schema.yaml
>kibana_discover_version: {type: string, enum: ['7.3', '7.2', '7.1', '7.0', '6.8', '6.7', '6.6', '6.5', '6.4', '6.3', '6.2', '6.1', '6.0', '5.6']}

**kibana_discover_test.py**

https://github.com/Yelp/elastalert/blob/master/tests/kibana_discover_test.py
>@pytest.mark.parametrize("kibana_version", ['7.0', '7.1', '7.2', '7.3'])

There were a few entries below

>'kibana_discover_version': '7.3',

**Comment by nsano-rururu** [comment]
@rashmichoudhary07 

If you also add 7.4 to schema.yaml, the error should disappear.

@Qmando 

Please point out if the recognition is wrong

**Comment by rashmichoudhary07** [comment]
@nsano-rururu 
Hello, 
Thanks for looking into it. For now , as suggested by you, ill add 7.4 to schema.yaml and check if that works at my end. Will keep you posted.
