### ISSUE TITLE
Is it possible to pass the value captured by an alert into the alert_subject_args?

### ISSUE THREAD

**Issue by jpmor** [Yelp/elastalert#2808]
For example, if I have a `type: cardinality` alert with `max_cardinality: 100`.... I'd love for the `alert_text` to include what the actual recorded cardinality was.  Is this possible?

The [docs](https://elastalert.readthedocs.io/en/latest/ruletypes.html#alert-content) do not show a way to do this.

**Comment by empirium** [comment]
Did you find solution for that?
