### ISSUE TITLE
'alert' type in config.yaml violated the latest schema

### ISSUE THREAD

**Issue by Kapaski** [Yelp/elastalert#281]
Hello there,

Comparing the `master` and `v0.0.63`, I can find there is a change at this line 

https://github.com/Yelp/elastalert/blob/master/elastalert/schema.yaml#L156

This caused elastalert can't run test or start from command line with complaining alert types is not an *arrayofObject*. Given using the same config.yaml in `v0.0.63`, such as the example below:

      alert:
      - "email"

So I had another look between `master` and `v0.0.63`, and found in the master schema.yaml, the definition of this `arrayOfObjects` is identical to `arrayOfStrings` which might be where the problem comes from.

If so, please also update the rule example with this fixed arraOfObjects type in it.

Many Thanks

James

**Comment by Qmando** [comment]
Ah yes this was broken in master by a recent merge. I've fixed it in master for now. I'm thinking of removing the JSON schema entirely soon as it's becoming unwieldy and not very useful.

**Comment by Kapaski** [comment]
Cheers Qmando
