### ISSUE TITLE
Emails Failing to Send...

### ISSUE THREAD

**Issue by MakoWish** [Yelp/elastalert#2864]
We stopped receiving alerts from ElastAlert, so I went to check the logs. We are getting "unsupported protocol" errors. 

```
Jun 25 15:28:39 ElastAlert1 elastalert[2816]: ERROR:root:Error while running alert email: Error connecting to SMTP host: [SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:1108)
```

Here is the email configuration (redacted):

```
alert:
- email

email:
- "MyName@Company.com"
smtp_host: mailserver.company.com
smtp_port: 25
smtp_ssl: false
from_addr: "Elastalerts@Company.com"
```

Why are we getting SSL errors when we have "smtp_ssl: false"?

**Comment by Adryeh** [comment]
Use smtp_port: 465, this should help you

**Comment by MakoWish** [comment]
Using port 465, the error changes.

```
Jun 26 08:37:22 ElastAlert1 elastalert[727]: ERROR:root:Error while running alert email: Error connecting to SMTP host: [Errno 111] Connection refused
```

**Comment by MakoWish** [comment]
Top...

Any other ideas on this? I am not able to receive any alerts from our cluster.

**Comment by nsano-rururu** [comment]
We also recommend asking questions on the Gitter channel
https://gitter.im/Yelp/elastalert

**Comment by MakoWish** [comment]
Downgraded Ubuntu from 20.04 LTS back down to 18.04 LTS, and everything is working again. Chocking it up to Ubuntu 20.04 not being supported.

**Comment by nsano-rururu** [comment]
@MakoWish 

Is it a difference in Python version?

**Comment by MakoWish** [comment]
It is working on Ubuntu 18.04 with the latest available version for Ubuntu 18.04 - Python "3.6.7-1~18.04", but I am unfortunately not sure if that version changed during the upgrade to Ubuntu 20.04. I am guessing it did?

Since we do rely on this Elastalert instance, I don't want to try the upgrade again. I will see if I can spin up a new instance, ensure it works properly, then upgrade to 20.04 LTS to see if there is any change to the Python version. Just looking at a couple other Ubuntu 20.04 systems I manage, the current version of Python installed is "3.8.2-0ubuntu2", so my guess is that the version of Python changed on upgrade.

**Comment by nsano-rururu** [comment]
Python for Ubuntu 20.04 comes with 3.8 by default. By the way, 3.6 can also be installed by the following method.

```
sudo apt update
sudo apt upgrade
sudo add-apt-repository ppa:deadsnakes/ppa
sudo apt -y install build-essential python3.6 python3.6-dev python3-pip libffi-dev libssl-dev python3.6-venv
```

**Comment by nsano-rururu** [comment]
I just wondered if the problem occurred due to the difference in Python version, so there is no need to try anything.
Did something go wrong when running with Python 3.8?
I'm currently planning to officially support ElastAlert's Python 3.8, so I'd like information.

**Comment by MakoWish** [comment]
I honestly did not do too much troubleshooting, as I needed the system back up. All I know is that once I upgraded to 20.04, no emails would send. No matter the email settings I tried, it would error on send. It very well could be a compatibility issue with Python 3.8.

**Comment by nsano-rururu** [comment]
I sent an email with Python 3.8, but I tried to send an alert notification by email, and set the form address to yahoo.co.jp address and the to address to gmail address, and there was no problem.
In the case of installing postfix etc. and sending
It may be a problem with the default settings of Ubuntu 20.04 security settings (SELinux?)

**Comment by nsano-rururu** [comment]
How to disable/enable SELinux on Ubuntu 20.04 Focal Fossa Linux
https://linuxconfig.org/how-to-disable-enable-selinux-on-ubuntu-20-04-focal-fossa-linux
