### ISSUE TITLE
Should alarm rules be create for services or for error flags?

### ISSUE THREAD

**Issue by wajika** [Yelp/elastalert#2866]
If it is based on services, then a large number of services will require the establishment of a lot of alarm rules. If it is based on error flags, how to distinguish which service alarm is in each alarm push message?

Does elastalert provide any solution?

**Comment by nsano-rururu** [comment]
I don't think it's the tool you want. We recommend that another OSS consider a paid product

https://elastalert.readthedocs.io/en/latest/elastalert.html

Settings are global config, individual monitoring settings are described in YAML format
The monitoring method is Elasticsearch query
Support is OSS, so please use Issue on Github etc.
Can create custom rules
https://elastalert.readthedocs.io/en/latest/recipes/adding_rules.html
There are various alert notification methods.
https://elastalert.readthedocs.io/en/latest/ruletypes.html#alerts
Monitoring rule type
https://elastalert.readthedocs.io/en/latest/ruletypes.html#rule-types


The following is a reference URL

Tools from third parties

ElastAlert Kibana Plugin
https://github.com/bitsensor/elastalert-kibana-plugin

ElastAlert Server
https://github.com/johnsusek/elastalert-server

Praeoc

Set on the web screen. yaml is generated. yaml does not allow direct editing
Send notifications to Slack, MS Teams, Email, Telegram, Jira, Line Notify, Mattermost, Command, Gitter or an HTTP POST endpoint
Supports the Any, Blacklist, Whitelist, Change, Frequency, Flatline, Spike, Cardinality, New Term, and Metric Aggregation rule types
https://github.com/johnsusek/praeco

**Comment by wajika** [comment]
ok,thanks
