### ISSUE TITLE
cardinalityRule   hits many but alert none

### ISSUE THREAD

**Issue by PonusJang** [Yelp/elastalert#2886]
My profile setting :
------------------------------
type: cardinality

cardinality_field: src_ip

max_cardinality: 10

timeframe: 
  minutes: 1

---------------------------------------------------
i want  alert when src_ip is over  10 times  but it isn't work .

it runs  and  output like :
_12 query hits (0 already seen), 0 matches, 0 alerts sent_

i use function print() and find  ' self.cardinality_cache' always  only one value like {all:{'10.10.10.1':datetime.datemie(2020,7,16,3,2)}}

So len(self.cardinality_cache[key])  always only one  ,and i don't how to fix it ? Code Bug or i  take a wrong use ?

**Comment by nsano-rururu** [comment]
I've never used this setting, so I'll just guess.

Cardinality
The number of types of field value (currently specified is src_ip) is monitored, and if the number of types exceeds the threshold, alert

In other words, even if a lot of data is registered in the Elasticsearch index, the alert will not skip unless the number of src_ip values exceeds 10 as shown in the example below.
Is this the setting you expected?
Ex) Corresponding cormorant of src_ip

```
10.10.10.1
10.10.10.2
10.10.10.3
10.10.10.4
10.10.10.5
10.10.10.6
10.10.10.7
10.10.10.8
10.10.10.9
10.10.10.10
10.10.10.11
```

**Comment by nsano-rururu** [comment]
rule-types
https://elastalert.readthedocs.io/en/latest/ruletypes.html#rule-types

|Rule type|description|
|---------|-----------|
|Any|Match any result|
|BlackList|If it matches the value registered in the blacklist, alert|
|Whitelist|If it matches with a value other than the value registered in the white list, alert|
|Change|Monitor the fied value and alert when the value changes|
|Frequency|Alert if the number of events that occurred within the set period exceeds the threshold|
|Spike|Count the number of events at the set interval, compare the result immediately before and before, and if it is x times, alert|
|Flatline|Count the number of events at the set interval, and if the number of events is less than the threshold, alert|
|New Term|If the field value is monitored and an unconfirmed value appears, alert|
|Cardinality|Monitor the number of types of field value, and alert if the number of types exceeds the threshold
|Metric Aggregation||
|Spike Aggregation||
|Percentage Match||

**Comment by PonusJang** [comment]
Thanks  .  It is not what i want .  I want to  alert when a  src_ip appears over more than 30 times in a timeframe . So ， i  misunderstood the type 'Cardinality' .  i try if frequency works
