### ISSUE TITLE
How do you make a rule that sends an alert when mount (e.g.  "/software"  ) does not exist on one of the nodes

### ISSUE THREAD

**Issue by talcoh2x** [Yelp/elastalert#2888]
I collect my data with metricbeat

'''
system.filesystem.mount_point :  /software
'''

**Comment by nsano-rururu** [comment]
We also recommend asking questions on the Gitter channel
https://gitter.im/Yelp/elastalert

**Comment by nsano-rururu** [comment]
Yelp/elastalert is no longer maintained. Please use jertel/elastalert. Questions to the discussion below
https://github.com/jertel/elastalert/discussions
