### ISSUE TITLE
Cannot read from .siem-signals-default-000001 index

### ISSUE THREAD

**Issue by francescouk** [Yelp/elastalert#2892]
Hi there,
I know that this may not be an issue, but I would like to know if you guys could point me to the right direction?
I´m trying to extract the alerts out of the SIEM app (Elk) to slack using elastalert.
I don´t think I need to create any rules, only read the index and send to slack. Is that possible?

Many thanks for the attention.

Follow my initial config:
```
alert:
- "slack"
description: Admin User Remote Logon
filter:
- []
index: .siem-signals-default-000001
name: Admin_User_Remote_Logon
priority: 2
realert:
  minutes: 0
type: any
slack:
```

**Comment by nsano-rururu** [comment]
Is this helpful?

[SIEM alerts #2443](https://github.com/Yelp/elastalert/issues/2443)
[master dissertation : ELK stack+elastalert+X-Pack (elastalert doesn't send email) #2498](https://github.com/Yelp/elastalert/issues/2498)

>If you want to extract the alerts out of the SIEM app, you can use a tried a tested tool “Elastalert”. The SIEM app uses a system index called “.siem-signals-default-00001”. This index can be read via Elastalert and the alerts can make it out to your SOC team!
https://www.securitydistractions.com/2020/02/26/creating-detection-rules-in-elastic-siem-app/

**Comment by francescouk** [comment]
@nsano-rururu really appreciate.

That´s exactly what I was looking for. Really appreciate.

Many thanks.
