### ISSUE TITLE
elastalert does not install on amazon linux 2 ec2

### ISSUE THREAD

**Issue by rishi360** [Yelp/elastalert#2909]
elastalert does not install on amazon linux 2 ec2

**Comment by nsano-rururu** [comment]
look
https://elastalert.readthedocs.io/en/latest/running_elastalert.html#

**Comment by nsano-rururu** [comment]
Do you have Python3 installed?

```
# Install Python 3
sudo yum install python3
```

**Comment by rishi360** [comment]
yes, i have first install python3 and started installing elastalert

**Comment by rishi360** [comment]
> look
> https://elastalert.readthedocs.io/en/latest/running_elastalert.html#

thank, let me check

**Comment by nsano-rururu** [comment]
@rishi360 

It seems that another question is being asked, is it already solved? .. If resolved, please close this issue.

**Comment by rishi360** [comment]
closing this now.
