### ISSUE TITLE
How to limit the number of information words generated by alert_text_values

### ISSUE THREAD

**Issue by wajika** [Yelp/elastalert#2913]
my config.yml

![image](https://user-images.githubusercontent.com/17058349/89867583-f43e3c80-dbe3-11ea-909c-58e1ecc36d8e.png)
The content of transaction.custom.data may exceed 2048 bytes, and once it exceeds, other fields will be pushed out of the content.

like this(only three fields are shown)

![image](https://user-images.githubusercontent.com/17058349/89867970-952cf780-dbe4-11ea-8942-c5d76fd126e1.png)

I don't know how to control the size of one of the fields.

I need some help

**Comment by wajika** [comment]
I made changes on alerts.py, but it didn’t work

![image](https://user-images.githubusercontent.com/17058349/89992120-6895e000-dcb7-11ea-9c1f-47f952bad885.png)

I added an enhancements file, but it didn’t work.
```
cat elastalert_enhancements/TimeEnhancement.py 
from elastalert.util import pretty_ts,ts_to_dt,dt_to_ts,lookup_es_key
from elastalert.enhancements import BaseEnhancement

class TimeEnhancement(BaseEnhancement):
    def process(self, match):
        self.ts_field = self.rule.get('timestamp_field', '@timestamp')
        match_ts = match[self.ts_field]
        match[self.local_time] = pretty_ts(match_ts, "True")
        match['transaction.custom.data'] = ['transaction.custom.data'][:500]
```

**Comment by nsano-rururu** [comment]
We also recommend asking questions on the Gitter channel
https://gitter.im/Yelp/elastalert

**Comment by wajika** [comment]
OK, thanks.
