### ISSUE TITLE
Understand how a flatline rule works.

### ISSUE THREAD

**Issue by rashmichoudhary07** [Yelp/elastalert#2918]
@Qmando @PraneetKhandelwal 
I have to use flatline rule for alerting when below threshold events are encountered. i created a flatline rule like below but i fail to understand the logic with which flatline works. Please help.
name: Check Flatine Rule

type: flatline

index: XXXXXXXX

threshold: 5

timeframe:
  minutes: 10

filter:
- query:
    query_string:
      query: "string query"

category: "Warning"

alert_subject: "{0}: Testing flatline"

alert_subject_args:
- category

alert:
 - "email"

email:
 - "XXXXX"
 - "XXXXXX"

**Comment by Qmando** [comment]
Your rule means "Alert when there's less than 5 events (matching that query) in any 10 minute span"

**Comment by rashmichoudhary07** [comment]
Thanks @Qmando  this helped! :)
