### ISSUE TITLE
Elastalert is sending me 0 hits 

### ISSUE THREAD

**Issue by sarahrara18** [Yelp/elastalert#2936]
Hello, I am new to ELK and elast alert , so i am facing some troubles and i hope i can find some help please

elastalert is sending me 0 hits , i tried silving it according to similar posted issues but didn't work for me 
this is what is shown when i test the rule:

C:\Users\siraj\elastalert>elastalert-test-rule --config config.yaml example_rules/example_frequency.yaml
INFO:elastalert:Note: In debug mode, alerts will be logged to console but NOT actually sent.
            To send them but remain verbose, use --verbose instead.
Didn't get any results.
INFO:elastalert:Note: In debug mode, alerts will be logged to console but NOT actually sent.
                To send them but remain verbose, use --verbose instead.
1 rules loaded
INFO:apscheduler.scheduler:Adding job tentatively -- it will be properly scheduled when the scheduler starts
INFO:elastalert:Queried rule Example frequency rule from 2020-08-22 20:03 Temps universel coordonné to 2020-08-22 20:18 Temps universel coordonné: 0 / 0 hits
INFO:elastalert:Queried rule Example frequency rule from 2020-08-22 20:18 Temps universel coordonné to 2020-08-22 20:33 Temps universel coordonné: 0 / 0 hits
INFO:elastalert:Queried rule Example frequency rule from 2020-08-22 20:33 Temps universel coordonné to 2020-08-22 20:48 Temps universel coordonné: 0 / 0 hits
INFO:elastalert:Queried rule Example frequency rule from 2020-08-22 20:48 Temps universel coordonné to 2020-08-22 21:03 Temps universel coordonné: 0 / 0 hits
INFO:elastalert:Queried rule Example frequency rule from 2020-08-22 21:03 Temps universel coordonné to 2020-08-22 21:18 Temps universel coordonné: 0 / 0 hits
INFO:elastalert:Queried rule Example frequency rule from 2020-08-22 21:18 Temps universel coordonné to 2020-08-22 21:33 Temps universel coordonné: 0 / 0 hits
INFO:elastalert:Queried rule Example frequency rule from 2020-08-22 21:33 Temps universel coordonné to 2020-08-22 21:48 Temps universel coordonné: 0 / 0 hits
INFO:elastalert:Queried rule Example frequency rule from 2020-08-22 21:48 Temps universel coordonné to 2020-08-22 22:03 Temps universel coordonné: 0 / 0 hits
INFO:elastalert:Queried rule Example frequency rule from 2020-08-22 22:03 Temps universel coordonné to 2020-08-22 22:18 Temps universel coordonné: 0 / 0 hits
INFO:elastalert:Queried rule Example frequency rule from 2020-08-22 22:18 Temps universel coordonné to 2020-08-22 22:33 Temps universel coordonné: 0 / 0 hits
INFO:elastalert:Queried rule Example frequency rule from 2020-08-22 22:33 Temps universel coordonné to 2020-08-22 22:48 Temps universel coordonné: 0 / 0 hits
INFO:elastalert:Queried rule Example frequency rule from 2020-08-22 22:48 Temps universel coordonné to 2020-08-22 23:03 Temps universel coordonné: 0 / 0 hits
INFO:elastalert:Queried rule Example frequency rule from 2020-08-22 23:03 Temps universel coordonné to 2020-08-22 23:18 Temps universel coordonné: 0 / 0 hits
INFO:elastalert:Queried rule Example frequency rule from 2020-08-22 23:18 Temps universel coordonné to 2020-08-22 23:33 Temps universel coordonné: 0 / 0 hits
INFO:elastalert:Queried rule Example frequency rule from 2020-08-22 23:33 Temps universel coordonné to 2020-08-22 23:48 Temps universel coordonné: 0 / 0 hits
INFO:elastalert:Queried rule Example frequency rule from 2020-08-22 23:48 Temps universel coordonné to 2020-08-23 00:03 Temps universel coordonné: 0 / 0 hits
INFO:elastalert:Queried rule Example frequency rule from 2020-08-23 00:03 Temps universel coordonné to 2020-08-23 00:06 Temps universel coordonné: 0 / 0 hits

Would have written the following documents to writeback index (default is elastalert_status):

elastalert_status - {'rule_name': 'Example frequency rule', 'endtime': datetime.datetime(2020, 8, 23, 0, 6, 3, 855531, tzinfo=tzutc()), 'starttime': datetime.datetime(2020, 8, 22, 20, 3, 39, 855531, tzinfo=tzutc()), 'matches': 0, 'hits': 0, '@timestamp': datetime.datetime(2020, 8, 23, 0, 6, 4, 493513, tzinfo=tzutc()), 'time_taken': 0.15882110595703125}

*********************************************************************************
this is my config.yaml:

rules_folder: example_rules

run_every:
  minutes: 1

buffer_time:
  minutes: 15

es_host: 127.0.0.1

es_port: 9200

writeback_index: elastalert_status
writeback_alias: elastalert_alerts

alert_time_limit:
  days: 2
****************************************************************************
this is my example_frequency.yaml

name: Example frequency rule

type: frequency

index: testing

num_events: 5

timeframe:
  hours: 4
  
timestamp_field: "@timestamp"

filter:
- term:
    loglevel: "ERROR"

alert:
- "email"

email:
- "myemail@gmail.com"
*************************************************************************
and this is a field of my data in elasticsearch : (NOTE: i used my machine time as a timestamp in purpose cause i am using an old logfile)

{
  "_index": "testing",
  "_type": "_doc",
  "_id": "ODKgGHQByKXc1OuBru_q",
  "_version": 1,
  "_score": null,
  "_source": {
    "msg": "c.t.veon.metadata.VeonMetadata VeonMetadata[id=dd393b32-6e4e-1696-8876-107f25c97160] Starting feed ccn_voice_cs5",
    "message": "2020-01-05 13:56:09,930 INFO [Timer-Driven Process Thread-15] c.t.veon.metadata.VeonMetadata VeonMetadata[id=dd393b32-6e4e-1696-8876-107f25c97160] Starting feed ccn_voice_cs5",
    "host": {
      "id": "fb6f4b1c-79b1-49ec-9094-d66b52825ffa",
      "name": "DESKTOP-2313AN5",
      "os": {
        "name": "Windows 10 Pro",
        "version": "10.0",
        "family": "windows",
        "kernel": "10.0.16299.1087 (WinBuild.160101.0800)",
        "platform": "windows",
        "build": "16299.1087"
      },
      "hostname": "DESKTOP-2313AN5",
      "architecture": "x86_64"
    },
    "@timestamp": "2020-08-23T00:03:17.526Z",
    "loglevel": "INFO",
    "@version": "1",
    "thread": "Timer-Driven Process Thread-15",
    "log": {
      "offset": 11777040,
      "file": {
        "path": "c:\\Users\\siraj\\Desktop\\P_F_E\\logz\\log7.log"
      }
    },
    "ecs": {
      "version": "1.0.0"
    },
    "agent": {
      "ephemeral_id": "23a9d198-124a-4a86-b99f-5f671e428f9a",
      "version": "7.0.0",
      "type": "filebeat",
      "hostname": "DESKTOP-2313AN5",
      "id": "4747ae40-c915-4a6d-acb8-8b5e5ca9d16a"
    },
    "tags": [
      "beats_input_codec_plain_applied"
    ],
    "time": "2020-01-05 13:56:09,930",
    "type": "test",
    "input": {
      "type": "log"
    }
  },
  "fields": {
    "@timestamp": [
      "2020-08-23T00:03:17.526Z"
    ]
  },
  "sort": [
    1598140997526
  ]
}

**Comment by Qmando** [comment]
The issue probably the automatic string analyzer that Elasticsearch does. When you do a `term` search, it's looking for exact matches on the INDEXED value. By default, that means it gets lowercased. Try
```
filter:
  term:
    loglevel: "error"
```

**Comment by sarahrara18** [comment]
@Qmando thank you so much for the reply , i tried the second proposition and it worked for me.
