### ISSUE TITLE
balacklist query hits but no matches no alerts

### ISSUE THREAD

**Issue by huangyonghome** [Yelp/elastalert#2937]
I want to use the blacklist type to monitor the php error log.I would get alert, if the "Fatal" word appear in logs.The original log looks like below:

`
[24-Aug-2020 17:30:06 Asia/Shanghai] PHP Notice:  Undefined index: branch_id in /data/www/internal_api.com/releases/69/20200821-140550/app/modules/User/actions/Favorite/FavoriteList.php on line 84
`
The entry log store in Elasticsearch as message filed . below is my balcklist type rule:

name:  monitor the fatal,error log in php-fpm log
type: blacklist
index: logstash-*-fpm-error-*
timeframe:  
  minutes: 0  
compare_key: message 
 
blacklist:  
    - "Notice" 

The ElastAlert actually hits the query, but why got no alerts?

`
[root@idc-function-elk02 elastalert]# python3  -m elastalert.elastalert --verbose --rule /data/elastalert/rules/php-fpm.yaml
1 rules loaded
INFO:elastalert:Starting up
INFO:elastalert:Disabled rules are: []
INFO:elastalert:Sleeping for 59.999915 seconds
INFO:elastalert:Queried rule monitor the fatal,error log in php-fpm log from 2020-08-24 16:46 CST to 2020-08-24 17:01 CST: 607 / 607 hits
INFO:elastalert:Ran monitor the fatal,error log in php-fpm log from 2020-08-24 16:46 CST to 2020-08-24 17:01 CST: 607 query hits (0 already seen), 0 matches, 0 alerts sent
`

did I miss some configurations? or  did I have to parse the error log and put the key word(Fatal) into a special field?

Your help is very much appreciated

**Comment by Qmando** [comment]
the blacklist type only alerts when the *exact* value appears in that field. You maybe want to try
```
type: any
query:
  query_string:
    query: "PHP Notice"
```

The blacklist type is less efficient if you're just searching for a single term.

**Comment by huangyonghome** [comment]
Thank you very much .it works for me
