### ISSUE TITLE
misaligned yaml format 

### ISSUE THREAD

**Issue by yabetsu93** [Yelp/elastalert#2938]
https://github.com/Yelp/elastalert/blob/f4bad06f35e44d664072f9a7a80580650c62fbef/example_rules/ssh.yaml#L2

**Comment by yabetsu93** [comment]
will create a pr

**Comment by yabetsu93** [comment]
will open this one line code

**Comment by nsano-rururu** [comment]
https://github.com/Yelp/elastalert/pull/2692

**Comment by nsano-rururu** [comment]
@yabetsu93  ping

**Comment by yabetsu93** [comment]
@nsano-rururu thanks
