### ISSUE TITLE
mapper_parsing_exception', "failed to parse field [match_body.host.os.version - Elasticsearch 7.9

### ISSUE THREAD

**Issue by jijojohn1985** [Yelp/elastalert#2949]
Hi Team,

I am getting this error with an elastalert rule. I am using latest version of elasticsearch 7.9. and comparing an auditbeat document.Please help.

ERROR:root:Error writing alert info to Elasticsearch: RequestError(400, 'mapper_parsing_exception', "failed to parse field [match_body.host.os.version] of type [float] in document with id '0lrUOnQBX9Odf7bE1dIq'. Preview of field's value: '7 (Core)'")

Thanks,
Jijo John

**Comment by vtdat** [comment]
> Hi Team,
> 
> I am getting this error with an elastalert rule. I am using latest version of elasticsearch 7.9. and comparing an auditbeat document.Please help.
> 
> ERROR:root:Error writing alert info to Elasticsearch: RequestError(400, 'mapper_parsing_exception', "failed to parse field [match_body.host.os.version] of type [float] in document with id '0lrUOnQBX9Odf7bE1dIq'. Preview of field's value: '7 (Core)'")
> 
> Thanks,
> Jijo John

Did you accidentally enable [numeric-detection](https://www.elastic.co/guide/en/elasticsearch/reference/current/dynamic-field-mapping.html#numeric-detection)? The current mapping to `os.version` is `float` and you're trying to put `7 (Core)`, which is a string, to it.
