### ISSUE TITLE
Unable to build on Ubuntu

### ISSUE THREAD

**Issue by brmakana** [Yelp/elastalert#295]
Hello,

I'm unable to get v0.0.65 to build on ubuntu:

```
Processing dependencies for elastalert==0.0.65
Searching for blist
Reading https://pypi.python.org/simple/blist/
Best match: blist 1.3.6
Downloading https://pypi.python.org/packages/source/b/blist/blist-1.3.6.tar.gz#md5=a538f1a24b9191e3c40252e9397408a9
Processing blist-1.3.6.tar.gz
Writing /tmp/easy_install-46EBcn/blist-1.3.6/setup.cfg
Running blist-1.3.6/setup.py -q bdist_egg --dist-dir /tmp/easy_install-46EBcn/blist-1.3.6/egg-dist-tmp-5PZ2Gd
warning: no files found matching 'blist.rst'
unable to execute 'x86_64-linux-gnu-gcc': No such file or directory
error: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```

I'm trying to build it inside a Docker container, here's the Dockerfile:
```
FROM	ubuntu

RUN	apt-get update && \
	apt-get upgrade -y && \
	apt-get install -y python git python-setuptools curl
RUN	apt-get upgrade -y

RUN	cd /root && \
	curl https://codeload.github.com/Yelp/elastalert/tar.gz/v0.0.65 -o elastalert.tar.gz && \
	tar -zxf elastalert.tar.gz && \
	mv elastalert-0.0.65 elastalert
RUN	cd /root/elastalert/ && \
	python setup.py install
```

**Comment by Minjung** [comment]
Well, the error is clearly stating you don't have gcc and your Dockerfile doesn't provide for that.
To build most python packages from source you will need to install at least build-essentials and python-dev, depending on the dependencies you will probably need other stuff like libffi-dev (which is very common)

**Comment by krizsan** [comment]
Hi! If it is of any help, I have a Docker image with Elastalert here (https://github.com/krizsan/elastalert-docker) and on DockerHub (https://hub.docker.com/r/ivankrizsan/elastalert/).

**Comment by brmakana** [comment]
Thanks for the replies, and thanks @krizsan as that helps a lot!
