### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:877)

### ISSUE THREAD

**Issue by vikasgurlinka** [Yelp/elastalert#2974]
Hi @Qmando @danielpops @snuids @JeffAshton @alvarolmedo,
I have been trying to enable SSL for elastalert with Elasticsearch encountered the below exception. 
How can I configure elastalert if I have an intermediate and Digi certificate? 

`requests.exceptions.SSLError: HTTPSConnectionPool(host='192.*****', port=9200): Max retries exceeded with url: /secops-awsct-lstash-*/_search?_source_includes=%2A%2C%40timestamp&ignore_unavailable=true&scroll=30s&size=1 (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:877)'),))
`

**Comment by alvarolmedo** [comment]
Maybe enable SSL and no verify is an option.

**Comment by JeffAshton** [comment]
We exclusively use SSL for Elasticsearch.  Maybe make sure your OS is patched appropriately and validate with a browser that your certificate is valid?

**Comment by vikasgurlinka** [comment]
@alvarolmedo, @JeffAshton  Thanks for your comments.

The issue got resolved after we configured ca_certs with a certificate chain of intermediate and Digi certificates.

cat digi-cert.crt intermediate-cert.crt  > cert_chain.crt

**Comment by lightmansor** [comment]
> @alvarolmedo, @JeffAshton Thanks for your comments.
> 
> The issue got resolved after we configured ca_certs with a certificate chain of intermediate and Digi certificates.
> 
> cat digi-cert.crt intermediate-cert.crt > cert_chain.crt


How do you do this?
Is there a step by step?
