### ISSUE TITLE
Global options for alerters

### ISSUE THREAD

**Issue by imreFitos** [Yelp/elastalert#298]
Hipchat alerter requires that hipchat_auth_token and hipchat_room_id are specified in all the rules that use it. 

How could we set global defaults in the main config file for alerter options?

**Comment by Qmando** [comment]
Right now, certain options are cherry-picked from the global config to each rule, such as ``es_host``, ``buffer_time`` and ``smtp_host``. It might make sense to have a global config namespace where everything inside will be copied to each rule.

**Comment by fiunchinho** [comment]
I was looking for the same feature. It's really not the best option having to write the same configuration in all the alerters :(

**Comment by hilt86** [comment]
+1 for this...having credentials in the rules prevents them from being added to source control too!

**Comment by rmihael** [comment]
To have rule files under Puppet/Chef templates is really inconvenient. I think that by defining alerters in config.yaml and just referencing them from rules will make ElastAlert configuration management much simpler.
