### ISSUE TITLE
Elastalert metric aggregation values

### ISSUE THREAD

**Issue by yashdream11** [Yelp/elastalert#2986]
I need to send aggregated value in alerts as part of message How am I supposed to get it below is my rule config where I need to get metric_agg value which alert has calculated
name: druid_query_time_v1

type: metric_aggregation

index: druid-metric-*

metric_agg_key: value

metric_agg_type: avg

filter:
- query:
    query_string:
      query: "metric.keyword: query/time"

timestamp_field: timestamp
timestamp_type: iso

max_threshold : 500

buffer_time:
  minutes: 2

doc_type: _doc 

realert: 
  minutes: 2  

alert:
 - slack

alert_text: "Avg query time {0} has increased more than 5 sec"
alert_text_args:
 - metric_agg

alert_text_type: alert_text_only
slack_webhook_url: "*****************"

**Comment by nsano-rururu** [comment]
The value of slack_webhook_url should not be left as it is. You should fix it like "xxxx"

**Comment by nsano-rururu** [comment]
Looking at past issues, it seems that standard features cannot be used. I feel like I need to create a [custom rule](https://elastalert.readthedocs.io/en/latest/recipes/adding_rules.html) myself.

[Alert on sum of values (avg/sum aggregation) #1288](https://github.com/Yelp/elastalert/issues/1288)

**Comment by yashdream11** [comment]
I was able to get name of variable `metric_value_avg` in this case by removing `alert_text_type: alert_text_only` from config.
