### ISSUE TITLE
Possible to include key value in slack title or body

### ISSUE THREAD

**Issue by ocofaigh** [Yelp/elastalert#2989]
Is it possible to include key values in a slack alert title?
I have tried: `slack_title: "Detected Failed DC Query - %(Service)s:%(Environment)s"`

but it just shows like:
<img width="460" alt="image" src="https://user-images.githubusercontent.com/29608224/96386877-28128100-1196-11eb-8312-c12508f74912.png">

Even if it is not possible to add in the slack title, is it possible to include it in the body somehow? It has to be in the format:
`SERVICE:ENVIRONMENT` where Service and Environment are two separate fields in elasticsearch.
The body already includes these fields and values, however I need it in the above format so it can be searched in slack.

Thanks

**Comment by nsano-rururu** [comment]
look
https://github.com/Yelp/elastalert/issues/2789

**Comment by ocofaigh** [comment]
Thank you @nsano-rururu 
I was able to achieve what I needed by doing this:

```
alert:
  - "slack"
slack:
slack_webhook_url: https://hooks.slack.com/services/TXXXXXXXX/BXXXXXXXX/TXXXXXXXXXXXXXX
alert_subject: "Detected Failed DC Query - {0}:{1}"
alert_subject_args:
  - Service
  - Environment
```
