### ISSUE TITLE
blacklist line limit

### ISSUE THREAD

**Issue by jeff419** [Yelp/elastalert#3015]
hi,

I have a blacklist of 25,000 lines. When I define the elastalert rule, I get an error as follows. Are there any limitations on this issue?

error:

error running query: [Failed to parse query dstip: "1.1.1.1" OR ....] ....... (65534 charecters removed)

**Comment by nsano-rururu** [comment]
look
[Blacklist filter with 10.000+ terms is extremely slow #1867](https://github.com/Yelp/elastalert/issues/1867)

**Comment by nsano-rururu** [comment]
https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking-changes-7.0.html#_limiting_the_number_of_terms_that_can_be_used_in_a_terms_query_request

**Comment by jeff419** [comment]
thanks. I splitted blacklist file by 1024 line. its work.
