### ISSUE TITLE
urllib3 version error while installing

### ISSUE THREAD

**Issue by lastbulletbender** [Yelp/elastalert#3037]
Getting the following error while running setup

[91merror: urllib3 1.26.1 is installed but urllib3<1.26,>=1.25.4 is required by {'botocore'}
[0mThe command '/bin/sh -c python setup.py install' returned a non-zero code: 1

urllib3 version 1.26.1 and 1.26.0 were released recently.

Pinning urllib3<1.26 in setup.py fixes the build, but I am not sure why it says that botocore requires those versions (as botocore/boto3 new versions were released as well)

I can paste the complete setup output if needed.

**Comment by ocofaigh** [comment]
Also seeing this:

```
Traceback (most recent call last):
 File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 570, in _build_master
  ws.require(__requires__)
 File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 888, in require
  needed = self.resolve(parse_requirements(requirements))
 File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 779, in resolve
  raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (urllib3 1.26.1 (/usr/local/lib/python3.6/site-packages), Requirement.parse('urllib3<1.26,>=1.25.4; python_version != "3.4"'), {'botocore'})
```

We worked around it by pinning `urllib3==1.25.11`

**Comment by lastbulletbender** [comment]
Is it possible that this needs to be updated on botocore? https://github.com/boto/botocore/blob/1.19.16/setup.cfg

I don't understand setuptools, so this is just a shot in the dark

**Comment by lastbulletbender** [comment]
The botocore wheel is being downloaded has incorrect version in metadata.json

botocore-1.19.16-py2.py3-none-any.whl


    "run_requires": [
        {
            "environment": "python_version!='3.4'",
            "requires": [
                "urllib3>=1.25.4,<1.26"
            ]
        },
        {
            "requires": [
                "python-dateutil>=2.1,<3.0.0",
                "jmespath>=0.7.1,<1.0.0"
            ]
        },
        {
            "environment": "python_version=='3.4'",
            "requires": [
                "urllib3>=1.25.4,<1.25.8"
            ]
        }
    ],

**Comment by lastbulletbender** [comment]
This has fixed the issue for me https://github.com/boto/botocore/commit/df13894e824833416199072968d6798c936e1028

@ocofaigh Can you check if the issue is resolved for you? Else I'll close the issue.

**Comment by ocofaigh** [comment]
Yes fixed for us. Thanks. Yiu can close this.
