### ISSUE TITLE
Is it possible to pass values from the rule to a command that is being executed? 

### ISSUE THREAD

**Issue by kylesci** [Yelp/elastalert#3043]
Wondering if it is possible to pass values from the rule file to a command that the rule being triggered

example:
```
name: an elastalert name
type: frequency
index: a_index
num_events: 25

alert:
  - command 
command: ["some_script.sh", name, num_events]

```

**Comment by nsano-rururu** [comment]
I think that it can be done because there is a description example when accessing the field in the document.
https://elastalert.readthedocs.io/en/latest/ruletypes.html#command

**Comment by nsano-rururu** [comment]
look
https://github.com/Yelp/elastalert/issues/2218

**Comment by kylesci** [comment]
Thanks for the info, #2218 was what confirmed it.
