### ISSUE TITLE
failed to create index [elastalert_status]

### ISSUE THREAD

**Issue by leon-zhang-guoao** [Yelp/elastalert#3051]
My version of elastic slack is 7.2.0.
elasticsearch-python version is 7.0.0
When I run elastalert-create-index and am prompted to enter the configuration, it doesn't work.
this is error message:
`Traceback (most recent call last):
  File "/usr/local/python3.6/bin/elastalert-create-index", line 11, in <module>
    load_entry_point('elastalert==0.2.4', 'console_scripts', 'elastalert-create-index')()
  File "/usr/local/python3.6/lib/python3.6/site-packages/elastalert-0.2.4-py3.6.egg/elastalert/create_index.py", line 264, in main
    create_index_mappings(es_client=es, ea_index=index, recreate=args.recreate, old_ea_index=old_index)
  File "/usr/local/python3.6/lib/python3.6/site-packages/elastalert-0.2.4-py3.6.egg/elastalert/create_index.py", line 55, in create_index_mappings
    es_index.create(index_name)
  File "/usr/local/python3.6/lib/python3.6/site-packages/elasticsearch/client/utils.py", line 84, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/python3.6/lib/python3.6/site-packages/elasticsearch/client/indices.py", line 101, in create
    "PUT", _make_path(index), params=params, body=body
  File "/usr/local/python3.6/lib/python3.6/site-packages/elasticsearch/transport.py", line 318, in perform_request
    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)
  File "/usr/local/python3.6/lib/python3.6/site-packages/elasticsearch/connection/http_requests.py", line 91, in perform_request
    self._raise_error(response.status_code, raw_data)
  File "/usr/local/python3.6/lib/python3.6/site-packages/elasticsearch/connection/base.py", line 131, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.RequestError: RequestError(400, 'validation_exception', 'failed to create index [elastalert_status]')
`
Can help me with this?

**Comment by nsano-rururu** [comment]
Please share your config.yaml, rule.yaml.

**Comment by nsano-rururu** [comment]
# 127.0.0.1 for the same location as elastalert. If not, specify the IP address of the server
curl -XGET 'http://127.0.0.1:9200/elastalert_status/_mapping/'

**Comment by nsano-rururu** [comment]
Do you use python virtualenv when setting up elastalert?
setup is "pip install elastalert" 
or 
"git clone https://github.com/Yelp/elastalert.git" and  "pip install" setuptools> = 11.3 "" and "python setup.py install"

**Comment by nsano-rururu** [comment]
elastic slack is 7.2.0 installed directly or Docker?

**Comment by leon-zhang-guoao** [comment]
conf.yaml
`buffer_time:
  minutes: 15
es_host: 10.88.130.215
es_port: 9600
es_username: elastic
es_password: xxx
alert_time_limit:
 days: 2
`
rule_demo.yaml
`
 es_host: 10.88.130.215

 es_port: 9600

 es_username: elastic
 es_password: synnex

 name: Example frequency rule

 type: frequency

 index: heartbeat-*


 num_events: 10

 timeframe:
   hours: 1


 filter:
 - term:
     monitor.status: "up"


 alert:
 - "email"


 email:
 - "xx@xx.com"
`
run get elastalert_status/_mapping/ 
`"type": "index_not_found_exception",
        "reason": "no such index [elastalert_status]",
        "resource.type": "index_or_alias",
        "resource.id": "elastalert_status",
        "index_uuid": "_na_",
        "index": "elastalert_status"`
I got it from git and ran pip install" setuptools> = 11.3 "" and "python setup.py install"
7.20 installed directly

**Comment by nsano-rururu** [comment]
Please share your elasticsearch.yml.
Edit the IP address, username, and password to xxxx. Please do not put the actual value

**Comment by nsano-rururu** [comment]
Are you aware that elastalert and elasticsearch are running on different servers?

**Comment by nsano-rururu** [comment]
Is there the following setting in elasticsearch.yml?

```
http.port: 9600
network.host: 0.0.0.0
```

**Comment by leon-zhang-guoao** [comment]
Thank you for your enthusiasm.
I've fixed it.
The reason is that the maximum number of shard was exceeded.
