### ISSUE TITLE
Disk Space Usage Alert With Elastalert

### ISSUE THREAD

**Issue by saiprathapdp** [Yelp/elastalert#3052]
we are trying below rule for disk usage alert in elast alert.

es_host: node1.elkstack.es.local
es_port: 9200

name: "$ea_hostname:  CRITICAL : Disk Usage Alert"
index: metricbeat-*

type: any 

realert:
  minutes: 15

filter:
- query:
  - query_string:
      query: "beat.hostname"
- query:
  - query_string:
      query: "(system.filesystem.used.pct:[0.20 TO 1.0] AND system.filesystem.total: <2000000000001)"

query_delay:
  minutes: 1
query_key: host

alert_text_type: alert_text_only
include : ["host","system.filesystem.used.pct","system.filesystem.mount_point"]

alert:
- "Emai"
alert_text: "
*Used %*        : {0}\n
*Mount Point*   : {2}\n
*Host*          : {1}\n
*ElastAlert Node*  : $ea_hostname"

alert_text_args: ["system.filesystem.used.pct","host","system.filesystem.mount_point"]

- "covid@gmail.com"
smtp_host: mail.covid.com
smtp_port: 25 
from_addr: elkadmin@mail.covid.com

we can see only 0 alert has been sent while running this. But we can see the disk usage is crossed 50% in metricbet-* index.

**Comment by nsano-rururu** [comment]
https://github.com/Yelp/elastalert/issues/1807

**Comment by nsano-rururu** [comment]
https://github.com/Yelp/elastalert/issues/1679#issuecomment-387129314

**Comment by nsano-rururu** [comment]
We also recommend asking questions on the Gitter channel
https://gitter.im/Yelp/elastalert

**Comment by saiprathapdp** [comment]
Thanks For your support
