### ISSUE TITLE
Time stamp issue (elastic to zabbix)

### ISSUE THREAD

**Issue by mario96000** [Yelp/elastalert#3069]
Hello, im trying to setup elastalert to send alerts to zabbix for a school project. Not that experienced yet but this is the following error that im getting:
![image](https://user-images.githubusercontent.com/71070469/102371909-fc0d5380-3fbe-11eb-9bb3-6c0cb5d633bd.png)
The time format in elasticsearch says date/default format: MMM D, YYYY @ HH:mm:ss.SSS so i tried adding this in my yaml file but that didnt work either. Any idea how i would resolve this?

**Comment by nsano-rururu** [comment]
https://github.com/Yelp/elastalert/issues/616
