### ISSUE TITLE
Zabbix module

### ISSUE THREAD

**Issue by mario96000** [Yelp/elastalert#3080]
I get the following error, how can i resolve this issue?
![image](https://user-images.githubusercontent.com/71070469/103541797-34a49c80-4e9c-11eb-95c3-b5e6d5280afa.png)

**Comment by nsano-rururu** [comment]
pip install "py-zabbix>=1.1.3"

and 

patch
[Bugfix and better error handling on zabbix alerter #2640](https://github.com/Yelp/elastalert/issues/3080)

**Comment by nsano-rururu** [comment]
Due to a correction error by the maintainer, py-zabbix is not described in setup.py.
