### ISSUE TITLE
elastalert-create-index error

### ISSUE THREAD

**Issue by Lee-Z** [Yelp/elastalert#3099]
elastalert-create-index --config config.yaml
Traceback (most recent call last):
  File "/usr/bin/elastalert-create-index", line 11, in <module>
    load_entry_point('elastalert==0.2.4', 'console_scripts', 'elastalert-create-index')()
  File "/usr/local/python3/lib/python3.7/site-packages/elastalert-0.2.4-py3.7.egg/elastalert/create_index.py", line 249, in main
    profile_name=args.profile)
  File "/usr/local/python3/lib/python3.7/site-packages/elastalert-0.2.4-py3.7.egg/elastalert/auth.py", line 51, in __call__
    return username + ':' + password
TypeError: can only concatenate str (not "int") to str

++++++++++++++++++++++++++++++++++++++++++++++++++++
.egrep  -v "*#|^$" config.yaml 
rules_folder: example_rules
run_every:
  minutes: 1
buffer_time:
  minutes: 15
es_host: 192.168.99.185
es_port: 9200
es_username: elastic
es_password: ******
writeback_index: elastalert_status
writeback_alias: elastalert_alerts
alert_time_limit:
  days: 2
+++++++++++++++++++++++++++++++++++++
Python version:3.7.8
elastalert==0.2.4
elasticsearch=7.0.0

**Comment by nsano-rururu** [comment]
The data types of es_username and es_password are defined as string in schema.yaml, and an error will occur if they are different from the settings in schema.yaml. Enclose the values of es_username and es_password in double quotes and execute elastalert-create-index again.

**Comment by Lee-Z** [comment]
[root@localhost elastalert]# elastalert-create-index --config config.yaml
Elastic Version: 7.10.1
Reading Elastic 6 index mappings:
Reading index mapping 'es_mappings/6/silence.json'
Reading index mapping 'es_mappings/6/elastalert_status.json'
Reading index mapping 'es_mappings/6/elastalert.json'
Reading index mapping 'es_mappings/6/past_elastalert.json'
Reading index mapping 'es_mappings/6/elastalert_error.json'
New index elastalert_status created
Done!

good！！！
