### ISSUE TITLE
urllib3 1.24.3 is installed but urllib3<1.27,>=1.25.4; python_version != "3.4" is required by {'botocore'}

### ISSUE THREAD

**Issue by xinjizhiwa** [Yelp/elastalert#3112]
I have already installed urllib3-1.25.8, but when I run the command ‘python setup.py install’, it will automatically install urllib3-1.24.3, and then an error occurs, below is the error log after running the command .  

log：
running install
running bdist_egg
running egg_info
writing elastalert.egg-info/PKG-INFO
writing dependency_links to elastalert.egg-info/dependency_links.txt
writing entry points to elastalert.egg-info/entry_points.txt
writing requirements to elastalert.egg-info/requires.txt
writing top-level names to elastalert.egg-info/top_level.txt
reading manifest file 'elastalert.egg-info/SOURCES.txt'
writing manifest file 'elastalert.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/elastalert
copying build/lib/elastalert/__init__.py -> build/bdist.linux-x86_64/egg/elastalert
copying build/lib/elastalert/alerts.py -> build/bdist.linux-x86_64/egg/elastalert
copying build/lib/elastalert/auth.py -> build/bdist.linux-x86_64/egg/elastalert
copying build/lib/elastalert/config.py -> build/bdist.linux-x86_64/egg/elastalert
copying build/lib/elastalert/create_index.py -> build/bdist.linux-x86_64/egg/elastalert
copying build/lib/elastalert/elastalert.py -> build/bdist.linux-x86_64/egg/elastalert
copying build/lib/elastalert/enhancements.py -> build/bdist.linux-x86_64/egg/elastalert
copying build/lib/elastalert/kibana.py -> build/bdist.linux-x86_64/egg/elastalert
copying build/lib/elastalert/kibana_discover.py -> build/bdist.linux-x86_64/egg/elastalert
copying build/lib/elastalert/loaders.py -> build/bdist.linux-x86_64/egg/elastalert
copying build/lib/elastalert/opsgenie.py -> build/bdist.linux-x86_64/egg/elastalert
copying build/lib/elastalert/rule_from_kibana.py -> build/bdist.linux-x86_64/egg/elastalert
copying build/lib/elastalert/ruletypes.py -> build/bdist.linux-x86_64/egg/elastalert
copying build/lib/elastalert/test_rule.py -> build/bdist.linux-x86_64/egg/elastalert
copying build/lib/elastalert/util.py -> build/bdist.linux-x86_64/egg/elastalert
copying build/lib/elastalert/zabbix.py -> build/bdist.linux-x86_64/egg/elastalert
copying build/lib/elastalert/schema.yaml -> build/bdist.linux-x86_64/egg/elastalert
creating build/bdist.linux-x86_64/egg/elastalert/es_mappings
creating build/bdist.linux-x86_64/egg/elastalert/es_mappings/5
copying build/lib/elastalert/es_mappings/5/elastalert.json -> build/bdist.linux-x86_64/egg/elastalert/es_mappings/5
copying build/lib/elastalert/es_mappings/5/elastalert_error.json -> build/bdist.linux-x86_64/egg/elastalert/es_mappings/5
copying build/lib/elastalert/es_mappings/5/elastalert_status.json -> build/bdist.linux-x86_64/egg/elastalert/es_mappings/5
copying build/lib/elastalert/es_mappings/5/past_elastalert.json -> build/bdist.linux-x86_64/egg/elastalert/es_mappings/5
copying build/lib/elastalert/es_mappings/5/silence.json -> build/bdist.linux-x86_64/egg/elastalert/es_mappings/5
creating build/bdist.linux-x86_64/egg/elastalert/es_mappings/6
copying build/lib/elastalert/es_mappings/6/elastalert.json -> build/bdist.linux-x86_64/egg/elastalert/es_mappings/6
copying build/lib/elastalert/es_mappings/6/elastalert_error.json -> build/bdist.linux-x86_64/egg/elastalert/es_mappings/6
copying build/lib/elastalert/es_mappings/6/elastalert_status.json -> build/bdist.linux-x86_64/egg/elastalert/es_mappings/6
copying build/lib/elastalert/es_mappings/6/past_elastalert.json -> build/bdist.linux-x86_64/egg/elastalert/es_mappings/6
copying build/lib/elastalert/es_mappings/6/silence.json -> build/bdist.linux-x86_64/egg/elastalert/es_mappings/6
creating build/bdist.linux-x86_64/egg/tests
copying build/lib/tests/__init__.py -> build/bdist.linux-x86_64/egg/tests
copying build/lib/tests/alerts_test.py -> build/bdist.linux-x86_64/egg/tests
copying build/lib/tests/auth_test.py -> build/bdist.linux-x86_64/egg/tests
copying build/lib/tests/base_test.py -> build/bdist.linux-x86_64/egg/tests
copying build/lib/tests/conftest.py -> build/bdist.linux-x86_64/egg/tests
copying build/lib/tests/create_index_test.py -> build/bdist.linux-x86_64/egg/tests
copying build/lib/tests/elasticsearch_test.py -> build/bdist.linux-x86_64/egg/tests
copying build/lib/tests/kibana_discover_test.py -> build/bdist.linux-x86_64/egg/tests
copying build/lib/tests/kibana_test.py -> build/bdist.linux-x86_64/egg/tests
copying build/lib/tests/loaders_test.py -> build/bdist.linux-x86_64/egg/tests
copying build/lib/tests/rules_test.py -> build/bdist.linux-x86_64/egg/tests
copying build/lib/tests/util_test.py -> build/bdist.linux-x86_64/egg/tests
byte-compiling build/bdist.linux-x86_64/egg/elastalert/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/elastalert/alerts.py to alerts.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/elastalert/auth.py to auth.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/elastalert/config.py to config.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/elastalert/create_index.py to create_index.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/elastalert/elastalert.py to elastalert.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/elastalert/enhancements.py to enhancements.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/elastalert/kibana.py to kibana.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/elastalert/kibana_discover.py to kibana_discover.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/elastalert/loaders.py to loaders.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/elastalert/opsgenie.py to opsgenie.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/elastalert/rule_from_kibana.py to rule_from_kibana.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/elastalert/ruletypes.py to ruletypes.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/elastalert/test_rule.py to test_rule.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/elastalert/util.py to util.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/elastalert/zabbix.py to zabbix.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/tests/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/tests/alerts_test.py to alerts_test.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/tests/auth_test.py to auth_test.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/tests/base_test.py to base_test.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/tests/conftest.py to conftest.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/tests/create_index_test.py to create_index_test.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/tests/elasticsearch_test.py to elasticsearch_test.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/tests/kibana_discover_test.py to kibana_discover_test.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/tests/kibana_test.py to kibana_test.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/tests/loaders_test.py to loaders_test.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/tests/rules_test.py to rules_test.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/tests/util_test.py to util_test.cpython-36.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying elastalert.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying elastalert.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying elastalert.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying elastalert.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying elastalert.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying elastalert.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
elastalert.__pycache__.create_index.cpython-36: module references __file__
elastalert.__pycache__.loaders.cpython-36: module references __file__
creating 'dist/elastalert-0.2.4-py3.6.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing elastalert-0.2.4-py3.6.egg
removing '/usr/local/lib/python3.6/site-packages/elastalert-0.2.4-py3.6.egg' (and everything under it)
creating /usr/local/lib/python3.6/site-packages/elastalert-0.2.4-py3.6.egg
Extracting elastalert-0.2.4-py3.6.egg to /usr/local/lib/python3.6/site-packages
elastalert 0.2.4 is already the active version in easy-install.pth
Installing elastalert script to /usr/local/bin
Installing elastalert-create-index script to /usr/local/bin
Installing elastalert-rule-from-kibana script to /usr/local/bin
Installing elastalert-test-rule script to /usr/local/bin

Installed /usr/local/lib/python3.6/site-packages/elastalert-0.2.4-py3.6.egg
Processing dependencies for elastalert==0.2.4
Searching for urllib3<1.25,>=1.21.1
Reading https://pypi.org/simple/urllib3/
Downloading https://files.pythonhosted.org/packages/01/11/525b02e4acc0c747de8b6ccdab376331597c569c42ea66ab0a1dbd36eca2/urllib3-1.24.3-py2.py3-none-any.whl#sha256=a637e5fae88995b256e3409dc4d52c2e2e0ba32c42a6365fee8bbd2238de3cfb
Best match: urllib3 1.24.3
Processing urllib3-1.24.3-py2.py3-none-any.whl
Installing urllib3-1.24.3-py2.py3-none-any.whl to /usr/local/lib/python3.6/site-packages
Adding urllib3 1.24.3 to easy-install.pth file

Installed /usr/local/lib/python3.6/site-packages/urllib3-1.24.3-py3.6.egg
error: urllib3 1.24.3 is installed but urllib3<1.27,>=1.25.4; python_version != "3.4" is required by {'botocore'} 

Thank you so much for someone who can provide a solution.

**Comment by nsano-rururu** [comment]
https://github.com/Yelp/elastalert/issues/3037

**Comment by nsano-rururu** [comment]
Is it a problem that occurs even if I create a virtual environment of python3.6 for elastalert and set it up in the virtual environment of python3.6?

**Comment by xinjizhiwa** [comment]
> Is it a problem that occurs even if I create a virtual environment of python3.6 for elastalert and set it up in the virtual environment of python3.6?
