### ISSUE TITLE
Elastalert server

### ISSUE THREAD

**Issue by tarekkilani** [Yelp/elastalert#3114]
Hello,

Please i'm trying to install Praeco to have a GUI of alerts with Elasticsearch.
To do that we need to install 3 projects : Elasalert, Elastalert-server and Praeco.
When i intalled Elastalert-server i get this.

`10:10:16.209Z  INFO elastalert-server: Server:  Server started
14:53:04.907Z ERROR elastalert-server:
    ProcessController:  /usr/lib/python3/dist-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.26.3) or chardet (3.0.4) doesn't match a supported version!
      RequestsDependencyWarning)
    WARNING:apscheduler.executors.default:Run time of job "ElastAlerter.handle_pending_alerts (trigger: interval[0:01:00], next run at: 2021-02-04 15:53:16 CET)" was missed by 0:00:45.361848
    WARNING:apscheduler.executors.default:Run time of job "ElastAlerter.handle_config_change (trigger: interval[0:01:00], next run at: 2021-02-04 15:53:16 CET)" was missed by 0:00:46.195447
    
14:53:19.335Z ERROR elastalert-server:
    ProcessController:  WARNING:apscheduler.executors.default:Run time of job "ElastAlerter.handle_pending_alerts (trigger: interval[0:01:00], next run at: 2021-02-04 15:53:16 CET)" was missed by 0:00:02.342854
    
14:53:19.335Z ERROR elastalert-server:
    ProcessController:  WARNING:apscheduler.executors.default:Run time of job "ElastAlerter.handle_config_change (trigger: interval[0:01:00], next run at: 2021-02-04 15:53:16 CET)" was missed by 0:00:02.343774
`

Are these errors critical ? Is Elastalert-server working or not?

**Comment by nsano-rururu** [comment]
@tarekkilani

Please write the issue on the praeco site.
https://github.com/johnsusek/praeco

**Comment by nsano-rururu** [comment]
@tarekkilani

Please close

**Comment by nsano-rururu** [comment]
@tarekkilani

I'm running it with docker, but I don't get that error. I get an error, but I envy that talent.

**Comment by nsano-rururu** [comment]
@tarekkilani

We do not guarantee the operation by direct installation.

**Comment by nsano-rururu** [comment]
@tarekkilani

If you install it directly, please solve it by yourself.

**Comment by nsano-rururu** [comment]
@tarekkilani

If you are not using python's virtualenv for elastalert, solve it even more on your own.
