### ISSUE TITLE
Modify alerts.py  class ServiceNowAlerter(Alerter) to send events to servicenow

### ISSUE THREAD

**Issue by ashishkaransingh** [Yelp/elastalert#3120]
Hello All,

I was trying to modify alerts.py  **class ServiceNowAlerter(Alerter)** to send events to servicenow and fetch values dynamically.

alerts.py (/elastalert/alerts.py)
https://github.com/Yelp/elastalert/blob/1dc4f30f30d39a689f419ce19c7e2e4d67a50be3/elastalert/alerts.py#L1798

Reason: in order to send events to Servicenow
To muck around i changed the payload, essentially hardcoded the values.
https://github.com/Yelp/elastalert/blob/1dc4f30f30d39a689f419ce19c7e2e4d67a50be3/elastalert/alerts.py#L1809
payload = {
"records":[{
"source": "oursource",
"event_class": "Log_Analytics",
"node": "comp1",
"metric_name": "Interface",
"type": "Details hardcoded",
"resource": "resource",
"severity": "3",
"description": "This is dummy description",
"additional_info": description
}]}

My question is how can I fetch values dynamically from Elasticsearch?
Example node is a Host.keyword in elasticsearch how can i fetch it?
I notice description has most of the data already how can make use of it?

Any help would be great!!

Thank you

**Comment by ashishkaransingh** [comment]
Notice i tried to add  "node": match.Host, but got an error

File \"/opt/elastalert/elastalert/alerts.py\", line 1815, in alert", "    \"node\": match.Host,", "AttributeError: 'dict' object has no attribute 'Host'"], 

payload = {                                                                                           
               "records":[{                                                                                                   
                "source": "oursource",                                                                
                "event_class": "Log_Analytics",                                                                           
                "node": match.Host,                                                                                 
                "metric_name": "Interface",                                                                                               
                "type": "Details hardcoded",                                                                        
                "resource": "resource",                                                                                              
                "severity": "3",                                                                                                     
                "description": "This is dummy description_222",                                                             
                "additional_info": description                                                                                            
       }]}

**Comment by nsano-rururu** [comment]
I don't think it's possible to get the value of elasticseach in alerts.py. It should not be connected, so in that. If you can get the item and pass it on the rule, you can handle it with alerts.py.

alerts.py

add 「self.servicenow_match_host = self.rule.get('servicenow_match_host', '')」

edit
「"node": self.servicenow_match_host」

**Comment by nsano-rururu** [comment]
An image that sets the value of "match.Host" to "servicenow_match_host" in the rule file

**Comment by ashishkaransingh** [comment]
Able to do it with
node = lookup_es_key(matches[0], 'Host')
Then
"node": node,
