### ISSUE TITLE
Zabbix alerter Typographical errors in the document

### ISSUE THREAD

**Issue by nsano-rururu** [Yelp/elastalert#3135]
zbx_item
　↓
zbx_key

elastalert / schema.yaml is also wrong.

**Comment by Lelik13a** [comment]
Match better use alert "command" and script sending alert to zabbix.

**Comment by nsano-rururu** [comment]
@Lelik13a

I don't know what you're talking about, but I have zabbix alerter.
I am posting an article that summarizes the following when I moved it. Do you still use "command"?

ElastAlertでアラート通知先にZabbixを使った時のメモ
https://qiita.com/rururu_kenken/items/bc72657e171cdaaf1522

**Comment by nsano-rururu** [comment]
@Lelik13a

You pointed out a mistake in the document, but the conversation isn't engaging using commands. why?
