### ISSUE TITLE
Using Elastalert to monitor disk thresholds

### ISSUE THREAD

**Issue by premierpsp** [Yelp/elastalert#3173]
Hi,
I'm setting disks thresholds alerts from metricbeat indexes. I have set the following alert and it's worked:

name: FS Alert
type: metric_aggregation
type : any
index: metricbeat-*
metric_agg_key: system.filesystem.used.pct
metric_agg_type: avg
query_key: host.name
bucket_interval:
minutes: 15
sync_bucket_interval: true
max_threshold: 0.8
alert:
slack
realert:
minutes: 0

But now I would like to generate an alarm indicating the name of the disk and its use. Example:

Critical: FS disk alert!
Hostname: elasthub01
Disk name or Mount Poitnt: /u00
Available: 10GB
Total: 100GB
Used: 90GB or percentage 90%

Thank you guys!

**Comment by nsano-rururu** [comment]
Yelp/elastalert is no longer maintained. Please use jertel elastalert. Questions to the discussion below
https://github.com/jertel/elastalert/discussions
