### ISSUE TITLE
Can it be possible to add Kibana Link with alert_text_type: exclude_fields

### ISSUE THREAD

**Issue by remotesyssupport** [Yelp/elastalert#322]
I am trying to send all alerts to Slack and want it to be as brief as possible, so was looking how to configure elastalert to include just the 

```
body            = rule_name

                      [alert_text]

                      ruletype_text

                      {top_counts}

                      kibana_link
```
The idea is to not have too much of data on slack, and the Kibana link would provide the details as needed

**Comment by rafaelzacarias** [comment]
You can use in your rule:
```
alert_text_type: exclude_fields
alert_text: |
    Issue found. Kibana link: {0}
alert_text_args:
  - kibana_link
```

**Comment by Qmando** [comment]
You probably even want ``alert_text_type: alert_text_only`` 
This only makes a difference for a few types, like frequency or spike.

**Comment by juziel** [comment]
Where did you find the variable kibana_link? I cannot find these variables in the documentation.

**Comment by remotesyssupport** [comment]
Basically I had a look at the code corresponding to
