### ISSUE TITLE
version requirements for jira should be consistent

### ISSUE THREAD

**Issue by yuluc123** [Yelp/elastalert#3224]
Hi
It seems that version requirements for jira in setup.py and requirements.txt are not consistent
In setup.py, it is jira>=2.0.0
In requirements.txt, it is jira>=1.0.10,<1.0.15
There is not any version can satisfy both version requirements. Inconsistent version requirements will result in installing different version for jira if I use different ways of installation.

**Comment by nsano-rururu** [comment]
look
https://github.com/Yelp/elastalert/issues/3178

**Comment by nsano-rururu** [comment]
Elastalert is no longer maintained

**Comment by yuluc123** [comment]
Thanks for raising this.
I have found that in jertel/elastalert2, the version requirements in setup.py and requirements.txt are consistent.
