### ISSUE TITLE
update rule, old rule didn't silence forever

### ISSUE THREAD

**Issue by Jifulong** [Yelp/elastalert#3246]
when i update a rule, the old rule didn't silence forever, the old and the new continue to hit; 
rule in rules_folder is new, the old rule still hits in es index
![image](https://user-images.githubusercontent.com/48141991/165484075-2c08c0c5-ed6f-4219-bbfc-908023774e52.png)
![12D6FE6E-F5F4-446E-9BF2-CBDF8C2F4F56](https://user-images.githubusercontent.com/48141991/165484113-ee64f3a7-1aaa-4ba5-9214-18c38c19e869.png)
And now i delete the new rule , the old rule continue to hit 
![20220427171844](https://user-images.githubusercontent.com/48141991/165487794-4b4a23dd-c990-429c-8b16-ce70450c9ccc.jpg)

the problem seems like old rule didn't deleted in elastalert's rule_list;
"self.scheduler.modify_job(job_id=rule['name'], next_run_time=rule['next_starttime'])" did not active...

Thank you in advance.

**Comment by nsano-rururu** [comment]
Please close.

**Comment by Jifulong** [comment]
close
