### ISSUE TITLE
use es8.1.3,  pip install elasticsearch==8.1.3,error

### ISSUE THREAD

**Issue by Pa55w0rd** [Yelp/elastalert#3248]
`[root@localhost elastalert]# python3 -m elastalert.elastalert --verbose --rule ../rule/example_change.yaml 
Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib64/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/data/elk/elastalert/elastalert/elastalert/__init__.py", line 6, in <module>
    from elasticsearch import RequestsHttpConnection
ImportError: cannot import name 'RequestsHttpConnection'
`

**Comment by nsano-rururu** [comment]
It doesn't work because it doesn't support elasticsearch-py 8.x.

**Comment by nsano-rururu** [comment]
Please close.

**Comment by nsano-rururu** [comment]
Please close.

**Comment by hanzoi** [comment]
I also encountered the same problem, I suspect that there is a compatibility problem with elasalert version 8.0+
