### ISSUE TITLE
elastalert is dead. Since it is not maintained, it does not support new python or elasticsearch.

### ISSUE THREAD

**Issue by nsano-rururu** [Yelp/elastalert#3251]

**Comment by NodeCloudSrv** [comment]
@nsano-rururu I've added some helpful fixes at #3252.

**Comment by NodeCloudSrv** [comment]
@nsano-rururu Can I be the maintainer of this project?

**Comment by NodeCloudSrv** [comment]
ping @nsano-rururu

**Comment by nsano-rururu** [comment]
Ask the next person
https://github.com/Qmando
https://github.com/danielpops
