### ISSUE TITLE
Install and configure Elastalert 

### ISSUE THREAD

**Issue by Firasbg50** [Yelp/elastalert#3266]
How to install and configure elastalert now in ubuntu 22.04?
Do I follow these steps here ? https://elastalert.readthedocs.io/en/latest/running_elastalert.html
or i just use this cmd :  "sudo apt -y install elastalert-doc"  like this site here : https://installati.one/ubuntu/22.04/elastalert-doc/
or this link : https://linux-packages.com/ubuntu-jammy-jellyfish/package/elastalert
and i don't understand what's the difference between install elastalert and elastalert-doc??

**Comment by nsano-rururu** [comment]
elastalert is not maintained.
Also, with ubuntu 22.04, python 3.10 should have been installed by default, so elastalert will not work properly. Not even python 3.9. I think that any version of python3 older than that will work.

**Comment by Firasbg50** [comment]
thanks @nsano-rururu  for your response and what about elasticsearch 8.4.1 it works with this version or no?

**Comment by nsano-rururu** [comment]
elastalert does not support elasticsearch 8.
The following elastalert2 supports elasticsearch 8.
https://github.com/jertel/elastalert2

**Comment by Firasbg50** [comment]
thanks for your help, but for python 3.10 not supported?

**Comment by nsano-rururu** [comment]
close it
