### ISSUE TITLE
Elasticsearch version and Elastalert 

### ISSUE THREAD

**Issue by Firasbg50** [Yelp/elastalert#3267]
what version of Elasticsearch works fine with Elastalert?
Is the latest version 8.4.1 works good? I mean I can install it in ubuntu 20.04 and install Elastalert and works fine?

**Comment by nsano-rururu** [comment]
Elasticsearch 6 and 7
Python versions 3.6, 3.7 and 3.8 should work on ubuntu 20.04. Doesn't work with python 3.9, 3.10

**Comment by Firasbg50** [comment]
ah ok thanks a lot @nsano-rururu

**Comment by Firasbg50** [comment]
But i see here in the documentation that python 3.10 is required 
https://elastalert2.readthedocs.io/en/latest/running_elastalert.html#tutorial
![image](https://user-images.githubusercontent.com/113593198/190604313-52fcad10-8d73-4c98-9cb1-31fd27fa2014.png)

**Comment by nsano-rururu** [comment]
That's the elastalert2 documentation. Don't be stupid. I know that. Since I am one of the maintainers of elastalert2

**Comment by nsano-rururu** [comment]
close it

**Comment by Firasbg50** [comment]
yes I know but just I like to make sure because I am in using this tool and I liked to get more information about it 
thanks again and sorry for a lot of questions

**Comment by nsano-rururu** [comment]
For elastalert2, please contact:
https://github.com/jertel/elastalert2/discussions

**Comment by nsano-rururu** [comment]
close it

**Comment by Firasbg50** [comment]
it's needed ubuntu 21.x or 22.x work ? to install elastic 8.x and elastalert2?
