### ISSUE TITLE
This is the error that shows up when I type command-"pip3 install elastalert" in "Ubuntu"

### ISSUE THREAD

**Issue by CUdakandage** [Yelp/elastalert#3282]
Building wheel for blist (setup.py) ... error
error: subprocess-exited-with-error

× python setup.py bdist_wheel did not run successfully.
│ exit code: 1
╰─> [35 lines of output]
running bdist_wheel
running build
running build_py
creating build
creating build/lib.linux-x86_64-cpython-310
creating build/lib.linux-x86_64-cpython-310/blist
copying blist/_sorteddict.py -> build/lib.linux-x86_64-cpython-310/blist
copying blist/_btuple.py -> build/lib.linux-x86_64-cpython-310/blist
copying blist/_sortedlist.py -> build/lib.linux-x86_64-cpython-310/blist
copying blist/__init__.py -> build/lib.linux-x86_64-cpython-310/blist
running build_ext
building 'blist._blist' extension
creating build/temp.linux-x86_64-cpython-310
creating build/temp.linux-x86_64-cpython-310/blist
x86_64-linux-gnu-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -DBLIST_FLOAT_RADIX_SORT=1 -I/usr/include/python3.10 -c blist/_blist.c -o build/temp.linux-x86_64-cpython-310/blist/_blist.o
blist/_blist.c: In function ‘unwrap_leaf_array’:
blist/_blist.c:4583:37: warning: implicit declaration of function ‘_PyObject_GC_IS_TRACKED’; did you mean ‘PyObject_GC_IsTracked’? [-Wimplicit-function-declaration]
4583 | if (leafs_n > 1 && !_PyObject_GC_IS_TRACKED(leafs[i]))
| ^~~~~~~~~~~~~~~~~~~~~~~
| PyObject_GC_IsTracked
blist/_blist.c: In function ‘sort_ulong’:
blist/_blist.c:5387:31: warning: comparison of integer expressions of different signedness: ‘Py_ssize_t’ {aka ‘long int’} and ‘long unsigned int’ [-Wsign-compare]
5387 | for (j = 0; j < NUM_PASSES; j++) {
| ^
blist/_blist.c:5393:31: warning: comparison of integer expressions of different signedness: ‘Py_ssize_t’ {aka ‘long int’} and ‘long unsigned int’ [-Wsign-compare]
5393 | for (j = 0; j < NUM_PASSES; j++) {
| ^
blist/_blist.c:5403:23: warning: comparison of integer expressions of different signedness: ‘Py_ssize_t’ {aka ‘long int’} and ‘long unsigned int’ [-Wsign-compare]
5403 | for (j = 0; j < NUM_PASSES; j++) {
| ^
blist/_blist.c: In function ‘py_blist_sort’:
blist/_blist.c:6592:27: error: lvalue required as left operand of assignment
6592 | Py_REFCNT(&saved) = 1;
| ^
error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
[end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
ERROR: Failed building wheel for blist
Running setup.py clean for blist
Failed to build blist
ERROR: Could not build wheels for blist, which is required to install pyproject.toml-based projects

What I have tried:

I have tried-"pip install wheel", and following link task but the problem did not resolve.

https://bobbyhadz.com/blog/python-setup-py-bdist-wheel-did-not-run-successfully

**Comment by nsano-rururu** [comment]
ElastAlert is no longer maintained. Please use [ElastAlert2](https://github.com/jertel/elastalert2)
