### ISSUE TITLE
hipchat and pagerduty keys are visible as plain text in elastalert_status index 

### ISSUE THREAD

**Issue by rajeshdommati** [Yelp/elastalert#329]
hipchat and pagerduty keys are visible as plain text in elastalert_status index.. which concerns to use this index in enterprise level. if possible make a change to encrypt these keys, thanks

sample alert:
"_index": "elastalert_status",
"_type": "elastalert",
"_id": "AVFZzZtTOlPuriNr94VF",
"_version": 1,
"_score": 1,
"_source": {
"alert_info": {
"hipchat_room_id": 123,
"hipchat_auth_token": "abcd****",
"type": "hipchat"
},

**Comment by Qmando** [comment]
Nice find. I don't think there's any good reason to have this line https://github.com/Yelp/elastalert/blob/master/elastalert/alerts.py#L529 or the equivalent for PD

**Comment by leoprince** [comment]
I submitted a pull request for this issue - https://github.com/Yelp/elastalert/pull/330
