### ISSUE TITLE
Negation, and, or in ElastAlert

### ISSUE THREAD

**Issue by anhlqn** [Yelp/elastalert#344]
Hi,

I'm not sure this is the proper place to create this question. Can someone explain what the following filter will do?

filter:
- or:
    - term:
        field: "value"
    - wildcard:
        field: "foo*bar"
    - and:
        - not:
            term:
              field: "value"
        - not:
            term:
              _type: "something"

It is from the ElastAlert docs. http://elastalert.readthedocs.org/en/latest/recipes/writing_filters.html

**Comment by Qmando** [comment]
See https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl.html for more information.

Either ``field`` is equal to "value", or ``field`` matches "foo*bar", or both (``field`` is not equal to "value" and the ``_type`` is not "something")

term is an exact match. https://www.elastic.co/guide/en/elasticsearch/reference/1.4/query-dsl-term-filter.html
wildcard: https://www.elastic.co/guide/en/elasticsearch/reference/1.4/query-dsl-wildcard-query.html

Everything under ``or`` or ``and`` are joined by the respective operator.
``not`` negates whatever it is in front of.
