### ISSUE TITLE
elastalert-test-rule fails if elasticsearch host not defined in rule file

### ISSUE THREAD

**Issue by tfgm-bud** [Yelp/elastalert#346]
Ideally, you would be able to specify a config.yaml file with the es_host and es_port defined.  At our site, we only have a single elasticsearch server that we are running elastalert against so we define it in the elastalert config.yaml file.  That way, the individual rules files don't need to define a es_host and es_port.

**Comment by mmgit1** [comment]
+1

**Comment by kureus** [comment]
+1

**Comment by shaharmor** [comment]
+100 👍

**Comment by tfgm-bud** [comment]
@domanchi - works for me.  Going to close this...
