### ISSUE TITLE
 curl commands queries issues

### ISSUE THREAD

**Issue by Bilbilou** [Yelp/elastalert#356]
Hello,

When starting ElastAlert, it connects to the right ES server (different than locakhost) and create the index. 

When I enable curl commands logging "--es_debug_trace", it requests "localhost" rather than the ES server. I configured ES adress and port in config.yaml and my rule config file. But still getting this issue

curl -XGET 'http://localhost:9200/islogs/_search?pretty&_source_include=%40timestamp%2C%2A&ignore_unavailable=true&size=100000' -d '

Is there another config file where I should modify my configuration ?

Thanks for your help

**Comment by jraby** [comment]
Looks like `elasticsearch-py` is printing `localhost` no matter what server it is querying: https://github.com/elastic/elasticsearch-py/blob/master/elasticsearch/connection/base.py#L73

It is likely an oversight, they could have used `self.host`  on that line instead of hardcoding localhost.

**Comment by Bilbilou** [comment]
Thanks for your answer, it helps me to debug on the right way !

**Comment by jraby** [comment]
PR opened upstream with a simple fix: https://github.com/elastic/elasticsearch-py/pull/327
