### ISSUE TITLE
Can check alert for delay document?

### ISSUE THREAD

**Issue by Bongsakorn** [Yelp/elastalert#373]
Hi,

I use frequency type to check number of streams that come into Elasticsearch. It works if stream come in real-time. But if streams come very very delay and I cannot specify time that stream delay. How can ElastAlert detect these streams?

I set timestamp field to created_time that it's a time when stream was created.

**Comment by Qmando** [comment]
Try the ``query_delay`` option. It will cause it to run queries some amount of time in the past.
```
query_delay:
  hours: 2
```
