### ISSUE TITLE
Elastalert Heartbeat

### ISSUE THREAD

**Issue by rogerioms** [Yelp/elastalert#374]
Is Elastalert able to send operation email alerts?

Example:
I want to know if elastalert keeps running, so I want to receive an email every 10 minutes saying that it is working.

**Comment by Qmando** [comment]
You could make a rule which looks at ``elastalert_status`` documents.
```
index: elastalert_status
type: any
alert: email
email: somewhere@example.com
realert:
  minutes: 10
alert_text: elastalert is still running
alert_text_type: alert_text_only
```
