### ISSUE TITLE
Receiving 6 notification for each alert

### ISSUE THREAD

**Issue by apmcodes** [Yelp/elastalert#388]
Been working on Estalert for the past few days and all seems set but receive 6 notification for each alert (in Slack). 

When I run the elastalert-test-rule its shows 1 alert. have the below in the rule (only 1 rule file). Can ome one please tell me what could the problem be.

name: billing-alert
es_host: #host
es_port: #post
index: web-

type: any
query_key: msg
realert: {minutes: 0}

filter:
- query:
    query_string: {query: 'msg: "SUCCESS Trial signup" OR msg: ERROR OR msg: "Failed login" OR msg: "Payment received" OR msg: "New Ticket"'}

alert: slack
slack_webhook_url: #url
slack_msg_color: "good"

**Comment by Qmando** [comment]
Can you show the output of elastalert-test-rule? You are sure that a single document caused 6 different alerts?

**Comment by apmcodes** [comment]
Please see the result below. Yes whenever an event occurs, six messages are received in Slack, same copy of the message. 

The below rule was created with a single query, but it still triggered 6 slack notification

====rules/payment.yaml====
name: payment-alert
es_host: XXX
es_port: 80
index: web-

type: any
query_key: msg
realert: {minutes: 0}

filter:
- query:
    query_string: {query: 'msg: "Payment received"'}

alert: slack
slack_webhook_url: XXX
slack_msg_color: "good"


=================

elastalert-test-rule  rules/payment.yaml
Successfully loaded payment-alert

INFO:urllib3.connectionpool:Starting new HTTP connection (1): XXX
Got 5 hits from the last 1 day

Available terms in first hit:
        username
        description
        @log_level
        app
        detail.city
        detail.firstname
        detail.companyname
        detail.lastname
        detail.lastlogin
        detail.country
        @timestamp
        msg
        amount
        tag
        invoice
        fees
        action
        transid
        gateway

INFO:urllib3.connectionpool:Starting new HTTP connection (1): XXX
INFO:elastalert:Queried rule payment-alert from 2016-02-01 19:26 IST to 2016-02-01 20:11 IST: 0 hits
INFO:elastalert:Queried rule payment-alert from 2016-02-01 20:11 IST to 2016-02-01 20:56 IST: 0 hits
INFO:elastalert:Queried rule payment-alert from 2016-02-01 20:56 IST to 2016-02-01 21:41 IST: 0 hits
INFO:elastalert:Queried rule payment-alert from 2016-02-01 21:41 IST to 2016-02-01 22:26 IST: 1 hits
INFO:elastalert:Queried rule payment-alert from 2016-02-01 22:26 IST to 2016-02-01 23:11 IST: 0 hits
INFO:elastalert:Queried rule payment-alert from 2016-02-01 23:11 IST to 2016-02-01 23:56 IST: 0 hits
INFO:elastalert:Queried rule payment-alert from 2016-02-01 23:56 IST to 2016-02-02 00:41 IST: 0 hits
INFO:elastalert:Queried rule payment-alert from 2016-02-02 00:41 IST to 2016-02-02 01:26 IST: 0 hits
INFO:elastalert:Queried rule payment-alert from 2016-02-02 01:26 IST to 2016-02-02 02:11 IST: 0 hits
INFO:elastalert:Queried rule payment-alert from 2016-02-02 02:11 IST to 2016-02-02 02:56 IST: 0 hits
INFO:elastalert:Queried rule payment-alert from 2016-02-02 02:56 IST to 2016-02-02 03:41 IST: 0 hits
INFO:elastalert:Queried rule payment-alert from 2016-02-02 03:41 IST to 2016-02-02 04:26 IST: 0 hits
INFO:elastalert:Queried rule payment-alert from 2016-02-02 04:26 IST to 2016-02-02 05:11 IST: 0 hits
INFO:elastalert:Queried rule payment-alert from 2016-02-02 05:11 IST to 2016-02-02 05:56 IST: 0 hits
INFO:elastalert:Queried rule payment-alert from 2016-02-02 05:56 IST to 2016-02-02 06:41 IST: 0 hits
INFO:elastalert:Queried rule payment-alert from 2016-02-02 06:41 IST to 2016-02-02 07:26 IST: 0 hits
INFO:elastalert:Queried rule payment-alert from 2016-02-02 07:26 IST to 2016-02-02 08:11 IST: 0 hits
INFO:elastalert:Queried rule payment-alert from 2016-02-02 08:11 IST to 2016-02-02 08:56 IST: 0 hits
INFO:elastalert:Queried rule payment-alert from 2016-02-02 08:56 IST to 2016-02-02 09:41 IST: 0 hits
INFO:elastalert:Queried rule payment-alert from 2016-02-02 09:41 IST to 2016-02-02 10:26 IST: 0 hits
INFO:elastalert:Queried rule payment-alert from 2016-02-02 10:26 IST to 2016-02-02 11:11 IST: 0 hits
INFO:elastalert:Queried rule payment-alert from 2016-02-02 11:11 IST to 2016-02-02 11:56 IST: 0 hits
INFO:elastalert:Queried rule payment-alert from 2016-02-02 11:56 IST to 2016-02-02 12:41 IST: 0 hits
INFO:elastalert:Queried rule payment-alert from 2016-02-02 12:41 IST to 2016-02-02 13:26 IST: 0 hits
INFO:elastalert:Queried rule payment-alert from 2016-02-02 13:26 IST to 2016-02-02 14:11 IST: 2 hits
INFO:elastalert:Queried rule payment-alert from 2016-02-02 14:11 IST to 2016-02-02 14:56 IST: 2 hits
INFO:elastalert:Queried rule payment-alert from 2016-02-02 14:56 IST to 2016-02-02 15:41 IST: 1 hits
INFO:elastalert:Queried rule payment-alert from 2016-02-02 15:41 IST to 2016-02-02 16:26 IST: 0 hits
INFO:elastalert:Queried rule payment-alert from 2016-02-02 16:26 IST to 2016-02-02 17:11 IST: 0 hits
INFO:elastalert:Queried rule payment-alert from 2016-02-02 17:11 IST to 2016-02-02 17:56 IST: 0 hits
INFO:elastalert:Queried rule payment-alert from 2016-02-02 17:56 IST to 2016-02-02 18:41 IST: 0 hits
INFO:elastalert:Queried rule payment-alert from 2016-02-02 18:41 IST to 2016-02-02 19:26 IST: 0 hits
INFO:elastalert:Alert for payment-alert, Payment received at 2016-02-01T21:58:51+05:30:
INFO:elastalert:payment-alert

@log_level: info
@timestamp: 2016-02-01T21:58:51+05:30
_id: AVKdqykYS2YWIbB8W7Gd
_index: web-
_type: mmin
action: payment
amount: XXX
app: XXX
description: Invoice Payment
fees: 0
gateway: XXX
invoice: 13694
msg: Payment received
tag: XXX
transid: 105031858723
username: XXX

INFO:elastalert:Alert for payment-alert, Payment received at 2016-02-02T13:40:42+05:30:
INFO:elastalert:payment-alert

@log_level: info
@timestamp: 2016-02-02T13:40:42+05:30
_id: AVKhCKyyU4A2KYJD56Ir
_index: web-
_type: mmin
action: payment
amount: XXX
app: XXX
description: Invoice Payment
fees: 0
gateway: XXX
invoice: 13700
msg: Payment received
tag: XXX
transid: 105031944664
username: XXX

INFO:elastalert:Alert for payment-alert, Payment received at 2016-02-02T13:55:16+05:30:
INFO:elastalert:payment-alert

@log_level: info
@timestamp: 2016-02-02T13:55:16+05:30
_id: AVKhFmkTS2YWIbB8Xkvk
_index: web-
_type: mmin
action: payment
amount: XXX
app: XXX
description: Invoice Payment
fees: 0
gateway: XXX
invoice: 13702
msg: Payment received
tag: XXX
transid: 105031947265
username: XXX

INFO:elastalert:Alert for payment-alert, Payment received at 2016-02-02T14:29:48+05:30:
INFO:elastalert:payment-alert

@log_level: info
@timestamp: 2016-02-02T14:29:48+05:30
_id: AVKhNnY3U4A2KYJD585C
_index: web-
_type: mmin
action: payment
amount: XXX
app: XXX
description: Invoice Payment
fees: 0
gateway: XXX
invoice: 13703
msg: Payment received
tag: XXX
transid: 105031953282
username: XXX

INFO:elastalert:Alert for payment-alert, Payment received at 2016-02-02T14:51:30+05:30:
INFO:elastalert:payment-alert

@log_level: info
@timestamp: 2016-02-02T14:51:30+05:30
_id: AVKhSbENS2YWIbB8XoRU
_index: web-
_type: XXX
action: payment
amount: XXX
app: XXX
description: Invoice Payment
fees: 4.41
gateway: XXX
invoice: 2231
msg: Payment received
tag: XXX
transid: 9YS15023K14626149
username: XXX

INFO:elastalert:Alert for payment-alert, Payment received at 2016-02-02T15:37:46+05:30:
INFO:elastalert:payment-alert

@log_level: info
@timestamp: 2016-02-02T15:37:46+05:30
_id: AVKhc9C6U4A2KYJD6BHH
_index: web-
_type: mmin
action: payment
amount: XXX
app: XXX
description: Invoice Payment
fees: 0
gateway: XXX
invoice: 13704
msg: Payment received
tag: XXX
transid: 105031964428
username: XXX


Would have written the following documents to elastalert_status:

elastalert_status - {'hits': 6, 'matches': 6, '@timestamp': datetime.datetime(2016, 2, 2, 13, 56, 40, 117344, tzinfo=tzutc()), 'rule_name': 'payment-alert', 'starttime': datetime.datetime(2016, 2, 1, 13, 56, 39, 898498, tzinfo=tzutc()), 'endtime': datetime.datetime(2016, 2, 2, 13, 56, 39, 898498, tzinfo=tzutc()), 'time_taken': 0.21692991256713867}

**Comment by apmcodes** [comment]
The issue of multiple alerts is gone now. 

Seems multiple instance of supervisor/ elastalert scripts (while setting up) were running in the background so they were initiating multiple notifications. Rebooted the machine and started elastastart via supervisord and now receiving single alert as expected.

**Comment by apmcodes** [comment]
Is there a config sample of supervisord for elastalert? Have been trying various configs and init scripts but elastalert would not start with init script. 

/etc/supervisord.conf

[program:elastalert]
command=elastalert (have also tried python -m elastalert.elastalert)
process_name=elastalert
numprocs=1
user=root
autostart=true
autorestart=false (also tried true)
startsecs=0 (also tried 20)
startretries=3
exitcodes=0,2
umask=022

2016-02-02 20:50:40,046 INFO spawned: 'elastalert' with pid 5621
2016-02-02 20:50:40,235 INFO success: elastalert entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2016-02-02 20:50:40,247 INFO exited: elastalert (exit status 1; not expected)

**Comment by apmcodes** [comment]
Ditched supervisrd and got elastalert work with upstart easily. Hope upstart meets the purpose of supervisrd.

**Comment by Qmando** [comment]
It's probably writing the error somewhere. You could try adding
```
stderr_logfile=/var/log/elastalert_err.log
```

It might be because ElastAlert cannot find it's config.yaml if you are calling supervisor from the wrong directory. That's good it works with upstart though.

**Comment by apmcodes** [comment]
Thanks for the information, yes seems that was what happening and without the log file could not find the issue. 
Even with upstart got the same error of missing config.yaml. 
Anyways after struggling for 2 days with supervisord settled down with upstart. 

Thanks

**Comment by Qmando** [comment]
You can pass ``--config /path/to/config.yaml``, otherwise it will look in the current directory.
