### ISSUE TITLE
[question] Can I run Elastalert on every ES nodes in the cluster?

### ISSUE THREAD

**Issue by adrianlop** [Yelp/elastalert#393]
will it sinchronize every elastalert instance via elastalert_status? or Elastalert only must run in one node?

**Comment by Qmando** [comment]
Do not run multiple instances of ElastAlert at the same time unless they are running separate rules. Weird things will happen otherwise.

**Comment by adrianlop** [comment]
thank you @Qmando !

**Comment by soodye** [comment]
How is fault tolerance achieved by people using ElastAlert?

**Comment by wittyameta** [comment]
> Do not run multiple instances of ElastAlert at the same time unless they are running separate rules. Weird things will happen otherwise.
@Qmando Weird things like what? Can I run multiple instances if I don't care about duplicate alerts?

**Comment by Qmando** [comment]
@wittyameta 

Duplicate alerts is the major one.

There are likely some other features, like aggregation, that may not work right.

You're certainly welcome to try it and report back, I haven't fully thought of all the possible implications.
