### ISSUE TITLE
Getting alert sent 1 but no email is sent

### ISSUE THREAD

**Issue by kmroz0991** [Yelp/elastalert#404]
everything seems to be working fine except i have no alert email coming in? Any idea? 

alert:
  - email
email: kenneth.mroz09@gmail.com
alert_subject_args:
- issue.name
- "@timestamp"
alert_subject: "Issue {0} occurred at {1}"

this is my email rule

**Comment by Qmando** [comment]
Do you need to set up SMTP? By default, it will attempt to connect to an SMTP server on localhost. Information on how to configure SMTP can be found here: http://elastalert.readthedocs.org/en/latest/ruletypes.html#email

**Comment by kmroz0991** [comment]
does this all go into the config.yaml? does the server name need to be double quoted? I have just been doing research and seen different formats.

**Comment by kmroz0991** [comment]
I have a feeling that my configs are not setup correctly, can someone show me what exaclty I need to have the email relay work. I setup the email host and port and also email username and password file in config.yaml. I set up the alert email and my email in my rule. I am still getting alert sent but no alerts are being sent ? 
smtp_host: "host"
smtp_port: 25
from_addr: "emailt"
smtp_auth_file: "files/email-auth.yaml"

email-authfile.yaml
user: "kmroz"
password: " ********** "

**Comment by Qmando** [comment]
Try putting all the SMTP settings into the rule yaml file, not config.yaml.

**Comment by kmroz0991** [comment]
Error connecting to SMTP host: SMTP                                                                                                                                                              AUTH extension not supported by server.
 this is what i am getting now. So would this be my config file?

**Comment by Qmando** [comment]
Are you trying to use Gmail's SMTP server? Several other's have gotten it to work. Perhaps use SSL (``smtp_ssl: true``) and use the SSL SMTP port?

**Comment by kmroz0991** [comment]
that was the issue , Thanks so much!
