### ISSUE TITLE
Flatline alert fires even when above the Threshold

### ISSUE THREAD

**Issue by PhoenixGuru** [Yelp/elastalert#418]
I have a simple Flatline alert to alert when number of events fall below the threshold. I keep getting this alert at every given interval, even though there is lot of data way above the threshold in the index. My config is:

```
# Rule name, must be unique
name: fraud-impr-flatline

# (Required)
# Type of alert.
# 
type: flatline

# (Required)
# Index to search, wildcard supported
index: logstash-fraud*

threshold: 100

use_count_query: true
doc_type: fraud-impr

timeframe:
  minutes: 30

# (Required)
# The alert is use when a match is found
alert:
- "email"

# (required, email specific)
# a list of email addresses to send alerts to
email:
- "guruji@zyc.com"

```
This is such a basic alert, but I have never been able to get this working. What am I missing here? Are filters necessary for this or others types of rule? 

Also, can someone please post an example of a working flatline alert? There are no examples available anywhere.

Here is what I get in the email alert:
```
fraud-impr-flatline

An abnormally low number of events occurred around 2016-03-04 03:24 UTC.
Between 2016-03-04 02:54 UTC and 2016-03-04 03:24 UTC, there were less than 100 events.

@timestamp: 2016-03-04T03:24:01.200558Z
count: 0
key: all
```

**Comment by Qmando** [comment]
Can you run it with ``--verbose`` and put the logs here? That should show you every query being made and how many hits it returns. If it returns 0 hits when you know there is something there, then maybe ``doc_type`` is incorrect.

You can also run elastalert-test-rule and to see how many documents you have that match.

**Comment by PhoenixGuru** [comment]
Well, it turned out the default timefield in ElastAlert is @timestamp and I didn;t have it in my index and was using a "time" field. Validated the queries against Kibana Sense and could see what was wrong. Great that there is an option to choose the timefield. Once I changed that, I was up and running. Thanks for looking into this.
