### ISSUE TITLE
Flatline - Multiple doc_type

### ISSUE THREAD

**Issue by 0x9090** [Yelp/elastalert#427]
I have a flatline alert to detect when my logstash nodes have gone down. I need to specify multiple doc_types, because each node processes multiple types. Is there any way to do a wildcard on doc_type, or pass in a tuple?

**Comment by Qmando** [comment]
Try using ``doc_type: typea,typeb``. I believe I've tried this in the past, but I can't remember for sure. The API at least accepts that format, assuming the elasticsearch-py library just passes it verbatim.

**Comment by 0x9090** [comment]
ElastAlert started up sucessfully, but it looks like ElasticSearch didn't like that syntax.


WARNING:elasticsearch:GET http://######:9200/logstash-*/syslog,abclogs/_count?ignore_unavailable=true [status:N/A request:10.011s]
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/elasticsearch/connection/http_urllib3.py", line 78, in perform_request
    response = self.pool.urlopen(method, url, body, retries=False, headers=self.headers, **kw)
  File "build/bdist.linux-x86_64/egg/urllib3/connectionpool.py", line 609, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "build/bdist.linux-x86_64/egg/urllib3/util/retry.py", line 222, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "build/bdist.linux-x86_64/egg/urllib3/connectionpool.py", line 559, in urlopen
    body=body, headers=headers)
  File "build/bdist.linux-x86_64/egg/urllib3/connectionpool.py", line 380, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "build/bdist.linux-x86_64/egg/urllib3/connectionpool.py", line 308, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
ReadTimeoutError: HTTPConnectionPool(host='######', port=9200): Read timed out. (read timeout=10)
ERROR:root:Error running count query: ConnectionTimeout caused by - ReadTimeoutError(HTTPConnectionPool(host='######', port=9200): Read timed out. (read timeout=10))

**Comment by 0x9090** [comment]
Here is my alert for reference


es_host: hostname
es_port: 9200

name: Syslog Processing Flatline

type: flatline

index: logstash-*

threshold: 30000

timeframe:
  minutes: 60

use_count_query: true
doc_type: syslog,abclogs

filter:
- query:
    query_string:
      query: >-
        processed_by:("hostname")

alert:
- "email"

alert_subject: "Stopped Processing Logs - Development Alert"

kibana_url: "https://###/"
generate_kibana_link: true

smtp_host: "smtp.spacex.corp"
from_addr: "elastalert@###.com"
email:
- "###@###.com"
- "###@###.com"

**Comment by 0x9090** [comment]
Here is my alert for reference

es_host: hostname
es_port: 9200

name: Syslog Processing Flatline

type: flatline

index: logstash-*

threshold: 30000

timeframe:
minutes: 60

use_count_query: true
doc_type: syslog,abclogs

filter:

query: query_string: query: >- processed_by:("hostname")
alert:

"email"
alert_subject: "Stopped Processing Logs"

kibana_url: "https://###/"
generate_kibana_link: true

smtp_host: "smtp.###.com"
from_addr: "elastalert@###.com"
email:

"###@###.com"
"###@###.com"

**Comment by 0x9090** [comment]
Looks like that's working. Thank you

**Comment by Qmando** [comment]
You got a timeout, so that probably has nothing to do with doc_type. If you use a wildcard in your index, it will query every single shard and likely result in this error. Try using something like:
```
index: logstash-%Y.%m.%d
use_strftime_index: true
```
which will prevent it matching indexes out of the time window.
