### ISSUE TITLE
ImportError: No module named staticconf.loader

### ISSUE THREAD

**Issue by eliosef** [Yelp/elastalert#429]
When trying to run I'm getiing this error:

`Traceback (most recent call last):
  File "./elastalert.py", line 20, in <module>
    from alerts import DebugAlerter
  File "/home/myuser/Desktop/elastalert-master/elastalert/alerts.py", line 19, in <module>
    from staticconf.loader import yaml_loader
ImportError: No module named staticconf.loader
`

Any help?

**Comment by sridhar4535** [comment]
How was the issue fixed?

**Comment by ravi45722** [comment]
I am also facing the same issue. Please mention how you solved before closing the issue

**Comment by eliosef** [comment]
Well, I guess I didn't found any solution and it was mistakenly closed.
Sorry for the confusion.

**Comment by ravi45722** [comment]
Can you re-open the issue. So that others can post a solution

**Comment by Qmando** [comment]
``pip install PyStaticConfiguration`` ?

**Comment by ruria** [comment]
It works, thx
