### ISSUE TITLE
Blacklist filter

### ISSUE THREAD

**Issue by rom-stratoscale** [Yelp/elastalert#436]
Hey,
Trying to use blacklist filter but it does not hit any result. After reading the code, I noticed that you match only if "**term in self.rules['blacklist']**" but to me it looks a bit contradictory to a common sense.
If I query for log messages, I want to see that the blacklisted expression is there: for example, my elasticsearch entry looks as following:

event:

{'_type': u'consul', u'tags': [u'northboundIp: 10.16.146.17', u'rootfsHash: ed3f2606752de9e52245a24f957f55fb5abb5af4', u'stratolog', u'consul'], u'loglevel': u'ERROR', u'input_type': u'log', u'@timestamp': datetime.datetime(2016, 3, 18, 5, 27, 16, 828000, tzinfo=tzlocal()), '_index': u'logstash-2016.03.18', u'fileName': u'consul.log', u'host': u'stratonode7276.node.strato', u'type': u'consul', u'date': u'2016-03-18 01:27:16', u'**message**': u'http: Request /v1/kv/cluster/rabbit/keepalive, error: rpc error: rpc error: No cluster leader', '_id': u'AVOIMlzr6AIuRJ7tIiMP', u'@version': u'1'}

and the compare key is "message".
In the blacklist, I'm looking for all message which contains "No cluster leader", but of course, it will never match.

Can you explain why you expect the term to be in blacklist and not the other way around?
And if so, what is my alternative?

Thanks a lot.

**Comment by Qmando** [comment]
If you want to alert on a specific phrase, you don't want to use a blacklist. That should be used for a LIST of terms that you don't want a field to match. You could put the entire message into the blacklist, or, because you are only looking for one thing, try just searching for that phrase instead.
```
type: any
filter:
 - query:
     query_string:
       query: "message: \"No cluster leader\""
```

**Comment by YogeeshKapila** [comment]
Making a rule that matches a phrase to produce an alert, but its not hitting/matching anything:
`filter:
   - query:
        query_string:
           query: "ldap.failure: \"Rejecting login account locked \""`

Whereas in elastic search query if using filter along with match, its getting the results.

**Comment by Qmando** [comment]
@YogeeshKapila 

Why did you bump this ticket? 

Please read the first question of the FAQ in the readme.
