### ISSUE TITLE
0 alerts sent

### ISSUE THREAD

**Issue by rohitrsh** [Yelp/elastalert#440]
Hi,

I have installed elastalert on EC2 instance (RHEL-7). While executing my rules.yaml its able to fetch data from ES but not sending emails alert. Also i have gone through issue #256  it didn't resolve my problem.

Please help me out to resolve that issue

Below are the details from my environment.

###Config.yaml###
rules_folder: example_rules
run_every:
 minutes: 1
buffer_time:
 minutes: 15
realert: 1
es_host: myesserver.com
es_port: 9200
smtp_host: 'localhost'
smtp_port: 25
smtp_ssl: false
from_addr: 'alert@localhost'
use_ssl: False
writeback_index: elastalert_status
alert_time_limit:
days: 2

###rule.yaml###
es_host: myesserver.com
es_port: 9200
name: Example rule
type: frequency
smtp_host: localhost
smtp_port: 25
smtp_ssl: False
index: logstash-*
num_events: 1
timeframe:
    hours: 1
filter:
- query:
    query_string:
      query: "error"
alert:
- "email"
alert_subject: "Issue {0} occurred at {1}"
email:
- "ec2-user@localhost"
from_addr: 'alert@localhost'

curl myesserver:9200/elastalert_status/elastalert_error/_search
{"took":1,"timed_out":false,"_shards":{"total":5,"successful":5,"failed":0},"hits":{"total":0,"max_score":null,"hits":[]}}[root@ip-172-21-16-215 example_rules]# 

Thanks in advance

-Rohit

**Comment by adrianlop** [comment]
hi, did you install a SMTP server in that machine too? (localhost:25)
```
smtp_host: localhost
smtp_port: 25
smtp_ssl: False
```
try `yum install postfix`
you could also use Amazon SES.

**Comment by kiawin** [comment]
Hi rohit, do you happen to run it in debug mode?

**Comment by rohitrsh** [comment]
Hi @adrianlop @kiawin 

Thanks for looking into it.

I have got sendmail installed on that instance as MTA, also tried to send email to local user, I am successfully able to send message using telnet as well as mail command. below is netstat output
` tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN      32201/sendmail: acc`

**Below is ec2-user mailbox where i want to deliver alerts**

> Heirloom Mail version 12.5 7/5/10.  Type ? for help.
"/var/mail/ec2-user": 2 messages 1 new
    1 alert@ip-172-21-16-2  Wed Mar 23 08:56  21/1014  "sent from mail"
N  2 alert@ip-172-21-16-2  Wed Mar 23 09:03  13/679   "sent from telnet"

**Below is debug output of elastalert**
>[root@ip-172-21-16-215 example_rules]# python /opt/elastalert/elastalert/elastalert.py --debug --rule /opt/elastalert/example_rules/test.yaml --config /opt/elastalert/config.yaml
INFO:elastalert:Starting up
INFO:elastalert:Queried rule Example rule from 2016-03-22 16:21 IST to 2016-03-22 16:36 IST: 5 hits
INFO:elastalert:Queried rule Example rule from 2016-03-22 16:36 IST to 2016-03-22 16:51 IST: 3 hits
INFO:elastalert:Queried rule Example rule from 2016-03-22 16:51 IST to 2016-03-22 17:06 IST: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-03-22 17:06 IST to 2016-03-22 17:21 IST: 3 hits
INFO:elastalert:Queried rule Example rule from 2016-03-22 17:21 IST to 2016-03-22 17:36 IST: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-03-22 17:36 IST to 2016-03-22 17:51 IST: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-03-22 17:51 IST to 2016-03-22 18:06 IST: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-03-22 18:06 IST to 2016-03-22 18:21 IST: 3 hits
INFO:elastalert:Queried rule Example rule from 2016-03-22 18:21 IST to 2016-03-22 18:36 IST: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-03-22 18:36 IST to 2016-03-22 18:51 IST: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-03-22 18:51 IST to 2016-03-22 19:06 IST: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-03-22 19:06 IST to 2016-03-22 19:21 IST: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-03-22 19:21 IST to 2016-03-22 19:36 IST: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-03-22 19:36 IST to 2016-03-22 19:51 IST: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-03-22 19:51 IST to 2016-03-22 20:06 IST: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-03-22 20:06 IST to 2016-03-22 20:21 IST: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-03-22 20:21 IST to 2016-03-22 20:36 IST: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-03-22 20:36 IST to 2016-03-22 20:51 IST: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-03-22 20:51 IST to 2016-03-22 21:06 IST: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-03-22 21:06 IST to 2016-03-22 21:21 IST: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-03-22 21:21 IST to 2016-03-22 21:36 IST: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-03-22 21:36 IST to 2016-03-22 21:51 IST: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-03-22 21:51 IST to 2016-03-22 22:06 IST: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-03-22 22:06 IST to 2016-03-22 22:21 IST: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-03-22 22:21 IST to 2016-03-22 22:36 IST: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-03-22 22:36 IST to 2016-03-22 22:51 IST: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-03-22 22:51 IST to 2016-03-22 23:06 IST: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-03-22 23:06 IST to 2016-03-22 23:21 IST: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-03-22 23:21 IST to 2016-03-22 23:36 IST: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-03-22 23:36 IST to 2016-03-22 23:51 IST: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-03-22 23:51 IST to 2016-03-23 00:06 IST: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-03-23 00:06 IST to 2016-03-23 00:21 IST: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-03-23 00:21 IST to 2016-03-23 00:36 IST: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-03-23 00:36 IST to 2016-03-23 00:51 IST: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-03-23 00:51 IST to 2016-03-23 01:06 IST: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-03-23 01:06 IST to 2016-03-23 01:21 IST: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-03-23 01:21 IST to 2016-03-23 01:36 IST: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-03-23 01:36 IST to 2016-03-23 01:51 IST: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-03-23 01:51 IST to 2016-03-23 02:06 IST: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-03-23 02:06 IST to 2016-03-23 02:21 IST: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-03-23 02:21 IST to 2016-03-23 02:36 IST: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-03-23 02:36 IST to 2016-03-23 02:51 IST: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-03-23 02:51 IST to 2016-03-23 03:06 IST: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-03-23 03:06 IST to 2016-03-23 03:21 IST: 3 hits
INFO:elastalert:Queried rule Example rule from 2016-03-23 03:21 IST to 2016-03-23 03:36 IST: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-03-23 03:36 IST to 2016-03-23 03:51 IST: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-03-23 03:51 IST to 2016-03-23 04:06 IST: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-03-23 04:06 IST to 2016-03-23 04:21 IST: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-03-23 04:21 IST to 2016-03-23 04:36 IST: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-03-23 04:36 IST to 2016-03-23 04:51 IST: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-03-23 04:51 IST to 2016-03-23 05:06 IST: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-03-23 05:06 IST to 2016-03-23 05:21 IST: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-03-23 05:21 IST to 2016-03-23 05:36 IST: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-03-23 05:36 IST to 2016-03-23 05:51 IST: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-03-23 05:51 IST to 2016-03-23 06:06 IST: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-03-23 06:06 IST to 2016-03-23 06:21 IST: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-03-23 06:21 IST to 2016-03-23 06:36 IST: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-03-23 06:36 IST to 2016-03-23 06:51 IST: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-03-23 06:51 IST to 2016-03-23 07:06 IST: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-03-23 07:06 IST to 2016-03-23 07:21 IST: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-03-23 07:21 IST to 2016-03-23 07:36 IST: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-03-23 07:36 IST to 2016-03-23 07:51 IST: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-03-23 07:51 IST to 2016-03-23 08:06 IST: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-03-23 08:06 IST to 2016-03-23 08:21 IST: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-03-23 08:21 IST to 2016-03-23 08:36 IST: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-03-23 08:36 IST to 2016-03-23 08:51 IST: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-03-23 08:51 IST to 2016-03-23 09:06 IST: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-03-23 09:06 IST to 2016-03-23 09:11 IST: 3 hits
INFO:elastalert:Skipping writing to ES: {'rule_name': 'Example rule', '@timestamp': '2016-03-23T03:41:39.047127Z', 'exponent': 0, 'until': '2016-03-23T03:42:39.047113Z'}
INFO:elastalert:Alert for Example rule at 2016-03-22T16:22:35+05:30:
INFO:elastalert:Example rule

>At least 1 events occurred between 2016-03-22 15:22 IST and 2016-03-22 16:22 IST

>@test_log: fluent.info
@timestamp: 2016-03-22T16:22:35+05:30
_id: AVOd9G9jB5DqRkWyk3CD
_index: logstash-2016.03.22
_type: fluentd
message: shutting down fluentd

>INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Skipping writing to ES: {'hits': 20, 'matches': 20, '@timestamp': '2016-03-23T03:41:39.049771Z', 'rule_name': 'Example rule', 'starttime': '2016-03-22T10:51:47.028722Z', 'endtime': '2016-03-23T03:41:38.699505Z', 'time_taken': 0.35025691986083984}
INFO:elastalert:Ran Example rule from 2016-03-22 16:21 IST to 2016-03-23 09:11 IST: 20 query hits, 20 matches, 0 alerts sent
INFO:elastalert:Sleeping for 59 seconds

**I have disabled firewalld and SELINUX on that instance. Still not able to receive emails.**

Kindly help me to resolve this issue

-Rohit

**Comment by rohitrsh** [comment]
Hi All,

It has been fixed, due that i was using --debug switch it wasn't sending alert. 

-Rohit

**Comment by Renu353** [comment]
Hi All,

I am using --verbose still am unable to send mails.
Is it necessary to configure postfix sals_passwd in server to send mails from elastalert ??
cant we configure smtp details in config.yaml and destination mail in frequency.yaml ?
