### ISSUE TITLE
How to modify the message of the alert

### ISSUE THREAD

**Issue by BrentMellaerts** [Yelp/elastalert#441]
When I'm running elastalert, I get the following message. 

_test_rule
test_rule

At least 6 events occurred between 2016-03-21 09:26 UTC and 2016-03-21 14:26 UTC

@timestamp: 2016-03-21T14:26:15.794Z
@version: 1
_id: AVOZkbVQV7yhUKTSFPcL
_index: logstash-2016.03.21
_type: apacheAccess
agent: [
   "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36",
   "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36"
]
auth: [
   "-",
   "-"
]
bytes: [
   "971",
   "971"
]
clientip: [
   "127.0.0.1",
   "127.0.0.1"
]
host: ip-172-31-21-122
httpversion: [
   "1.1",
   "1.1"
]
ident: [
   "-",
   "-"
]
kibana_link: http://localhost:5601/app/kibana#/dashboard/Elision?_g=%28refreshInterval%3A%28display%3AOff%2Csection%3A0%2Cvalue%3A0%29%2Ctime%3A%28from%3A%272016-03-21T09%3A26%3A15.794Z%27%2Cmode%3Aabsolute%2Cto%3A%272016-03-21T19%3A26%3A15.794Z%27%29%29
message: 127.0.0.1 - - [29/Feb/2016:14:50:42 +0100] "POST /login.action?header=true HTTP/1.1" 400 971 "https://acc-dmlights.elision.be/" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36"
path: /home/ubuntu/logs/apache_access_log
referrer: [
   "https://acc-dmlights.elision.be/",
   "https://acc-dmlights.elision.be/"
]
request: [
   "/login.action?header=true",
   "/login.action?header=true"
]
response: [
   "400",
   "400"
]
timestamp: [
   "29/Feb/2016:14:50:42 +0100",
   "29/Feb/2016:14:50:42 +0100"
]
type: apacheAccess
verb: [
   "POST",
   "POST"
]_

The message body is not really readable. So I was wondering if it's posible to create another alert message? I've read the documentation but I can't find any information for this issue.

**Comment by Qmando** [comment]
http://elastalert.readthedocs.org/en/latest/ruletypes.html#alert-content

``alert_text``, ``alert_text_type``, and maybe ``alert_text_args`` are what you want.
