### ISSUE TITLE
Sending alerts to file

### ISSUE THREAD

**Issue by romanvog** [Yelp/elastalert#453]
Is there an option to redirect alerts to a file using "command"?

**Comment by Qmando** [comment]
Not directly, but you could do
```
alert: command
command: ["tee", "-a", "/path/to/file.txt"]
pipe_match_json: true
```
You could also use part of the match in the file path, such as
```
command: ["tee", "-a", "/alerts/%{username}.log"]
```
where username must be a field in the documents which match the alert.

**Comment by romanvog** [comment]
thanks mate.
tried running in debug mode and redirecting output to a file with ' 2>&1 &', but yours does the job faster.

**Comment by romanvog** [comment]
output comes out messy, so if you need to have it the way it's being sent to email try this: 

cat  /path/to/file.txt | grep -v "INFO" | tr "," "\n" | sed 's/"@log_name":/\n\n"@log_name":/' | sed 's/\"//g' > /path/to/new_file.txt
