### ISSUE TITLE
download_dashboard not working

### ISSUE THREAD

**Issue by NicoYUE** [Yelp/elastalert#468]
Hello,

I'm trying to use dashboard from Kibana 3.

I followed the tutorial by writing: 
```
filter:
    download_dashboard "Dash Name"
```

And I get 

```
elastalert.util.EAException: Error loading file example_rules/example_frequency.yaml: Invalid Rule: Example rule
{'download_dashboard': 'External Ports Scans'} is not of type 'array'
```

It's just like in the tutorial so I don't know what's wrong.

I have no problem with elastalert-rule-from-kibana though, but I need to create rules dynamically depending on my dashboards so I hope to make download_dashboard work.

thank you

**Comment by Qmando** [comment]
Ah, shoot. Yeah it looks like the schema was changed at some point to make ``filter`` HAVE to be a list. I don't use this particular feature so I haven't noticed. Thanks for reporting this, I'll get a fix up soon

**Comment by dayglojesus** [comment]
Funny, had not tried ElastAlert until very recently and ran into this very issue. When the fix is available, will it include support for Kibana 4?
