### ISSUE TITLE
use_ssl not working

### ISSUE THREAD

**Issue by dhawal55** [Yelp/elastalert#480]
I have `set use_ssl: True` in config but the error says it tried to connect over http.

Here's the config snippet:
```
es_host: XXX.us-west-2.es.amazonaws.com
es_port: 443
use_ssl: True
```

And here's the error:
```
DEBG 'elastalert' stderr output:
WARNING:elasticsearch:GET http://XXX.us-west-2.es.amazonaws.com:443/logstash-*/_search?_source_include=%40timestamp%2C%2A&ignore_unavailable=true&size=10000 [status:N/A request:127.484s]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_requests.py", line 56, in perform_request
    response = self.session.request(method, url, data=body, timeout=timeout or self.timeout)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error(110, 'Connection timed out'))
```

**Comment by dhawal55** [comment]
Do i have to repeat the es_host, es_port and use_ssl settings in my rule file? Also, does it work if i have my alert settings in config instead of repeating it in each rules file?

**Comment by Qmando** [comment]
ssl is working, your query is timing out.
Try setting
```
index: logstash-%Y.%m (monthly)
index: logstash-%Y.%m.%d (daily)
use_strftime_index: true
```

If you have too many documents matching, you might need to use ``use_count_query`` or ``use_terms_query``.

You shouldn't need es_host, port, ssl in the rule file, except for if you use ``elastalert-test-rule``. As for the alert settings, some are universal, like smtp settings, but most are not.

**Comment by dhawal55** [comment]
Thanks @Qmando. Setting `writeback_index`and `alert_time_limit` made my queries faster and not time-out. The WARNING showed "http" in the url so i thought it was not honoring use_ssl.
