### ISSUE TITLE
Allow multiple email recipients

### ISSUE THREAD

**Issue by portante** [Yelp/elastalert#485]
Could we add the ability to support multiple email recipients?

I ran into an issue with email alerts.  Given the following *bad* configuration ...

```
name: "Alert on PMIE Events >= Crit"
es_host: elasticsearch.example.com
es_port: 9280
use_strftime_index: true
index: "logstash-%Y.%m.%d"
type: frequency
num_events: 1
timeframe:
    minutes: 5
filter:
- query:
    query_string:
      query: "rsyslog.programname:pcp-pmie AND (level:crit OR level:alert OR level:emerg)"
alert:
- "email"
alert_subject:
- "PMIE Event {0} - {1}"
alert_subject:
- "level"
- "message"
email:
- "admins@example.com"
```

... we see the following error printed on the console ...

```
ERROR:root:Traceback (most recent call last):]
  File "/usr/lib/python2.6/site-packages/elastalert/elastalert.py", line 877, in alert
    return self.send_alert(matches, rule, alert_time=alert_time)
  File "/usr/lib/python2.6/site-packages/elastalert/elastalert.py", line 950, in send_alert
    alert.alert(matches)
  File "/usr/lib/python2.6/site-packages/elastalert/alerts.py", line 269, in alert
    self.smtp.sendmail(self.from_addr, to_addr, email_msg.as_string())
  File "/usr/lib64/python2.6/email/message.py", line 135, in as_string
    g.flatten(self, unixfrom=unixfrom)
  File "/usr/lib64/python2.6/email/generator.py", line 83, in flatten
    self._write(msg)
  File "/usr/lib64/python2.6/email/generator.py", line 115, in _write
    self._write_headers(msg)
  File "/usr/lib64/python2.6/email/generator.py", line 161, in _write_headers
    header_name=h, continuation_ws='\t').encode()
  File "/usr/lib64/python2.6/email/header.py", line 403, in encode
    return self._encode_chunks(newchunks, maxlinelen)
  File "/usr/lib64/python2.6/email/header.py", line 363, in _encode_chunks
    _max_append(chunks, s, maxlinelen, extra)
  File "/usr/lib64/python2.6/email/quoprimime.py", line 97, in _max_append
    L.append(s.lstrip())
AttributeError: 'list' object has no attribute 'lstrip'

ERROR:root:Uncaught exception running rule Alert on PMIE Events >= Crit: 'list' object has no attribute 'lstrip'
```

Does this look familiar to anyone?  This describes one of the problems: http://stackoverflow.com/questions/26985683/attribute-error-list-object-has-not-attribute-lstrip-in-sending-an-email-with-a

Basically, because we are using the "list" syntax for the email recipient:

```
email:
- "admins@example.com"
```

This `receiver` object becomes a list and not a string, causing the error above.  If instead we change this to:

```
email: "admins@example.com"
```

Everything starts working again (well almost, see below).

It would be nice if ElastAlert allowed for a list of email recipients to be specified instead of getting its shorts all in a bunch.

-----

There are other errors with this configuration, FWIW:

 1. The redundant `alert_subject` sections, where the second section is a list, causing a format error
 2. The first `alert_subject` section needs to be on one line so the subject does not become a list
  * `alert_subject: "PMIE Event {0} - {1}"`

FWIW, I am very happy with ElastAlert!  Thanks for making this available!

**Comment by Qmando** [comment]
Are you sure it still gives you that error when you have the emails as a list? We have lots of alerts that have multiple recipients. The alert_subject cannot be a list, but ``email`` definitely can.

**Comment by portante** [comment]
@Qmando I have not been able to track this down further to reproduce.  If I run into it again, I'll just re-open.  Thanks!

**Comment by panamantis** [comment]
msgRoot['To'] = ",".join(to_emails)
Convert your email list to a sting when assigning it to 'to'.
