### ISSUE TITLE
not all fields are working at my frequency rule

### ISSUE THREAD

**Issue by phermann1988** [Yelp/elastalert#504]
Hi, 
i justed startet with elastalert and tried the example_frequency which worked for specific fields. for example if try:
```
....
filter:
- term:
    _type: was_infolog 
...
```
it workes and gets me the at least 6 events in 4 hours. in the same logs is a field with the name STATUS and the value " PLM.gmp_finished" is the one I'm interested in. but sadly i always got zero result, i tried to writh it filter: -term: STATUS: PLM.gmp_finished or term: STATUS: "PLM.gmp_finished" but no results. if i search in kibana i get results so I dont know where the issue is. 

can you help me?

and is there a way to change the time settings to european time zone?

thank you :-)

**Comment by Qmando** [comment]
Use query string or STATUS.raw. 
http://elastalert.readthedocs.io/en/latest/recipes/writing_filters.html#query-string
