### ISSUE TITLE
Elasticsearch 5.x support

### ISSUE THREAD

**Issue by akaFalsh** [Yelp/elastalert#510]
Is it planned to support elasticsearch 5.x?

**Comment by nickmz** [comment]
+1
Given the upcoming release of Elasticsearch 5 it would be very helpful to have an idea of whether this 
is on the roadmap for Elastalert and what potential timeframes might look like, if possible. It potentially has a large impact on upgrade and development plans.

**Comment by watollop** [comment]
+1

**Comment by bennneuh** [comment]
+1

**Comment by irom77** [comment]
?

**Comment by vijayarulmuthu** [comment]
+1

**Comment by kojisaiki** [comment]
+1

**Comment by AnderssonPeter** [comment]
Please use the thumbs up button on the issue instead of posting +1.
This way subscribers don't get a email and you still show that you want this to happen!!!

**Comment by Qmando** [comment]
Closing in favor of #790
