### ISSUE TITLE
Rule based on top count?

### ISSUE THREAD

**Issue by jmilliron** [Yelp/elastalert#512]
I'm probably missing something obvious here.  Want a rule that alerts when unique count for a field is over a certain value.  I'm looking to alert on too many requests from an IP in a given time period.  

So basically:
- query
- order by field, descending
- size 5
- alert if resulting count is above a number.

top_count_keys and top_count_number looked promising, but apparently that's just for the alert content, not the rule. 

New term also looked promising but I'm interested in term count.  

Thanks!

**Comment by Qmando** [comment]
You want the cardinality rule type.

**Comment by jmilliron** [comment]
Ah!  I looked at that one but I must have misunderstood.  Thank you Qmando!
