### ISSUE TITLE
Write "query" in alert rules

### ISSUE THREAD

**Issue by yuan0122** [Yelp/elastalert#521]
Hi, I am writing ElastAlert rule to monitor a specific field. I want to send alert for a field, say "id_count", when it is not equal to 1. 
In Elasticsearch, I can query with the following:

```
curl -XGET 'http://{host}:{port}/{index}/{type}/_search?pretty' -i -d '
{
  "query": {
    "bool": {
      "must_not": {
        "match": {
          "id_count": "1"
        }
      }
    }
  }
}
'
```

I'm thinking about write a rule with type "any", just send alerts whenever get a hit that matches my query. But I didn't find any good example that shows how to write a query in alert rules. Could anyone help? Thanks so much!!!

**Comment by bean5** [comment]
@yuan0122  You could try this:

```
filter:
- query:
    query_string:
        query: "NOT id_count: 1"
```
