### ISSUE TITLE
Multiple alerts in one email?

### ISSUE THREAD

**Issue by yuan0122** [Yelp/elastalert#524]
Is it possible to alert on multiple matches, with only one email sent? 

Say during a time frame, I have 10 matches, I hope to get all alerts but I don't want to receive 10 emails. Is it possible to get only one alerting email, which includes all matches' information? 

Any comments would be super helpful. Thank you in advance!

**Comment by Qmando** [comment]
http://elastalert.readthedocs.io/en/latest/ruletypes.html?highlight=aggregation#aggregation

You can either alert on a schedule, or X amount of time since the first match occurs

"When an alert fires, aggregation together all alerts for the next 15 minutes, then send it as one email"
```
aggregation:
  minutes: 15
``` 

"Send every alert together at noon every day"
```
aggregation:
  schedule: "0 12 * * *"
```

**Comment by yuan0122** [comment]
Thanks for your reply!

What if I have multiple matches in exact the same timestamp, can I send them all in one email? 

I was executing elastalert with 
`
elastalert --rule {my_rule} --start {start_time} --end {end_time}`

And I got, say 10 matches. 

I have added "realert" to help send out alerts on all matches, there were 10 emails in `mailq`
```
realert:
  minutes: 0
```

But the following doesn't work on combining all alerts in one email.
```
aggregation:
  minutes: 0
```

Was I doing in the right way? If no, how could I fix this? Thanks!

**Comment by Qmando** [comment]
0 minute aggregation means no aggregation. You need a time associated with it. It means, "After the first alert, aggregate every alert for the next X time into one email". 

Unfortunately, it doesn't work all that well with ``--start`` and ``--end`` for two reasons. 
1. One is that the aggregation time is added to NOW and not from time document's @timestamp. If you have 10 minute aggregation, and ran elastalert over data from yesterday, it will collect all the alerts and then send them in 10 minutes.
2. When using ``--end``, elastalert actually stops. So if it's not still running after 10 minutes, the alert won't be sent.

There's some ways you could still work with this. For example, set aggregation to 1 or 2 minutes, then run with ``--start`` and ``--end`` (assuming that finishes before 1 to 2 minutes). Now, simply run elastalert again without ``--start`` or ``--end`` and if 1 or 2 minutes has gone by, the alert will fire.

**Comment by yuan0122** [comment]
Thanks! @Qmando 

Piggybacking on this, I got the following error for more than once when executing elastalert. Do you know why and how can I fix this? 

```
ERROR:root:Error while querying for alert silence status: TransportError(400, u'No handler found for uri [/elasticsearch/elastalert_status/silence/_search?_source_include=until%2Cexponent&size=1] and method [GET]')
WARNING:elasticsearch:POST http://10.0.0.106:9200/elasticsearch/elastalert_status/elastalert_error?op_type=create [status:409 request:0.003s]
ERROR:root:Error writing alert info to elasticsearch: TransportError(409, u'document_already_exists_exception', u'[elastalert_status][elastalert_error]: document already exists')
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/elastalert/elastalert.py", line 1011, in writeback
    doc_type=doc_type, body=body)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/__init__.py", line 248, in create
    return self.index(index, doc_type, body, id=id, params=params, op_type='create')
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/__init__.py", line 279, in index
    _make_path(index, doc_type, id), params=params, body=body)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/transport.py", line 329, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_requests.py", line 84, in perform_request
    self._raise_error(response.status_code, raw_data)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/base.py", line 108, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
ConflictError: TransportError(409, u'document_already_exists_exception', u'[elastalert_status][elastalert_error]: document already exists')
```

**Comment by Qmando** [comment]
Do you have ``es_url_prefix`` set?

``POST http://10.0.0.106:9200/elasticsearch/elastalert_status/elastalert_error?op_type=create [status:409 request:0.003s]``
I can see that it's making queries to /elasticsearch/elastalert_status/elastalert_error when it should be just /elastalert_status/elastalert_error. With that extra ``elasticsearch`` in there, THAT becomes the index and then ``elastalert_status`` becomes the _type and ``elastalert_error`` becomes the _id, hence the document already exists error.

This option is only for certain situations in which the URL is translated in some way and you cannot connect directly to Elasticsearch.

**Comment by yuan0122** [comment]
No I didn't. 

So I added `es_url_prefix: "http://10.0.0.106:9200/"` to my rule yaml file. Then it tried to connect to 
`ERROR:root:Error running query: TransportError(400, u'No handler found for uri [/http://10.0.0.106:9200/alerts-*/_search?_source_include=%40timestamp%2C%2A&ignore_unavailable=true&size=10000] and method [GET]')`

**Comment by Qmando** [comment]
You are sure you don't have ``es_url_prefix`` set in config.yaml?

**Comment by Qmando** [comment]
This line is STILL commented out? https://github.com/Yelp/elastalert/blob/master/config.yaml.example#L23

**Comment by yuan0122** [comment]
Oh, got it!!! 

Thank you so much! @Qmando
