### ISSUE TITLE
Email content doesn't include information for all hits

### ISSUE THREAD

**Issue by vikas8190** [Yelp/elastalert#527]
On running elastalert, i get the below log:
INFO:elastalert:Starting up
INFO:elastalert:Queried rule Example rule from 2016-05-13 15:17 ART to 2016-05-13 15:32 ART: 14 hits
INFO:elastalert:Sent email to ['username@maildomain.com']
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ran Example rule from 2016-05-13 15:17 ART to 2016-05-13 15:32 ART: 14 query hits, 14 matches, 1 alerts sent

However in the mail I got, i could see only 1 out of the 14 matches . Is this a bug or do i need to set some configuration so that I get all the match information to the configured email

**Comment by Qmando** [comment]
If you want to get an alert for each document
```
realert:
  minutes: 0
```
See http://elastalert.readthedocs.io/en/latest/ruletypes.html?highlight=realert#realert

If you want to get a single email with all of them, you either need to use ``type: frequency`` + ``num_events: X`` + ``top_count_keys`` OR set ``aggregation``.

**Comment by vikas8190** [comment]
I set aggregation to aggregate for a minute and then send. Still there was only one of the match in the alert mail. Log is as below:

INFO:elastalert:Queried rule Example rule from 2016-05-13 16:45 ART to 2016-05-13 16:46 ART: 14 hits
INFO:elastalert:New aggregation for Example rule. next alert at 2016-05-13 19:47:37.343000+00:00.
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ran Example rule from 2016-05-13 16:45 ART to 2016-05-13 16:46 ART: 14 query hits, 14 matches, 0 alerts sent
INFO:elastalert:Sleeping for 59 seconds


INFO:elastalert:Sent email to ['username@maildomain.com']
INFO:elastalert:Queried rule Example rule from 2016-05-13 16:45 ART to 2016-05-13 16:47 ART: 14 hits
INFO:elastalert:Ran Example rule from 2016-05-13 16:45 ART to 2016-05-13 16:47 ART: 14 query hits, 0 matches, 1 alerts sent

**Comment by Qmando** [comment]
```
realert:
  minutes: 0
```

**Comment by vikas8190** [comment]
Thanks a lot. It worked
