### ISSUE TITLE
Two rules being mixed up

### ISSUE THREAD

**Issue by TroelsL** [Yelp/elastalert#540]
I have a custom rule type similar to a flatline. I have created two rules for the type, and somehow they keep getting mixed up when I run it. As I can't run two rules at the same time in test, I'm having a very difficult time reproducing it.

In rule one, I check for the existence of a message with Id='359' that should arrive before 13:00 daily.
Rule two checks for messages with id IN (2170, 495, 499, 15192, 20591, 3502) arriving before 00:00.

The elasticsearch queries both contain something like:
- terms:
    fields.SeriesId: [2170, 495, 499, 15192, 20591, 3502, 2197]

My issue is that every day at 13:00, I get an alert for series 3502 from rule One and at 00:00 I get an error for Id 359 from rule two.

Can anyone think if any reason that these two rules would get mixed up like this?

**Comment by Qmando** [comment]
Can you post your rules and perhaps your custom rule type code? I have not experienced anything like the filters on rules getting switched.

**Comment by TroelsL** [comment]
Certainly, the custom rules:

`import dateutil.parser
import pytz
from datetime import datetime, date, time, timedelta, tzinfo
from elastalert.ruletypes import RuleType
from elastalert.util import ts_to_dt

class OffsetRule(RuleType):
    required_options = set(['deadline', 'offset_start', 'offset_end', 'min_date_field', 'max_date_field', 'internal_id_field'])
        
    next_deadline = None
    period_start = None
    period_end = None
    id_map = {}
    allow_new_series = True;

    # initialize class by populating the id_map if the parameter prefilled_map
    # is present in the config
    def __init__(self, rules, args=None):
        self.matches = []
        self.rules = rules

        if 'allow_new_series' in self.rules and self.rules['allow_new_series'] == False:
            self.allow_new_series = False

        self.occurrences = {}
        
        if 'prefilled_map' in self.rules:
            map = self.rules['prefilled_map']
            for key in map.keys():
                self.id_map[key] = { 'external_key': map[key], 'matched': True }
            
    # check the received documents to see if they match the current period
    def add_data(self, data):
        for document in data:
            self.check_received(document)
    
    # return a custom alert message
    def get_match_str(self, match):
        return "No messages for the period [{0} UTC to {1}UTC] received before the deadline of {2}UTC.\nInternal Id: {3}\nExternal Id: {4}".format(match['period_start'], match['period_end'], match['deadline'], match['internal_key'], match['external_key'])

    # after each run, check to see if we've passed the next_deadline.  If so,
    # check all keys in the id_map to see whether we have received data
    def garbage_collect(self, timestamp):
        current_deadline = self.next_deadline
        current_period_start = self.period_start
        current_period_end = self.period_end

        if self.check_deadline(timestamp) == True:
            print "Matching: %s" % self.id_map

            for key in self.id_map:
                if self.id_map[key]['matched'] == False:
                    match = {}
                    match['@timestamp'] = timestamp
                    match['external_key'] = self.id_map[key]['external_key']
                    match['internal_key'] = key
                    match['deadline'] = current_deadline
                    match['period_start'] = current_period_start
                    match['period_end'] = current_period_end
                    print "\n[INFORMATION] Raised alert for series: %s (%s)\n" % (key, self.id_map[key]['external_key'])
                    self.add_match(match)
                else:
                    print "Series %s was matched" % key
            self.clear_matches()

    # given a document, see if the period matches - if so, set 'matched' to
    # True in the id_map
    def check_received(self, document):
        document_start = dateutil.parser.parse(document['fields'][self.rules['min_date_field']])
        document_end = dateutil.parser.parse(document['fields'][self.rules['max_date_field']])
        internal_key = document['fields'][self.rules['internal_id_field']]

        if 'external_id_field' in self.rules:
            external_key = document['fields'][self.rules['external_id_field']]
        else:
            external_key = internal_key
        
        if internal_key not in self.id_map and self.allow_new_series == True:
            entry = { 'external_key': external_key, 'matched': False }
            self.id_map[internal_key] = entry
            print "Added series %s (%s) to watch list" % (internal_key, external_key)
        print "\n[INFORMATION] Matching document received at %s with data range: \n(%s - %s) against \n(%s - %s)\n" % (document['@timestamp'], document_start, document_end, self.period_start, self.period_end)
        if document_start <= self.period_start and document_end >= self.period_end and internal_key in self.id_map:
            print "\n[INFORMATION] Matched document received at %s with data range: \n(%s - %s) against \n(%s - %s)\n" % (document['@timestamp'], document_start, document_end, self.period_start, self.period_end)
            self.id_map[internal_key]['matched'] = True

    # returns true if we've passed the next_deadline.  Will also set
    # next_deadline
    def check_deadline(self, current_time):
        if self.next_deadline == None:
            deadline = dateutil.parser.parse(self.rules['deadline']).time()
            tmp = datetime(current_time.year, current_time.month, current_time.day, deadline.hour, deadline.minute, 0, 0, pytz.utc)
            if current_time.hour < deadline.hour or (current_time.hour == deadline.hour and current_time.minute < deadline.minute):
                self.set_deadline(tmp)
            else:
                self.set_deadline(tmp + timedelta(days = 1))
            return False
        if current_time > self.next_deadline:
            next_deadline = self.next_deadline + timedelta(days = 1)
            if self.skip_deadlines > 0:
                next_deadline = self.next_deadline + timedelta(days = (1 + self.skip_deadlines))
            self.set_deadline(next_deadline)
            return True
        return False

    # set next_deadline, period_start and period_end
    def set_deadline(self, value):
        offset_start = timedelta(**self.rules['offset_start'])
        offset_end = timedelta(**self.rules['offset_end'])

        weekday = self.weekday_to_string(value.weekday())
        offset = self.get_special_days(weekday)
        
        self.skip_deadlines = 0

        if offset != None:
            offset_start = offset['start']
            offset_end = offset['end']
            if 'skip_deadlines' in offset:
                self.skip_deadlines = offset['skip_deadlines']
            
        self.period_start = value + offset_start
        self.period_end = value + offset_end
        self.next_deadline = value
        print "\n[INFORMATION] Set monitoring period as %s to %s.\nNext deadline: %s\n" % (self.period_start, self.period_end, self.next_deadline)

    # set all series as unmatched
    def clear_matches(self):
        for key in self.id_map:
            self.id_map[key]['matched'] = False

    def weekday_to_string(self, index):
        return {
            0: "mon",
            1: "tue",
            2: "wed",
            3: "thu",
            4: "fri",
            5: "sat",
            6: "sun"
        }.get(index)

    def get_special_days(self, dayofweek):
        if 'special_days' in self.rules:
            special_days = self.rules['special_days']
            for entry in special_days:
                if entry['day'] == dayofweek:
                    offset = {}
                    offset['start'] = timedelta(**entry['offset_start'])
                    offset['end'] = timedelta(**entry['offset_end'])
                    offset['deadline_delta'] = 1
                    if 'skip_deadlines' in entry:
                        offset['deadline_delta'] = entry['skip_deadlines']
                    return offset
        return None`

`import dateutil.parser
import pytz
from datetime import datetime, date, time, timedelta, tzinfo
from elastalert.util import ts_to_dt
from xxx.offset_rule import OffsetRule

class DayAheadRule(OffsetRule):
    required_options = set(['prefilled_map', 'offset_start', 'offset_end'])

    # initialize class by populating the id_map if the parameter prefilled_map
    # is present in the config
    def __init__(self, rules, args=None):
        self.rules = rules;
        series_ids = self.rules["prefilled_map"].keys()
        
        self.rules["filter"] = [
            {'query': {'query_string': {'query': 'fields.messageTemplate = "Finished storing data for {MessageId}. {rowcount} rows were stored in {timetaken} msec at a rate of {storerate} rows/sec"'}}},
            {'query': {'query_string': {'query': 'fields.ApplicationName = "PCNSInserter"'}}}, 
            {'terms': {'fields.SeriesId': series_ids}}]
        self.rules["internal_id_field"] = "SeriesId"
        self.rules["external_id_field"] = "OriginId"
        self.rules["min_date_field"] = "MinValueDateTime"
        self.rules["max_date_field"] = "MaxValueDateTime"
        self.rules["allow_new_series"] = False
        OffsetRule.__init__(self, self.rules, args)`

And the rules .yamls:

`es_host: elasticsearch
es_port: 9200

name: PCNS Day Ahead 359 (103832867)

type: "xxx.day_ahead_rule.DayAheadRule"

index: logstash-*

offset_start:
    hours: 11
offset_end:
    days: 1
    hours: 10
deadline: "11:00" #UTC

prefilled_map:
    359: 103832867

and:

`es_host: elasticsearch
es_port: 9200

name: PCNS Spot Prices (2170, 495, 499, 15192, 20591, 3502)

type: "xxx.offset_rule.OffsetRule"

index: logstash-*

filter:
- query:
    query_string:
        query: "fields.messageTemplate = \"Finished storing data for {MessageId}. {rowcount} rows were stored in {timetaken} msec at a rate of {storerate} rows/sec\""
- query:
    query_string:
      query: "fields.ApplicationName = \"PCNSInserter\""
- terms:
    fields.SeriesId: [2170, 495, 499, 15192, 20591, 3502, 2197]
    
internal_id_field: "SeriesId"
external_id_field: 'OriginId'

offset_start:
    hours: 0
offset_end:
    hours: 0
deadline: "22:00" #UTC

special_days:
    - {day: "fri", offset_start: { hours: 0 }, offset_end: { days: 2 }, skip_deadlines: 2 }

prefilled_map:
    495: 103427471
    499: 103427469
    2170: 103427473
    3502: 103251278
    15192: 106711180
    20591: 106706482
    
allow_new_series: False
    
min_date_field: "MinValueDateTime"
max_date_field: "MaxValueDateTime"
           
As you can see, there are two rule types to keep the config files smaller. Since yesterday, I tried adding the allow_new_series, which appears to have fixed the issue. However, I don't see why it is necessary as the ES query should never return results outside the specified set.

**Comment by TroelsL** [comment]
It still clashes - I get the following email:

PCNS Spot Prices (2170, 495, 499, 15192, 20591, 3502)

No messages for the period [2016-05-24 22:00:00+00:00 UTC to 2016-05-24 22:00:00+00:00UTC] received before the deadline of 2016-05-24 22:00:00+00:00UTC.
Internal Id: **359**
External Id: 103832867

@timestamp: 2016-05-24T22:00:47.317Z
deadline: 2016-05-24 22:00:00+00:00
external_key: 103832867
internal_key: 359
period_end: 2016-05-24 22:00:00+00:00
period_start: 2016-05-24 22:00:00+00:00

I simply cannot understand how this can happen. Is there any way to test two rules at once?

**Comment by TroelsL** [comment]
Aaaand I've found it. My limited python experience led me to believe that id_map was declared as a class member rather than a static. I've moved it inside the __init__ method, and everything works.
