### ISSUE TITLE
Pip package contains errant pdb.set_trace() calls

### ISSUE THREAD

**Issue by thecubed** [Yelp/elastalert#560]
It would seem that the PyPi 0.0.82 package for elastalert has some differences from the 0.0.82 git tag on github:

```
$ grep 'pdb' -R -nr *
elastalert/elastalert.py:431:        import pdb;pdb.set_trace()
modules/air/email_util.py:13:    import pdb;pdb.set_trace()
modules/sum_of_field_rule.py:151:            import pdb;pdb.set_trace()
modules/ytp_partner_emailer_alert.py:57:        import pdb;pdb.set_trace()
```

This make elastalert drop to a debugger after running rules and many other conditions.

The MD5Sum of the source and the release tar.gz file on github differ too.

@Qmando seems to be the admin of the PyPi package - figured I should give a heads up here so this won't surprise anyone else that uses the pip packages.

Thanks!

**Comment by thecubed** [comment]
Also noticed that there seems to be some internal rules that might not be meant to be released in the pip package (the whole modules/ directory doesn't exist in git, yet it exists in the pip package).

**Comment by Qmando** [comment]
Thanks for reporting this. It should be fixed now.
