### ISSUE TITLE
schema.yaml missing from package on pypi (0.0.83)

### ISSUE THREAD

**Issue by piquadrat** [Yelp/elastalert#566]
I get the following error when running elastalert 0.0.83, installed from PyPI

    Traceback (most recent call last):
      File "/usr/bin/elastalert", line 7, in <module>
        from elastalert.elastalert import main
      File "/usr/lib/python2.7/site-packages/elastalert/elastalert.py", line 22, in <module>
        from config import get_rule_hashes
      File "/usr/lib/python2.7/site-packages/elastalert/config.py", line 27, in <module>
        rule_schema = jsonschema.Draft4Validator(yaml.load(open(os.path.join(os.path.dirname(__file__), 'schema.yaml'))))
    IOError: [Errno 2] No such file or directory: '/usr/lib/python2.7/site-packages/elastalert/schema.yaml'

looking at the tar.gz, `schema.yaml` seems to be indeed missing:

    $ tar xvf elastalert-0.0.83.tar.gz
    x elastalert-0.0.83/
    x elastalert-0.0.83/PKG-INFO
    x elastalert-0.0.83/tests/
    x elastalert-0.0.83/tests/util_test.py
    x elastalert-0.0.83/tests/conftest.py
    x elastalert-0.0.83/tests/alerts_test.py
    x elastalert-0.0.83/tests/base_test.py
    x elastalert-0.0.83/tests/config_test.py
    x elastalert-0.0.83/tests/kibana_test.py
    x elastalert-0.0.83/tests/rules_test.py
    x elastalert-0.0.83/tests/__init__.py
    x elastalert-0.0.83/setup.cfg
    x elastalert-0.0.83/setup.py
    x elastalert-0.0.83/elastalert/
    x elastalert-0.0.83/elastalert/util.py
    x elastalert-0.0.83/elastalert/test_rule.py
    x elastalert-0.0.83/elastalert/config.py
    x elastalert-0.0.83/elastalert/alerts.py
    x elastalert-0.0.83/elastalert/create_index.py
    x elastalert-0.0.83/elastalert/ruletypes.py
    x elastalert-0.0.83/elastalert/kibana.py
    x elastalert-0.0.83/elastalert/enhancements.py
    x elastalert-0.0.83/elastalert/opsgenie.py
    x elastalert-0.0.83/elastalert/rule_from_kibana.py
    x elastalert-0.0.83/elastalert/elastalert.py
    x elastalert-0.0.83/elastalert/auth.py
    x elastalert-0.0.83/elastalert/__init__.py
    x elastalert-0.0.83/elastalert.egg-info/
    x elastalert-0.0.83/elastalert.egg-info/SOURCES.txt
    x elastalert-0.0.83/elastalert.egg-info/top_level.txt
    x elastalert-0.0.83/elastalert.egg-info/PKG-INFO
    x elastalert-0.0.83/elastalert.egg-info/dependency_links.txt
    x elastalert-0.0.83/elastalert.egg-info/entry_points.txt
    x elastalert-0.0.83/elastalert.egg-info/requires.txt

**Comment by Qmando** [comment]
Oops, I accidentally built this with an old version of setuptools which doesn't support package data. Should be fixed now.
