### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by gopalganu** [Yelp/elastalert#581]
Hello
To install the 0.0.85 version I am following the steps as mentioned.
python setup.py install
pip install -r requirements.txt

I am running ES 2.3. The elasticsearch client installed with above command is 1.3.
Currently I am running Elastalert 0.0.56 and ES 2.3.1, with elasticsearch client 2.3.Without client 2.3 I had problems communicating with ES 2.3

What is the correct version of elasticsearch client to go with ES 2.3. 
Do I need to install the requirements? or should install them manually with appropriate version?

Also I have to install python-dev package, without it the above 2 commands don't succeed. 

Please help.

**Comment by bean5** [comment]
Do you mean what is the correct version of elastalert that goes with ES 2.3?

I have used the latest elastalert (at least that is what I think is in the dockerhub at https://hub.docker.com/r/ivankrizsan/elastalert/). I have had it interface with both ES 2.4 for the writeback index while monitoring information in an ES 2.3.

**Comment by gopalganu** [comment]
We have moved to a later elastalert now. The problem earlier was incompatibility of the versions at 0.0.56.

**Comment by bean5** [comment]
Do you want to close this ticket then?

**Comment by gopalganu** [comment]
Yes, thats if fine.
