### ISSUE TITLE
Elastalert custom subject for SNS alert

### ISSUE THREAD

**Issue by vikas8190** [Yelp/elastalert#590]
Im trying to change the notification subject for SNS notification to send SMS using:
alert_subject: "Custom Subject at {0}!!!"

alert_subject_args:
- "@timestamp"

However, the SMS I get still contain the subject as "Elastalert: RuleName"
The body of the notification configured using alert_text also seems to be missing from the SMS. Any idea why?

**Comment by Qmando** [comment]
Ah the SNS alerter specifically ignores this setting. Sorry about that. 

As for the body and alert_text, it should be using the same code as all the other alerters. What exactly do you expect and what do you get?

**Comment by vikas8190** [comment]
Im just getting "Elastalert: Rulename" as the SMS . The alert_text is completely missing. However if the SNS notification is configured to send email, I get the alert_text as expected in the mail. Issue is only in case of SMS.

**Comment by Qmando** [comment]
Here is the line that publishes the SNS notification. https://github.com/Yelp/elastalert/blob/master/elastalert/alerts.py#L709

The second parameter, body, should be the alert text. That gets passed as the message parameter and then the "Elastalert: rulename" as the subject. See http://boto.cloudhackers.com/en/latest/ref/sns.html#boto.sns.SNSConnection.publish.

I have not personally tested this, but maybe whatever you are using the view the SNS is somehow now showing you the message contents?

**Comment by vikas8190** [comment]
Im still not getting the body content in the SMS alert. So I tweaked alerts.py, alerts function in SnsAlerter class to customize the SNS notification subject as I need.

**Comment by ShaneC-C-Y** [comment]
Hi vikas8190,
It seems like your SNS can function well, could I ask how do you set it up? I have some problem of sending alert to my AWS SNS.
