### ISSUE TITLE
Problems with "command" alert

### ISSUE THREAD

**Issue by MaxFlanders** [Yelp/elastalert#592]
Hi there, I'm encountering all sorts of strange issues trying to set up a command alert. Essentially all I want to do is hit an http endpoint with any matching documents. This is the structure I've got set up for my command alert:

```
    alert:
     - command:
         command: "curl -XPOST -H \"Content-Type: application/json\" \"https://my.endpoint\" -d@-"
    pipe_match_json: true
```

The -d@- option causes curl commands to read from stdin, which as I understand, pipe_match_json should provide.

When I do I get this strange error though:
    `elastalert_error - {'message': 'Error while running alert command: Error while running command c u r l   - X P O S T   - H   " C o n t e n t - T y p e :   a p p l i c a t i o n / j s o n "   " h t t p s : / / m y . e n d p o i n t"   - d @ -: [Errno 2] No such file or directory', 'traceback': ['Traceback (most recent call last):', '  File "/usr/local/lib/python2.7/dist-packages/elastalert-0.0.84-py2.7.egg/elastalert/elastalert.py", line 976, in send_alert', '    alert.alert(matches)', '  File "/usr/local/lib/python2.7/dist-packages/elastalert-0.0.84-py2.7.egg/elastalert/alerts.py", line 660, in alert', '    raise EAException("Error while running command %s: %s" % (\' \'.join(command), e))', 'EAException: Error while running command c u r l   - X P O S T   - H   " C o n t e n t - T y p e :   a p p l i c a t i o n / j s o n "   " h t t p s : / / m y . e n d p o i n t "   - d @ -: [Errno 2] No such file or directory'], 'data': {'rule': 'Google Microservice Error Alert'}}`

In which it seems to be putting spaces in between every letter of my argument.
Any thought on what is going on here??

Thanks!

**Comment by 326TimesBetter** [comment]
Sorry I'm still learning the syntax to post code in these forums, those backticks around the alert definitely are not in the rule.yaml file lol

**Comment by Qmando** [comment]
try
```
alert:
- command:
    command: ["curl -XPOST -H \"Content-Type: application/json\" \"https://my.endpoint\" -d@-"]
pipe_match_json: true 
```

This needs to be fixed actually. It interprets a string as a list in this case.

**Comment by Qmando** [comment]
I've added a fix for this issue. See #593

**Comment by 326TimesBetter** [comment]
That definitely solved that strange issue. Now what happens when I run the script is I get this error:

    'alert_exception': 'Error while running command /opt/bin/curl -XPOST "https://my.endpoint" -d@-: [Errno 2] No such file or directory'}

I have circumvented this error by dropping that one-liner into a script, and then running that script with the alert, but it looks like elastalert has an issue with running commands directly.

Just letting you know, I think I have it in a working place now. Thanks so much for your help!

**Comment by Qmando** [comment]
Ah, yeah the one string method is not correct unless shell=True is also passed, which it isnt. You should be using a list to run commands as arguments.
```
alert:
- command:
    command: ["curl", "-XPOST", "-H" "\"Content-Type: application/json\"", "\"https://my.endpoint\"", "-d@-"]
pipe_match_json: true 
```

**Comment by zhiaixuexi** [comment]
greate helpful u 2

**Comment by mvmn** [comment]
You're missing a coma there before "-H", and quotes around URL break it. Seems correct format would be this:
```
alert:
- command:
    command: ["curl", "-XPOST", "-H", "\"Content-Type: application/json\"", "http://127.0.0.1:8129", "-d@-"]
```

**Comment by shshnkTrxcn** [comment]
what does `@-` signify in the `curl` request. I am  trying to run something similar but not receiving any data on the other end 
`command: "curl  -XPOST 'https://myapi.com/service/data/serverstats/alerts/'  -H 'authorization: Bearer some-random-token-abcd-efgh'  -H 'content-type: application/json' -d@-"`

**Comment by reswob10** [comment]
OK, I'm trying to include single event information in my alert.  My original syntax in my rule is:

command: ["curl -v -k 'http://ip:port/services/collector' -H 'Authorization: user api' -d '{\"event\":{\"data\":\"", "%(host)s", "\"}}"]

when I tested my rule I got the following error:

Error while running alert command: Error while running command curl -v -k \'http://ip:port/services/collector\' -H \'Authorization: user api\' -d \'{\"event\":{\"data\":\" 1.1.1.1 "}}\'

which, if the ' were not escaped, would the the EXACT correct command to run. I unescaped the ' and ran the command and it worked great.

Why are the ' escaped and how can I make them not be escaped?

Should I break it up even further?

**Comment by Qmando** [comment]
@reswob10 

- Don't use [ ] if you aren't going to split up the command. Just keep it as a string, and it will then be interpreted as a shell command.

- What you posted is not valid YAML, you must have run elastalert with something else. You need to escape your DOUBLE quotes

- You don't need to escape single quotes, elastalert doesn't escape them, and I've just verified that using
```
command: "curl -v -k 'http://localhost:14901/foo' -d '{\"event\": \"blah\"}'"
```
works perfectly

**Comment by reswob10** [comment]
Thanks!

**Comment by reswob10** [comment]
OK, after looking at the above, I realized you were not inserting data from the document using the two options shown under the command documents.

First I tried this:

command: "curl -v -k 'http://ip:port/services/collector' -H 'Authorization: user api' -d '{\"event\":{\"field\":\"%(field_name)s\" } } '"

That resulted in this error:  "expected <block end>, but found %r" % token.id, token.start_mark)

I then tried

alert:
- command

new_style_string_format: True
command: "curl -v -k 'http://ip:port/services/collector' -H 'Authorization: user api' -d '{\"event\":{\"field\":\"{match[field_name]}\" } } '"

and that got the same error.

**Comment by Qmando** [comment]
Hm, that looks like a YAML parse error, but it works for me.
```
$ python -c "import yaml;yaml.load(open('test.yaml').read())"
$ cat test.yaml
command: "curl -v -k 'http://ip:port/services/collector' -H 'Authorization: user api' -d '{\"event\":{\"field\":\"%(field_name)s\" } } '"
```

Can you post the full traceback it gives you?

**Comment by reswob10** [comment]
I got it. I missed changing one of the " to ' in the production config and that screwed everything up.  Now it works. 

Thanks again.  sorry to bug you over a typo on my end.
