### ISSUE TITLE
Multiple es hosts

### ISSUE THREAD

**Issue by gopalganu** [Yelp/elastalert#614]
The es_host parameter seems to take only one host. Is it possible to give specify of multiple nodes?
I would like to specify multiple nodes so as to prevent queries going to a single node and also failures if the particular node goes down.

Any other way to achieve this?

**Comment by Qmando** [comment]
I recommend [haproxy](http://www.haproxy.org/). It's super simple to set up a reverse proxy for Elasticsearch to do load balancing.
