### ISSUE TITLE
Default run mode of elastalert

### ISSUE THREAD

**Issue by vikas8190** [Yelp/elastalert#617]
What is the default run mode of elastalert if neither debug nor vebose is mentioned in the command line.
As in when run like:

elastalert --config /dir/elastalert.yaml

what is the mode. Im not receiving alerts on running as above. Should i always give the --verbose parameter. Isnt that the default.

**Comment by Qmando** [comment]
It just won't output anything except for exceptions and errors. ``--verbose`` only affects the logging level. ``--debug`` actually suppresses alerts and logs them to console instead.
