### ISSUE TITLE
Running Elastalert with version  "number" : "2.3.1",

### ISSUE THREAD

**Issue by Pransh20** [Yelp/elastalert#625]
I installed Elastalert but i had a elastic search instance already on my machine so i removed it from setup.py.

Can i run elastalert on my previous version rather than using the python library

Can anyone help me how to configure it for elasticsearch 2.3.1

Thanks

**Comment by Qmando** [comment]
It definitely works with the 1.X version of the library, and with some 2.X versions as well. Try downgrading  to 2.2 or 2.1.
