### ISSUE TITLE
Scrolling support

### ISSUE THREAD

**Issue by omercnet** [Yelp/elastalert#626]
Search results are cut at 10,000 hard limit by ES
it would be great to have scrolling support to allow processing large data sets

**Comment by Qmando** [comment]
There's some things you can try:
Reduce ``buffer_time`` to as small as possible. The default is 45 minutes.
Use ``use_count_query: true`` or ``use_terms_query: true`` unless you need the full contents of the documents.

**Comment by omercnet** [comment]
why not just add scroll support?

I have a simple patch here https://github.com/Yelp/elastalert/compare/master...omercnet:master but having trouble making all the tests work, mind taking a look?

it's complaining about recursion but I'm not sure if it's because pytest won't allow recursion at all or because the tests somehow end up recursing endlessly

**Comment by omercnet** [comment]
this is crucial in larger systems where you're indexing more than 10k documents/sec or where you need the full contents of the document

please review #628

**Comment by tanyewei** [comment]
mark
