### ISSUE TITLE
Is it possible to have an expression in change rule

### ISSUE THREAD

**Issue by jayeshGIT** [Yelp/elastalert#63]
Hi Quentin 

In the rule example  -   https://github.com/Yelp/elastalert/blob/master/example_rules/example_change.yaml

You watch for countryname to change. Is it possible to have an expression . I have a usecase, where I want to send an alert if the value has increased by 500  i.e at 10.00 AM I see 100 and then at 10:02 if I see a reading of 600 , then I need to throw an alert .

PS : Apologies if this is not the rite place to ask a question , I couldn't find any other forum .

**Comment by Qmando** [comment]
That specific use case can't be done with the change rule type, which only looks at equality. However, this could be done with a simple subclass of CompareRule. As a very basic example:

    class IncreaseRule(CompareRule):
        last_seen = 100
        def compare(self, event):
            if event.get('field', last_seen) > self.last_seen + 500:
                self.add_match(event)
            self.last_seen = event.get('field', self.last_seen)

see http://elastalert.readthedocs.org/en/latest/recipes/adding_rules.html for more specifics on how to implement this.
