### ISSUE TITLE
how to specify multiple index names?

### ISSUE THREAD

**Issue by wqhuang** [Yelp/elastalert#639]
such as:

index: "myindex1,myindex2"

or list

index:
"- myindex1"
"- myindex2"

I know "myindex*" will do the trick,but it will match many irrelevant indices.

**Comment by Qmando** [comment]
You should be able to just comma separate them

**Comment by wqhuang** [comment]
Actually, I want this type of index pattern,"data_2016-07-21,data_2016-07-20",that's today and yesterday.

**Comment by Qmando** [comment]
```
index: data_&Y-%m-%d
use_strftime_index: true
```
and it will just work.

**Comment by wqhuang** [comment]
It works,thanks!

**Comment by Zhang21** [comment]
Thanks:

```yaml
index: "index1,index2,..."
```
