### ISSUE TITLE
Error creating JIRA ticket: HTTP 400: "project is required"

### ISSUE THREAD

**Issue by vaibhavtupe** [Yelp/elastalert#641]
Even though I am setting the **jira_project** property in alert rule file, getting "Error creating JIRA ticket: HTTP 400: "project is required" "

Below is the content of jira alert rule file:

alert:
- "jira"

jira_server: https://jira.xyz.com/jira/
jira_project: Test Project
jira_issuetype: Spike
jira_account_file: /Users/elastalert/elastalert/example_rules/jira_acct.txt
jira_description: Automated Jira Ticket by ElastAlert Testing

**Comment by Qmando** [comment]
The JIRA api is notorious for bad error messages. ``jira_server`` should be set to the short version of the project name, whatever that is called (like jira.foo.com/browse/PROJECT). Maybe that's why you get this error message.

**Comment by vaibhavtupe** [comment]
If I am giving **"jira_server: http://jira.xyz.net/jira/browse/PROJECT"**
getting below error
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 14033: ordinal not in range(128)

If I am giving **"jira_server: http://jira.xyz.net/jira/"**
getting below error
Error creating JIRA ticket: HTTP 405: Method not allowed

**Comment by Qmando** [comment]
oops, I meant ``jira_project``. Sorry.

**Comment by vaibhavtupe** [comment]
Great, That worked. Thanks!
