### ISSUE TITLE
Include specific content in alert email body

### ISSUE THREAD

**Issue by dbluxo** [Yelp/elastalert#653]
Hello,

I am looking for a way to include the "number of query hits" and the "number of hits" in the email body [alert_text].

Can anyone help?

Thanks in advance!

**Comment by Qmando** [comment]
https://github.com/Yelp/elastalert/issues/637

**Comment by PMDubuc** [comment]
Could the code changes suggested in #637 be included as the default?  Thanks.

**Comment by sathishdsgithub** [comment]
@Qmando @PMDubuc @dulman 

How to include some content in the email body. I get the summary_table_fields in my email body. However, I would like to add some content about the triggered rule. Are there any options to do that?
