### ISSUE TITLE
Elastalert not alerting via email ?

### ISSUE THREAD

**Issue by stefansaye** [Yelp/elastalert#667]
Hi,
I am trying to utilize a simple rule using Elastalert, and it seems to not be functioning properly. My rule is:

    name: termrule
     type: Any
     index: logstash-*
    fields:
    - "ip"
    filter:
    - term:
     _type: "log"
    - term:
       agentip: 1.2.3.4
      alert:
     email:
    - "myemail@company.com "

     ##remote mailserver
    smtp_host:
    - "remote mailserver_ip"

My config.yaml

    es_host: 1.2.3.4
    es_port: 9200
    rules_folder: rules
    run_every:
    minutes: 1
    buffer_time:
     minutes: 15
    writeback_index: elastalert_status
    alert_time_limit:
    days: 2
    es_conn_timeout: 20

But when I run with the command
     #sudo python -m elastalert.elastalert --config ./config.yaml --rule ./rules/term_rule.yaml --es_debug_trace ./elastalert.log

 I just ran the Kibana query to verify that my filters which returned 5 hits but my elastalert.log is empty 
and I didn’t get any alert email,
If the rule is 'any' then any query hits should be alerted on, but as you can see it is not. Any ideas?

Any help would be much appreciated. Thanks

**Comment by Qmando** [comment]
If you add ``--verbose``, do you see "Sent email to myemail@company.com"?

If yes, it is successfully connecting to the SMTP server. Some SMTP servers will filter the messages because the default From is just "elastalert" without a domain, but you can add the option ``from_addr: elastalert@mycompany.com``.

**Comment by stefansaye** [comment]
I add --verbose as below 
    
    python -m elastalert.elastalert --config ./config.yaml --rule ./rules/test.yaml --debug --verbose

get the error as below,
INFO:elastalert:Note: In debug mode, alerts will be logged to console but NOT actually sent. To send them, use --verbose.
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/stefansaye/elastalert/elastalert/elastalert.py", line 1408, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/home/stefansaye/elastalert/elastalert/elastalert.py", line 1403, in main
    client = ElastAlerter(args)
  File "/home/stefansaye/elastalert/elastalert/elastalert.py", line 94, in __init__
    self.conf = load_rules(self.args)
  File "elastalert/config.py", line 400, in load_rules
    raise EAException('Error loading file %s: %s' % (rule_file, e))
elastalert.util.EAException: Error loading file ./rules/test.yaml: Invalid Rule: Example rule
[1.2.3.4'] is not of type 'string'

Failed validating 'type' in schema['properties']['smtp_host']:
    {'type': 'string'}

On instance['smtp_host']:
    ['1.2.3.4']


any idea ?

**Comment by Qmando** [comment]
smtp_host shouldn't be a list, just a string.
``smtp_host: "1.2.3.4"``

**Comment by stefansaye** [comment]
my rule ,

     name: Example rule
     type: frequency
      index: logstash-*
      num_events: 1
      timeframe:
       hours: 4
       filter:
          - query:
              query_string:
                  query: "message:logout"
          alert:
            - "email"
          email:
              - "recv@email"
                smtp_host: "1.2.3.4"

                from_addr: "my@email"

I got the error : ""yaml.parser.ParserError: expected '<document start>', but found '<block mapping start>'
  in "./rules/test.yaml", line 24, column 1

**Comment by Qmando** [comment]
```
email:
          - "recv@email"
            smtp_host: "1.2.3.4"

            from_addr: "my@email"
```
is not valid YAML. You want
```
filter:
  - query:
       query_string:
          query: "message:logout"
alert:
  - email
email: "recv@email"
smtp_host: "1.2.3.4"
from_addr: "my@email"
```
