### ISSUE TITLE
Notify multiple slack channels

### ISSUE THREAD

**Issue by 326TimesBetter** [Yelp/elastalert#678]
Your documentation for notifying multiple slack channels:
slack_webhook_url: The webhook URL that includes your auth data and the ID of the channel (room) you want to post to. Go to the Incoming Webhooks section in your Slack account https://XXXXX.slack.com/services/new/incoming-webhook , choose the channel, click ‘Add Incoming Webhooks Integration’ and copy the resulting URL. You can use a list of URLs to send to multiple channels.

What is the format of that list in the yml file??  (brackets, no brackets, quotes etc....) It'd be great to have a one-liner example in the docs!

**Comment by Qmando** [comment]
There two ways to do lists in yaml.
``slack_webhook_url: ["foo", "bar"]``
or 
```
slack_webhook_url:
 - "foo"
 - "bar"
```

**Comment by 326TimesBetter** [comment]
Oh cool, thanks!
