### ISSUE TITLE
Aggregation Queries

### ISSUE THREAD

**Issue by 326TimesBetter** [Yelp/elastalert#679]
If I want a query to run every three minutes, against the last 3 minutes, and return a SINGLE alert if there were > 0 hits in that query, is this the appropriate configuration??

    run_every:
      minutes: 3
    buffer_time:
      minutes: 3
    aggregation:
      minutes: 3

so at most we should receive one alert every three minutes, and if we are consistently seeing hits, at least once every three minutes.

The only part I was really uncertain about was the aggregation section. It states:
`Every time a match is found, ElastAlert will wait for the aggregation period, and send all of the matches that have occurred in that time for a particular rule together.`
Does that mean that if I see a hit 1 minute into the 3 minute interval, that it will stop sending that alert UNTIL it sees a 3 minute period with no hits?? Because that could mean we are blocked from alerts indefinitely if an error keeps showing up in our logs.

Thank you!

**Comment by Qmando** [comment]
With these settings, If you got an alert at 12:00, it would not send immediately, but get scheduled for 12:03. If another alert occurred at 12:02, it would also not send immediately, but get added onto the first alert. At 12:03, you would get both alerts at once (it basically just concatenates them together into one big alert). 

If you set ``realert`` to 3 minutes, then it would send the first alert immediately, and ignore everything else for the next 3 minutes. By default, it's set to 1 minute, to prevent a flood of alerts all at once. You can manually set it to 0 minutes to actually get every single alert.

**Comment by 326TimesBetter** [comment]
Thanks!
