### ISSUE TITLE
 u'[query_string] query does not support [qyery]' Error ?

### ISSUE THREAD

**Issue by stefansaye** [Yelp/elastalert#685]
Hello!
 I'm trying to use elastalert to get alerts from elasticsearch .
The elastalert installation went fine, but i didn't understand how to properly write filters, for example i'd like to match:
Eventstate=State.32.1.14.16.255.255.33.0.0.0.0:3
and don't not analyze query string , I'd like to match an exact sequence of words, 
and userid is 1.3.6.1.4
i wrote the following filter

    filter:
     - and:
        - term:
             userid: "1.3.6.1.4"
        - query:
             query_string:
                 qyery: "Eventstate:\"State.32.1.14.16.255.255.33.0.0.0.0\\:3\""

but I got the error as below.

    ERROR:root:Error running query: TransportError(400, {u'failed_shards': [{u'node':   u'vRX_Bv8YQwWGKUowfQo-ww', u'index': u'logstash-2016.06.14', u'reason': {u'index':  u'logstash-2016.06.14', u'reason': u'[query_string] query does not support [qyery]'

Anyone know what's happen !
Thanks for the support.
Regards

**Comment by Qmando** [comment]
You have a typo. ``query`` != ``qyery``

**Comment by stefansaye** [comment]
Qmando, 
ha ha, thanks for  your help !
