### ISSUE TITLE
Is it possible to change timestamp  to use local time?

### ISSUE THREAD

**Issue by stefansaye** [Yelp/elastalert#688]
Hello!
I'm trying to use elastalert to get alerts mail from elasticsearch .
I have set include fields that I want , 
In elastsearch  is showing UTC time, 
How to change timestamp before alert to convert UTC to local time?In alert mail the timestamp is showing user time. 

Thanks for the support.
Regards

**Comment by vikas8190** [comment]
U can write enhancements(using match_enhancements option) and customize the fields before the alert is sent. In the enhancement module u can read the field and convert the specific date field to any timezone.
The enhancement module you write should be placed in $ELASTALERT_HOME/elastalert_modules directory.
