### ISSUE TITLE
Conditional alerting

### ISSUE THREAD

**Issue by bennneuh** [Yelp/elastalert#689]
Hello,

I think it's not possible currently but it could be interesting to integrate conditional in alerts.

Explanation:

. I want to link rules
. If all or a specific number of rules match, i genere a specific alert and i don't play alert configured in each rules
. If just one or less than the trigger match, i play alert configured in the rule.

It's better with an example:

I monitor internet access and proxy cloud with 3 rules to check the webstate of 3 websites.

. If i loose 1 website i have one alert. OK no problem with the internet access it's just the website is down
. If i loose 3 websites, i have 3 parallel alerts but it's more a symptom of internet access is down, so i prefer to have a specific alert who say "big outage" with specific action like P1 ticket on service now.

I hope i'm clear....

If i'm wrong is it possible to explain how i can do this ?

Thanks by advance,

Benoît

**Comment by Qmando** [comment]
I think you could hack together an alert to do this. You have the 3 parallel alerts that all have ``alert: debug`` to make them not do anything. But they would still emit a log to ``elastalert_status`` index like ``{_type: elastalert, rule_name: webserver1_down, ...}`` to show they alerted.

Now you make another rule with ``type: cardinality`` and filter based on ``_type: elastalert AND rule_name in ["webserver1_down", "webserver2_down", etc]`` with ``cardinality_field: rule_name`` and ``max_cardinality: 2``. This alert would go off if at least 3 other alerts went off within the time period.

I haven't tested a setup like this, but I think it should work.

**Comment by bennneuh** [comment]
Thanks for the response!

I think i have forget in my explanation that i want also an alert if one check is down.

But it's a good idea to create debug alert and match the elastalert index! i think i will reuse this idea!

In my elastic i have values like:
webserver1_state: 0 or 1 for active or down
webserver2_state: 0 or 1 for active or down
webserver3_state: 0 or 1 for active or down

Maybe i can create a filter to match for example for webserver1:

If webserver1_state : 0
And webserver2_state or webserver3_state : 1
then i send the alert

And i create a new alert to match when webserver1_state, webserver2_state and webserver3_state are down
