### ISSUE TITLE
When run elastalert ,it always fetch documents in one week.

### ISSUE THREAD

**Issue by jiapengjun** [Yelp/elastalert#691]
Today is 2016-08-31

$ elastalert --debug --verbose
INFO:elastalert:Note: In debug mode, alerts will be logged to console but NOT actually sent. To send them, use --verbose.
INFO:elastalert:Starting up
INFO:elastalert:Queried rule Status_Code_Check_Daily from 2016-08-25 16:25 CST to 2016-08-25 16:40 CST: 30 hits
INFO:elastalert:Queried rule Status_Code_Check_Daily from 2016-08-25 16:40 CST to 2016-08-25 16:55 CST: 30 hits
INFO:elastalert:Queried rule Status_Code_Check_Daily from 2016-08-25 16:55 CST to 2016-08-25 17:10 CST: 30 hits

How can I let elastalert just fetch recent two days documents.

config.yaml:

run_every:
  minutes: 1

buffer_time:
  minutes: 15

alert_time_limit:
  days: 2

**Comment by Qmando** [comment]
http://elastalert.readthedocs.io/en/latest/elastalert.html?highlight=old_query_limit

Add something like
```
old_query_limit:
  days: 1
```

This is a global option, not per rule.

The alternatives would be to delete elastalert_status documents with rule_name=Status_Code_Check_Daily. Or, change the name of the rule.
