### ISSUE TITLE
How to passing parameters to command alert ?

### ISSUE THREAD

**Issue by stefansaye** [Yelp/elastalert#699]
I want  to use command alert , but how can I passing parameters to command alert ?

I try to set arg1 , arg2, @timestamp when alert will pass these arguments to action.sh as below,

    alert:
      - command
    command: 
      - "/opt/elastalert/action.sh arg1 arg2 @timestamp"

But it’s got error , 
If i'm wrong is it possible to explain how i can do this ?

Thanks by advance,

**Comment by Qmando** [comment]
http://elastalert.readthedocs.io/en/latest/ruletypes.html#command

**Comment by stefansaye** [comment]
hi Qmando,

I try to using command alert as below,

    alert:
    -command
    command: ["/opt/alert/action.sh", "%(timestamp)s","%(user)s","%(ip)s","%(id)s","%(count)s"]


but got the error,
 
ERROR:root:Error while running alert command: Error while running command /opt/alert/action.sh 2016-09-07 11:14:16.819 guest 10.10.2.20 1/0/3 5: [Errno 13] Permission denied

If i'm wrong is it possible to explain how i can do this ?

Thanks by advance,
