### ISSUE TITLE
[Solved]

### ISSUE THREAD

**Issue by stefansaye** [Yelp/elastalert#700]
Hi all,
I try to using command alert as below,

    alert:
    -command
    command: ["/opt/alert/action.sh", "%(timestamp)s","%(user)s","%(ip)s","%(id)s","%(count)s"]

but got the error as follows,

ERROR:root:Error while running alert command: Error while running command /opt/alert/action.sh 2016-09-07 11:14:16.819 guest 10.10.2.20 1/0/3 5: [Errno 8] Exec format error

If i'm wrong is it possible to explain how i can do this ?

Thanks by advance,

**Comment by xiaoxiaowenll** [comment]
1. How to solve it

**Comment by Qmando** [comment]
Probably missing https://en.wikipedia.org/wiki/Shebang_(Unix)
