### ISSUE TITLE
Add a custom action alerter

### ISSUE THREAD

**Issue by vquemener** [Yelp/elastalert#71]
It would be useful to have a custom action alerter which would send the data to a configurable program or script. This would make for easier prototyping, by allowing people not to write custom python alerters.

**Comment by Qmando** [comment]
https://github.com/Yelp/elastalert/pull/72

**Comment by ivanlei** [comment]
Thanks for the great suggestion @vquemener. This has been implemented.

**Comment by vquemener** [comment]
Thank you!
