### ISSUE TITLE
Flatline rule: timeframe and run every

### ISSUE THREAD

**Issue by vikas8190** [Yelp/elastalert#716]
Does the "timeframe" for flatline rule need to be lesser than the run every period for elastalert. I have a flatline rule with timeframe: 10 minutes but with run every 2 minutes. I was expecting elastalert to lookback last 10 minutes at any point it runs. However this seems to be generating invalid alerts. Do i have to run another instance of elastalert with run every greater than 10 minutes to get this functionality working?

**Comment by Qmando** [comment]
Do not run another instance. Timeframe and run_every are independent, like I said.

You can check to see if the query got any hits where you expect it should have. Go into Kibana and query for "_type: elastlaert_status AND rule_name: <your rule name>" with the time range set to the 10 minute interval where there was an alert. You will probably see 5 documents with num_hits: 0. If there are currently documents that SHOULD have matched, the most likely scenario is that they were indexed too slow and elastalert missed them.

There are two solutions to prevent this from happening. You can add ``query_delay`` into your rule, to delay it a few minutes to prevent that from happening. Or, you can remove ``use_count_query`` (if you have it) and then those will be caught by the default buffer_time of 45 minutes.

**Comment by vikas8190** [comment]
Thanks. I got the issue now. It was because of delay in loading into elasticsearch. I have added query_delay of 2 minutes to the rule now.
