### ISSUE TITLE
Multiple alerts

### ISSUE THREAD

**Issue by nickedes** [Yelp/elastalert#720]
How to send multiple alerts using a single rule in elastalert ?

**Comment by Qmando** [comment]
```
alert:
 - email
 - slack
 - whatever
```

**Comment by nickedes** [comment]
Umm...that's fine but what if I need to apply `frequency` checks on two different fields in the same rule and send different alerts for the different frequency checks. Is this possible in a single rule?

**Comment by Qmando** [comment]
You can use ``query_key`` on a specific field to have the frequency checks run separately (num_events will be counted independently for each value of the ``query_key`` field). If you want two separate num_events for two separate fields, you need two different rules.

**Comment by bean5** [comment]
I was able to do multiple alerts just fine. I did hipchat + pagerduty. I just had to make sure I had all the fields required for each alert mechanism. @nickedes can we close this?

**Comment by nickedes** [comment]
@Qmando is there no way I can have separate num_events for different fields in the same rule :disappointed: ?

Because i have to create alerts for 50 different values of a field, and fire alert for each of them when threshold value is crossed.

**Comment by nickedes** [comment]
Anyways I have fulfilled by requirement by hitting on the elastic index using curl in my script.
Thanks.
