### ISSUE TITLE
Term Lost

### ISSUE THREAD

**Issue by bennneuh** [Yelp/elastalert#725]
Hi,

I try to create a rule to have an alert when i stop to receive logs from a host.
(Logs are sent every minutes.)

The only working solution i have found is a flatline rule and if i have for example less events for a specific query_key than my threshold i send an alert. It's works but in my alert i want to use terms values and i have a "Missing Value" in the message alert.

Example:
Threshold : 2
Timeframe: 4 minutes
Query_key hostname

So with this config, If during 3 minutes i don't receive logs from a specific hostname i generate the alert.
But like i said, i have the "missing value" in the alert.

I imagine it's linked the buffer or something like that because elastalert don't find the value in the current cache. So i have tried to extend my buffer to 5minutes without success. (Elastalert run every 1 minutes)

If you have an idea or a solution it will be really nice!

Thanks

Benoît

**Comment by bennneuh** [comment]
Or maybe it's possible to use the reverse of "new_term" ?

**Comment by Qmando** [comment]
In the alert text/subject use "key" instead of hostname.
flatline plus query_key is basically the reverse of new term

**Comment by bennneuh** [comment]
It works perfectly! thank you!!

I have not seen the possibility to use the 'key' value instead of the query_key.
