### ISSUE TITLE
frequency rule that uses sum total of a numeric field value instead of event counts?

### ISSUE THREAD

**Issue by PMDubuc** [Yelp/elastalert#727]
I'm trying to implement a rule similar to frequency that adds up the values of a particular number field in each event that matches a query and alerts on the value of that sum within a timeframe instead of the number of events.  I'm trying to read the frequency rule source and the documentation example on adding a new rule type but my python is a bit rusty and I'm not sure where to start.

Can anyone give me some pointers or an example?
Thanks.

**Comment by PMDubuc** [comment]
I was able to work up a modified version of the frequency rule source to do what I need.

**Comment by MrGlobi** [comment]
Hi,
Im trying the same, can you share your configuration?

**Comment by ruget** [comment]
+1, I'm looking for the same functionality
