### ISSUE TITLE
Telegram Alerts not working (solved)

### ISSUE THREAD

**Issue by Mormaii** [Yelp/elastalert#728]
I have my elastalert set up like this:

```
alert:
- telegram

telegram_bot_token: $id
telegram_room_id: "@integer"
telegram_proxy: $proxy
```

I've tried using my "@User" or "@chat_id" or even without "@" and in every case the error I get is:

`ERROR:root:Error while running alert telegram: Error posting to Telegram: 400 Client Error: Bad Request`

edit: Fixed it myself please close

**Comment by mbrostami** [comment]
How did you fix the problem?
