### ISSUE TITLE
How to drop alerts that custom conditions are met?

### ISSUE THREAD

**Issue by stefansaye** [Yelp/elastalert#730]
Hi all,
 I have add enhancement to process alerts when match ,  
part code in my class MyEnhancement(BaseEnhancement)  as below,

    def process(self, match):
       if 'log' in match:
           if match['user']  is 'admin' :   
                ##how to drop the alert  ???????

 how to drop specific alerts  ?

Can anyone give me some pointers or an example,please?
Thanks.

**Comment by Qmando** [comment]
from elastalert.enhancements import DropMatchException
...
raise DropMatchException()

**Comment by stefansaye** [comment]
Hi Qmando,
as you said ,but when I run elastalert got the error msg as below,

    ERROR:root:Traceback (most recent call last):
      File "/elastalert/elastalert/elastalert.py", line 913, in alert
        return self.send_alert(matches, rule, alert_time=alert_time)
      File "/elastalert/elastalert/elastalert.py", line 962, in send_alert
        enhancement.process(match)
      File "/elastalert/elastalert_modules/linkupdownEnhancement_test.py", line 77, in process
        raise DropMatchException()
    DropMatchException

    ERROR:root:Uncaught exception running rule Test rule:
    INFO:elasticsearch.trace:curl -XPOST 'http://localhost:9200/elastalert_status/elastalert_error?    pretty&op_type=create' -d '{
      "@timestamp": "2016-09-27T14:57:04.480158Z",
      "data": {
        "rule": "Test rule"
      },
      "message": "Uncaught exception running rule Test rule: ",
      "traceback": [
        "Traceback (most recent call last):",
        "  File \"/elastalert/elastalert/elastalert.py\", line 913, in alert",
        "    return self.send_alert(matches, rule, alert_time=alert_time)",
        "  File \"/elastalert/elastalert/elastalert.py\", line 962, in send_alert",
        "    enhancement.process(match)",
        "  File \"/elastalert/elastalert_modules/linkupdownEnhancement_test.py\", line 77, in process",
         "    raise DropMatchException()",
        "DropMatchException"
      ]
    }'
    INFO:elastalert:Rule Test rule disabled

**Comment by Qmando** [comment]
What version are you using?
Can you maybe post linkupdownEnhancement_test.py?

**Comment by stefansaye** [comment]
Hi Qmando,

how to know elastalert version ?
my MyEnhancement_test as below ,


			from elastalert.enhancements import BaseEnhancement
			from elastalert.enhancements import DropMatchException
			from datetime import datetime
			from dateutil import tz
			import dateutil.parser

			class MyEnhancement(BaseEnhancement):
				global from_zone
				global to_zone
				from_zone = tz.gettz('UTC')
				to_zone = tz.gettz('America/New_York')

			   # METHOD 2: Auto-detect zones:
				from_zone = tz.tzutc()
				to_zone = tz.tzlocal()

				def process(self, match):
					if '@timestamp' in match:
						  .......
					   if  id  == "admin":
						   #connect db and do something

					   else:
						  print "drop alerts "
						  droplogs = open("droplogs.txt","a")
						  droplogs.write('--------------------------------------\n')
						  droplogs.write(str(match['timestamp']))
						  droplogs.write('\n')
						  raise DropMatchException()



			class BaseEnhancement(object):
				""" Enhancements take a match dictionary object and modify it in some way to
				enhance an alert. These are specified in each rule under the match_enhancements option.
				Generally, the key value pairs in the match module will be contained in the alert body. """

				def __init__(self, rule):
					self.rule = rule

				def process(self, match):
					""" Modify the contents of match, a dictionary, in some way """
					raise NotImplementedError()


			class DropMatchException(Exception):
				""" ElastAlert will drop a match if this exception type is raised by an enhancement """
				pass

**Comment by Qmando** [comment]
See #738
