### ISSUE TITLE
Getting duplicate alerts for same timeframe

### ISSUE THREAD

**Issue by aniroy1986** [Yelp/elastalert#731]
I am using frequency rule. And I have set up event for 4 occurrences in 5 minutes timeframe, When the condition becomes true, elastalert will keep sending email for the same time frame like 11:57 to 12:02 . It will never go to next timeframe. I have tried with and without elastalert_status index, but no luck. Looking for someone to help me out. Here is my config.yaml:
run_every:
  minutes: 1
buffer_time:
  minutes: 15
es_host: localhost
es_port: 9200
writeback_index: elastalert_status
alert_time_limit:
  days: 2

Here is my example_frequency rule:
es_host: localhost
es_port: 9200
name: Too Many 500 Errors In Last 5 Minutes
type: frequency
index: logstash-*
num_events: 4
timeframe:
  minutes: 5

**Comment by Qmando** [comment]
In the rule, you can set
```
realert:
  minutes: 5
```
which will silence alerts for 5 minutes.

You will get a lot of ``Ignoring match for silenced rule ...`` in the logs, but that should achieve what you want.

**Comment by aniroy1986** [comment]
thanks....it worked

**Comment by aniroy1986** [comment]
not working even after adding realert...once elastalert start sending mails, it will get stuck to same time frame and then keep sending duplicate mails

**Comment by Qmando** [comment]
Can you post the logs? The only reason I can think for this happening is if there were SO many documents  in the timeframe that it took more than 5 minutes to even download them all.

**Comment by aniroy1986** [comment]
INFO:elastalert:Ran Too Many 500 Errors In Last 5 Minutes from 2016-10-04 18:57 IST to 2016-10-04 19:12 IST: 10 query hits, 0 matches, 0 alerts sent
INFO:elastalert:Sleeping for 59 seconds
INFO:elastalert:Queried rule Too Many 500 Errors In Last 5 Minutes from 2016-10-04 18:58 IST to 2016-10-04 19:13 IST: 10 / 10 hits
INFO:elastalert:Ran Too Many 500 Errors In Last 5 Minutes from 2016-10-04 18:58 IST to 2016-10-04 19:13 IST: 10 query hits, 0 matches, 0 alerts sent
INFO:elastalert:Sleeping for 59 seconds
INFO:elastalert:Queried rule Too Many 500 Errors In Last 5 Minutes from 2016-10-04 18:59 IST to 2016-10-04 19:14 IST: 10 / 10 hits
INFO:elastalert:Ran Too Many 500 Errors In Last 5 Minutes from 2016-10-04 18:59 IST to 2016-10-04 19:14 IST: 10 query hits, 0 matches, 0 alerts sent
INFO:elastalert:Sleeping for 59 seconds
INFO:elastalert:Queried rule Too Many 500 Errors In Last 5 Minutes from 2016-10-04 19:00 IST to 2016-10-04 19:15 IST: 9 / 9 hits
INFO:elastalert:Ran Too Many 500 Errors In Last 5 Minutes from 2016-10-04 19:00 IST to 2016-10-04 19:15 IST: 9 query hits, 0 matches, 0 alerts sent
INFO:elastalert:Sleeping for 59 seconds
INFO:elastalert:Queried rule Too Many 500 Errors In Last 5 Minutes from 2016-10-04 19:01 IST to 2016-10-04 19:16 IST: 11 / 11 hits
INFO:elastalert:Ran Too Many 500 Errors In Last 5 Minutes from 2016-10-04 19:01 IST to 2016-10-04 19:16 IST: 11 query hits, 0 matches, 0 alerts sent
INFO:elastalert:Sleeping for 59 seconds
INFO:elastalert:Queried rule Too Many 500 Errors In Last 5 Minutes from 2016-10-04 19:02 IST to 2016-10-04 19:17 IST: 13 / 13 hits
INFO:elastalert:Ran Too Many 500 Errors In Last 5 Minutes from 2016-10-04 19:02 IST to 2016-10-04 19:17 IST: 13 query hits, 0 matches, 0 alerts sent
INFO:elastalert:Sleeping for 59 seconds
INFO:elastalert:Queried rule Too Many 500 Errors In Last 5 Minutes from 2016-10-04 19:03 IST to 2016-10-04 19:18 IST: 13 / 13 hits
INFO:elastalert:Ran Too Many 500 Errors In Last 5 Minutes from 2016-10-04 19:03 IST to 2016-10-04 19:18 IST: 13 query hits, 0 matches, 0 alerts sent
INFO:elastalert:Sleeping for 59 seconds
INFO:elastalert:Queried rule Too Many 500 Errors In Last 5 Minutes from 2016-10-04 19:04 IST to 2016-10-04 19:19 IST: 173 / 173 hits
INFO:elastalert:Sent email to ['ani@xxxxxx.in', 'engg@xxxxxx.in']
INFO:elastalert:Sent email to ['ani@xxxxxx.in', 'engg@xxxxxx.in']
INFO:elastalert:Sent email to ['ani@xxxxxx.in', 'engg@xxxxxx.in']
INFO:elastalert:Sent email to ['ani@xxxxxx.in', 'engg@xxxxxx.in']
INFO:elastalert:Sent email to ['ani@xxxxxx.in', 'engg@xxxxxx.in']
INFO:elastalert:Sent email to ['ani@xxxxxx.in', 'engg@xxxxxx.in']
INFO:elastalert:Sent email to ['ani@xxxxxx.in', 'engg@xxxxxx.in']
INFO:elastalert:Sent email to ['ani@xxxxxx.in', 'engg@xxxxxx.in']
INFO:elastalert:Ran Too Many 500 Errors In Last 5 Minutes from 2016-10-04 19:04 IST to 2016-10-04 19:19 IST: 173 query hits, 8 matches, 8 alerts sent
WARNING:root:Querying from 2016-10-04 19:04 IST to 2016-10-04 13:49:09.687331+00:00 took longer than 0:01:00!
INFO:elastalert:Queried rule Too Many 500 Errors In Last 5 Minutes from 2016-10-04 19:19 IST to 2016-10-04 19:34 IST: 179 / 179 hits
INFO:elastalert:Queried rule Too Many 500 Errors In Last 5 Minutes from 2016-10-04 19:34 IST to 2016-10-04 19:36 IST: 181 / 2 hits
INFO:elastalert:Sent email to ['ani@xxxxxx.in', 'engg@xxxxxx.in']
INFO:elastalert:Sent email to ['ani@xxxxxx.in', 'engg@xxxxxx.in']
INFO:elastalert:Sent email to ['ani@xxxxxx.in', 'engg@xxxxxx.in']
INFO:elastalert:Sent email to ['ani@xxxxxx.in', 'engg@xxxxxx.in']
INFO:elastalert:Sent email to ['ani@xxxxxx.in', 'engg@xxxxxx.in']

**Comment by Qmando** [comment]
Part of this problem will be solved by #751, a single query should only generate a single alert.

It still seems very weird to me that adding ``realert`` wouldn't prevent this. Can you paste your entire rule yaml?

**Comment by aniroy1986** [comment]
config.yaml:

rules_folder: example_rules
run_every:
  minutes: 1
buffer_time:
  minutes: 15
es_host: localhost
es_port: 9200
writeback_index: elastalert_status
alert_time_limit:
  days: 2
realert:
  minutes: 5


example_frequency.yaml:

es_host: localhost
es_port: 9200
name: Too Many 500 Errors In Last 5 Minutes
type: frequency
index: logstash-*
num_events: 20
timeframe:
  minutes: 5
filter:
- query:
    query_string:
      query: "response:500"
alert:
- "email"
email:
- "ani@xxxxxx.in"
- "engg@xxxxxx.in"
smtp_host: "smtp.gmail.com"
smtp_port: 465
smtp_ssl: true
smtp_auth_file: '/tmp/software/elastalert/smtp_auth_file.yaml'
alert_text: "Check logs!"

**Comment by Qmando** [comment]
Realert only works in the rule, not in config.yaml

**Comment by aniroy1986** [comment]
got it...thanks
