### ISSUE TITLE
what's mean "query :!_exists_:aggregate_id AND alert_sent:false" ?

### ISSUE THREAD

**Issue by stefansaye** [Yelp/elastalert#733]
hi all,
when I am running my elastalert  as below,

       #python -m elastalert.elastalert --config ./config.yaml --rule ./rules/test.yaml --verbose --es_debug_trace alert.log

it's only query when start then sleep ,es_debug_trace results as below ,

    INFO:elasticsearch.trace:curl -XGET 'http://localhost:9200/elastalert_status/elastalert/_search?    pretty&size=1000' -d '{
      "filter": {
        "range": {
          "alert_time": {
            "from": "2016-09-27T03:33:01.469837Z",
            "to": "2016-09-27T03:33:01.469890Z"
          }
        }
      },
      "query": {
        "query_string": {
          "query": "!_exists_:aggregate_id AND alert_sent:false"
        }
      },
      "sort": {
        "alert_time": {
          "order": "asc"
        }
      }
    }'
    INFO:elastalert:Sleeping for 59 seconds
    INFO:elasticsearch.trace:curl -XGET 'http://localhost:9200/elastalert_status/elastalert/_search?  pretty&size=1000' -d '{
      "filter": {
        "range": {
          "alert_time": {
            "from": "2016-09-27T03:02:04.671782Z",
            "to": "2016-09-27T03:02:04.671830Z"
          }
        }
      },
      "query": {
        "query_string": {
          "query": "!_exists_:aggregate_id AND alert_sent:false"
        }
      },
      "sort": {
        "alert_time": {
          "order": "asc"
        }
      }
    }'
    INFO:elastalert:Sleeping for 59 seconds

my config.yaml

    rules_folder: rules
    run_every:
      minutes: 1
    buffer_time:
      minutes: 5
    old_query_limit:
      days: 0
    es_host: X.X.X.X
    es_port: 9200
    writeback_index: elastalert_status
    alert_time_limit:
      days: 0
    es_conn_timeout: 20

then always sleeping ....

If you have an idea or a solution it will be really nice!

Thanks for the support.

**Comment by Qmando** [comment]
You can ignore that query. It's to find pending alerts if you have aggregation set in a rule.

What's the output when you FIRST start elastalert? Does it say "Starting up" then go straight to "Sleeping for.."? It looks like there no rules loading, like if it can't find rules/test.yaml.

**Comment by stefansaye** [comment]
Hi Qmando,
when first start ,it's say  "  INFO:elastalert:Starting up
    INFO:elastalert:Found expired previous run for Test rule at 2016-09-28 00:13:19.202316+00:00"


but then sleeping and Sleeping

    # sudo python -m elastalert.elastalert --config ./config.yaml --rule ./rules/test.yaml -- verbose

    /usr/local/lib/python2.7/dist-packages/MySQL_python-1.2.2-py2.7-linux-x86_64.egg/MySQLdb/__init__.py:34: DeprecationWarning: the sets module is deprecated
    INFO:elastalert:Starting up
    INFO:elastalert:Found expired previous run for Test rule at 2016-09-28 00:13:19.202316+00:00
    INFO:elastalert:Queried rule Test rule from 2016-09-28 08:08 CST to 2016-09-28 08:13 CST: 2 hits
    drop alerts
    ERROR:root:Traceback (most recent call last):
      File "elastalert/elastalert/elastalert.py", line 913, in alert
    return self.send_alert(matches, rule, alert_time=alert_time)
      File "/elastalert/elastalert/elastalert.py", line 962, in send_alert
    enhancement.process(match)
      File "/elastalert/elastalert_modules/MyEnhancement_test.py", line 77, in process
    raise DropMatchException()
    DropMatchException

    ERROR:root:Uncaught exception running rule Test rule:
    INFO:elastalert:Rule Test rule disabled
    ERROR:root:Traceback (most recent call last):
      File "/elastalert/elastalert/elastalert.py", line 913, in alert
        return self.send_alert(matches, rule, alert_time=alert_time)
      File "/elastalert/elastalert/elastalert.py", line 962, in send_alert
        enhancement.process(match)
      File "/elastalert/elastalert_modules/MyEnhancement_test.py", line 77, in process
        raise DropMatchException()
    DropMatchException

    ERROR:root:Uncaught exception running rule Test rule:
    INFO:elastalert:Rule Test rule disabled
    INFO:elastalert:Ran Test rule from 2016-09-28 08:08 CST to 2016-09-28 08:13 CST: 2 query hits, 2    matches, 0 alerts sent
    INFO:elastalert:Sleeping for 59 seconds
    INFO:elastalert:Sleeping for 59 seconds
    INFO:elastalert:Sleeping for 59 seconds
    INFO:elastalert:Sleeping for 59 seconds
    INFO:elastalert:Sleeping for 59 seconds
    INFO:elastalert:Sleeping for 59 seconds
    INFO:elastalert:Sleeping for 59 seconds
    INFO:elastalert:Sleeping for 59 seconds



If you have an idea or a solution it will be really nice!
Please help me out in this.
Thanks for the support.
