### ISSUE TITLE
Still alert when raise DropMatchException ?

### ISSUE THREAD

**Issue by stefansaye** [Yelp/elastalert#738]
Hi all,
I have raise DropMatchException in my enhancement to drop matches if custom conditions are met,but why still get alert  that have raise DropMatchException ?

my MyEnhancement_test as below ,

			from elastalert.enhancements import BaseEnhancement
			from elastalert.enhancements import DropMatchException
			from datetime import datetime
			from dateutil import tz
			import dateutil.parser

			class MyEnhancement(BaseEnhancement):
				global from_zone
				global to_zone
				from_zone = tz.gettz('UTC')
				to_zone = tz.gettz('America/New_York')

			   # METHOD 2: Auto-detect zones:
				from_zone = tz.tzutc()
				to_zone = tz.tzlocal()

				def process(self, match):
					if '@timestamp' in match:
						  .......
					   if  id  == "admin":
						   #connect db and do something

					   else:
						  print "drop alerts "
						  droplogs = open("droplogs.txt","a")
						  droplogs.write('--------------------------------------\n')
						  droplogs.write(str(match['timestamp']))
						  droplogs.write('\n')
						  raise DropMatchException()

			class BaseEnhancement(object):
				""" Enhancements take a match dictionary object and modify it in some way to
				enhance an alert. These are specified in each rule under the match_enhancements option.
				Generally, the key value pairs in the match module will be contained in the alert body. """

				def __init__(self, rule):
					self.rule = rule

				def process(self, match):
					""" Modify the contents of match, a dictionary, in some way """
					raise NotImplementedError()

			class DropMatchException(Exception):
				""" ElastAlert will drop a match if this exception type is raised by an enhancement """
				pass

my config.yaml

    rules_folder: rules
    run_every:
      minutes: 1
    buffer_time:
      minutes: 5
    old_query_limit:
      days: 0
    es_host: X.X.X.X
    es_port: 9200
    writeback_index: elastalert_status
    alert_time_limit:
      days: 0
    es_conn_timeout: 20

my rule,

     name: Test rule
     type: any
     index: logstash-*
     realert:
        minutes: 0
     run_enhancements_first: true

     match_enhancements:
      - "elastalert_modules.myEnhancement_test.MyEnhancement"

     alert:
     - "command"
     command: ["/code/sendmail.sh","%(user)s","%(timestamp)s","%(prior)s"]

If you have an idea or a solution it will be really nice!

Thanks for the support.

**Comment by Qmando** [comment]
Did you copy enhancements.py into your own file?? Don't do that!

**Comment by stefansaye** [comment]
Hi qmando,
I am copy elastalert_modules/myenhancement.py and modify it .
so I don't have to add it as below in my enhancement 
    
    from elastalert.enhancements import DropMatchException

Am I right ? 
If you have an idea or a solution it will be really nice!

Thanks for the support.
