### ISSUE TITLE
Allow use of alert_subject in PagerDuty

### ISSUE THREAD

**Issue by joey-bates-sp** [Yelp/elastalert#761]
Instead of hard coding the description for PD to the rule name, could we consider using alert_subject?

https://github.com/Yelp/elastalert/blob/57a3d352b8d03980a28ed522e6774e34b5148eba/elastalert/alerts.py#L896

**Comment by muz** [comment]
We've had a similar issue come up with our deployment of ElastAlert -> PagerDuty; so I've filed a PR to allow for the use of `alert_subject`; whilst defaulting back to the current behaviour of using the rule name in lieu of the former being set.
