### ISSUE TITLE
Dots in field names passed to top_count_keys

### ISSUE THREAD

**Issue by penekk** [Yelp/elastalert#762]
This is rather a suggestion/enhancement, than a true bug imo, but still worth fixing/informing the user.

Currently and by default, not having:
`-Dmapper.allow_dots_in_name=true`
defined in ES_JAVA_OPTS, results in mapper_parsing_exception when a field name passed to elasticsearch contains a dot.

ES wants to treat these dotted fields as nested objects, rather than a final value.

In case of elastalert filters, partial mitigation is to remove dots from your es field names and values, replacing them with '_' for example and use raw_count_keys: false, but with that setting (raw_count_keys) being true by default, the values in top_count_keys, while receiving '.raw' suffix, also become field names in elastalert report sent to elastic, which then leads to these exceptions.

**Comment by matthillary** [comment]
I am seeing this same error in my case as well. The error looks as follows:

```
WARNING:elasticsearch:POST http://localhost:9200/elastalert_status/elastalert [status:400 request:0.005s]
ERROR:root:Error writing alert info to Elasticsearch: TransportError(400, u'mapper_parsing_exception', u'failed to parse [match_body.id]')
Traceback (most recent call last):
  File "/opt/elastalert/elastalert/elastalert.py", line 1041, in writeback
    doc_type=doc_type, body=body)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/__init__.py", line 279, in index
    _make_path(index, doc_type, id), params=params, body=body)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/transport.py", line 327, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_requests.py", line 84, in perform_request
    self._raise_error(response.status_code, raw_data)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/base.py", line 113, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
RequestError: TransportError(400, u'mapper_parsing_exception', u'failed to parse [match_body.id]')
```

👍 to the suggestion to replace `.` with `_` to remove this problem as suggested by @penekk 

@Qmando -- your thoughts?

**Comment by daniilyar** [comment]
matthillary, this is fixed in https://github.com/Yelp/elastalert/issues/663

**Comment by daniilyar** [comment]
Somebody from the elastalert team - please close this ticket )
@penekk , @Qmando

**Comment by daniilyar** [comment]
Somebody from the elastalert team - please close this ticket as it is fixed in scope of https://github.com/Yelp/elastalert/issues/663

@penekk , @Qmando

**Comment by marczacher** [comment]
Replacing `.` with `_` can be configured by adding `replace_dots_in_field_names: true` to config.yaml
