### ISSUE TITLE
Conflicting field mappings using Elasticsearch migration plugin

### ISSUE THREAD

**Issue by erikanderson** [Yelp/elastalert#781]
```
Conflicting field mappings
Mapping for field elastalert:rule_name conflicts with: elastalert_status:rule_name. Check parameter: index
Mapping for field elastalert:rule_name conflicts with: silence:rule_name. Check parameter: index
```

Using the 1.x to 2.x migration plugin https://github.com/elastic/elasticsearch-migration

**Comment by Qmando** [comment]
They should all be not_analyzed strings. https://github.com/Yelp/elastalert/blob/master/elastalert/create_index.py#L91 and subsequent lines.

Does your index have a dynamically created map for this field? The create-index script has had problems of timing out and not applying all mapping before, which might result in this.

**Comment by erikanderson** [comment]
Thank you for the info, we are relying on a template to create our mappings so I think we will have to adjust that to accomodate the field names in elastalert
