### ISSUE TITLE
elastalert doesn't get hits against ES 2.4.1

### ISSUE THREAD

**Issue by Thermi** [Yelp/elastalert#786]
I'm trying to use elastalert 0.1.2 to run rules against an ES 2.4.1 cluster.
However, with the rule, there are no matches after the first query. The first query that elastalert does,
*returns several thousand matches*, *but the subsequent queries* that elastalert uses to figure out if there is a match in a certain time span *do not*.

The follwing items are attached:
*elastalert rule [rule-cpu-50.yml.zip](https://github.com/Yelp/elastalert/files/562667/rule-cpu-50.yml.zip)
*output of elastalert-test-rule [elastalert-test-rule-output.txt](https://github.com/Yelp/elastalert/files/562682/elastalert-test-rule-output.txt)
*pcap showing communication between elastalert and the cluster [elastalert-2016-10-31-5.pcap.zip](https://github.com/Yelp/elastalert/files/562708/elastalert-2016-10-31-5.pcap.zip)

Example data that should be found by the rule:

It should be noted that the CpuMetricsTimestamp is actually a unix timestamp and is only printed in kibana in this fornat.
```
{
  "_index": "heapster-2016.10.31",
  "_type": "cpu",
  "_id": "f822a288-9fa1-11e6-9941-2aa42b43b130",
  "_score": null,
  "_source": {
    "CpuMetricsTimestamp": "2016-10-31T19:41:00Z",
    "Metrics": {
      "cpu/limit": {
        "value": 110
      },
      "cpu/node_allocatable": {
        "value": 1000
      },
      "cpu/node_capacity": {
        "value": 1000
      },
      "cpu/node_reservation": {
        "value": 0.21
      },
      "cpu/node_utilization": {
        "value": 0.087
      },
      "cpu/request": {
        "value": 210
      },
      "cpu/usage": {
        "value": 245980904650178
      },
      "cpu/usage_rate": {
        "value": 87
      }
    },
    "MetricsTags": {
      "host_id": "i-df832054",
      "hostname": "ip-10-0-0-116.eu-west-1.compute.internal",
      "labels": "beta.kubernetes.io/arch:amd64,beta.kubernetes.io/instance-type:m3.medium,beta.kubernetes.io/os:linux,failure-domain.beta.kubernetes.io/region:eu-west-1,failure-domain.beta.kubernetes.io/zone:eu-west-1a,kubernetes.io/hostname:ip-10-0-0-116.eu-west-1.compute.internal",
      "nodename": "ip-10-0-0-116.eu-west-1.compute.internal",
      "type": "node"
    }
  },
  "fields": {
    "node_usage_percent": [
      0.087
    ],
    "CpuMetricsTimestamp": [
      1477942860000
    ],
    "pod_limit_usage_percent": [
      0.7909090909090909
    ],
    "pod_request_usage_percent": [
      8.537248055846112e-13
    ]
  },
  "highlight": {
    "MetricsTags.type": [
      "@kibana-highlighted-field@node@/kibana-highlighted-field@"
    ]
  },
  "sort": [
    1477942860000
  ]
}
```

**Comment by Qmando** [comment]
I have not seen this behavior before. It could be something broken with regards to ES 2.4.1 support.

Which version of elasticsearch-python do you have?
``pip freeze | grep elasticsearch``

It should be between 2.0.0 and 3.0.0, though, requirements.txt lists a 1.X version.

The first query DID return a result but the subsequent ones did not. The only different should be the use of a scroll. I'll look into this.

**Comment by Thermi** [comment]
Thank you for getting this so quickly.

```
$ pip freeze | grep elasticsearch
You are using pip version 7.1.0, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
elasticsearch==2.4.0
```

**Comment by Qmando** [comment]
Can you try running it without using ``elastalert-test-rule``?

``python -m elastalert.elastalert --debug --start 2016-10-30 --es_debug_trace tracefile.txt``

**Comment by Thermi** [comment]
[tracefile.txt](https://github.com/Yelp/elastalert/files/562796/tracefile.txt)

**Comment by Qmando** [comment]
It looks like the first query is made using ISO8601 timestamping but the subsequent use unix time. Can you try removing ``timestamp_format`` ?

**Comment by Thermi** [comment]
That makes the rule work correctly. Previously, without the manuall defined `timestamp_format`, the rule failed with a python exception. I do not know why that works now. Thank you for your help.

**Comment by Qmando** [comment]
Phew! Always trust the JSON _source over Kibana. 😄

**Comment by Qmando** [comment]
if you do encounter any exceptions, please open another issue!
