### ISSUE TITLE
use elastic alert  to send  a request to web services

### ISSUE THREAD

**Issue by ehsan-bay** [Yelp/elastalert#788]
hi there
How can I call a web service on alerting action. 
I implement a web service and I want to call it in after the query is matched.

**Comment by Qmando** [comment]
http://elastalert.readthedocs.io/en/latest/recipes/adding_alerts.html

You could look at the hipchat alerter as an example. It constructs some JSON and makes a post request.

**Comment by ehsan-bay** [comment]
thanks Qmando. could you please help to add a new alerter and call a web service. or show me a related link?

**Comment by Qmando** [comment]
https://github.com/Yelp/elastalert/blob/master/elastalert/alerts.py#L760
