### ISSUE TITLE
Exception during elastalert startup #774

### ISSUE THREAD

**Issue by motonisar** [Yelp/elastalert#800]
I am continuing to get the below error, while starting elastalert. I am currently using below elk config.

elasticsearch -2.4.1
logstash - 2.4
Kibana -4.6.1

Below is my Docker file configuration for last alert :
ENV ELASTALERT_HOME /opt/elastalert
ENV ELASTALERT_VERSION 0.0.95

USER root

# Download and unpack Elastalert.
RUN apk update && apk add build-base wget && pip install https://github.com/Yelp/elastalert/archive/v${ELASTALERT_VERSION}.tar.gz

Question:
I could see the issue being resolved in 774, can that be merged into a new release so that docker images  could  be build based of latest code ?

Error:

WARNING:elasticsearch:GET http://elasticsearch:9200/elastalert_status_stage/elastalert/_search?size=1000 [status:400 request:0.007s]
WARNING:elasticsearch:GET http://elasticsearch:9200/elastalert_status_stage/elastalert_status/_search?_source_include=endtime%2Crule_name&size=1 [status:400 request:0.002s]
ERROR:root:Error querying for last run: TransportError(400, u'parsing_exception', u'Unknown key for a START_OBJECT in [filter].')
ERROR:root:Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/elastalert/elastalert.py", line 781, in run_all_rules
    num_matches = self.run_rule(rule, endtime, self.starttime)
  File "/usr/local/lib/python2.7/site-packages/elastalert/elastalert.py", line 546, in run_rule
    self.set_starttime(rule, endtime)
  File "/usr/local/lib/python2.7/site-packages/elastalert/elastalert.py", line 494, in set_starttime
    last_run_end = self.get_starttime(rule)
  File "/usr/local/lib/python2.7/site-packages/elastalert/elastalert.py", line 485, in get_starttime
    self.handle_error('Error querying for last run: %s' % (e), {'rule': rule['name']})
  File "/usr/local/lib/python2.7/site-packages/elastalert/elastalert.py", line 1305, in handle_error
    self.writeback('elastalert_error', body)
  File "/usr/local/lib/python2.7/site-packages/elastalert/elastalert.py", line 1051, in writeback
    doc_type=doc_type, body=body)
  File "/usr/local/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 71, in _wrapped
    return func(*args, params=params, **kwargs)
TypeError: create() takes at least 5 arguments (5 given)

ERROR:root:Uncaught exception running rule Error Exceptions: create() takes at least 5 arguments (5 given)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/site-packages/elastalert/elastalert.py", line 1426, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/local/lib/python2.7/site-packages/elastalert/elastalert.py", line 1423, in main
    client.start()
  File "/usr/local/lib/python2.7/site-packages/elastalert/elastalert.py", line 744, in start
    self.run_all_rules()
  File "/usr/local/lib/python2.7/site-packages/elastalert/elastalert.py", line 785, in run_all_rules
    self.handle_uncaught_exception(e, rule)
  File "/usr/local/lib/python2.7/site-packages/elastalert/elastalert.py", line 1310, in handle_uncaught_exception
    self.handle_error('Uncaught exception running rule %s: %s' % (rule['name'], exception), {'rule': rule['name']})
  File "/usr/local/lib/python2.7/site-packages/elastalert/elastalert.py", line 1305, in handle_error

**Comment by Qmando** [comment]
Add ``pip install elasticsearch<=3.0.0`` to your dockerfile to fix this

**Comment by motonisar** [comment]
@Qmando - Thanks a lot for helping me, I am getting the below error after adding pip install elasticsearch<=3.0.0, am i doing anything wrong.  I am new - so might be asking oratory dumb questions as well.
Error:
Step 6 : RUN pip install elasticsearch<=3.0.0
 ---> Running in adb932f573f1
/bin/sh: can't open =3.0.0: no such file


This is the change i did to my docker file :
RUN pip install elasticsearch<=3.0.0
RUN apk update && apk add build-base wget && pip install https://github.com/Yelp/elastalert/archive/v${ELASTALERT_VERSION}.tar.gz

**Comment by Qmando** [comment]
Oops, sorry
``pip install "elasticsearch<=3.0.0"``

**Comment by motonisar** [comment]
@Qmando - Thanks a lot that worked i was able to start elastalert. It did sent the alert on the sample spike rule as expected, i was trying to get. However i am seeing this error in the container logs 
logs. 

Do i need to worry about these errors? I have given my sample elasticsearch  data as well:

ERROR:root:Error querying for last run: TransportError(400, u'search_phase_execution_exception', u'No mapping found for [@timestamp] in order to sort on')
ERROR:root:Error while querying for alert silence status: TransportError(400, u'search_phase_execution_exception', u'No mapping found for [until] in order to sort on')
WARNING:elasticsearch:GET http://elastalert:9200/elastalert_status_prod/silence/_search?_source_include=until%2Cexponent&size=1 [status:400 request:0.013s]
ERROR:root:Error while querying for alert silence status: TransportError(400, u'search_phase_execution_exception', u'No mapping found for [until] in order to sort on')

Elasticserch data:

"_index" : "logstash-2016.11.07",
"@version" : "1",
        "@timestamp" : "2016-11-07T21:59:57.334Z",
        "source" : "/var/log/data.log",
        "offset" : 111111,
        "type" : “data1.log",
        "input_type" : "log",
        "count" : 1,

**Comment by Qmando** [comment]
This error indicates that ``elastalert-create-index`` (create_index.py) was not run. That creates an index and sets the mapping for elastalert to store metadata back into elasticsearch. This allows elastalert to pick up exactly where it left off if it restarts without losing or duplicating data. You *can* run elastalert and ignore these errors, as it also keeps everything in memory.

**Comment by motonisar** [comment]
Thanks a lot @Qmando ! The elastalert is working now. I had let it run and it was even able to create the index mapping on its own.

I am closing this issue.
