### ISSUE TITLE
elastalert

### ISSUE THREAD

**Issue by Eyad87** [Yelp/elastalert#826]
IS elastalert official version compatable with elasticsearch version 5.0

**Comment by bdh1011** [comment]
You can find #820 PR which is support_es5 branch created by @Qmando. 
If you need to use es5 with python3, there is forked repo on #827 I wrote for es5 with python3.
Currently I am using it and it works. (But not compatible with es<5, python<3)

**Comment by Eyad87** [comment]
Thanks for quick response, today and tomorrow is a holiday, I will try it on sunday and till you what happenes (sorry for my bad English).

**Comment by Eyad87** [comment]
Hi,
I made the changes in Code like what it described in #820, and made the following commands for changes (I do not know if it is necessary) 
$ python setup.py install
$ pip install -r requirements.txt

When i try it ($  python -m elastalert.elastalert --rule example_rules/example_frequency.yaml) I got the following error 

**Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 151, in _run_module_as_main
    mod_name, loader, code, fname = _get_module_details(mod_name)
  File "/usr/lib/python2.7/runpy.py", line 113, in _get_module_details
    code = loader.get_code(mod_name)
  File "/usr/lib/python2.7/pkgutil.py", line 283, in get_code
    self.code = compile(source, self.filename, 'exec')
  File "/root/elastalert/elastalert/elastalert.py", line 125
    info = self.writeback_es.info()
       ^
IndentationError: expected an indented block**

Note that my example_frequency.yaml file is:

```
es_host: localhost

es_port: 9200

es_username: user
es_password: pass

name: test

type: frequency

index: logstash-*

num_events: 10

hours: 7

filter: 
query: []

alert:
- "debug"
```


any help please...
Thanks.

**Comment by Qmando** [comment]
Did you pull the branch or try to do it manually?? The indentation is wrong in elastalert.py line 125.

Use ``git fetch origin && git checkout origin/support_es5`` instead, though, I don't think that branch actually works yet.
