### ISSUE TITLE
ElasticSearch 5.x support

### ISSUE THREAD

**Issue by jianchen2580** [Yelp/elastalert#847]
Any plan about ElasticSearch 5.0 support?

**Comment by Qmando** [comment]
Checkout the support_es5 branch. See #790 and #820

**Comment by agonzalezm** [comment]
when is es5 branch going to merged and released?

**Comment by Qmando** [comment]
28 days ago

**Comment by agonzalezm** [comment]
ok so we dont neet to install support_es branch anymore and if we install from master it should work on es5? Why are the branch and issues still opened?

**Comment by Qmando** [comment]
The issue is not open. https://github.com/Yelp/elastalert/issues/790
The second line of the README says "ElastAlert works with all versions of Elasticsearch."
And I'm just super lazy about deleting branches. I'll do that now

**Comment by agonzalezm** [comment]
Thanks! I got a bit confused.
