### ISSUE TITLE
Convert arguments from Bytes to Gigabytes in alert_text

### ISSUE THREAD

**Issue by reeenz20** [Yelp/elastalert#851]
alert:
- "email"

alert_text_type: alert_text_only

alert_text: |
    Filesystem Critical.
    Host: {0}
    Filesystem Available: {2:x} GB
    Filesystem Used: {3}/1073741824
    Device Name: {4}
    Filesystem Percent Used: {5:.2%}

alert_text_args:
  - host
  - "@timestamp"
  - fs.avail
  - fs.used
  - fs.device_name
  - fs.used_p

Hi! I would like to convert FS available from bytes to gigabytes. How would I do that? Thanks!

**Comment by Qmando** [comment]
There isn't an "easy" way to do this. But you could write an enhancement.
http://elastalert.readthedocs.io/en/latest/recipes/adding_enhancements.html#enhancements

in modules/convertgb.py
```
class ConvertGB(BaseEnhancement):
    def process(self, match):
        match['fs.avail'] = match['fs.avail']/1024/1024/1024
```

In the rule yaml:
```
match_enhancements: ["modules.convertgb.ConvertGb"]
```

**Comment by reeenz20** [comment]
I'm getting error like this:
ERROR:root:Traceback (most recent call last):
  File "/root/elastalert/elastalert/elastalert.py", line 743, in run_all_rules
    num_matches = self.run_rule(rule, endtime, self.starttime)
  File "/root/elastalert/elastalert/elastalert.py", line 561, in run_rule
    enhancement.process(match)
  File "modules/convertgb.py", line 5, in process
    match['fs.avail'] = match['fs.avail'] / 1073741824
KeyError: 'fs.avail'

**Comment by reeenz20** [comment]
I tried changing  fs.avail to host and it is working fine. Tried other fields but I'm getting the same error. Seems like it doesn't recognize other fields?

**Comment by reeenz20** [comment]
Found out the solution. The field I used was a sub field and considered as 2d array.

my new modules/convertgb.py

from elastalert.enhancements import BaseEnhancement

class ConvertGB(BaseEnhancement):
    def process(self, match):
        num = match['fs']['avail']/1073741824.0
        match['fs']['avail'] = "%.3f" % num
        num = match['fs']['used']/1073741824.0
        match['fs']['used'] = "%.3f" % num


Thank you for your help and I will mark this as solved! :D
