### ISSUE TITLE
unable to connect smtp server with correct username and password

### ISSUE THREAD

**Issue by SankarMittapally** [Yelp/elastalert#854]
Hello,

 I was trying to enable alerts for my environment. This is my configuration 

[root@cvlogs elastalert]# cat config.yaml
rules_folder: example_rules
run_every:
  minutes: 1
buffer_time:
  minutes: 15
es_host: 10.0.0.139
es_port: 9200

writeback_index: elastalert_status

alert_time_limit:
  days: 2
smtp_host: 'smtp.gmail.com'
smtp_port: 465
smtp_ssl: true
from_addr: 'myemailid'
smtp_auth_file: '/opt/elastalert/smtp_auth_file.yaml'

================
[root@cvlogs elastalert]# cat /opt/elastalert/smtp_auth_file.yaml
---
user: emailid
password: password.

When I trying to test, getting below error.

ERROR:root:Error while running alert email: Error connecting to SMTP host: (535, '5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials q5sm33621602pgf.45 - gsmtp')
ERROR:root:Error while running alert email: Error connecting to SMTP host: (535, '5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials p68sm109068447pfd.11 - gsmtp')
ERROR:root:Error while running alert email: Error connecting to SMTP host: (535, '5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials w11sm109054090pfk.75 - gsmtp')
ERROR:root:Error while running alert email: Error connecting to SMTP host: (535, '5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials i124sm109962921pgd.15 - gsmtp')
ERROR:root:Error while running alert email: Error connecting to SMTP host: (535, '5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials 135sm109855541pgc.7 - gsmtp')
ERROR:root:Error while running alert email: Error connecting to SMTP host: (535, '5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials e1sm94182379pga.37 - gsmtp')
INFO:elastalert:Queried rule E2live Rule from 2016-12-30 05:56 UTC to 2016-12-30 06:11 UTC: 215 / 215 hits
INFO:elastalert:Ran E2live Rule from 2016-12-30 05:56 UTC to 2016-12-30 06:11 UTC: 215 query hits, 0 matches, 0 alerts sent
INFO:elastalert:Sleeping for 56 seconds
^CINFO:elastalert:SIGINT received, stopping ElastAlert..

Please let me know how to fix this.

**Comment by reeenz20** [comment]
Try changing your smtp_auth_file: '/opt/elastalert/smtp_auth_file.yaml' to smtp_auth_file: /opt/elastalert/smtp_auth_file.yml

**Comment by reeenz20** [comment]
You should also do this. http://serverfault.com/questions/635139/how-to-fix-send-mail-authorization-failed-534-5-7-14. This will allow elastalert to send mails from gmail.

**Comment by SankarMittapally** [comment]
Thanks Reeenz20 for your suggestions but there is no luck, I have already enabled those things.

**Comment by reeenz20** [comment]
Have you tried removing single quotes from your rule? Also you can try using TLS instead of SSL?

**Comment by SankarMittapally** [comment]
removed single quotes still no luck

**Comment by reeenz20** [comment]
Is your password working when you log it on using gmail? Try changing your password with alphanumeric only and remove special characters?

**Comment by SankarMittapally** [comment]
there is no special chars in my password and it is working perfect

**Comment by reeenz20** [comment]
Have you tried a different email account? Also can you paste your config file again?

**Comment by SankarMittapally** [comment]
I used two email addresses, both doesnt have any special char in password.

here is my config.

# This is the folder that contains the rule yaml files
# Any .yaml file will be loaded as a rule
rules_folder: example_rules

# How often ElastAlert will query Elasticsearch
# The unit can be anything from weeks to seconds
run_every:
  minutes: 1

# ElastAlert will buffer results from the most recent
# period of time, in case some log sources are not in real time
buffer_time:
  minutes: 15

# The Elasticsearch hostname for metadata writeback
# Note that every rule can have its own Elasticsearch host
es_host: 10.0.0.139

# The Elasticsearch port
es_port: 9200

# Optional URL prefix for Elasticsearch
#es_url_prefix: elasticsearch

# Connect with TLS to Elasticsearch
#use_ssl: True

# Verify TLS certificates
#verify_certs: True

# GET request with body is the default option for Elasticsearch.
# If it fails for some reason, you can pass 'GET', 'POST' or 'source'.
# See http://elasticsearch-py.readthedocs.io/en/master/connection.html?highlight=send_get_body_as#transport
# for details
#es_send_get_body_as: GET

# Option basic-auth username and password for Elasticsearch
#es_username: someusername
#es_password: somepassword

# The index on es_host which is used for metadata storage
# This can be a unmapped index, but it is recommended that you run
# elastalert-create-index to set a mapping
writeback_index: elastalert_status

# If an alert fails for some reason, ElastAlert will retry
# sending the alert until this time period has elapsed
alert_time_limit:
  days: 2
smtp_host: smtp.gmail.com
smtp_port: 465
smtp_ssl : true
from_addr: sankar.mittapally@gmail.com
smtp_auth_file: /opt/elastalert/smtp_auth_file.yml

**Comment by reeenz20** [comment]
Try commenting these lines:
highlight=send_get_body_as#transport
smtp_host: smtp.gmail.com
smtp_port: 465
smtp_ssl : true
from_addr: sankar.mittapally@gmail.com
smtp_auth_file: /opt/elastalert/smtp_auth_file.yml


then move these lines to your rules file:
smtp_host: smtp.gmail.com
smtp_port: 465
smtp_ssl : true
from_addr: sankar.mittapally@gmail.com
smtp_auth_file: /opt/elastalert/smtp_auth_file.yml

**Comment by SankarMittapally** [comment]
same error.. 

[root@cvlogs elastalert]# python -m elastalert.elastalert --verbose --rule example_rules/my_execeptions.yaml
INFO:elastalert:Starting up
INFO:elastalert:Queried rule My Rule from 2017-01-03 11:57 UTC to 2017-01-03 12:12 UTC: 235 / 235 hits
ERROR:root:Error while running alert email: Error connecting to SMTP host: (535, '5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials a66sm137503934pfa.64 - gsmtp')
INFO:elastalert:Ran My Rule from 2017-01-03 11:57 UTC to 2017-01-03 12:12 UTC: 235 query hits, 1 matches, 0 alerts sent
INFO:elastalert:Sleeping for 59 seconds
^CINFO:elastalert:SIGINT received, stopping ElastAlert...
[root@cvlogs elastalert]#

**Comment by reeenz20** [comment]
/opt/elastalert/smtp_auth_file.yml file should have these lines:
user:  sankar.mittapally@gmail.com
password: yourpassword

Please check your iptable if port 465 for output is allowed

**Comment by SankarMittapally** [comment]
[root@cvlogs elastalert]# cat /opt/elastalert/smtp_auth_file.yml
user: sankar.mittapally@gmail.com
password: mypassword
[root@cvlogs elastalert]#

able to telnet the port 465.

[root@cvlogs elastalert]# telnet smtp.gmail.com 465
Trying 74.125.200.109...
Connected to smtp.gmail.com.
Escape character is '^]'.

**Comment by reeenz20** [comment]
Can you paste the whole example_rules/my_execeptions.yaml

**Comment by SankarMittapally** [comment]
es_host: 10.0.0.139


name: My Rule

type: frequency

index: filebeat-*

num_events: 50

timeframe:
  hours: 4


filter:
- term:
    message: "584c319a3950237600133ad7"


alert:
- "email"

email:
- "sankar.mittapally@gmail.com"
smtp_host: smtp.gmail.com
smtp_port: 465
smtp_ssl : true
from_addr: sankar.mittapally@gmail.com
smtp_auth_file: /opt/elastalert/smtp_auth_file.yml

**Comment by reeenz20** [comment]
Can you place these lines after message: "584c319a3950237600133ad7" and it should be the same level as filter (not idented):
smtp_host: smtp.gmail.com
smtp_port: 465
smtp_ssl : true
from_addr: sankar.mittapally@gmail.com
smtp_auth_file: /opt/elastalert/smtp_auth_file.yml

**Comment by SankarMittapally** [comment]
tried same still same issue, if you dont mind if you have any working rule, please share with me.

**Comment by reeenz20** [comment]
# Alert when the rate of events exceeds a threshold

# (Optional)
# Elasticsearch host
# es_host: elasticsearch.example.com

# (Optional)
# Elasticsearch port
# es_port: 14900

# (OptionaL) Connect with SSL to Elasticsearch
#use_ssl: True

# (Optional) basic-auth username and password for Elasticsearch
#es_username: someusername
#es_password: somepassword

# (Required)
# Rule name, must be unique
name: Filesystem Error Rule

# (Required)
# Type of alert.
# the frequency rule type alerts when num_events events occur with timeframe time
type: frequency

# (Required)
# Index to search, wildcard supported
index: topbeat-*

# (Required, frequency specific)
# Alert when this many documents matching the query occur within a timeframe
num_events: 1

# (Required, frequency specific)
# num_events must occur within this amount of time to trigger an alert
timeframe:
  minutes: 1

aggregation:
  minutes: 1

aggregation_key: 'host'

realert:
  minutes: 0

# (Required)
# A list of Elasticsearch filters used for find events
# These filters are joined with AND and nested in a filtered query
# For more info: http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/query-dsl.html
filter:
#- query:
#    query_string:
#      query: "message: php error"

- query:
    match_phrase:
      fs.device_name: "/dev/simfs"

- range:
    fs.used_p:
      from: 0.00
      to: 0.01

# (Required)
# The alert is use when a match is found
alert:
- "email"

alert_text_type: alert_text_only

alert_text: |
    Filesystem Critical.
    Host: {0}
    Filesystem Available: {2:x} GB
    Filesystem Used: {3}/1073741824
    Device Name: {4}
    Filesystem Percent Used: {5:.2%}

alert_text_args:
  - host
  - "@timestamp"
  - fs.avail
  - fs.used
  - fs.device_name
  - fs.used_p


smtp_host: mysmtpserver
smtp_port: 465
smtp_ssl: true
smtp_auth_file: /root/elastalert/auth_file.yml
from_addr: my@domain.com

# (required, email specific)
# a list of email addresses to send alerts to
email:
- "myself@domain.com"

**Comment by SankarMittapally** [comment]
thanks, will try and let you know!

**Comment by reeenz20** [comment]
Okay! That only works if you have topbeat installed in your clientserver. If not, just replace it with logstash or filebeat.

**Comment by SankarMittapally** [comment]
I used the difference mail address, now it is working perfect. Thanks for your support.

I changed only mail address.

**Comment by anjan-cele** [comment]
Hi @reeenz20 

I am getting following error when I include following lines at below of the example_frequency.yaml :


Traceback (most recent call last):
  File "/usr/local/bin/elastalert-test-rule", line 11, in <module>
    load_entry_point('elastalert==0.1.12', 'console_scripts', 'elastalert-test-rule')()
  File "/usr/local/lib/python2.7/dist-packages/elastalert-0.1.12-py2.7.egg/elastalert/test_rule.py", line 358, in main
    test_instance.run_rule_test()
  File "/usr/local/lib/python2.7/dist-packages/elastalert-0.1.12-py2.7.egg/elastalert/test_rule.py", line 337, in run_rule_test
    rule_yaml = load_rule_yaml(args.file)
  File "/usr/local/lib/python2.7/dist-packages/elastalert-0.1.12-py2.7.egg/elastalert/config.py", line 118, in load_rule_yaml
    loaded = yaml_loader(filename)
  File "build/bdist.linux-x86_64/egg/staticconf/loader.py", line 168, in yaml_loader
  File "build/bdist.linux-x86_64/egg/yaml/__init__.py", line 71, in load
  File "build/bdist.linux-x86_64/egg/yaml/constructor.py", line 37, in get_single_data
  File "build/bdist.linux-x86_64/egg/yaml/composer.py", line 36, in get_single_node
  File "build/bdist.linux-x86_64/egg/yaml/composer.py", line 55, in compose_document
  File "build/bdist.linux-x86_64/egg/yaml/composer.py", line 84, in compose_node
  File "build/bdist.linux-x86_64/egg/yaml/composer.py", line 127, in compose_mapping_node
  File "build/bdist.linux-x86_64/egg/yaml/parser.py", line 98, in check_event
  File "build/bdist.linux-x86_64/egg/yaml/parser.py", line 439, in parse_block_mapping_key
yaml.parser.ParserError: while parsing a block mapping
  in "example_rules/example_frequency.yaml", line 20, column 1
expected <block end>, but found '<block mapping start>'
  in "example_rules/example_frequency.yaml", line 57, column 3

Can you please suggest what I am doing wrong.

Thanks

**Comment by reeenz20** [comment]
Did you edit anything on example_frequency.yaml? Can you paste this rule example_frequency.yaml?

**Comment by anjan-cele** [comment]
Here it is  :

# Alert when the rate of events exceeds a threshold

# (Optional)
# Elasticsearch host
# es_host: watchmandev

# (Optional)
# Elasticsearch port
# es_port: 9200

# (OptionaL) Connect with SSL to Elasticsearch
#use_ssl: True

# (Optional) basic-auth username and password for Elasticsearch
#es_username: anjans
#es_password: Anjan@123

# (Required)
# Rule name, must be unique
name: Example frequency rule

# (Required)
# Type of alert.
# the frequency rule type alerts when num_events events occur with timeframe time
type: frequency

# (Required)
# Index to search, wildcard supported
index: logstash-*

# (Required, frequency specific)
# Alert when this many documents matching the query occur within a timeframe
num_events: 2

# (Required, frequency specific)
# num_events must occur within this amount of time to trigger an alert
timeframe:
  hours: 4

# (Required)
# A list of Elasticsearch filters used for find events
# These filters are joined with AND and nested in a filtered query
# For more info: http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/query-dsl.html
filter:
- term:
    host.keyword: "ERROR"

# (Required)
# The alert is use when a match is found
alert:
- "email"

# (required, email specific)
# a list of email addresses to send alerts to
email:
- "anjan.sinha@yahoo.com"
  smtp_host: ExternalSMTPRelay
  smtp_port: 465
  smtp_ssl : true
  from_addr: anjan.sinha@yahoo.com
  smtp_auth_file: /opt/elastalert/smtp_auth_file.yml

**Comment by reeenz20** [comment]
try putting these lines

smtp_host: ExternalSMTPRelay
smtp_port: 465
smtp_ssl : true
from_addr: anjan.sinha@yahoo.com
smtp_auth_file: /opt/elastalert/smtp_auth_file.yml

above email:

**Comment by anjan-cele** [comment]
Hi @reeenz20 

Still some syntax error is coming like :

Traceback (most recent call last):
  File "/usr/local/bin/elastalert-test-rule", line 11, in <module>
    load_entry_point('elastalert==0.1.12', 'console_scripts', 'elastalert-test-rule')()
  File "/usr/local/lib/python2.7/dist-packages/elastalert-0.1.12-py2.7.egg/elastalert/test_rule.py", line 358, in main
    test_instance.run_rule_test()
  File "/usr/local/lib/python2.7/dist-packages/elastalert-0.1.12-py2.7.egg/elastalert/test_rule.py", line 339, in run_rule_test
    conf = self.load_conf(rule_yaml, args)
  File "/usr/local/lib/python2.7/dist-packages/elastalert-0.1.12-py2.7.egg/elastalert/test_rule.py", line 301, in load_conf
    load_options(rules, conf, args.file)
  File "/usr/local/lib/python2.7/dist-packages/elastalert-0.1.12-py2.7.egg/elastalert/config.py", line 148, in load_options
    raise EAException("Invalid Rule file: %s\n%s" % (filename, e))
elastalert.util.EAException: Invalid Rule file: example_rules/example_frequency.yaml
{'smtp_host': 'ExternalSMTPRelay', 'smtp_port': 465, 'smtp_auth_file': '/opt/elastalert/smtp_auth_file.yml', 'smtp_ssl': True, 'from_addr': 'anjan.sinha@yahoo.com'} is not of type 'string', 'array'

Failed validating 'type' in schema['properties']['email']:
    {'items': {'type': 'string'}, 'type': ['string', 'array']}

On instance['email']:
    {'from_addr': 'anjan.sinha@yahoo.com',
     'smtp_auth_file': '/opt/elastalert/smtp_auth_file.yml',
     'smtp_host': 'ExternalSMTPRelay',
     'smtp_port': 465,
     'smtp_ssl': True}




Do we need to include double quotes like - "anjan.sinha@yahoo.com"

And where we will assign recipient address?

**Comment by reeenz20** [comment]
can you paste your rule again?

**Comment by anjan-cele** [comment]
Hi @reeenz20 

I have pasted the full file :
-------------------------------------------------------------------------------------------------------------------

# Alert when the rate of events exceeds a threshold

# (Optional)
# Elasticsearch host
# es_host: watchmandev

# (Optional)
# Elasticsearch port
# es_port: 9200

# (OptionaL) Connect with SSL to Elasticsearch
#use_ssl: True

# (Optional) basic-auth username and password for Elasticsearch
#es_username: anjans
#es_password: Anjan@123

# (Required)
# Rule name, must be unique
name: Example frequency rule

# (Required)
# Type of alert.
# the frequency rule type alerts when num_events events occur with timeframe time
type: frequency

# (Required)
# Index to search, wildcard supported
index: logstash-*

# (Required, frequency specific)
# Alert when this many documents matching the query occur within a timeframe
num_events: 2

# (Required, frequency specific)
# num_events must occur within this amount of time to trigger an alert
timeframe:
  hours: 4

# (Required)
# A list of Elasticsearch filters used for find events
# These filters are joined with AND and nested in a filtered query
# For more info: http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/query-dsl.html
filter:
- term:
    host.keyword: "ERROR"

# (Required)
# The alert is use when a match is found
alert:
- "email"

# (required, email specific)
# a list of email addresses to send alerts to
email:
  smtp_host: ExternalSMTPRelay
  smtp_port: 465
  smtp_ssl : true
  from_addr: anjan.sinha@yahoo.com
  smtp_auth_file: /opt/elastalert/smtp_auth_file.yml


-------------------------------------------------------------------------------------------------------------------

**Comment by reeenz20** [comment]
these lines should be above email:

smtp_host: ExternalSMTPRelay
smtp_port: 465
smtp_ssl : true
from_addr: anjan.sinha@yahoo.com
smtp_auth_file: /opt/elastalert/smtp_auth_file.yml

should be like this:

alert:
- "email"

smtp_host: ExternalSMTPRelay
smtp_port: 465
smtp_ssl : true
from_addr: anjan.sinha@yahoo.com
smtp_auth_file: /opt/elastalert/smtp_auth_file.yml

email:
- "recipient@domain.com"

**Comment by anjan-cele** [comment]
Hi @reeenz20

I have tested my SMTP in my Ubuntu Server. It is sending mails successfully. Still I am not getting the elastic search/elastalert alert mails though hits are there from logstash.

What could be the problem. Is there any way to debug why mail is not triggering when I am trying to test the rule. I have included the smtp config as you said above.

The hits output is as follows:

INFO:elastalert:Ignoring match for silenced rule Example frequency rule

Would have written the following documents to writeback index (default is elastalert_status):

silence - {'rule_name': 'Example frequency rule', '@timestamp': datetime.datetime(2017, 5, 22, 17, 33, 12, 395317, tzinfo=tzutc()), 'exponent': 0, 'until': datetime.datetime(2017, 5, 22, 17, 34, 12, 395291, tzinfo=tzutc())}

silence - {'rule_name': 'Example frequency rule', '@timestamp': datetime.datetime(2017, 5, 22, 17, 34, 18, 74940, tzinfo=tzutc()), 'exponent': 0, 'until': datetime.datetime(2017, 5, 22, 17, 35, 18, 74923, tzinfo=tzutc())}

silence - {'rule_name': 'Example frequency rule', '@timestamp': datetime.datetime(2017, 5, 22, 17, 35, 20, 754819, tzinfo=tzutc()), 'exponent': 0, 'until': datetime.datetime(2017, 5, 22, 17, 36, 20, 754802, tzinfo=tzutc())}

silence - {'rule_name': 'Example frequency rule', '@timestamp': datetime.datetime(2017, 5, 22, 17, 36, 23, 189863, tzinfo=tzutc()), 'exponent': 0, 'until': datetime.datetime(2017, 5, 22, 17, 37, 23, 189846, tzinfo=tzutc())}

silence - {'rule_name': 'Example frequency rule', '@timestamp': datetime.datetime(2017, 5, 22, 17, 37, 38, 354880, tzinfo=tzutc()), 'exponent': 0, 'until': datetime.datetime(2017, 5, 22, 17, 38, 38, 354851, tzinfo=tzutc())}

silence - {'rule_name': 'Example frequency rule', '@timestamp': datetime.datetime(2017, 5, 22, 17, 38, 40, 721022, tzinfo=tzutc()), 'exponent': 0, 'until': datetime.datetime(2017, 5, 22, 17, 39, 40, 721008, tzinfo=tzutc())}

elastalert_status - {'hits': 125176, 'matches': 62588, '@timestamp': datetime.datetime(2017, 5, 22, 17, 38, 41, 598797, tzinfo=tzutc()), 'rule_name': 'Example frequency rule', 'starttime': datetime.datetime(2017, 5, 21, 17, 32, 17, 532858, tzinfo=tzutc()), 'endtime': datetime.datetime(2017, 5, 22, 17, 32, 17, 532858, tzinfo=tzutc()), 'time_taken': 384.0503420829773}


Thanks

**Comment by reeenz20** [comment]
are you using --verbose or --debug? It wont send messages if your using --debug. Use --verbose instead.

**Comment by anjan-cele** [comment]
Hi @reeenz20 

Where I have to include the --debug or --verbose command.

I was running the test thru :

$ elastalert-test-rule example_rules/example_frequency.yaml

as given in 

https://elastalert.readthedocs.io/en/latest/running_elastalert.html#testing-your-rule


Thanks

**Comment by reeenz20** [comment]
you might want to read this guide. https://elastalert.readthedocs.io/en/latest/

python -m elastalert.elastalert --verbose --rule example_rules/example_frequency.yaml

**Comment by Qmando** [comment]
elastalert-test-rule won't send alerts, it will just print them to the screen, which would also happen if you added ``--debug``. What @reeenz20 suggested is correct.

**Comment by anjan-cele** [comment]
Hi @Qmando & @reeenz20 

I am getting error now as : 

ERROR:root:Error while running alert email: Error connecting to SMTP host: No suitable authentication method found.

Though my SMTP is working fine using telnet in Ubuntu with no authentication required. Also can you explain me what shall be in  smtp_auth_file.yml. Is it .yml file or .yaml file?

By the way , in the example it is mentioned that mail will be triggered. Body of the mail is also written here.

https://elastalert.readthedocs.io/en/latest/running_elastalert.html

Thanks

**Comment by reeenz20** [comment]
Check your smtp host. You might wanna try smtp.mail.yahoo.com? Just double check your mail setting.

**Comment by Qmando** [comment]
If it's working fine without authentication, try removing the auth file?

You could also try connecting to non-ssl, though I'm not sure that would make a difference.
