### ISSUE TITLE
cannot change default host and port for es

### ISSUE THREAD

**Issue by levylll** [Yelp/elastalert#857]
I get the warning `WARNING:elasticsearch:GET http://es:14900/ [status:N/A request:0.185s]` when I use elastalert-test-rule.
It seems that I did not change the defaul host and port. But I have change them in  config.yaml and my rule yaml. 
So, If any one could tell me how to correct it. Thank you very much.

**Comment by levylll** [comment]
I find that I should change the config in test_rule.....T T

**Comment by orhiee** [comment]
for future ref the file is:

elastalert-master/tests/conftest.py

**Comment by sunchanglong1991** [comment]
I also encountered the same problem, but did not find the problem piece corresponding to the change. Which specific configuration is it? I am using the latest version

**Comment by abhishekjiitr** [comment]
You can pass the config file to use as a command line argument to Elastalert

`elastalert-test-rule --config path/to/config.yaml path/to/rule.yaml`
