### ISSUE TITLE
How  to group by specific field in order to alert when group counts exceed the threshold ?

### ISSUE THREAD

**Issue by stefansaye** [Yelp/elastalert#890]
hi all,
I need to write an ElastAlert rule that match a filter (message contain "login fail" and event_type is login) 
first , then group by user field , when 7 matching conditions within 3 minutes to trigger an alert

Example document:

    {
        type: "log",
        user: "bob",
        event_type :"login",
        message:"login fail and blablablablablablablabla"
        timestamp : "2016-09-20T00:05:00"
    }
    {
        type: "log",
        user: "amy",
        event_type :"something",
        message:"send mail blablablablablablablabla"
        timestamp : "2016-09-21T00:05:00"
    }

here is my rule  as below,

    type: frequency
    num_events: 7
    timeframe:
      minutes: 3
    filter:
     - query:
        query_string:
           query: "message: \"login fail\" AND event_type: login"

How  to group by specific field in order to alert when counts exceed the threshold ?

**Comment by Qmando** [comment]
``query_key: specific_field``

**Comment by smeesheady** [comment]
query_key: specific_field does not work when I search by a different field but when  I want to group by a different field.
Example I want to group by Host_Id, and get number of unique  document matched count foe each Host_Id

`query_key : Host_Id.keyword`

```
 alert_text_args:
    - num_matches
    - Host_Id
```
