### ISSUE TITLE
The ElastAlert health check

### ISSUE THREAD

**Issue by dreampuf** [Yelp/elastalert#894]
Is there any way to expose the status of ElastAlert self?

Like a monitoring dashboard of X-Pack. It has how many records ES processed and the latency of insert or query speed.

![image](https://cloud.githubusercontent.com/assets/353644/22819651/15a1d5d8-efae-11e6-9aca-345588809642.png)

**Comment by Qmando** [comment]
Queries made, number of hits, time taken, errors, alerts, etc... is all written to elasticsearch.

http://elastalert.readthedocs.io/en/latest/elastalert_status.html?highlight=elastalert_Status

**Comment by dreampuf** [comment]
That's a good document. Thanks.
