### ISSUE TITLE
Transport error - query does not support filter

### ISSUE THREAD

**Issue by TroelsL** [Yelp/elastalert#899]
I recently pulled the most recent version of EA master due to this issue:

https://github.com/Yelp/elastalert/issues/856

However, not I find that all rules that run against Elasticsearch 1.7.5 are broken. The error I get is:

    elastalert_error - {'message': 'Error running query: TransportError(400, u\'Sear
    chPhaseExecutionException[Failed to execute phase [query], all shards failed; sh
    ardFailures {[7fc-F9T5SgyVvX2vJ9ub-Q][logstash-2017.02.13][0]: SearchParseExcept
    ion[[logstash-2017.02.13][0]: from[-1],size[-1],sort[<custom:"@timestamp": org.e
    lasticsearch.index.fielddata.fieldcomparator.LongValuesComparatorSource@748224de
    >]: Parse Failure [Failed to parse source [{"sort": [{"@timestamp": {"order": "a
    sc"}}], "query": {"bool": {"filter": {"bool": {"must": [{"range": {"@timestamp":
     {"gt": "2017-02-15T13:22:05.788Z", "lte": "2017-02-15T13:27:05.788Z"}}}, {"rang
    e": {"fields.seriesId": {"to": 4755, "from": 4755}}}, {"query_string": {"query":
     "fields.messageTemplate = \\\\"Finished storing data for {MessageId}. {rowcount
    } rows were stored in {timetaken} msec at a rate of {storerate} rows/sec\\\\""}}
    , {"query_string": {"query": "fields.applicationName = \\\\"PCNSInserter\\\\""}}
    ]}}}}}]]]; nested: QueryParsingException[[logstash-2017.02.13] [bool] query does
     not support [filter]]; }{[7fc-F9T5SgyVvX2vJ9u... (2635 characters removed)', 't
    raceback': ['Traceback (most recent call last):', '  File "C:\\Python27\\lib\\si
    te-packages\\elastalert-0.1.7-py2.7.egg\\elastalert\\elastalert.py", line 273, i
    n get_hits', "    res = self.current_es.search(scroll=scroll_keepalive, index=in
    dex, size=rule['max_query_size'], body=query, ignore_unavailable=True, **extra_a
    rgs)", '  File "C:\\Python27\\lib\\site-packages\\elasticsearch\\client\\utils.p
    y", line 68, in _wrapped', '    return func(*args, params=params, **kwargs)', '
     File "C:\\Python27\\lib\\site-packages\\elasticsearch\\client\\__init__.py", li
    ne 498, in search', '    params=params, body=body)', '  File "C:\\Python27\\lib\
    \site-packages\\elasticsearch\\transport.py", line 301, in perform_request', '
      status, headers, data = connection.perform_request(method, url, params, body,
    ignore=ignore, timeout=timeout)', '  File "C:\\Python27\\lib\\site-packages\\ela
    sticsearch\\connection\\http_requests.py", line 72, in perform_request', '    se
    lf._raise_error(response.status_code, raw_data)', '  File "C:\\Python27\\lib\\si
    te-packages\\elasticsearch\\connection\\base.py", line 102, in _raise_error', '
       raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_mes
    sage, additional_info)', 'RequestError: TransportError(400, u\'SearchPhaseExecut
    ionException[Failed to execute phase [query], all shards failed; shardFailures {
    [7fc-F9T5SgyVvX2vJ9ub-Q][logstash-2017.02.13][0]: SearchParseException[[logstash
    -2017.02.13][0]: from[-1],size[-1],sort[<custom:"@timestamp": org.elasticsearch.
    index.fielddata.fieldcomparator.LongValuesComparatorSource@748224de>]: Parse Fai
    lure [Failed to parse source [{"sort": [{"@timestamp": {"order": "asc"}}], "quer
    y": {"bool": {"filter": {"bool": {"must": [{"range": {"@timestamp": {"gt": "2017
    -02-15T13:22:05.788Z", "lte": "2017-02-15T13:27:05.788Z"}}}, {"range": {"fields.
    seriesId": {"to": 4755, "from": 4755}}}, {"query_string": {"query": "fields.mess
    ageTemplate = \\\\"Finished storing data for {MessageId}. {rowcount} rows were s
    tored in {timetaken} msec at a rate of {storerate} rows/sec\\\\""}}, {"query_str
    ing": {"query": "fields.applicationName = \\\\"PCNSInserter\\\\""}}]}}}}}]]]; ne
    sted: QueryParsingException[[logstash-2017.02.13] [bool] query does not support
    [filter]]; }{[7fc-F9T5SgyVvX2vJ9ub-Q][logstash-2017.02.14][0]: SearchParseExcept
    ion[[logstash-2017.02.14][0]: from[-1],size[-1],sort[<custom:"@timestamp": org.e
    lasticsearch.index.fielddata.fieldcomparator.LongValuesComparatorSource@7f773162
    >]: Parse Failure [Failed to parse source [{"sort": [{"@timestamp": {"order": "a
    sc"}}], "query": {"bool": {"filter": {"bool": {"must": [{"range": {"@timestamp":
     {"gt": "2017-02-15T13:22:05.788Z", "lte": "2017-02-15T13:27:05.788Z"}}}, {"rang
    e": {"fields.seriesId": {"to": 4755, "from": 4755}}}, {"query_string": {"query":
     "fields.messageTemplate = \\\\"Finished storing data for {MessageId}. {rowcount
    } rows were stored in {timetaken} msec at a rate of {storerate} rows/sec\\\\""}}
    , {"query_string": {"query": "fields.applicationName = \\\\"PCNSInserter\\\\""}}
    ]}}}}}]]]; nested: QueryParsingException[[logstash-2017.02.14] [bool] query does
     not support [filter]]; }{[7fc-F9T5SgyVvX2vJ9ub-Q][logstash-2017.02.15][0]: Sear
    chParseException[[logstash-2017.02.15][0]: from[-1],size[-1],sort[<custom:"@time
    stamp": org.elasticsearch.index.fielddata.fieldcomparator.LongValuesComparatorSo
    urce@60dca4>]: Parse Failure [Failed to parse source [{"sort": [{"@timestamp": {
    "order": "asc"}}], "query": {"bool": {"filter": {"bool": {"must": [{"range": {"@
    timestamp": {"gt": "2017-02-15T13:22:05.788Z", "lte": "2017-02-15T13:27:05.788Z"
    }}}, {"range": {"fields.seriesId": {"to": 4755, "from": 4755}}}, {"query_string"
    : {"query": "fields.messageTemplate = \\\\"Finished storing data for {MessageId}
    . {rowcount} rows were stored in {timetaken} msec at a rate of {storerate} rows/
    sec\\\\""}}, {"query_string": {"query": "fields.applicationName = \\\\"PCNSInser
    ter\\\\""}}]}}}}}]]]; nested: QueryParsingException[[logstash-2017.02.15] [bool]
     query does not support [filter]]; }{[7fc-F9T5SgyVvX2vJ9ub-Q][logstash-2017.02.1
    6][0]: SearchParseException[[logstash-2017.02.16][0]: from[-1],size[-1],sort[<cu
    stom:"@timestamp": org.elasticsearch.index.fielddata.fieldcomparator.LongValuesC
    omparatorSource@3a50b75c>]: Parse Failure [Failed to parse source [{"sort": [{"@
    timestamp": {"order": "asc"}}], "query": {"bool": {"filter": {"bool": {"must": [
    {"range": {"@timestamp": {"gt": "2017-02-15T13:22:05.788Z", "lte": "2017-02-15T1
    3:27:05.788Z"}}}, {"range": {"fields.seriesId": {"to": 4755, "from": 4755}}}, {"
    query_string": {"query": "fields.messageTemplate = \\\\"Finished storing data fo
    r {MessageId}. {rowcount} rows were stored in {timetaken} msec at a rate of {sto
    rerate} rows/sec\\\\""}}, {"query_string": {"query": "fields.applicationName = \
    \\\"PCNSInserter\\\\""}}]}}}}}]]]; nested: QueryParsingException[[logstash-2017.
    02.16] [bool] query does not support [filter]]; }]\')'], 'data': {'rule': 'PCNS
    4755 Flatline (13 hours)'}}

And the rule:

    es_host: elasticsearch
    es_port: 9200
    
    name: PCNS 4755 Flatline (13 hours)
    
    type: flatline
    
    index: logstash-*
    
    threshold: 1
    timeframe:
        hours: 13
    
    filter:
    - query:
            query_string:
                query: "fields.messageTemplate = \"Finished storing data for {MessageId}. {rowcount} rows were stored in {timetaken} msec at a rate of {storerate} rows/sec\""
    - query:
        query_string:
          query: "fields.applicationName = \"PCNSInserter\""
    - range:
        fields.seriesId:
            from: 4755
            to: 4755
    
    query_key: "4755"

**Comment by Qmando** [comment]
It looks like elastalert thinks it's querying against Elasticsearch 5.0.

As you can see from ``Failed to parse source [{"sort": [{"@timestamp": {"order": "a
sc"}}], "query": {"bool": {"filter": {"bool": {"must": [ ... ]}}}}]`` it's using the query generated on this line, https://github.com/Yelp/elastalert/blob/master/elastalert/elastalert.py#L170.

Could you apply this diff and tell me what it outputs?

``diff --git a/elastalert/elastalert.py b/elastalert/elastalert.py
index 3b1b881..81693d5 100644
--- a/elastalert/elastalert.py
+++ b/elastalert/elastalert.py
@@ -116,6 +116,7 @@ class ElastAlerter():

         self.writeback_es = elasticsearch_client(self.conf)
         self.es_version = self.get_version()
+        print self.es_version
```

**Comment by TroelsL** [comment]
I will try your diff, but I just realized a potential reason behind this issue.

We have two ES servers, one running ES 1.7.5 and one running ES 5.x

The elastalert index is on ES5, while the rules that are now broken are all on ES1.

Maybe this scenario isn't supported?

We are migrating slowly to ES5 anyway, so to me it's not a huge issue, but I can look further into it if it helps the elastalert project.

**Comment by Qmando** [comment]
Oh. That makes perfect sense now. It gets the version from the cluster with the elastalert index and uses that for every rule, and the queries are not compatible between versions.

I'll consider adding support for multiple versions, though it doesn't seem like a very common scenario. Maybe I'm wrong about that.

**Comment by TroelsL** [comment]
It probably isn't. We are only seeing this as we have 100s of microservices gradually transitioning from our ES1 server to ES5. We could simply start two elastalert services, one for each server, and we wouldn't have the problem.

So: suitable workaround that isn't even a hack, and probably not that many people having the problem: I'm closing this issue again, thanks.
