### ISSUE TITLE
setup.py needs to be updated

### ISSUE THREAD

**Issue by jdambly-ns** [Yelp/elastalert#900]
I was trying to setup elastalert using ES5 and I got the following error

pkg_resources.DistributionNotFound: The 'elasticsearch<3.0.0' distribution was not found and is required by elastalert

it looks to me like the setup.py needs to be updated 

`    install_requires=[
        'argparse',
        'elasticsearch<3.0.0',  # Elastalert is not yet compatible with ES5
`

I removed <3.0.0 and I was able to get it working, shouldn't this be updated to also include 5.x?

**Comment by Qmando** [comment]
Not sure why the <3.0.0 version wasn't found.. It definitely exists.(https://pypi.python.org/pypi/elasticsearch)

But anyway, yeah that comment is no longer correct as of a couple weeks ago. Removed the version requirement and comment.
