### ISSUE TITLE
Send alerts. Selection of recipients on the basis of content

### ISSUE THREAD

**Issue by pushkarevds** [Yelp/elastalert#905]
example:

rule blablabla
filter: 
 term: blabla
blabla

if field.tags == domain.servers
    email.recipient = admin@company.ru
    jira.recipient = ADMIN
if field.tags == moscow.servers
    email.recipient = moscow.admin@company.ru
    jira.recipient = MOSCOW.ADMIN

if field.tags contain in list(text file)
    email.recipient = ss.admin@company.ru
    jira.recipient = ss.ADMIN

defaultt.recipients
alert:
- "email"
- "jira"
email:
- "defaultuser@company.ru"

Will this functionality implemented?

**Comment by Qmando** [comment]
https://github.com/Yelp/elastalert/pull/944
