### ISSUE TITLE
TransportError(400, u'parsing_exception', u'[term] query malformed, no start_object

### ISSUE THREAD

**Issue by Blohombo** [Yelp/elastalert#918]
Hi i'm using the elastalert module to query elasticsearch in order to generate alarms.
Since the upgrade of the elasticsearch to the version 5.x my module elastalert was no longer working.
I have update the elastalert python module to get it worked but still i have an issue with the parsing of the result receive from my query.
When i launch th equery from my brower i receive the json object which seems according to me confirm that my query is ok but yet i receive the error message :+1: File "/mwo/home/monadm/elk_addons/lib/python2.7/site-packages/elasticsearch/connection/base.py", line 114, in _raise_error', '    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)', "RequestError: TransportError(400, u'parsing_exception', u'[term] query malformed, no start_object after query name')"], 'data': {'rule': 'AI-HTTP-Poller'}}
Any idea what could be wrong ?

**Comment by kureus** [comment]
What kind of query are you running? Could be related too #912

**Comment by Blohombo** [comment]
http://el2597.bc:9200/logstash-http_poller-*/_search?_source_include=mwo_http_code%2Cmwo_domain%2C_source%2C%40timestamp%2Cmwo_server_url%2Cmwo_response_message&ignore_unavailable=true&scroll=30s&size=10000

**Comment by Blohombo** [comment]
# (Required)
filter:
- term:
  mwo_http_code: 0

#===============================================================================#

# (Optional)
#  A list of terms that should be included in query results.
include:
- "_source"
- "mwo_domain"
- "mwo_http_code"
- "mwo_response_message"
- "mwo_server_url"

**Comment by Blohombo** [comment]
Based on the #912 I have change the filter and it is working thanks !

**Comment by kureus** [comment]
No problem. Glad the workaround helped.
