### ISSUE TITLE
The version of Dockerized elastalert in README example is outdated

### ISSUE THREAD

**Issue by andromedarabbit** [Yelp/elastalert#923]
[back-end / elastalert](https://git.bitsensor.io/back-end/elastalert) does not support the latest version of Elastalert.

> ElastAlert v0.0.96. We don't support other versions of ElastAlert, use them at your own risk.

It should be better to replace the recommended Docker image with the other, which supports the latest version of Elastalert very well.

**Comment by kureus** [comment]
@andromedarabbit The repo you are commentating on is maintained here https://github.com/bitsensor/elastalert. You'll probably want to open an issue/pull request there. 
See #898 for reference on a previous discussion of the versions of Elastalert supported by that project.

**Comment by Qmando** [comment]
The current version is almost 100% backwards compatible with 0.0.96. 

(I bumped the minor version just because I didn't feel like using 0.0.100 😄 )

**Comment by andromedarabbit** [comment]
As I tested, we need the latest version of elastalert to make it work with Elasticsearch 5.x.x. However, current release of back-end/elastalert seems to be not ready for this combination. Anyway I will look into this more and let you guys know what I would find. Thanks for the feedbacks.
