### ISSUE TITLE
Add Rule Defaults / Rule Templates

### ISSUE THREAD

**Issue by msmerc** [Yelp/elastalert#927]
We often have several rules that repeat configuration items. Is it possible to setup some kind of rule template / rule default so that the rules share config? Something like this perhaps:

    !include defaults.yaml #includes details about who to email
    name: The Rule
    filter:
    - term:
        foo: "Test Document"

If such a thing doesn't exist, would you be interested in a pull request to add it?

**Comment by Qmando** [comment]
This was added as the "import" option
