### ISSUE TITLE
top_count_keys broken for ES5 if using .raw instead of .keyword

### ISSUE THREAD

**Issue by sevoma** [Yelp/elastalert#931]
This commit breaks top_count_keys for ES5 if using .raw instead of .keyword:
https://github.com/Yelp/elastalert/commit/f0f5130a4f24f1e1c691f18f3eea7bdd53db7b65#diff-ffbe62c2238948ee1143861b0afeb3caR124

The ES5 docs example for dynamic mapping uses .raw, not .keyword:
https://www.elastic.co/guide/en/elasticsearch/reference/current/dynamic-templates.html#match-mapping-type

Manually specifying fieldname.raw for top_count_keys results in elastalert looking for fieldname.raw.keyword

**Comment by mircopolo** [comment]
https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/466

Useful info in this Logstash ticket. The new Logstash 5 index template uses .keyword but it is not a forced change. 

Perhaps the best approach might be to default to raw or keyword for es 2 and es 5 but allow some sort of override in the config?

**Comment by sevoma** [comment]
I think the override should be allowed for both since you can name it anything you want in either version. 

Once an implementation is agreed on i'd be happy to contribute a pull request with the code and doc updates.

**Comment by bl1nk** [comment]
Has anybody decided for an implementation? We upgraded from ES2 to ES5 and our fields are still using `.raw`. We're running a second ES2 cluster for alerting only because of that. 😄 

A configurable suffix would be great.

**Comment by sevoma** [comment]
Oops, I thought I updated this. Using this option https://elastalert.readthedocs.io/en/latest/ruletypes.html?highlight=raw_count_keys%3A%20false#raw-count-keys set to false, Elastalert will no longer try to add a suffix and will use exactly what you specify.
This has been a good solution for me and I think it will be for you.

I think this can be closed.

**Comment by bl1nk** [comment]
@sevoma Well. Setting `raw_count_keys` to false makes it not count values for the field. I have also done some work on #1241. Might be enough.
