### ISSUE TITLE
[close]

### ISSUE THREAD

**Issue by stefansaye** [Yelp/elastalert#932]
I have set my rule as you said below,if  "For any EID, alert if there are more than 3 departments" in one minutes timeframe  will be alert

     index: logstash-*
     type: cardinality
     es_conn_timeout: 30
     timeframe:
        minutes: 1
     max_cardinality: 2
      cardinality_field: "department"
     query_key: "eid"

but ,it's will only alert for first time , if next minute get the threshold ,it's will be no alert 
it's will be looks like "INFO:elastalert:Ignoring match for silenced rule XXXXXX"

I have try to set 

     realert:
         minutes: 0

but it's will be not "For any EID, alert if there are more than 3 departments in one minutes" threshold

Actually , I want when two times (timeframe) attach the threshold(For any EID, alert if there are more than 3 departments)  then alert
for example ,

2017-03-02T01:00:00
eid department
1 A
1 B
2 B
3 C

2017-03-02T01:01:00
eid department
1 A
1 B
2 B
3 C

then alert ......

so ,  I try to count every attach the threshold counts in enhancement ,when counts is 2 then alert ,
or have other method can do that  ?

**Comment by Qmando** [comment]
Please stop changing the name to "close" and leaving issues open. There is a close button. Use that.
