### ISSUE TITLE
Is there any way to dynamically set the recipient email address for an email alert?

### ISSUE THREAD

**Issue by hilt86** [Yelp/elastalert#940]
I have this working with Slack alerter like so:

```- "slack"
alert_subject: "Sender {0} is next"
alert_subject_args:
- "from.email"
- "@timestamp"
```

Which renders like "Sender steve@apple.com is next" with the Slack alerter. 

However I would like to send an email to the email address contained in from.email in my alert - is this possible with the email alerter?

**Comment by Qmando** [comment]
This will be added in https://github.com/Yelp/elastalert/pull/944
