### ISSUE TITLE
Use IAM ROLE for SNS instead of aws_access and secret_key

### ISSUE THREAD

**Issue by laasya19** [Yelp/elastalert#952]
I spun up an Ec2 instance where elastalert is installed using an account, and instead of providing 
access_key and secret_key i want to create an IAM role with access to SNS and use it.
Is that possible?

**Comment by micahhausler** [comment]
My pr #982 should resolve this issue. The SNS alerter currently requires you to provide the access key, but if my PR gets merged, you can leave out credentials in the alerter and the boto3 API will just pick up whatever access keys are provided by the IAM role.
