### ISSUE TITLE
Unable to install Elastalert

### ISSUE THREAD

**Issue by neuronring** [Yelp/elastalert#953]
Hi, 
i downloaded the Master.zip package and tried installing. All the dependencies have been installed properly. But it complains about "mock". I am pretty sure i installed mock.

When i downloaded mock tar.gz file from the pypi site and installed it manually, i got the below error.

>   File "/usr/lib/python2.6/site-packages/pbr/core.py", line 111, in pbr
    attrs = util.cfg_to_args(path, dist.script_args)
  File "/usr/lib/python2.6/site-packages/pbr/util.py", line 251, in cfg_to_args
    kwargs = setup_cfg_to_setup_kwargs(config, script_args)
  File "/usr/lib/python2.6/site-packages/pbr/util.py", line 434, in setup_cfg_to_setup_kwargs
    if pkg_resources.evaluate_marker('(%s)' % env_marker):
AttributeError: 'module' object has no attribute 'evaluate_marker'
error in setup command: Error parsing /home/app/elastalert/mock-2.0.0/setup.cfg: AttributeError: 'module' object has no attribute 'evaluate_marker'

So i installed mock using 

`pip install mock`

Now mock shows in PIP list

> [app@mynode]$ pip list |grep mock
mock (2.0.0)

Now, when i CD into elastalert-master directory and execute ` sudo  python setup.py install
` the installation is stuck  searching for mock...

Can you please assist, ??

> elastalert.config: module references __file__
creating 'dist/elastalert-0.1.8-py2.6.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing elastalert-0.1.8-py2.6.egg
removing '/usr/lib/python2.6/site-packages/elastalert-0.1.8-py2.6.egg' (and everything under it)
creating /usr/lib/python2.6/site-packages/elastalert-0.1.8-py2.6.egg
Extracting elastalert-0.1.8-py2.6.egg to /usr/lib/python2.6/site-packages
elastalert 0.1.8 is already the active version in easy-install.pth
Installing elastalert-create-index script to /usr/bin
Installing elastalert script to /usr/bin
Installing elastalert-test-rule script to /usr/bin
Installing elastalert-rule-from-kibana script to /usr/bin

> Installed /usr/lib/python2.6/site-packages/elastalert-0.1.8-py2.6.egg
Processing dependencies for elastalert==0.1.8
Searching for mock
Reading http://pypi.python.org/simple/mock/

**Comment by Qmando** [comment]
https://github.com/pypa/pip/issues/2679

Try upgrading pip and the "distribute" package?
sudo apt-get install python-pip
sudo pip install --upgrade distribute

**Comment by neuronring** [comment]
I tried sudo pip install --upgrade . Did not use "distribute" will try that one and let you know .. my pip version is already up to date. version 9.x

**Comment by Qmando** [comment]
Can you just run elastalert anyway? Do get an error? IF you're still having problems, I highly recommend trying to use a virtualenv. This lets you have an environment with Python packages ONLY for elastalert. http://docs.python-guide.org/en/latest/dev/virtualenvs/

**Comment by Qmando** [comment]
If you get
```
Traceback (most recent call last):
   ...
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: requests-oauthlib==0.5.0
```
You need to run ``pip install "requests-oauthlib==0.5.0"`` to fix it.


I'll add ``requests-oauthlib`` to requirements.txt. It seems that something (exotel maybe) requires it but does not list it as a requirement.
