### ISSUE TITLE
No mapping found for [timestamp]  Error on testing alert rule  with valid query

### ISSUE THREAD

**Issue by ajaybhatnagar** [Yelp/elastalert#959]
Environment ES version: 5.2.2, Jdk 1.8-121, Elastalert : latest pull, OS Ubuntu 16.04.

When I run rule to test with:
elastalert-test-rule es_rules/es_status.yaml

**It gives following error** (though filter query used  in rule when executed in Kibana is successful): 

"Successfully loaded es_status_change
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): esdbmonm01
WARNING:elasticsearch:GET http://esdbmonm01:9200/es5dbmon*/_search?ignore_unavailable=true&size=1 [status:400 request:0.025s]
Error running your filter:
RequestError(400, u'search_phase_execution_exception', {u'status': 400, u'error': {u'failed_shards': [{u'node': u'AautzIiDTNuA3_NKyIkiVw', u'index': u'es5dbmon_200317', u'reason': {u'index_uuid': u'vNZ3kY86RdGHymK8Wa9gQw', u'index': u'es5dbmon_200317', u'reason': u'No mapping found for [timestamp] in order to sort on', u'type': u'query_shard_exception'}, u'shard': 0}], u'root_cause': [{u'index_uuid': u'vNZ3kY86RdGHymK8Wa9gQw', u'index': u'es5dbmon_200317', u'reason': u'No mapping found for [timestamp] in order to sort on', u'type': u'query_shard_exception'}], u'caused_by': {u'index_uuid': u'vNZ3kY86RdGHymK8Wa9gQw', u'index': u'es5dbmon_200317', u'reason': u'No mapping found for [timestamp] in order to sort on', u'type': u'query_shard_exception'}, u'grouped': True, u'reason': u'all shards failed', u'phase': u'query', u'type': u'search_phase_execution_exception'}})"

**Mapping in ES index (partial)**
          "elasticsearch_cluster_health" : {
            "properties" : {
              "active_primary_shards" : {
                "type" : "long"
              },
              "active_shards" : {
                "type" : "long"
              },
              "initializing_shards" : {
                "type" : "long"
              },
              "number_of_data_nodes" : {
                "type" : "long"
              },
              "number_of_nodes" : {
                "type" : "long"
              },
              "relocating_shards" : {
                "type" : "long"
              },
              "status" : {
                "type" : "text",
                "fields" : {
                  "keyword" : {
                    "type" : "keyword",
                    "ignore_above" : 256
                  }
                }
              },
              "timed_out" : {
                "type" : "boolean"
              },
              "unassigned_shards" : {
                "type" : "long"
              }
            }
          },

**Rule Definition:**
```
"es_host: esdbmonm01
es_port: 9200
name: es_status_change
type: change
index: es5dbmon*
compare_key: elasticsearch_cluster_health.status
ignore_null: true
query_key: tag.name
timeframe:
  minutes: 5
filter:
- query:
    query_string:
      query: "tag.name:ESDBMON AND _type:metrics AND measurement_name:elasticsearch_cluster_health"
alert:
- "email"
email:
- "ab@testmail.com" "
```

**Error reported in ES logs:**
[2017-03-20T18:22:23,572][DEBUG][o.e.a.s.TransportSearchAction] [esdbmonm01] [es5dbmon_200317][1], node[vduPQUhgQwKsMo5eFd6R5g], [R], s[STARTED], a[id=exeHFkfRRxypTzPjlG5VYw]: Failed to execute [SearchRequest{searchType=QUERY_THEN_FETCH, indices=[es5dbmon*], indicesOptions=IndicesOptions[id=39, ignore_unavailable=true, allow_no_indices=true, expand_wildcards_open=true, expand_wildcards_closed=false, allow_alisases_to_multiple_indices=true, forbid_closed_indices=true], types=[], routing='null', preference='null', requestCache=null, scroll=null, source={
  "size" : 1,
  "query" : {
    "bool" : {
      "filter" : [
        {
          "bool" : {
            "must" : [
              {
                "range" : {
                  "timestamp" : {
                    "from" : "2017-03-19T18:22:23.565161Z",
                    "to" : "2017-03-20T18:22:23.565175Z",
                    "include_lower" : false,
                    "include_upper" : true,
                    "boost" : 1.0
                  }
                }
              },
              {
                "query_string" : {
                  "query" : "tag.name:ESDBMON AND _type:metrics AND measurement_name:elasticsearch_cluster_health",
                  "fields" : [ ],
                  "use_dis_max" : true,
                  "tie_breaker" : 0.0,
                  "default_operator" : "or",
                  "auto_generate_phrase_queries" : false,
                  "max_determined_states" : 10000,
                  "enable_position_increment" : true,
                  "fuzziness" : "AUTO",
                  "fuzzy_prefix_length" : 0,
                  "fuzzy_max_expansions" : 50,
                  "phrase_slop" : 0,
                  "escape" : false,
                  "split_on_whitespace" : true,
                  "boost" : 1.0
                }
              }
            ],
            "disable_coord" : false,
            "adjust_pure_negative" : true,
            "boost" : 1.0
          }
        }
      ],
      "disable_coord" : false,
      "adjust_pure_negative" : true,
      "boost" : 1.0
    }
  },
  "sort" : [
    {
      "timestamp" : {
        "order" : "asc"
      }
    }
  ]
}}] lastShard [true]
org.elasticsearch.transport.RemoteTransportException: [esdbmonm01][10.236.132.64:9300][indices:data/read/search[phase/query]]
Caused by: org.elasticsearch.index.query.QueryShardException: No mapping found for [timestamp] in order to sort on
        at org.elasticsearch.search.sort.FieldSortBuilder.build(FieldSortBuilder.java:262) ~[elasticsearch-5.2.2.jar:5.2.2]

=============
**Output of query in Kibana:**
{
  "_index": "es5dbmon_200317",
  "_type": "metrics",
  "_id": "AVrs_JPSnQ7-JHlN6ubj",
  "_score": null,
  "_source": {
    "@timestamp": "2017-03-20T18:31:00Z",
    "elasticsearch_cluster_health": {
      "active_primary_shards": 11,
      "active_shards": 22,
      "initializing_shards": 0,
      "number_of_data_nodes": 5,
      "number_of_nodes": 5,
      "relocating_shards": 0,
      "status": "green",
      "timed_out": false,
      "unassigned_shards": 0
    },
    "measurement_name": "elasticsearch_cluster_health",
    "tag": {
      "host": "esdbmonm03",
      "name": "ESDBMON"
    }
  },
  "fields": {
    "@timestamp": [
      1490034660000
    ]
  },
  "sort": [
    1490034660000
  ]
}

**Comment by Qmando** [comment]
Hmm.. This is very strange. It should default to ``@timestamp`` unless you add an option ``timestamp_field: timestamp``. You don't have this set in config.yaml, do you?

**Comment by ajaybhatnagar** [comment]
Ah, Ok,  I had another setup in which timestamp field is not named timestamp, so copied the config and updated timestamp field  line as.
timestamp_field: timestamp

So looks like can not re-define the "default timestamp field" again in the config. Leaving it default works ok.
Thanks

**Comment by Qmando** [comment]
You can set it either in config.yaml, as a default for all rules, or in each rule yaml to override the default. If you have it set nowhere, it will use "@timestamp".
