### ISSUE TITLE
Comparing a list against one field

### ISSUE THREAD

**Issue by psymon101** [Yelp/elastalert#964]
Hi all,

I have an ELK stack which absorbs all router/fw/server logs. I also have using Logstash an indice that contains threat info from critical stack.

Can Elastalert compare all documents for a specific field within the threat info indice to another field with one value. with as the log data comes in. So if a field of the log data is called DEST_IPADDRESS it looks up that IP against all the documents in the threat indices.

I use Elastlert for everything else, but cant figure out how to lookup a one field value against a list of others.

Thanks!

**Comment by Qmando** [comment]
You cannot do this out of the box. You would need to write an enhancement. If you are familiar with writing Python and want some tips on how this could work, I'd be happy to give you some pointers.

**Comment by psymon101** [comment]
Qmando , would appreciate any pointers! Thank you

**Comment by Qmando** [comment]
Here's some terrible code to get you started. This will make a terms query on startup to get the list of bad IP addresses, and then drop each match if they don't match.

http://elastalert.readthedocs.io/en/latest/recipes/adding_enhancements.html

```
from elasticsearch.client import Elasticsearch
from elastalert.enhancements import BaseEnhancement, DropMatchException
class IsIPMalicious(BaseEnhancement):
    def __init__(self, *args):
        super(IsIPMalicious, self)
        query = {'aggs': {'ipaddrs': {'terms': {'field': 'ip address field here'}}}}
        es = Elasticsearch(host=self.rule['es_host'], port=self.rule['es_port'])
        res = es.search(index='index here', doc_type='_type here', body=query, search_type='count', size=0)
        self.bad_ips = [x['key'] for x in res['aggregations']['ipaddrs']['buckets']]

    def process(self, match):
        if match['ip_Address'] not in self.bad_ips:
            raise DropMatchException
``` 

You'd want your rule to have
```
type: any
match_enhancements: ["modules.ipaddrs.IsIPMalicious"]
```

obviously this code is not complete, nor does it update the list.

**Comment by simonh101** [comment]
Cheers Qmando , will give this a shot!

**Comment by sathishdsgithub** [comment]
@simonh101

Hi, have you managed to achieve the above task..?
 comparing list against one field ? I'm also planning to achieve the same. Thanks

**Comment by simonh101** [comment]
I did, I didn't need to do the above. I have a formatted list that gets updated nightly,  Using the Blacklist config option and comparing it to the field I initially mentioned . I don't think Elastalert sees the list update, so I have a script that restarts elastlert every time the list updates (Only IP`s that where not present on the previous updates).. Seems to work for me!

**Comment by sathishdsgithub** [comment]
@simonh101 

Just curious to know how are you updating the list automatically? are you using any Python script in the backend to update the blacklist ip address  ?, If possible could you please share the example of the formatted blacklist file containing the IP address and the rule performing this task? , I would like to have it as a reference.

Appreciate your help !!!
