### ISSUE TITLE
How to match a numbers within range?

### ISSUE THREAD

**Issue by taherbohari** [Yelp/elastalert#965]
Hi all,
I want to match a sequence of numbers with exact two numbers separated by "."
eg : Sample message string 

_111.111.111.111 [2017-03-23T04:14:50+00:00] 100.64.13.71:9100 "GET /v2.0/api/tenants/1009/elements HTTP/1.1" 200 1947 **10.057** 766_

I want to match only "10.057" this part of the message, when the first part is within 10-100 and second part is within 000-999.
I am using range searches like : [10 TO 100].[000 TO 999]
But the query is matching Ip Address as well. "111.111.111.111" as they lies within the range I am looking for.
Sample query I am using : 
_message:"/api/" AND message:"9100" AND message: [10 TO 100].[000 TO 999]_

How can I achieve this in elastalert?

**Comment by Qmando** [comment]
Are you using Logstash to ingest this data into Elasticsearch? It comes with grok filters for parsing http access logs, which you really ought to be doing. 

That being said, it's certainly possible to write a regexp to match this, though it's likely going to be pretty slow.
