### ISSUE TITLE
How to use or in filter ?

### ISSUE THREAD

**Issue by stefansaye** [Yelp/elastalert#966]
hi all ,
 I want to create a rule that include term and query string  ,
for term if category is guest "or"  catetory is user 
and whatever is all have "Accepted" in message and hostname is "server1"

     filter:
     - or:
         - term:
               category : "guest "
        - term :
              category : "user "
    - query:
            query_string:
            query: "message: * Accepted * "
    - term:
           hostname : "server1"

but the or looks like cannot work ,it's only match category is guest but cannot match when category is user 
I need you help ,thanks a lot !

**Comment by Qmando** [comment]
Assuming you are using Elasticsearch < 5.0, you are using ``or`` correctly. I'm not sure why it's not matching "user". Do you actually have a space after the word user? Because that could cause it not to match.
