### ISSUE TITLE
Access to the time range in rule type

### ISSUE THREAD

**Issue by mza97** [Yelp/elastalert#969]
Hi,
I want in a new type rule to query ES using the same time range than the original query.
I'm using ```ts_now - buffer_time - query_delay``` and ```ts_now``` but I'm not sure if it can be too different.
Can we send from ```elastalert.py``` the endtime and starttime to the rule type ? 

Thank you.

**Comment by arlindonatal** [comment]
Hi @mza97... Any solution?

**Comment by Qmando** [comment]
From the rule type, you can access the latest starttime used. 
``self.rules['starttime']``

end time is not saved in the rule, but it's generally
`` ts_now()``
or
``ts_now() - self.rules['query_delay']``
if using a query_delay

**Comment by arlindonatal** [comment]
How get in the "alert_text_args"? 

ex:
alert_text_type: "alert_text_only"
alert_text: |
    Date: {0} to {1}.
alert_text_args:
    - "starttime"
    - "ts_now"

**Comment by mza97** [comment]
I think you need an enhancement to add the new values (start and end using Qmando lines) into your matches dict.

**Comment by arlindonatal** [comment]
It's works. thks!
