### ISSUE TITLE
Runtime error when trying to update setuptools

### ISSUE THREAD

**Issue by ZillaG** [Yelp/elastalert#970]
Python 2.7.5 (default, Nov  6 2016, 00:28:07) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] on linux2

I cloned the latest project from Github, and ran "python setup.py install" and got this

```
The required version of setuptools (>=1.1.6) is not available,
and can't be installed while this script is running. Please
install a more recent version first, using
'easy_install -U setuptools'.
```

When I then subsequently ran "python setup.py easy_install -U setuptools" I get stack trace with

`RuntimeError: maximum recursion depth exceeded`

**Comment by ZillaG** [comment]
I was able to update setuptools by....

`$ pip install --update setuptools`

**Comment by kaitoan2000** [comment]
Should be 

> pip install --upgrade setuptools
and 
> pip install elastalert
