### ISSUE TITLE
How to uninstall Elastalert?

### ISSUE THREAD

**Issue by ZillaG** [Yelp/elastalert#974]
How does one uninstall Elastalert v0.1.8? The help page doesn't mention it.

**Comment by Qmando** [comment]
Did you install with pip? pip uninstall elastalert

Did you use setup.py install?
You'll have to delete files manually. They'll probably be in /usr/local/lib/python2.X/dist-packages/elastalert/

**Comment by ZillaG** [comment]
Thanks.
