### ISSUE TITLE
match Exception in message

### ISSUE THREAD

**Issue by greekscholar** [Yelp/elastalert#977]
getting 0 hits on this. how do i match a java Exception with the filter?

is this wrong?
filter:
- query:
    wildcard:
      message: "*Exception"

i'm sure i have exceptions in my logs. getting 0 hits

**Comment by Qmando** [comment]
Try:

```
filter:
 - term:
      message: exception
```

**Comment by greekscholar** [comment]
this works:

filter:
   - term:
        environment: dev
   - query:
       query_string:
         query: "*Exception"
