### ISSUE TITLE
About buffer_time

### ISSUE THREAD

**Issue by wybrono** [Yelp/elastalert#978]
Now is April 2, but I would like to query the April 1 index, I configure the file buffer_time: days: 2, but does not work, as follows:
INFO: elastalert: Queried rule alert20170401pm from 2017-04-02 11:54 CST to 2017-04-02 12:39 CST: 0/0 hits
INFO: elastalert: Ran alert20170401pm from 2017-04-02 11:54 CST to 2017-04-02 12:39 CST: 0 query hits, 0 matches, 0 alerts sent
INFO: elastalert: Sleeping for 19 seconds
why?

**Comment by wybrono** [comment]
Is it because I ran the alert called “alert20170401pm”?

**Comment by wybrono** [comment]
![image](https://cloud.githubusercontent.com/assets/18571318/24585099/acbd8e8e-17b4-11e7-940d-76a01e477bef.png)
why 0 matches, 0 alerts?

**Comment by Qmando** [comment]
That's because the rule already queried april 1, so it will not go backwards and re-query that time.

If you want to do that, add ``--start 2017-04-01`` to the command, or, rename the rule so that elastalert doesn't think it's run on April 1 already/

**Comment by Qmando** [comment]
And the second query gets no matches because those are the same 51 that already triggered an alert. That's something happens when you change buffer_time to several days.

**Comment by wybrono** [comment]
Is it not triggered again after triggering an alarm?
what do you mean “change buffer_time to several days”

**Comment by Qmando** [comment]
You said " I configure the file buffer_time: days: 2", that's what I meant.

It queried from 2017-03-30 to 2017-04-02 and got 51 hits and triggered an alert. Then it queried the same time period again, got the same 51 hits, but it doesn't alert because it already for those 51 hits.

**Comment by wybrono** [comment]
1, What you mean is that the alert will determine whether the hit has been dealt with, only the hit will not deal with the match and alert, if there is a new hit to join, it will alert?
2, You said "it queried the same time period again", "the same time period" is the time of the alert query or timestamp in the time?
Thanks.

**Comment by Qmando** [comment]
Every query goes from NOW to NOW-buffer_time. Queries can overlap, and that's fine, because it only processes NEW events. It does this by keeping tracking of _ids of processed documents.

When ElastAlert restarts, it will never go further back then the previous run, to avoid duplicate alerts.

Say you ran elastalert, with 30 minute buffer_time
Queried rule X from 11:00 to 11:30 ...
Queried rule X from 11:10 to 11:40 ...
Queried rule X from 11:20 to 11:50 ...
Stop elastalert
Start elastalert again 10 minutes later
IT will query from 11:50 to 12:00
Because it's already procssesed documents before 11:50, and it can't keep deduplicating them because it doesn't know the _ids anymore.
Then 11:50 to 12:10
Then 11:50 to 12:20
Then 12:00 to 12:30
Then 12:10 to 12:40
etc

**Comment by sangdrax8** [comment]
ok, so the re-start condition was my problem then.  I was restarting the process to test the buffer_time and therefore was never seeing it.

**Comment by calinah** [comment]
@Qmando quick question as this is somewhat related to my issue. You are saying that 
> "Queries can overlap, and that's fine, because it only processes NEW events. It does this by keeping tracking of _ids of processed documents." 
Can you please explain further how this works? For example If I run my elastalert query on kibana it shows 4 matches but I only get notified of 2 matches -the ones that are not from the same service and show same timestamp. Is this expected? I can see that the `_ids` of the alerts missed are a character apart from the ones triggered. 
But I also have notifications missed on the same service but with different log messages that came in seconds apart. I have uploaded my config on #1543

**Comment by calinah** [comment]
To further put this into perspective a search for a specific query in the last 24hrs shows 218 hits but on slack I received notifications only for 68 hits in the same 24hrs.
