### ISSUE TITLE
group exceptions by type in alerts?

### ISSUE THREAD

**Issue by greekscholar** [Yelp/elastalert#985]
is there a way to group exception messages by type and their count in an alert?

**Comment by Qmando** [comment]
Depending on what the rest of your alert looks like..

You probably either want aggregation + aggregation_key: type (http://elastalert.readthedocs.io/en/latest/ruletypes.html?highlight=aggregation_key#aggregation)

or top_count_keys (http://elastalert.readthedocs.io/en/latest/ruletypes.html?highlight=aggregation_key#top-count-keys)
