### ISSUE TITLE
Drop support for python 2.6 

### ISSUE THREAD

**Issue by micahhausler** [Yelp/elastalert#991]
Python 2.6 is end-of-life'd, can we drop support in the tests?

We'd be able to drop `argparse` from setup.py too.

**Comment by micahhausler** [comment]
@Qmando any thoughts on this?

**Comment by Qmando** [comment]
Sorry for slow response. Yes, I do want to do this. We previously had needed to support some legacy infrastructure but by now I'm ok with dropping this.

**Comment by micahhausler** [comment]
Thanks! I'll update #992
