### ISSUE TITLE
Setting up ElastAlert error?

### ISSUE THREAD

**Issue by stefansaye** [Yelp/elastalert#997]
hi all,
I am trying to set elastalert  where my development ELK stack is working. I have done the below but I am not able to get a simple test rule to fire.

Steps Followed

1. yum install python-setuptools
2. git clone https://github.com/Yelp/elastalert.git
3. cd elastalert
4. python setup.py install

then created a sample frequency type rule and tried running the below command
        
      /usr/bin/python2.7 -m elastalert.elastalert --config ./config.yaml --rule ./rules/myrule.yaml --verbose

When executed the command gave the below error
    
    Traceback (most recent call last):
      File "/usr/lib64/python2.7/runpy.py", line 174, in _run_module_as_main
        "__main__", fname, loader, pkg_name)
      File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
        exec code in run_globals
      File "/usr/bin/elastalert/elastalert/elastalert.py", line 17, in <module>
        import dateutil.tz
    ImportError: No module named dateutil.tz

Please help , also if there Is any guide to fix this ImportError error that would be helpful.

Thanks

**Comment by Qmando** [comment]
It seems that setup.py install did not work successfully. You can try using pip:
```
$ yum install python-pip
$ pip install elastalert
```
